= Links - 3^rd^ November 2024
Julien Kirch
v1.0, 2024-11-03
:article_lang: en
:figure-caption!:
:article_description: Sprints for game writers, controlling the context, city builder games & violence, cult of the founder

== link:https://blog.lauramichet.com/why-you-should-not-make-your-games-writers-sprint/[Why you should not make your games writers sprint]

[quote]
____
Iterating adds functionality to code. Iteration adds quality to writing. These are super, super different things.

This means that the first draft of anything will probably be the lowest-quality version of it. Everyone _believes_ themselves capable of judging the quality of writing, so writers often get extremely harsh and incompetent feedback from people who simply do not know what they are talking about. If a writer shares a rough first draft, they may suddenly find all sorts of random, panicked people from all disciplines and seniority levels swooping down on them to criticize their work - or even demanding to do some writing themselves.

Creative leaders in particular often judge writers harshly for showing real WIP assets. I have worked on games where an executive gave me line edits on an early draft script, panicking because it wasn't done yet. I've seen executives who had never written a story in their life tell me they could critique my team's work because they'd read _Save The Cat._ These are people who no idea what's acceptable in an early draft and what's not. They do not know when a script is "done," and they panic when they see anything that isn't final, because they're worried it will never get any better.

I've found that many writers' work practices are strongly affected by the fragility and anxiety of creative leadership. While writers in a very emotionally supportive, protected environment may be comfortable with widely sharing rough first drafts and iterating on them in the Agile process, they will refuse if they are vulnerable to _coordinated attack by feral executive_.
____

[quote]
____
The big difference between a deadline and an Agile-style points-costing system is that a deadline _tells the writer how much work to do on the draft._ Games writing is often "functional" within the game's feature set at every draft stage (or has the potential to be functional once implemented). If you can read it, you could ship it if you _had_ to -- or at least push what you have into a build, or send a sub-par script to VO records.
____

== link:https://maybeelse.site/words/the-problem-of-witches/[The problem of witches]

[quote]
____
"`What is true power`" is supposed to be one of those deep, philosophical questions with no real answer. It—and the thought experiments which grow on it like clinging weeds—are meant to become a mirror to the speaker's biases, to reveal how they think about the world. Let that be so.

To my mind, the answer is simple: true power is control of the context in which the world is understood. It is the ability to say "`this is what the world is`", and be heard.
____

== link:https://ko-fi.com/post/City-builders-and-the-culture-fantasy-play-I2I014OUK9[Citybuilders and the culture fantasy play]

[quote]
____
Because this is where all of this ends at: Citybuilders, like their bigger sister the 4X strategy games and their older uncle the wargaming tabletop games, are ostensibly and foremost a fantasy about violence and how the culture at play is based on violence. How that violence is gamefied is where the different genres of strategy games are distinguishing themselves from one another. Citybuilders might, at first glance, look like innocent management games that make their spreadsheet nature simply look more fascinating. But underneath the aesthetics there is a whole map of different kinds of violence reproduced and acculturated, whether it be through gentrification in SimCity or state repression in the case of Workers & Resources.

There is a tendency when talking about these things to brush concerns about violence in video games and society aside by remarking that, well, the world is a violent place so no one should really be surprised that that violence is found everywhere. But that misses the point that these reproductions of violence are not a necessary preclusion to any work of art humans create. They are decisions, if maybe unconscious ones. Just like the children who play shopkeepers because they've seen the socio-cultural situation of going to the shop, we all reproduce our culture through our actions and the things we imagine because we are living in a culture. But unlike the children, given enough time to become mature, responsible people, we are able to reflect upon the culture we are living in and make decisions that might run counter to stereotypical representations. For Workers & Resources, all it would have required is the conscious decision to _not_ include a secret police in the exact same way SimCity or Cities: Skylines decided to do not, or -- in absence of that and in service of the amorphous "`historical accuracy`" -- at least a toggle to disable the active repression of the populace in the same way electricity can be turned off. Whether as a state, as a mayor, as an artist, as a game developer, or as an individual, violence is always a choice.
____

== link:https://www.programmablemutter.com/p/the-cult-of-the-founders[The cult of the founders]

[quote]
____
Furthermore -- my theory goes -- this is one part of the explanation for why so many of his fellow founders cheered Musk on. They too are disillusioned prophets. Once, they believed that software would eat the world. They'd ride their sandworms from the desert through the shield to their own glory and the despair of their enemies, smash everything up, and create a galactic empire of inspiration and awesomeness. Instead, they found themselves managing self-ramifying and self-perpetuating empires of bureaucracy, submerged beneath memos and trivial decisions, and worst of all, _dealing with fucking HR_ and surly and subordinate employees who didn't share their values, nor behave as worshipfully as they ought have done.

There is a _lot_ more to Silicon Valley workplace politics than this, but I would guess that these kinds of resentments among leaders play a fairly significant role. What they are now doing isn't what they thought they were signing up for.

So when Musk swoops in, buys a big company that is notoriously badly managed, and promises to cut away the bureaucracy, make the big necessary decisions, and show the world what a real Silicon Valley CEO looks like, is it any wonder that his fellow founders, and their hangers-on and financiers were cheering? Rip out the routinization, and let all that raw charismatic magnificence do its thing, just like they thought it would when they were in their twenties.

Of course, it turns out that propheting is a terrible business model at scale. Weber indeed suggests that there is something fundamentally immature about those can't accept the complexities of a routinized world and deal with them. The story of Twitter's aging boy-king (and he does, somehow, seem creepily boyish beneath the flesh and wrinkles), is in part one of the inadequacies of the cult-leadership style when you are trying to run a big complex public facing company. You can't just ignore routine, and minister to the cult. You need to keep a lot of non-worshippers happy too.
____
