= Links - 28^th^ January 2024
Julien Kirch
v1.0, 2024-01-28
:article_lang: en
:figure-caption!:
:article_description: Management and details, DevEx, theory of fucks

== link:https://cutlefish.substack.com/p/tbm-268-going-deep[TBM 268: "`Going Deep`"]

[quote]
____
Respect existing reporting lines, but bring the teams closer to senior leaders at least occasionally to encourage the flow of information and model the discipline (and safety and respectful feedback) needed to navigate the current reality. It isn't about "`flattening`" the org chart but rather about ensuring people who can discuss reality are in the room.
____

== link:https://dl.acm.org/doi/10.1145/3639443[DevEx in Action: A study of its tangible impacts]

[quote]
____
Most developers know they need good DevEx to do their
best work. Furthermore, because so many companies today
are software-driven, their ability to be profitable depends on
their developers' ability to be productive and creative, and
write and maintain high-quality software, with low technical
debt. Even a company's ability to innovate and be profitable
depends on DevEx -- because if it's too hard to do daily work,
it's definitely too hard to innovate.

Knowing intuitively the importance of DevEx, however,
is not always enough to make a compelling case to upper
management. When management rightfully asks if DevEx
has an impact on business, this study can provide an
answer, showing that DevEx affects the performance of
individual developers, teams, and organizations. Further,
our analysis clearly indicates which factors should be
given priority for teams to achieve positive outcomes. This
evidence can justify a DevEx initiative, as well as provide
actionable insights to guide a DevEx intervention.
Now that you are sold on improving DevEx, how can
____

== link:https://aworkinglibrary.com/writing/unified-theory-of------[A unified theory of fucks]

[quote]
____
Because here's what I've learned: if you give your fucks to the unliving -- if you plant those fucks in institutions or systems or platforms or, gods forbid, interest rates-you will run out of fucks. One day you will reach into that bag and your hand will meet nothing but air and you will be bereft. You will realize the loss of something you did not know you ever had. But if you give a fuck about the living, about all your living kin in all the kingdoms, _they will give a fuck right back._ Maybe not every one of them; maybe not every time. Some people's bags have been empty for a long while, and they may feel the need to ration whatever they have; some people have been taught that to give a fuck is to lose something, not realizing that to withhold is what it means to lose. But I believe -- I know from having given and received, from having lost and been renewed -- that enough of them will come back that you can keep on giving, for a while at least, for as long as any of us has time to give.
____
