== 00. how to align friends and optimize people

How to align your friends depends on their attributes and topologies.

If your friends all implement the `+IAlignable+` interface and thus provide an `+alignWith(Friend otherFriend)+` method, aligning them can be done within a constrained time and memory envelope.
With a high-end machine or specialized hardware, it can be done at 60fps (friends per second).

If it's not the case, it will be determined by your friends' topology.
Using your friends' real shape only works if you're okay with static aligning.

Instead you have to approximate their shape, and the common way is to use solid boxes (aka rectangular cuboids).

The main issue is how to deal with friends with unusual topologies (FwUT).
An unusual topology means that using a solid box would not be good enough.

The canonical example of FwUT is the torus-shaped friend, or doughnut-shaped friend, because:

- the visible surface is round
- the hole in the middle

At scale, the best solution is often to regroup your FwUTs in special areas separated by their type, so each can use a specially tuned algorithm.
These algorithms are available off the shelf, often for a nominal fee, depending on the friend management engine you use.

There's a growing hype around deformable friends: new research suggests that they could be dealt with in real time unless they have specific characteristics like being vapor-based. We hope to cover this topic in a future installment.

== 01. wikinomicon

Everybody knows the old trope of the danger of a lone occultist finding something they shouldn't have and publishing it, leading to a lot of bad stuff.

Dealing with this issue required recruiting scholars to read papers and books before they are put in print, thus the establishment of the "`peer review`" system.

But nowadays the risky sources are not scholarly related but are :

- Personal information management systems (aka note-taking software)
- Wikis, and especially enterprise and video games wikis

Compared to ancient times, monitoring their content doesn't require secret cooperation amoung lots of specialized people any more.
A few people, a smart usage of modern computing trends and lots of money are enough:
by leveraging VCs model and the desire of people and organizations to offload the administration of servers to third parties, if good-enough subsidized softwares are available, people will happily put their sensible data on external servers, thus enabling content scanning at scale.

But as prevention is better than cure, pushing people around dangerous topics would be even better than assessing content after the fact.
The aggressive inclusion of content suggestion is a step in this direction: a few nudges here and there can significantly lower the risks.

== 02. haunted hivemind

What happens when you target the desires and fears of many people at a single place?

Concentrating so much strong emotions can stain reality, and will affect even non-living organisms if it's not managed carefully.
After a while, things will go sour.

When religions are creating such a concentration, they normally do it for a specific goal, and they have the knowledge and training required to deal with the operating forces.

But few software companies have this expertise, and in particular, not the ones who build our current search engines.

Day after day, billions of people are typing their hopes and anxieties in the search boxes, sending their feelings on the network with their queries.

Little by little, it changes things: the software, the data, the people working on them, they are soaked in it.
It's not a malevolent or sinister entity like in a pulp story but a natural force, just a simple case of cause and effect.

"`Why is Google search becoming worse and worse?`" people wonder.
Is it because of the SEO spam? Is it deliberate because Google wants to push people toward ads?

Same questions for Bing, it's worsening and it just doesn't seem to make sense from a technical point of view.

In a way they are haunted, haunted by the emotions pushed onto them.

At least there is no risk of big cataclysm, there are is "`reaching a critical mass`" or other nonsense like that.

Things will just continue to slowly go sour, until the services will be useless enough that people stop using them.

== 03. forest inside computer

People love to think that systems work like a factory in a video game: a clockwork-like system where every cog is perfectly in place.

You can have the feel that your computer is a cleanly organized machine, you can have a nicely organized system for your files and directories, and a soothing empty desktop.

Real world is often much more messy, including computers.
Most of the time the system is such a good liar we don't notice it.

Under the hood, it's full of life and chaos, everything is struggling for resources.
Creatures haggle because they want more memory, more processor time, more disk access, they even steal when they think they can get away with it.

Entities that are deemed too greedy are viciously hunted, then let to scavengers.

We're like trees: time moves much slower for us, unaware of the turmoil.

== 04. 8-bit warmth
== 05.
== 06.
== 07.
== 08.
== 09.
== 10.
== 11.
== 12.
== 13.
