== Day 01: how to align friends and optimize people

How to align your friends depends of their attributes and topologies.

If your friends all implements the `IAlignable` interface and thus provide a `alignWith(Friend otherFriend)` method, aligning them can be done within a constrained time and memory envelope.
With a high-end machine or specialized hardware, it can be done at 60fps (friends per second).

If it's not the case, it will depends of your friends' topology.
Using your friends' real shape only work if you're okay with static aligning.

Instead you have to approximate their shape, and the common way is to use solid boxes (aka rectangular cuboids).

The main issue is how to deal with friends with unusual topologies (FwUT).
A unusual topology means that using a solid box would not be good enough.

The canonical example of FwUT is the torus friend, or doughnut-shaped friend, because of :

- everything is round
- a hole in the middle

At scale, the best solution is often to regroup your FwUT in special areas separated by their type, so each can use a specially tuned algorithm.
These algorithms are available off the shelf, often for a nominal fee, depending of the friend management engine you use.

There's a growing hype around deformable friends: new research suggest that they could be dealt with in real time unless they have specific characteristics like being vapor-based. We hope yo cover this topic in a future installment.