graph TD

Start[Fetch a state from the list]
Valid[Check if can go in this direction]
KOValid[Stop]
Duplicate[Check if state has not already been processed]
KODuplicate[Stop]
Winning[Check if the new state is a winning one]
Add[Add the new state to the list]
Solution[\o/ Found a solution!]

Start --> |Iterate on the four possible directions|Valid
Valid --> |Yes|Duplicate
Valid --> |No| KOValid
Duplicate --> |Yes|Winning
Duplicate --> |No|KODuplicate
Winning --> |Yes|Solution
Winning --> |No|Add
Add --> Start