= Outline for a transport game
Julien Kirch
v0.1, 2018-10-23
:article_lang: en

This is an outline for a transport-theme game I have in mind since some time.

Inspirations : link:https://en.wikipedia.org/wiki/Transport_Tycoon[Transport Tycoon] that I played a long time ago and link:https://play.google.com/store/apps/details?id=com.rocketcolastudio.rvtih[Rocket Valley Tycoon] I played a bit a few week ago.

Basicaly there are "nodes" whith requirements, and you create tranport links between them so you can satisfy the needs of the nodes.

== What I like / I want

* Something casual, with a side of "idle game": things a bit mundane to do
* Something with a link:https://www.are.na/max-kreminski/gardening-games["gardening"] quality
* A game where you can't loose, or loose a significant thing: it's OK to have some pushback to not loosing a significant amount of time
* Something where the workflow are not final: requirements change/become more complex as the game goes so you need to patch your design little by little
* Mobile compliant

* Would be nice if cooperative multiplayer could be added after the fact

== What I don't like / I don't want

* The colonialist theme or undertone that many games in this are seem to have
* A classical tech-themed progression tree
* Hidden data
* Something too industrial like factorio
* Resource depletion : don't like the mechanic, "resource mutation" perhaps ?
* Durability on things if it doesn't add anything beside micro-management
* Micro-management to improve efficiency: the game should calculate the best routes for you, or routes good enough that you don't have to care

== Questions

* Topic / theme ?
* Visual style ?
* Tree progression gateway ?
* How to have several areas and make interesting while avoiding it to be "n areas = 1 area * n times" thing ?
