= Links - 9^th^ April 2023
Julien Kirch
v1.0, 23-04-09
:article_lang: en
:figure-caption!:
:article_description: Incremental games and work, SQL:2023, dark matter developers, custom game engines, innovation vs stability, grid world

== link:https://www.pastemagazine.com/games/idle-games?post_type=article&p=356661[Idle threat: what incremental games say about our relationship to work]

[quote]
____
On the other hand, Mat Jones asks in his essay on free-to-play
link:https://www.rockpapershotgun.com/let-it-die-free-to-play-is-good-actually[Let it die] "`What even are videogames if not perverse, unintentional
exercises in alienation?`" Idle games situate us in patterns of
production, and nature sim versions take that one step further by
implying that the process of producing things that produce other things
is relaxing. You're focused mainly on development and accumulation, two
processes that have been troubled in the city-building conversation.
This is the darkness at the heart of my floating zen garden: at its
base, _Garden Galaxy_ is a (one-time payment based) gacha that is framed
as a zen garden for relaxation.

To play any game, you need to do _something_ to progress. You can walk
around and look at flowers or talk with NPCs all day, but the majority
of the time you have to wake up and participate in some system or
another. The difference is that _Garden Galaxy_ and games like it use
loops that were created in much more work-centered, sometimes even
predatory games. Can these more pleasant versions ever get out from
under that shadow?

None of these questions takes away from the fun I had with _Garden
Galaxy_. But as we've done with genres like the city builder and the
strategy game, it's worthwhile to examine the roots of the idle game and
treat its descendents to the same examination, so we can reimagine how
to really use games to trouble processes of work and production -- and
maybe, in the spirit of idleness's earlier definition, truly relax.
____

== link:http://peter.eisentraut.org/blog/2023/04/04/sql-2023-is-finished-here-is-whats-new[SQL:2023 is finished: Here is what's new]

[quote]
____
SQL:2023 has been wrapped. The final text has been submitted by the
working group to ISO Central Secretariat, and it's now up to the ISO
gods when it will be published. Based on past experience, it could be
between a few weeks and a few months.

In the meantime, we can look at what is new. The changes can be grouped
into three areas:

. Various smaller changes to the existing SQL language
. New features related to JSON
. A new part for property graph queries

Let's look at each one.
____

== link:https://dx.tips/whats-your-dark-matter-strategy[What's your dark matter strategy?]

[quote]
____
With the most optimistic take, summing across ALL of these audiences (no
overlap), you only capture ~33% of the market. Meaning if you, as a
developer content creator, _reached every conventional audience there is
on every platform there is_, _you still would not be reaching two thirds of developers_. And those you _could_ reach would be majority newer
developers who have the time and desire to spend on your content.

The other 2/3 of developers aren't spending their free time at meetups
or watching livestreams. They'll maybe go to one conference every three
years. They don't care about the hot takes. They have to look up the
acronyms you take for granted. They don't know what new framework is
obviously the future, and which code pattern was _so yesterday_.
____

== link:https://gist.github.com/raysan5/909dc6cf33ed40223eb0dfe625c0de74[Custom game engines: a small study]

[quote]
____
A couple of weeks ago I played (and finished) link:https://store.steampowered.com/app/752590/A_Plague_Tale_Innocence[A Plague Tale], a game by link:https://en.wikipedia.org/wiki/Asobo_Studio[Asobo Studio]. I was really captivated by the game, not only by the beautiful graphics but also by the story and the locations in the game. I decided to investigate a bit about the game tech and I was surprised to see it was developed with a custom engine by a relatively small studio. I know there are some companies using custom engines but it's very difficult to find a detailed market study with that kind of information curated and updated. So this article.
____

== link:https://dadadrummer.substack.com/p/against-innovation[Against innovation]

[quote]
____
I went online and started asking everyone I know
in audio engineering how to deal with this situation. To my surprise,
the advice I got back was nearly unanimous: unplug. Stop updating.
Revert to the stable system you had before. And take everything offline
so this doesn't happen again.

It seemed a clever solution to my small-scale, personal studio problem.
But I was taken aback when some of the professionals who offered this
advice said it is what they do, too. Even with their very extensive
skillsets. Could it be that some of the most sophisticated audio
technicians I know - mastering engineers in particular, those tasked in
our industry with maintaining and constantly improving audio standards -
choose to ignore innovation for the sake of stability?
____

== link:https://alex.miller.garden/grid-world/[Grid world]

[quote]
____
When I was a kid, my dad gave me a piece of paper with a grid printed on
it. It consisted of larger squares than standard graph paper, about an
inch in size. It was basically a blank chessboard. The columns of the
grid were labeled with letters ("`A`", "`B`", "`C`", etc.), the rows labeled
with numbers ("`1`", "`2`", "`3`", …). My dad then helped me draw a map of
an imaginary island within the grid's boundaries. I sketched the
squiggly coastline of my island, forming a splattered blob shape, within
which I added the obvious necessary features all mysterious islands
require: forests of crudely draw trees, a mountain with a cave entrance
leading to a secret underground network of caverns, an abandoned hut on
the beach. There were variations of this game: sometimes the map was of
a completely imaginary place, but other times we mapped a known area --
like our backyard -- and added fantastic elements.

My dad showed me how we could use the labeled rows and columns of the
grid to address places of interest in our imagined islands: buried
treasure was at square "`B-4`", the entrance of the cave was at square
"`C-2`". We listed out the landmarks next to the map, creating a
coordinate-based index. The grid plus index elevated my child-like
imaginary treasure island into the grown-up world of official maps and
systems, and thereby transformed it into a real, visitable place.

An obsession was born. I was intoxicated by graph paper. The emptiness
of a totally blank page intimidated me by demanding that I make the
first move, but graph paper invited my participation by steering my
pencil in the grooves of its strictly regular lines. The grid was like a
friend who had already done half the work for me. I drew mazes, maps,
patterns, plans -- all held by the sturdiness of the grid. The effect was
soothing. Through the grid's lattice, all my drawings, no matter how
primitive, took on an air of rational certainty.
____
