= Links - 28^th^ May 2023
Julien Kirch
v1.0, 2023-05-28
:article_lang: en
:figure-caption!:
:article_description: Monochrome image dithering, IE's content rating system, CSS & hiring, CSS crimes

== link:https://surma.dev/things/ditherpunk/[Ditherpunk -- The article I wish I had about monochrome image dithering]

[quote]
____
I always loved the visual aesthetic of dithering but never knew how it's done. So I did some research. This article may contain traces of nostalgia and none of Lena.
____


== link:https://www.devever.net/~hl/pics[Memoirs from the old web: IE's crazy content rating system]

[quote]
____
Today, Internet Explorer has been consigned to the dustbin of history,
yet its quirks and peculiar features remain an interesting area of
discussion from a historical perspective. There was one particular
feature of IE which not only now seems comically naive, but also
completely impractical: namely, IE tried to pioneer a system of content
rating.

This was essentially a standardised "`parental controls`" system. The idea
was that a webpage could be rated in terms of the profanity, nudity,
sex, violence, etc. that it contained.
____

== link:https://www.mikeaparicio.com/posts/2023-05-22-why-were-bad-at-css/[Why we're bad at CSS]

[quote]
____
We're bad at writing CSS. Without deep knowledge of CSS and with an inability to hire people with that knowledge, people go to great lengths to avoid writing CSS, whether by relying on Bootstrap/Tailwind or trying to do everything in JavaScript. They end up over-complicating things to the point where their CSS is extremely hard to maintain.
____

== link:https://www.todayintabs.com/p/just-take-a-crowbar-to-it[Just take a crowbar to it]

[quote]
____
Forget tips and tricks for web development: have you considered doing
some CSS crimes instead? On Cohost, the
link:https://cohost.org/rc/tagged/css%20crimes["`CSS Crimes`"] tag is filled
with users pushing the site to its limit in new and exciting ways. This
is because Cohost allows CSS and HTML in posts, prompting an eclectic
array of creations. There are digital
link:https://cohost.org/rykarn/post/1488595-moire-animations[Moiré animations], DIY erasure poetry
link:https://cohost.org/fish/post/1489759-erasure-poetry[on a post claiming that erasure poetry is an act of destruction], an
link:https://cohost.org/Planeshift/post/1341477-div-style-width-30[in-post pixel art maker], or
link:https://cohost.org/amypercent/post/1269093-resize-a-bug[a worm to stretch and squash]. 

The word "`crime`" says something about the way that users feel about what
they're doing: there's a sense of deviance to it, of the medium being
twisted in unanticipated ways. They're pushing at the bounds of how
we're used to engaging with platforms, to make something unanticipated.
link:http://amodern.net/wp-content/uploads/2016/05/2010_Original_Rosa-Menkman-Glitch-Studies-Manifesto.pdf[In her __Glitch Studies Manifesto__ Rosa Menkman wrote]:

[quote]
_____
Sometimes, [artists] use the computers' inherent maxims as a façade, to
trick the audience into a flow of certain expectation that the artwork
subsequently rapidly breaks out of. As a result, the spectator is forced
to acknowledge that the use of the computer is based on a genealogy of
conventions, while in reality the computer is a machine that can be bent
or used in many different ways.
_____
____
