= Links - 11^th^ February 2024
Julien Kirch
v1.0, 2024-02-11
:article_lang: en
:figure-caption!:
:article_description: Wiring a PDF, clowns with snakes for arms, wrong DB decisions, IP fragmentation

== link:https://speakerdeck.com/ange/lets-write-a-pdf-file[Let's write a PDF file]

[quote]
_____
A simple walk-through to learn
the basics of the PDF format
(at your rhythm)
_____

== link:https://without.boats/blog/let-futures-be-futures/[Let futures be futures]

[quote]
____
It's not "`nasal demons`" undefined behavior bad, or even "`clowns with snakes for arms`" JavaScript bad
____

== link:https://blog.anayrat.info/en/2024/02/05/postgres-again-elected-dbms-of-the-year-in-2023-but-im-worried/[Postgres again elected DBMS of the Year in 2023, but I'm worried]

[quote]
____
It takes a few minutes to make a wrong decision on a database

And sometimes several months/years to fix it.
____

== link:https://lwn.net/SubscriberLink/960913/abc5e28254c219ec/[So you think you understand IP fragmentation?]

[quote]
____
Generally speaking, IP fragmentation is bad for performance in just about every dimension: throughput, latency, CPU usage, memory usage, and network congestion. To see why, imagine a typical IPv4 packet of 20 bytes of IP metadata and 1480 bytes of data that has been fragmented into packets that each contain only eight bytes or fewer of data for a total of 1480/8 = 185 packets. (This is possible but unlikely to ever happen in reality; usually packets are only split into two pieces.)
____
