= Agile : de l'opposition à l'institution 
Julien Kirch
v0.1, 2019-10-15
:article_lang: fr
:article_description: Un autre parti révolutionnaire institutionnel

L'agile est link:../agile-inculpabilite/[une] link:/autonomie-dev-coaching-agilite/[de mes] link:../cacher-management-visuel/[obsessions], et encore je vous épargne les mauvais memes postés sur Twitter.

Je pense avoir trouvé une des raisons.

== L'agile et la subversion

Quand j'ai commencé à travailler, dans les années 2000, l'agile était une force de questionnement, voire de subversion.

Les projets étaient en cycle en V, et c'était l'évidence, une manière de faire qui n'était pas vraiment discutée tant elle était naturelle.

L'agile proposait des approches différentes, d'un type nouveau.
Il remettait en cause des choses dont on n'imaginait qu'elles pouvaient l'être.

Par exemple le _pair-programming_ : beaucoup ne comprenaient pas que l'idée puisse être proposée tant elle semblait incongrue.
Passer de l'incompréhension ("je ne comprends pas : deux personnes qui codent ensemble ?") à l'oppposition ("je pense qu'ensemble les personnes vont coder moins vite que séparément") pouvait déjà demander du travail.

Pour moi c'était un des attrait de l'agile : en dehors des pratiques proposées qui semblait aller dans le bon sens, c'était d'ouvrir des brèches dans les évidences.

== L'agile institutionnel

Aujourd'hui l'agile est institutionnel.
Je ne veut pas dire que tout le monde applique les pratiques agiles, ou que l'agile n'évolue plus.

Seulement, avec son arrivée "au pouvoir", l'agile a perdu sa capacité de remise en cause.
Les pratiques continuent à s'étendre, à s'adapter.
Mais elles ne remettent plus en cause d'évidence, ou du moins plus à la même échelle.

Inventer de nouvelles pratiques ce n'est pas la même chose que d'inventer de nouvelles questions.

Le parallèle avec des partis politiques arrivés au pouvoir et c'étant normalisés me fait penser que c'était probablement inévitable, et que la capacité créative de l'agile devrait continuer à diminuer petit à petit.

Si je suis très heureux de nombre de pratiques apportées par l'agile, je suis un peu nostalgique de cette époque pleine de "possibles".

== Que faire ? Car il faut faire quelque chose

Ma frustration vient de mon ressenti qu'il reste plein de choses à faire, à inventer mais donc également d'abord à questionner, et mon envie de ne pas en rester là.

== Faire de l'entrisme ?

J'ai longtemps pensé que la meilleure solution était de prêter main forte pour continuer à faire progresser l'agile.

De s'accomoder des désagréments pour pouvoir se servir du mot "agile" qui ouvre tant de porte, et de l'auditoire dont une partie partage cette frustration et devrait être à l'écoute.

Malheursement, l'histoire nous a enseigné les limites de l'link:https://fr.wikipedia.org/wiki/Entrisme[entrisme] : on commence par vouloir changer les choses de l'intérieur, et on termine comme un engrenage du système.

== Faire autre chose !

Je pense que la meilleure chance de réinventer quelque chose est de travailler en dehors de l'agile.

Se réclamer "neo-agile" ou "agile 3.0" ou ne sais-je quoi d'autre, c'est consacrer une partie de l'énergie à l'agile existant et aux personnes qui s'en réclament.

À mon avis, il faut aller planter sa tente ailleurs et construire autre chose, en commençant par bruler en effigie quelques unes de nos idoles pour nous donner l'énergie nécessaire à inventer de nouvelles questions, à redevenir différent·e·s, à redevenir infréquentables comme l'étaient les agilistes à leurs débuts.

Il sera bien temps, plus tard, de voir comment convaincre le reste du monde, voire de s'appuyer sur les frustrations de l'agile pour recruter.

Mais avoir ça en tête dès le début, c'est se priver d'un espace de liberté et augmenter les risque de faire un peu mieux mais pas différent.