= Être pris·e au sérieux quand on travaille dans le développement
Julien Kirch
v0.1, 2022-06-05
:article_lang: fr

Être pris·e au sérieux dans son travail est déterminant pour se faire entendre.

Dans le développement, deux choses sont importantes pour que ça soit le cas{nbsp}:

. la compétence,
. la capacité à correspondre au portrait que les autres se font d'une personne compétente qui travaille dans le développement.

L'importance des deux varie selon les organisations.
Même si j'en ai très envie, je n'irais pas jusqu'à dire que dans certains endroits le premier élément n'a aucune importance, mais au minimum le second est absolument essentiel dans votre carrière.
Il est particulièrement important pour se faire reconnaitre par les autres personnes qui travaillent dans le développement.

Le second est aussi celui qui est particulièrement injuste.

Tout d'abord il dépend de qui vous êtes, ainsi si vous êtes un homme blanc cisgenre présentant les caractéristiques d'une personne ayant fait des études secondaires, la partie est déjà presque gagnée.
Là dessus malheureusement vous ne pouvez pas faire grand chose.

Il dépend aussi de vos centres d'intérêts et de vos goûts, surtout en matière de techniques.

Par exemple{nbsp}:

- Utiliser un clavier mécanique,
- Utiliser un thème sombre,
- Aimer les langages fonctionnels et/ou exotiques, et dénigrer les autres langages et les personnes qui les utilisent sans qu'elles y voient un problème,
- Beaucoup utiliser le terminal, et particulièrement un éditeur de code en mode texte.

(La liste n'est pas exhaustive et dépend des communautés, des organisations et même des équipes, certains qui sont valorisés à certains endroits peuvent être des freins ailleurs, mais en cumuler quelques uns vous donne un avantage à peu près partout.)

Je ne dis pas que les personnes qui font ces choix se trompent, mais je dis que faire ses choix et le faire savoir va avoir tendance à ce que les autres vous prennent au sérieux, car cela montre que vous faite partie du groupe.

Pour les personnes qui ont fait une école d'informatique "`classique`", ces goûts font partie de l'apprentissage délivré par l'école, au même titre que les compétences techniques.

Cela fonctionne même si cela n'est pas perçu par les élèves ou même par le corps enseignant.
(Pierre Bourdieu dirait que ça fonctionne d'autant mieux que cela n'est pas perçu.)

Les personnes ayant suivi un autre cursus, par exemple une formation courte, n'ont souvent pas acquis ces goûts, et sont donc désavantagées par rapport aux autres.

== Que faire{nbsp}?

=== Si vous n'avez pas les bon codes

Si vous êtes dans ce cas, ma suggestion est de vous y mettre.
C'est-à-dire d'écouter autour de vous de quoi parlent les personnes qui semblent donner le ton, et de d'investir du temps dans la liste des sujets qui sont valorisés.

C'est un peu dommage, mais voyez ça comme une compétence que vous développez, de la même manière qu'une compétence technique classique.

Et encore une fois je ne dis pas que d'appendre à mieux utiliser votre terminal est inutile, mais qu'en plus d'être possiblement utile sur le plan technique, cela vous sera utile pour être pris·e au sérieux.

J'ai choisi volontairement d'exclure de la liste les choses non liées à l'informatique, comme d'aimer les films de science-fiction ou les jeux de rôles.
Ce n'est pas que je pense qu'avoir ces goûts ne vous aide pas, mais j'espère qu'aller jusque là n'est pas nécessaire.

== Si vous les avez

Si vous établi votre statut dans votre organisation en ayant par exemple un poste à responsabilité, essayez de prendre conscience que ce qui se joue.

L'objectif n'est pas de vous culpabiliser, mais d'essayer d'utiliser votre position pour essayer de rendre ces éléments moins importants dans la lutte pour la reconnaissance, pour que les personnes n'ayant pas les bons codes soient moins désavantagées.

Cela passe par essayer de ne pas valoriser ces différents éléments plus qu'ils ne le devraient.
Ça peut être assez désagréable si vous même partagez ces goûts{nbsp}: il faut vous restreindre sur des choses qui vous passionnent.

Après c'est à vous de faire votre choix{nbsp}: décider de ne pas lutter contre le système c'est participer à ce qu'il perdure.