= Why Warhammer 40,000 is a good metaphor for software development: blood for the blood god, skulls for the skull throne, story points for the agile tyrant
Julien Kirch
v0.1, 2022-11-07
:article_lang: en
:doctype: book
:article_description: 

link:https://en.wikipedia.org/wiki/Warhammer_40,000[Warhammer 40,000] (aka w40k) is a franchise set in a sprawling science-fiction link:https://en.wikipedia.org/wiki/Grimdark[grimdark] universe (they even invented the term).

It's a miniature wargame, some role playing games and video games, and link:https://en.wikipedia.org/wiki/List_of_Warhammer_40,000_novels[several hundreds of books].
For a few years those books are one of my media of choice when I want to consume something that don't require any energy.

As with many operations of this size, the lore is inconsistent and even often contradictory, but a few essential things are always here:

[quote]
____
Forget the power of technology and science, for so much has been forgotten, never to be re-learned. Forget the promise of progress and understanding, for in the grim dark future there is only war. There is no peace amongst the stars, only an eternity of carnage and slaughter, and the laughter of thirsting gods.
____

And [line-through]#as everything I read,# they remind me of software development:

== Good stories needs [line-through]#marines# heroes

W40k lore has combat walkers the size of fortresses, spaceships the size of cites, spatial bases the size of moons.

But it's origin is a wargame focused on infantry units (the space marines archetype in science fiction has been heavily influenced by w40k ones), so w40k is a universe where infantry fight is paramount, even if it doesn't make any sense.

Books, even those that depicts massive conflicts, often tells stories focused on a few individual characters.

Because we need heroes (and traitors), because we need stories where a few people make a difference.

And forgotten be the cannon fodder who bears the bulk of the effort.

== Our worst problems are often created by ourselves

W40k has several deities or deities-like creatures, among them the four chaos gods.
They are malevolent against humanity, corrupting the body and souls and waging wars.

These are sustained by the emotions and desires of all material living things, especially humanity, having been created when humanity prospered and grew among the stars.

And now they plot humanity's demise (but aren't shy to mess with other sentient beings).

I like this better that the usual pride punishing stories that involves an existing god taking umbrage of a mortal: we actively created the god that want our fall, and there is no meaningful way to appease them.

== Automated things often run on hidden labour

W40k has gigantic machines with incredible complexity.
But there are no or very few advanced computers or things like AI.

Advanced "`automation`" don't rely on electronic, but on labour, lots of labour.

Spaceship engines rely on have people shoveling something looking like coal to be burnt, computation rely on people tabulating data manually.
This kind work is often a punishment, with people having no choice about it.

The lore is not shy about it: people in power have normalized it, for them it's just how things work, and the end justify the means.

== Forgetting important things does not prevent creating new things

W40k has a fall from grace tone: many technological breakthrough have been forgotten because of the endless wars.

But unlike many post-apocalyptic media, it's doesn't mean that technology is back to stone age, or even that we see things deteriorating: new things are constantly created.

The ultimate goal is to preserve the balance of power: humanity should always be the underdog.

So it's a mix of old powerful things maintained in working state somehow or other, and of new empowering things on the bleeding edge of technology, used by the same people.

Some software projects are green field, other are like crumbling worlds.
But the mix of old and new in w40k reminds me if what I felt on several project with legacy code being modernized, and that I think is rarely described.

== A religious links to our machines

== Ideology control in each team
