= Why Warhammer 40,000 is a good metaphor for software development: blood for the blood god, skulls for the skull throne, story points for the agile tyrant
Julien Kirch
v0.1, 2022-11-07
:article_lang: en
:doctype: book
:article_description: 

link:https://en.wikipedia.org/wiki/Warhammer_40,000[Warhammer 40,000] (aka w40k) is a franchise set in a sprawling science-fiction link:https://en.wikipedia.org/wiki/Grimdark[grimdark] universe (they even invented the term).

It's a miniature wargame, some role playing games and video games, and link:https://en.wikipedia.org/wiki/List_of_Warhammer_40,000_novels[several hundreds of books].
For a few years those books are one of my media of choice when I want to consume something that don't require any energy.

As with many operations of this size, the lore is inconsistent and even often contradictory, but a few essential things are always here:

[quote]
____
Forget the power of technology and science, for so much has been forgotten, never to be re-learned. Forget the promise of progress and understanding, for in the grim dark future there is only war. There is no peace amongst the stars, only an eternity of carnage and slaughter, and the laughter of thirsting gods.
____

And [line-through]#as everything I read,# they remind me of software development:

== Good stories needs [line-through]#marines# heroes

== Forgetting important things does not prevent creating new things

== Automated things often run on hidden tedious labour

== Our worst problems are often created by ourselves

== A religious links to our machines

== Ideology control in each team
