= Links - 5^th^ November 2023
Julien Kirch
v1.0, 2023-11-05
:article_lang: en
:figure-caption!:
:article_description: Finished software, abyss staring, LinkedIn posts

== link:https://josem.co/the-beauty-of-finished-software/[The beauty of finished software]

[quote]
____
Finished software is software that`'s not expected to change, and that`'s a feature! You can rely on it to do some real work.

Once you get used to the software, once the software works for you, you don`'t need to learn anything new; the interface will exactly be the same, and all your files will stay relevant. No migrations, no new payments, no new changes.
____

== link:https://cohost.org/nex3/post/3367237-if-you-stare-long-in[Abysss starring]

[quote]
____
if you stare long into the abyss, you will begin to accumulate AbyssBux® which you can use for discounts on premium abyssal products such as "`a vast and troubled nothingness`" and "`the void`" at participating abysses nationwide
____

== link:https://ludic.mataroa.blog/blog/an-empty-hall-of-smiling-assassins/[The empty hall of smiling assassins]

[quote]
____
One of the speakers, a man clearly into his 50s, talked about how he left his cushy job at a bank to… make his own bank… which seemed identical to the previous bank, except _he_ owned it and their apps were better. He then spoke at length about the nights he slept at the hotel they had their only branch in -- not like, in a _hotel room_ but _in the bank`'s physical branch_.

Fucking go home dude, what the fuck are you on about? Why is everyone impressed by this? This man has a family and kids, why is he out here sleeping in a bank branch? 
This is not aspirational, this is the part of the Twilight Zone where LinkedIn posts are real.
____
