= Statut des dev et coaching
Julien Kirch
v0.1, 2018-12-10
:article_lang: fr

== Les statut 

eaucoup 

Sujet sous-entendu dans beaucoup de manifestes (XP, agile, craft) : autonomie des personnes qui dev dans le choix de leurs outils et leur manière de travailler



Dans les orgs complexes ça peut être une question légitime : il y a les optimisations globales vs optimisations locales.
Objectivement parfois c'est nécessaire, mais objectivement parfois ça ne l'est pas, ou c'est maladroitement fait.

Mais souvent c'est plutot une question de rapport de force : plus que de savoir si les personnes font le bon choix, le sujet est « est ce que les dev sont légitimes à faire leur choix eux-mêmes ? »

Le dev a un statut hybride entre execution "écrire le code" et activité créative.
Cf le link:https://en.wikipedia.org/wiki/Deskilling[deskilling] qui vise en permanence à réduire le dev à de la pure execution

l'agile qui était une action pour donner de l'indépendance c'est en train de devenir une force de coercition avec les coachs qui ont une activité top-bottom

du coup d'autres manifestes pour essayer de relégitimer le statut des devs