= Links - 17^th^ July 2022
Julien Kirch
v1.0, 2022-07-17
:article_lang: en
:figure-caption!:
:article_description: Getting to the staff+ level, CSS behind Figma, spacing in CSS, knowledge of organizational operations

== link:https://leaddev.com/career-paths-progression-promotion/secret-getting-staff-level-leverage[The secret to getting to the staff+ level? Leverage.]

[quote]
____
Can you get big things done? Do people involve you in complex projects
because they trust you to make those projects successful?

The basic skill needed for execution leverage is project management.
Everyone needs to know how to do this at some level, and being extremely
good at it paired with strong technical skills can make you a powerhouse
individual contributor.

Beyond the nuts and bolts process stuff, the leverage you`'re developing
here is understanding how to organize the work to unearth risks early,
how to identify different possible approaches, and how to remain
flexible so that you can pull out a win from the project even if the
final outcome is quite different from the initial proposal. If you can
break a complex problem down into pieces that can be understood and
shared across people or teams, and turn an impossible project into a
concrete roadmap, you can show the kind of broad impact that drives
senior promotions.

Long-tenured engineers have some natural execution leverage because they
know where bodies are buried, but this is a slow path to career growth.
People discount the impact of long-tenured employees who can`'t explain
how their depth of understanding of the systems allows them to do things
that others can`'t, and are likely to think that the system needs to be
fixed instead of promoting the rare people who can work with it.
____

== link:https://ishadeed.com/article/figma-css/[The CSS behind Figma]

[quote]
____
While learning how to build a Figma plugin, I stumbled upon a few interesting usages of Flexbox and Grid in Figma. When I found them, I just got distracted and couldn`'t resist digging more.

Flexbox and Grid have been providing us web developers with lots of new capabilities to build new layouts, and what I will show you in this article is just that.

To move along with this article, you don`'t need to have a detailed knowledge of Flexbox or Grid, and I will try to explain most examples from the ground up.
____


== link:https://ishadeed.com/article/spacing-in-css/[Spacing in CSS]

[quote]
____
Spacer Components

Yes, you read it correctly. I was pointed to this
https://mxstbr.com/thoughts/margin[article] that discusses the concept
of avoiding margins and to use spacer components instead of them.

Let`'s suppose that a section needs a `24px` margin from the left, with
those restrictions in mind:

* Margin can`'t be used directly to the component, because it`'s an
already built design system.
* It should be flexible. The spacing might be on X page, but not in Y.

Quoting from
link:https://github.com/kylpo/react-playbook/blob/master/patterns/Spacing-Components.md[this]
React playbook:

> But in the real world, we do need spacing outside of components for
> composing them into pages and scenes. And this is where margin creeps
> into component code: for spacing compositions of components.

I do agree. For a large design system, it`'s not scalable to keep adding
margins to components. This will eventually result in a creepy code.
____

== link:https://doi.org/10.1287/orsc.2018.1277[Moving off the map: how knowledge of organizational operations empowers and alienates]

[quote]
____
This finding emerged inductively through a study of the experiences of employees across five organizations assigned to work on business process redesign (BPR) change teams. During this assignment, some employees had the opportunity to develop a detailed, comprehensive understanding of their organization`'s logic and operations. They see directly how the structure and operation of the organization, which they had perceived as purposively designed, relatively stable, and largely external, is continuously produced and emerges through social interaction. They observed, in an unmediated way, how the organization is far more malleable and changeable than they had imagined and, at the same time, far less centrally coordinated and actively designed. I examine how this knowledge reshapes their interpretation of possibilities for change and their evaluation of where they would be best placed to make change. The knowledge of the organization revealed through the mapping process alienates these employees from their central roles, and they voluntarily move to peripheral organizational change staff roles.
____

[quote]
____
Whereas those in dominant, or central, positions are inclined to defend orthodoxy, those in dominated positions are inclined toward heterodoxy. Second, because those on the periphery are more loosely embedded, they experience limited pressure to adhere to norms or role expectations or to participate in prescribed ways. They may act in unpredictable or naïve ways to tackle problems that others either do not notice or find intractable and solve them in ways that centrally located actors find unconventional. Third, people in marginal positions are often disadvantaged by current arrangements that motivate them to introduce changes that increase their status and resources. They may also have a more general interest in change because they have so little at stake in status quo arrangements.
____

[quote]
____
The lack of a higher order of design and guiding forces for daily organizing was a realization. The current design and logic was largely disconnected from the way work was performed and coordinated. In another organization, a team member explained that she had been "`assuming that somebody did this on purpose, and it wasn`'t done on purpose; it was just a series of random events that somehow came together`". They could not locate any one person or even a committee of people -- senior executives or senior employees -- who were designing and enforcing bureaucratic plans of action. Although senior employees make strategies and plans, the people putting together the maps saw that the eventual sorting out of how to actually meet these goals and targets via day-in, day-out work occurred in less anticipated ways. There was no central force actively evaluating, reining in, and coordinating actions and decisions across the organization. This explains, for example, the local efforts to improve quality and the creation of local databases and templates.

Some held out hope that one or two people at the top knew of these design and operation issues; however, they were often disabused of this optimism. For example, a manager walked the CEO through the map, presenting him with a view he had never seen before and illustrating for him the lack of design and the disconnect between strategy and operations. The CEO, after being walked through the map, sat down, put his head on the table, and said, "`This is even more fucked up than I imagined`". The CEO revealed that not only was the operation of his organization out of his control but that his grasp on it was imaginary.

They learned that what they had previously attributed to the direction and control of centralized, bureaucratic forces was actually the aggregation of the work and decisions of people distributed throughout the organization. Everyone was working on the part of the organization that they were familiar with, assuming that another set of people were attending to the larger picture, coordinating the larger system to achieve goals and keeping the organization operating. They found out that this was not the case.
____

[quote]
____
As part of the map-building process, employees were invited to identify their role on the map and to indicate how it was connected to other roles through either inputs or outputs. Team members recounted that it was difficult to observe employees "`go through a real emotional struggle when they see that what they are doing is not really adding value or that what they are doing is really disconnected from what they thought they were doing`". In one case, a finance manager noticed that his role was on the wall but that it was not connected to any other role on the wall. He had been producing financial reports and sending them to several departments because he understood them to be crucial for their decision-making process; however, no one had identified his work as an input to theirs. This realization was, in the end,

[quote]
_____
devastating for him. He was on the verge of tears … at first, he became very argumentative and was 
trying to convince people that you go from this Post-it note down here to mine. [Other employees 
explained] Well no, we don`'t do that. It was a two-hour conversation. And he finally sat down, and he said, 
so why am I doing this? It was devastating.
_____

The eventual outcome of this "`aha`" was that the manager was moved to another role in the department after working four years in a position that had served almost no purpose.

After such analyses, team members could not look at particular roles and people in the same way. One described how these observations evoked negative emotions:

[quote]
_____
You really start understanding all of the waste and all of the redundancy and all of the people who are 
employed as what I call intervention resources. The process doesn`'t work, so you have to bone it up by 
putting people in to intervene in the process to hold it together. So it is like glue. So I would look 
around [the company] and I would see all these walking glue sticks, and it was just absolutely depressing 
and frustrating at the same time.
_____

Reflecting on his job and his reasons for taking a new path, another explained, "`I was the glue that held the broken egg together. I was the workaround guy. I don`'t want to go back to that`". Team members did not want to go back to working as an "`intervention resource`".
____

[quote]
____
In my study, employees see how the organization, which they had perceived as purposively designed, relatively stable, and external, is continuously produced and emerges as people interact. As they identify fragmented systems and myriad principles guiding and coordinating this web of interactions, they begin to question the efficacy of their efforts to change the organization from central roles. They recast their central positions as ineffective roles that reproduce the organization`'s inefficiencies.
____
