= Coaching & effort
Julien Kirch
v0.1, 2019-08-07
:article_lang: fr

Imaginez une personne chargée d'améliorer la performance d'une équipe de développement.

Cela peut vouloir dire faire en sorte que l'équipe produise plus de chose, ou des choses de meilleure qualité, mais peu importe.

Pour cela la personne va proposer des modifications dans les outils utilisés et/ou les manières de travailler.

(Cela peut se faire de manière directe, en décidant, ou de manière indirecte, par exemple en "`challengeant l'équipe`" jusqu'à ce qu'elle décide de choisir des solutions qui semblent pertinente à la personne en charge de l'amélioration.)

Séparons ces modifications suivant leurs conséquences sur l'effort à fournir par les membres de l'équipe dans leur travail :

. Certaines modifications améliorent la performance en _diminuant_ les efforts à fournir
. Certaines modifications améliorent la performance en _maintenant au même niveau_ le niveau d'effort à fournir
. Certaines modifications améliorent la performance en _augmentant_ le niveau d'effort à fournir

Le premier cas est un win-win : l'organisation et les membres de l'équipe y gagnent tous les deux.
C'est la situation idéale, par exemple quand on met en place un outil pour remplacer une tâche qui demande un certain niveau d'effort.

Le second cas est un win-same : l'organisation y gagne mais pas les membres de l'équipe.

Le troisième cas est un win-lose : l'organisation y gagne mais les membres de l'équipe y perdent du point de vue personnel.
Par exemple les personnes vont rentrer chez elles plus fatiguées car elles auront travaillé plus fort, et en échange l'entreprise gagnera plus d'argent en vendant plus ou plus cher …

C'est par exemple le cas quand on automatise une tâche peu fatigante et qui permettait de souffler un peu, et qu'on augmente ainsi le niveau d'effort moyen à fournir.

Dans une entreprise industrielle, il peut exister des mécanismes prévu pour contrebalancer les effets de cette situation, par exemple les syndicats vont demander des augmentations de salaire, ou des diminution de temps de travail, pour faire en sorte que le résultat soit moins inégalitaire.

En revanche dans beaucoup d'entreprises informatiques, ces mécanismes n'existent pas.
Je dirai même que souvent, il n'existe même pas les conditions permettant de parler de cette situation.

En effet, le vocabulaire de l'"`engagement`" qui est à la mode dans ces entreprises dit que les employé·e·s doivent faire tout ce qui leur est possible pour obtenir le meilleur résultat.

Les objectifs de l'entreprises sont confondus avec les objectifs des personnes.

[quote]
____
Ma passion c'est d'apporter de la valeur.
____

Mentionner la possibilité que les deux peuvent s'opposer c'est quasiment faire preuve de sédition.

Par exemple dire "`si je fais ça mon travail va demander plus d'efforts, donc je ne suis pas d'accord pour le faire sans compensation`", vous fait passer pour un·e dangeureux·se anarchiste, au risque d'y gagner mauvaise réputation, des opportunités moins bonnes et des augmentations de salaire plus faibles …

'''

C'est quelque chose qui me questionne quand on me demande d'améliorer les résultats d'une équipe :
comment obtenir un résultat qui soit satisfaisant par l'organisation qui me mandate, sans léser les membres de l'équipe, alors qu'il est structurellement difficile pour elles de s'exprimer quand cela arrive.

Une partie du discours du coaching parle du besoin d'avoir l'accord des personnes pour cela, mais quel sens a cette accord quand exprimer son désaccord revient à prendre un risque pour sa carrière ?

J'ai l'impression que ce discours est encore une manière de forcer la coopération des personnes "`vous n'avez pas dit explicitement que vous vous opposez, c'est donc que vous êtes d'accord`" ou même de masquer la réalité de la violence du rapport de force "`je ne propose que des choses avec lesquelles les personnes sont d'accord, comme les personnes ne s'y opposent pas cela signifie que ce que je propose est dans leur intérêt`".
