= L'architecture de SI existe-t-elle encore ?
Julien Kirch
v0.1, 2018-05-14
:article_lang: fr

== Disclaimer

* Je suis architecte de SI et j'ai l'habitude d'intervenir sur des systèmes de grande taille

== L'architecture de SI existe-t-elle encore ?

* Les outils sont plus simples à utiliser et les protocoles se standardisent mais l'architecture de SI est encore un sujet
* Ça demande de connaître les outils, mais ça ne suffit pas, si tu te laisses guider par les outils tu ne fais pas de la bonne archi
* Par exemple pour avoir une stratégie ou gérer une transformation à grande échelle, ce sont des compétences d'architecture spécifiques mais aussi des compétence d'organisation et de rédaction

== Les développeur·euse·s et l'architecture de SI

* L'architecture de SI n'est pas limitée aux personnes qui ont le titre d'architecte
* La plupart des personnes qui développent ont un vernis sur l'archi de SI, notament parce que ce sont des extensions des questions d'architecture logicielles
* Le vernis est d'ailleurs très utile pour comprendre les enjeux, et faire en sorte que ce qui est fait dans le projet soit cohérent avec les décisions d'architecture au niveau du SI
* Mais le vernis n'est pas suffisant pour décider de tout : certaines décisions demandent de l'expertise en archi de SI, et cet expertise demande de l'expérience
* De la même manière que tout le monde dans une équipe n'est pas spécialiste de tous les outils, tout le monde n'est pas pointu en archi de SI
* En plus tout le monde n'a pas envie de travailler sur l'archi de SI : le sujet et un peu mou, beaucoup d'échanges pour mettre les personnes d'accord
* Du coup il faut reconnaître la compétence

== L'architecte et les projets

* L'archi 