= 24^th^ September 2017
Julien Kirch
v1.0, 2017-09-24
:article_lang: en

== link:http://thegamedesignforum.com/features/rd_hl_1.html[Reverse Design: Half-Life]

[quote]
____
Through the Reverse Design series and other documents, we have already set forward the overall history of videogame design several times. Therefore, for this summary I will try to be as brief and as specific to Half-Life as possible about the overall history of games. We will go into great depth about the history of the FPS, however, because of how relevant it is to Half-Life's design. For a more in-depth look at videogame design history, you can see the initial article about it, or the first few sections of Reverse Design: Super Mario World, which covers the composite era in greater depth. These shorter overviews will make the bigger picture of game design history much clearer. That said, it isn't necessary to read them; a synopsis of those articles will follow this introduction. For this book, we're going to focus on the transition from the composite era into the set piece era, and how that was an inevitable consequence of the collision of Western development techniques with Japanese game design styles. Half-Life straddles the composite and set piece eras in a significant way, and so it makes for a great example of the third great inflection point in videogame design history.

The history of videogame design, as we understand the field today, began in 1978 with the game Space Invaders. Obviously, videogames had been invented before this, but Space Invaders was the first game to demonstrate the core principle of videogame design. The designer of Space Invaders, Tomohiro Nishikado, was also the lead engineer responsible for building the physical components of the arcade machine. Because of an error in the way he configured the physical setup of the game, the ranks of enemies (the "space invaders" themselves) moved progressively faster as the player cleared the level of them. This meant that every level would get progressively harder toward the end, and then the difficulty would drop off considerably when the next level started. Although this was accidental, Nishikado kept this feature in the game and then embellished it by making the beginning of each level successively (but only slightly) more difficult. You can visualize the difficulty of the game like so:

Essentially, what Nishikado had done was to treat difficulty as something that could slide up and along an axis. This axis was entirely controlled by enemy behavior, and so we can call it the axis of obstacles—obstacles being the things out of a player's direct control which stand in the way of victory.

In the early 1980s, other Japanese designers began to experiment with the idea of another axis, one that actually does deal with an element of player control. This was the axis of abilities, which changed the things that players could do. There were two schools of thought as far as the axis of abilities went in the arcade era. The most obvious interpretation of the axis of abilities was in games like Phoenix, Galaga or Pac-Man which moved player abilities up and down on an axis of greater or lesser power. For example, in Galaga, the multi-ship powerup doubled the player's firepower.

But these powers were always just a secret back door into the axis of obstacles. With Galaga, it's obvious that the designers were simply increasing the ship’s shooting ability numerically—doubling it. It's not that different than if the developers were to simply cut the number of enemies by a large fraction. In Pac-Man it's less obvious but still essentially the same design idea. Over time, the duration of the power pellet's effect gradually diminishes while the enemies only grow in difficulty. Everything the player needs to know about the power pellet involves the duration of its use, which shrinks to nothing as the game goes on. This quantitative focus in powerups is just a back door into quantitative manipulation of the axis of obstacles.

The other school of thought on the axis of abilities sprang from the work of Shigeru Miyamoto. While most of the games of the early 1980s used powerups as an extra way to manipulate the axis of obstacles, Miyamoto's first game—Donkey Kong—did something very different. When Jump Man (Mario's first incarnation) gains the Hammer powerup in Donkey Kong, he loses the ability to jump, but gains the ability to attack enemies. Or, to put it another way, the game temporarily stops being a platformer and starts being an action game.

Instead of treating the axis of player abilities as another quantitative modifier of game difficulty, Donkey Kong sets up a scenario in which the axis of player abilities is one that moves between genres. In Donkey Kong, this was a very rudimentary idea and probably the product of serendipity rather than a clear plan, but Miyamoto and his team must have gotten the sense that moving between genres within a game would be the design style of the future. The great strength of a game that moved between genres (even if only in a small way) is that the game could present new challenges to the player without always getting quantitatively more difficult. The great weakness of arcade games was that, by constantly pushing up the axis of obstacles, they would lose many players who became frustrated by the skyrocketing difficulty before they could really get into the game.

In 1985, Miyamoto and his team created the first real composite game, Super Mario Bros. A composite game is a game in which a player can use the mechanics of one genre to solve the problems of another genre. The prototypical example is Super Mario Bros, in which the player can use platforming mechanics (jumping with momentum) to solve action game problems (defeating or avoiding enemies). The secret of a composite game, though, is not just combining two genres, but rather moving between those two genres without ever abandoning either one. Each level in Super Mario Bros "declines" (literally, leans toward) one of the two composited genres while never ceasing to be a combination of both. In the screenshots below you can probably guess whether the levels in question are in the platformer (lots of jumping) or action (more combat) declensions.

The back-and-forth motion between genres in the composite creates "composite flow." This is a phenomenon similar to ordinary psychological flow, in that the player becomes immersed in the task and forgets everything else. The unique feature of composite flow is that it is achieved by moving from one genre declension to the other just before the player gets bored or frustrated. All the while, however, the game is continuously getting more difficult. If you were to make a graph of it, it would look something like the figure you see below.

The axis of obstacles is still the foundation of the composite game; it's just that instead of the axis of abilities being a mere appendage of the axis of obstacles, it truly acts as another axis. Immediately after Super Mario Bros came out, videogame designers all over the world latched onto the idea of the composite game and started making their own combinations.

Composite design thoroughly displaced the arcade style of design, and so we call the period from 1985 until about 1998 the composite period, after which point another game design style became equally popular. During this time dozens of different composites flourished, and the practice of composite design advanced considerably. Designers created some truly great composite games through innovative combinations. Mega Man and Metroid both added shooting to platformers to great effect. Sonic the Hedgehog took the Action/Platformer composite of Super Mario Bros and added racing game mechanics. Castlevania added RPG elements to the Mario formula. ActRaiser created an odd but extremely likeable composite out of the Simulation, RPG and Action/Platformer combination. Even after the heyday of composite games, we still see new composites like Portal, which allows the player to solve platforming problems with shooter mechanics, or Katamari Damacy, which is really a racing game that operates by an accelerated RPG level-up system. Half-Life is partly a composite game, involving both the FPS genre and a considerable amount of platforming. The relationship between Half-Life's composite parts is, in fact, unusually complicated, because Half-Life is both a composite game and a set piece game, and the kind of composite game that Half-Life draws from has some special properties, too.

One of the most surprising developments of the composite era was the creation of new genres out of old ones. Plenty of games combined two genres in a way that left those two genres apparently intact. For example, everyone can see the way that Mega Man or Metroid alternates between shooter and platform content and sometimes mixes the two. Similarly, the RPG and action elements of The Legend of Zelda are still distinct. In the middle of the composite era, however, composites began to appear where the mix was blurrier. The real-time strategy genre is a good example of this. There are plenty of examples of strategy videogames, but players of the "pure strat" game tend to disdain the RTS as being not really "strategy." In a certain sense, this is correct because the RTS is quite a bit more than just strategy. Dune 2, the first real RTS, mixed several other genres into the formula. By adding not just action game combat but also Sim-City-style economic simulation, the RTS became its own distinct genre. That new genre didn't really retain the audiences of any of its composited parts; instead it created a new RTS-specific audience.

The FPS genre is largely the same. Obviously the FPS is a shooter and shooters go all the way back to the 1970s—but consider how little overlap there is between the hardcore enthusiasts of the FPS and the 'shmup, for example. They're both shooters, but the audience is different, and that difference stems from the genre composite. The first FPS, Wolfenstein 3D, brought together the aiming and dodging elements of the shooter, but it adopted first-person mechanics, exploration and level design of the CRPG.
____
