= Un modèle pour comprendre les choix dans l'IT et comment les influencer
Julien Kirch
v0.1, 2020-04-05
:article_lang: fr
:ignore_files: base.xml, prepare.rb

Quel langage ou framework utiliser{nbsp}? Microservices ou monolithe{nbsp}? Rénover une base de code existante ou la réécrire{nbsp}?
Beaucoup de choses ont été écrites sur les aspects technique et organisationnel de ce type décisions.

Mais j'ai l'impression qu'un autre aspect l'est moins{nbsp}: celui des intérêts des personnes qui sont impliquées.
Car quand une décision implique plusieurs partie prenantes, il est normal que leurs intérêts ne soient pas forcément les mêmes.
Par exemple que les intérêts des personnes qui développent sont différents de l'intérêt de l'organisations pour qui elles travaillent.

Si parfois ce sujet est évoqué directement, j'ai croisé beaucoup d'organisations où ça ne se fait pas.

Cela signifie que des décisions prises sont parfois mauvaises car on préfère ne pas prendre en compte ces éléments, mais aussi que les personnes qui n'ont pas une conscience claire de ces sujets peuvent passer à côté d'une partie des enjeux.

Je ne prétends pas qu'il soit possible de toujours trouver des solutions qui soient satisfaisantes pour tout le monde.
Mon objectif est plutôt de permettre de comprendre ce qui se passe, et de permettre aux personnes de pouvoir défendre leurs intérêts.

Avec le temps j'avais accumulé certaines idées sur ce sujet et j'ai cherché un moyen de les synthétiser d'une manière lisible.

J'ai construit le modèle en ayant en tête le type de choix dont je parle au début de l'article{nbsp}: choix de technologie, ou modèle de développement.
Il peut probablement s'appliquer à d'autres situations, mais je vais me concentrer sur ceux-là dans mes exemples.

== Les zones

Dans le modèle, j'ai identifié cinq zones d'intérêt qui s'appliquent lorsqu'une décision est prise.

Le modèle présente le point d'une vue d'une personne impliquée dans la décision.
Certaines des zones sont communes aux différentes personnes impliquées, d'autres dépendent de chaque personne.

=== Ce que la personne a envie de faire.

image::01-envie.svg[]

Il s'agit des choix qui correspondent aux envies de la personne.

Par exemple choisir une technologies exotiques, d'approches en rupture, peut-être non prouvées ou non fiables mais qui ont attisé sa curiosité.

=== Ce qui est bon pour la carrière de la personne

image::02-carriere.svg[]

Il s'agit des choix qui sont favorable à la carrière de la personne.

Par exemple le fait d'utiliser un technologie très demandée ailleurs, et qui se valoriserait donc très bien sur un CV.

Si cette technologie semble ennuyeuse à la personne, elle ne fera pas partie de la première zone.

=== Ce qui est bon pour l'organisation

image::03-bon.svg[]

Il s'agit des choix qui correspondent aux besoins de l'organisation dans laquelle travaille la personne.

Dans une grande organisation c'est une notion qui peut être assez floue, on peut quand même avoir une certaine idée de là où elle se trouve.

=== Ce qui est récompensé par l'organisation

image::04-recompense.svg[]

Il s'agit des choix possibles qui seront récompensé par l'organisation dans laquelle travaille la personne.

Par exemple ceux qui pourront être mis en avant au moment de demander une augmentation, ou qui vaudront d'être favorablement remarqué.

=== Ce que le·a consultant·e conseille

image::05-conseille.svg[]

Il s'agit de ce que pourra conseiller une personne extérieure à la décision, qui donne son avis mais qui ne sera pas partie prenante dans la mise en œuvre.

Il peut s'agir d'un·e consultant·e d'une entreprise extérieure, mais aussi d'un·e consultant·e interne, par exemple un·e architecte intervenant dans le processus.

Étant extérieure, cette personne ne subit pas forcément les mêmes influences.

Dans la suite de l'article, elle me permet de parler des contraintes et des biais spécifiques quand on est dans cette posture.

=== Les 5 zones

image::06-complet.svg[]

Voici le diagramme complet.

Dans mon idée, toutes les situations de recouvrement ou de non-recouvrement sont possibles, même si ça n'est pas forcément le cas dans toutes les décisions.

Encore une fois, l'objectif n'est pas forcément de toujours viser la zone centrale où tout les intérêt sont satisfaits, mais de comprendre les dynamiques à l'œuvre.

== Quelques croisements intéressants

== Faire bouger les zones

== Conclusion