= Un modèle pour comprendre les choix dans l'IT et comment les influencer
Julien Kirch
v0.1, 2020-04-05
:article_lang: fr
:ignore_files: base.xml, prepare.rb

Quel langage ou framework utiliser{nbsp}? Microservices ou monolithe{nbsp}? Rénover une base de code existante ou la réécrire{nbsp}?
Beaucoup de choses ont été écrites sur les aspects technique et organisationnel de ce type décisions.

Mais j'ai l'impression qu'un autre aspect l'est moins{nbsp}: celui des intérêts des personnes qui sont impliquées.
Car quand une décision implique plusieurs partie prenantes, il est normal que leurs intérêts ne soient pas forcément les mêmes.
Par exemple que les intérêts des personnes qui développent sont différents de l'intérêt de l'organisations pour qui elles travaillent.

Si parfois ce sujet est évoqué ouvertement, j'ai croisé beaucoup d'organisations où le faire est considéré comme un faux pas un peu vulgaire.

Cela signifie que des décisions prises sont parfois mauvaises car on préfère ne pas prendre en compte ces éléments, mais aussi que les personnes qui n'ont pas une conscience claire de ces sujets peuvent passer à côté d'une partie des enjeux.

Je ne prétends pas qu'il soit possible de toujours trouver des solutions qui soient satisfaisantes pour tout le monde.
Mon objectif est plutôt de permettre de comprendre ce qui se passe, et de permettre aux personnes de pouvoir défendre leurs intérêts.

Avec le temps j'avais accumulé certaines idées sur ce sujet et j'ai cherché un moyen de les synthétiser d'une manière lisible.

J'ai construit le modèle en ayant en tête le type de choix dont je parle au début de l'article{nbsp}: choix de technologie, ou modèle de développement.
Il peut probablement s'appliquer à d'autres situations, mais je vais me concentrer sur ceux-là dans mes exemples.

== Les zones

Dans le modèle, j'ai identifié cinq zones d'intérêt qui s'appliquent lorsqu'une décision est prise.

Le modèle présente le point d'une vue d'une personne impliquée dans la décision.
Certaines des zones sont communes aux différentes personnes impliquées, d'autres dépendent de chaque personne.

=== Ce que la personne a envie de faire.

image::envie.svg[]

Il s'agit des choix qui correspondent aux envies de la personne.

Par exemple choisir une technologies exotiques, d'approches en rupture, peut-être non prouvées ou non fiables mais qui ont attisé sa curiosité.

=== Ce qui est bon pour la carrière de la personne

image::carriere.svg[]

Il s'agit des choix qui sont favorable à la carrière de la personne.

Par exemple le fait d'utiliser un technologie très demandée ailleurs, et qui se valoriserait donc très bien sur un CV.

Si cette technologie semble ennuyeuse à la personne, elle ne fera pas partie de la première zone.

=== Ce qui est bon pour l'organisation

image::bon.svg[]

Il s'agit des choix qui correspondent aux besoins de l'organisation dans laquelle travaille la personne.

Dans une grande organisation c'est une notion qui peut être assez floue, on peut quand même avoir une certaine idée de là où elle se trouve.

=== Ce qui est valorisé par l'organisation

image::recompense.svg[]

Il s'agit des choix possibles qui seront récompensés par l'organisation dans laquelle travaille la personne.

Par exemple ceux qui pourront être mis en avant au moment de demander une augmentation, ou qui vaudront d'être favorablement remarqué.

=== Ce que le·a consultant·e conseille

image::conseille.svg[]

Il s'agit de ce que pourra conseiller une personne extérieure à la décision, qui donne son avis mais qui ne sera pas partie prenante dans la mise en œuvre.

Il peut s'agir d'un·e consultant·e d'une entreprise extérieure, mais aussi d'un·e consultant·e interne, par exemple un·e architecte intervenant dans le processus.

Étant extérieure, cette personne ne subit pas forcément les mêmes influences.

Dans la suite de l'article, elle me permet de parler des contraintes et des biais spécifiques quand on est dans cette posture.

=== Les 5 zones

image::complet.svg[]

Voici le diagramme complet.

Dans mon idée, toutes les situations de recouvrement ou de non-recouvrement sont possibles, même si ça n'est pas forcément le cas dans toutes les décisions.

Encore une fois, l'objectif n'est pas forcément de toujours viser la zone centrale où tout les intérêt sont satisfaits, mais de comprendre les dynamiques à l'œuvre et de bien faire ses choix.

image::milieu.svg[]

== Quelques endroits intéressants

=== Ce qu'on a envie de faire mais qui n'est pas bon pour sa carrière

image::envie-pas-carriere.svg[]

Une zone que les personnes qui sont passionnées de technique connaissent bien : que faire quand ce qu'on a envie de faire n'est pas valorisé dans les entreprises{nbsp}?

Je n'ai pas de réponse simple, mais une première étape possible est d'admettre cette situation existe et d'essayer de trouver une position pas trop inconfortable.

Une autre réponse possible est d'essayer de faire bouger les zones en convainquant les entreprises que ce qu'on a envie de faire leur est utile, ce qui pourra avoir comme conséquence de le valoriser.

Le mouvement DevSecOps peut ainsi se voir comme une manière pour des personnes travaillant ou ayant envie de travailler dans la sécurité de se faire une place au soleil.

== Ce qui est valorisé par l'organisation ne donne pas envie et n'est pas bon pour sa carrière

image::bon-pas-envie-ni-carriere.svg[]

C'est ce qui peut arriver quand une organisation utilise des outils développés en interne, ou même simplement pas au goût du jour{nbsp}: l'intérêt de l'organisation et celle des personnes qui y travaillent sont en décalage.

Recruter peut alors devenir compliqué car pourquoi venir travailler dans une structure en sachant que ce qu'on y fera ne sera ni amusant ni utile{nbsp}?

À nouveau il n'y a pas forcément de solution évidente{nbsp}: parfois maintenir un existant dans un langage obscur et en fin de vie est la meilleure solution.
Mais il faut accepter les conséquences de ce type de choix.

J'ai ainsi croisé certaines organisations faisant obstinément semblant de ne pas comprendre pourquoi personne ne postule à certaines de leurs offres d'emploi.

=== Ce qui est bon pour l'organisation mais pas valorisé

image::bon-pas-recompense.svg[]

Un grand classique des organisations dysfonctionnelles, où certaines des activités nécessaires ou au moins utiles à l'organisations ne sont pas valorisées.

Cela signifie que des personnes de bonnes volonté feront peut-être ce type de choix, mais qu'on ne peut pas attendre cela d'une personne.

Si vous avez de l'influence dans une organisation, une des manières d'être utile est d'essayer de faire diminuer cette zone pour aligner l'intérêt de l'organisation avec celle des personnes qui y travaillent.

Par contre ce qui me pose problème c'est d'essayer de convaincre les personnes de faire les choses comme il faut, en faisant appel à leur amour-propre et donc à leur zone "`envie`" même si cela les dessert personnellement.

Il y a aussi des organisations où cette zone est utilisée volontairement sous forme d'une sorte d'injonction contradictoire{nbsp}: on incite les personnes à faire des choses utiles tout en ne les récompensant pas pour cela.
Cela peut être une excellente manière de limiter les augmentations de salaire.

=== Ce qui est valorisé par l'organisation mais pas bon pour elle

image::recompense-pas-bon.svg[]

Là on touche à une zone vraiment dangereuse, surtout si en plus la zone valorisée rejoint les zones "`envie`" ou "`carrière`", car alors les personnes auront plusieurs raisons de faire des choix qui ne seront pas utiles à l'organisation, voire qui la desservent.

Dans cette situation je ne pense pas qu'on puisse en vouloir à une personne de faire le choix qui est le plus intéressant pour elle, c'est-à-dire d'opter pour la solution la mieux valorisée.

Pour les personnes qui ont à cœur de bien faire les choses, le fait d'avoir à choisir entre son intérêt et celui de l'organisation où elles travaillent peut être déchirant.

Ici encore on a un bon candidat pour faire bouger les lignes.

=== Ce qui est conseillé et bon, mais rien d'autre

image::conseille-bon-mais.svg[]

Je n'avais pas encore reparlé de la zone conseil.

Quand j'ai travaillé dans le conseil c'est une zone dont je discutait beaucoup avec certains amis{nbsp}:que faire quand la proposition qu'on pense la meilleure pour une organisation ne fait pas envie ni n'est utile aux personnes qui y travaillent, voire va à l'encontre de leurs intérêt.

Par exemple si on vous consulte sur "`faut-il mettre à jour le legacy ou réécrire ?`", les personnes qui auraient à travailler sur le legacy n'ont peut-être ni envie ni intérêt de le faire.
Et peut-être qu'en interne, ces personnes obtiendraient plus facilement des augmentations en sortant une nouvelle application avec des technologies nouvelles.

Ça signifie que même si elle semble être acceptée, ce genre de proposition de grande chance de mal finir.

Sans compter la question éthique de proposer quelque chose qui sert une organisation plutôt que les personnes qui y travaillent.

Je me demande si dans certains cas, les organisations qui savent qu'elles sont dans ce type de situation choisissent justement de faire appel à un avis extérieur pour faire passer un choix en évitant d'en prendre la responsabilité.

À nouveau il n'y a pas de solution magique, une des seules possibilité est de faire du lobbying pour que la bonne solution soit valorisée pour qu'au moins les personnes aient une raison de vous suivre.

== Pour conclure

J'espère que l'article vous auras donné quelques idées, voir même vous aura donné envie de réfléchir à vos dernières décisions pour voir où elles se trouvent sur le schéma.

Qu'une décision se trouve à un certain endroit ne signifie pas qu'elle est bonne ou mauvaise.
Seulement qu'elle a certains avantages et inconvénient, et qu'il ne faut pas se mentir quand une décision décision va à l'encontre de certains intérêt.