= Transmettre ses connaissances
Julien Kirch
v0.1, 2020-10-13
:article_lang: fr

Je parle ici plutôt des compétences liée à une connaissance intellectuelle, par opposition à une compétence manuelle, par exemple un "`coup de main`".

Il est difficile de mesurer la difficulté qu'il faut pour acquérir une certaine compétence.

(Je ne parle pas de mesurer sa compétence dans un domaine, mais d'acquérir une nouvelle compétence.)

== Quand une personne en voit une autre utiliser une compétence

Difficile de savoir la quantité de connaissance mobilisée quand on voit quelqu'un répondre à une question dans un échange{nbsp}: est ce qu'il s'agit d'un cas général et il suffit de mémoriser, ou est ce que cela dépend d'éléments de contexte qui ne sont pas forcément explicités.

[qanda]
____
Est ce qu'il est pertinent d'utiliser MongoDB{nbsp}?::
  Non
Non jamais, ou non pas dans ce cas précis ?::
____

== Quand une personne veut transmettre une de ses compétence à une autre personne

Quand on veut transmettre une compétence qui n'est pas seulement un fait isolé, il est en règle générale difficile de mesurer la quantité de connaissances qu'il faut transmettre.

Une compétence peut s'appuyer sur de nombreux éléments secondaires, qu'on mobilise de manière pas toujours consciente, typiquement l'expérience qu'on a pu accumuler sur un sujet pendant des mois ou des années.

Pour transmettre la compétence telle qu'on la possède, il faudrait transmettre l'intégralité de cette connaissance.

== Être efficace

Pour être efficace, il est tentant de séparer cette connaissance en deux partie :

. la partie qu'on explique en justifiant
. la partie qu'on n'explique pas mais qu'il faut savoir.

L'idée est que la deuxième partie correspond aux éléments qu'on n'a pas besoin de comprendre pour pouvoir utiliser la compétence, et où savoir par cœur suffit.

[qanda]
____
Pour MongoDB c'est facile{nbsp}: il ne faut jamais l'utiliser.::
  Jamais jamais, ou jamais mais dès fois quand même{nbsp}?
____

Le problème est qu'il est souvent difficile dans ce cas là d'expliquer dans quel cas le savoir par cœur n'est pas adapté.
Car cela revient à expliquer cette partie de manière détaillée.

== Le contexte

Quand on est dans un certain contexte et qu'on explique quelque chose, il est facile de perdre conscience de ce contexte, et du coup d'oublier que ce qu'on explique est vrai dans ce contexte mais pas dans un autre{nbsp}?

[qanda]
____
Pour MongoDB c'est facile{nbsp}: il ne faut jamais l'utiliser.::
  Dans aucun contexte{nbsp}?
Ça dépend, si t'as le choix entre MongoDB et Oracle…
____

Une personne qui en aura vu une autre mobiliser une compétence toujours dans le même contexte pourra ainsi avoir une idée tout à fait fausse des connaissances à avoir.

[qanda]
____
Mais tu disais toujours que MongoDB était la bonne solution{nbsp}::
  Oui mais à chaque fois c'était ça ou Oracle{nbsp}!
____
