= Loi de Goodhart et organisations pilotées par la donnée
Julien Kirch
v0.1, 2019-02-10
:article_lang: fr

Depuis quelques années, les organisations pilotées par la donnée (_data-driven organisations_ en anglais) sont à la mode.

L'idée est de ne pas piloter seulement les parties industrielles, par exemple mesurer la qualité, mais toute l'organisation, jusqu'aux décisions marketing et de gestion des personnes.

Poussé par des startups, par le même groupe de personnes qui aiment citer la loi de Goodhart.

[quote,'link:https://fr.wikipedia.org/wiki/Loi_de_Goodhart[Charles Goodhart]']
____
Lorsqu'une mesure devient un objectif, elle cesse d'être une bonne mesure.
____

L'opposition entre les deux suffit à illustrer le ridicule du pilotage et je pourrais presque m'arrêter là, mais creuser un peu cette opposition permet d'illustrer quelques éléments intéressants.

== « L'algorithme est objectif »

La métrique est rationnelle, s'en remettre à elle évite les jugements biaisés.

En tout cas c'est la théorie derrière le pilotage par la donnée : en décidant sur des mesures, plus de subjectivité.

Le contre-argument, popularisé par link:https://www.mathwashing.com[les critiques de l'intelligence artificelle], c'est que la subjectivité se cache alors dans l'algorithme.

C'est la différence entre appliquer une formule de calcul et choisir une formule plutôt qu'une autre, par exemple pour mesurer la productivité d'un ou d'une employée.

Piloter par la donnée pourquoi pas, si on assume le fait que le choix et la construction des données sont des choix, mais pas si c'est pour faire croire que les données sont immanentes.

== Le mythe de la métrique

Poussée pour utiliser des métriques, pour éviter les biais.

Cela correspond à un certain type de pensée où tout ce qui est important est quantifiable, à l'intersection du scientisme et du libéralisme économique.

Souvent par exemple on ne mesure que partiellements les choses, et que d'autres choses sont mal ou peu mesurées.

Les mesures correspondent à ce qu'on pense être important : on importe nos biais, et on oublie ce qui n'est pas mesurable.

Même quand on mesure bien, la loi de Goodhart illustre le fait que de prendre des quantités pour cibles est facteur de risque.

== Leadership et absence de courage

On parle beaucoup de leadership et d'innitiative, mais ce que je vois avec le pilotage par la donnée c'est tout l'inverse : piloter par la donnée c'est ne permettre que des initiatives qui agissent sur les bonnes données : ne permet pas l'inovation qui n'ai été anticipé dans les calculs.

Les seules personnes qui peuvent innover sont celles sur qui les chiffres ne s'appliquent pas, ou qui décident de quels chiffres s'appliquent.

Dans mon expérience, ça permet surtout aux manager de ne pas prendre de décision, ou de ne pas les assumer si on sait manier les indicateurs.

== « Oui mais non »

Quand on cite la loi de Goodhart dans ces organisations, "oui mais on sait bien qu'elles sont partielles, les gens ne vont pas suivre les règles au pieds de la lettre car ils et elles savent que l'objectif est le bien de l'orga et pas juste les chiffre".

link:../suivez-l-argent/[on ne peut pas demander aux personnes d'aller à l'encontre de leurs intérêts pour celui de l'organisation].
Souvent les personnes le font quand même un peu, ne serais-ce que parce qu'elles sont professionnelles, mais du coup ces personnes sont désavantagées par rapport aux personnes qui ne le font pas.

C'est vrai qu'il y a des marges de manœuvres, des exceptions : il est souvent possible d'être récompensé même si on ne suit pas la règle.
Malheursement link:../legitimite/[les personnes qui se sentent légitimes de ne pas appliquer la règle] et qui trouvent la bonne manière de ce justifier que leur cas est une exception.

== En conclusion

Pour moi le problème ne sont pas tant les organisations, que les personnes qui subissent leurs dysfonctionnements.

Pas de mesure ou pas de règles ce n'est pas bon, cf link:https://www.jofreeman.com/joreen/tyranny.htm[la tyrannie de l'absence de structure].

Mais n'utiliser que des métriques pose d'autres soucis, qu'en plus on peut pas voir car on pense qu'on maîtrise ce dont on a besoin.

Il faut des mesure mais ne pas se leurer sur leur limite, et avoir le courage de prendre et d'assumer des décisions.
