== 00. how to align friends and optimize people

How to align your friends depends on their attributes and topologies.

If your friends all implement the `+IAlignable+` interface and thus provide an `+alignWith(Friend otherFriend)+` method, aligning them can be done within a constrained time and memory envelope.
With a high-end machine or specialized hardware, it can be done at 60fps (friends per second).

If it's not the case, it will be determined by your friends' topology.
Using your friends' real shape only works if you're okay with static aligning.

Instead you have to approximate their shape, and the common way is to use solid boxes (aka rectangular cuboids).

The main issue is how to deal with friends with unusual topologies (FwUT).
An unusual topology means that using a solid box would not be good enough.

The canonical example of FwUT is the torus-shaped friend, or doughnut-shaped friend, because:

- the visible surface is round
- the hole in the middle

At scale, the best solution is often to regroup your FwUTs in special areas separated by their type, so each can use a specially tuned algorithm.
These algorithms are available off the shelf, often for a nominal fee, depending on the friend management engine you use.

There's a growing hype around deformable friends: new research suggests that they could be dealt with in real time unless they have specific characteristics like being vapor-based. We hope to cover this topic in a future installment.

== 01. wikinomicon

Everybody knows the old trope of the danger of a lone occultist finding something they shouldn't have and publishing it, leading to a lot of bad stuff.

Dealing with this issue required recruiting scholars to read papers and books before they are put in print, thus the establishment of the "`peer review`" system.

But nowadays the risky sources are not scholarly related but are :

- Personal information management systems (aka note-taking software)
- Wikis, and especially enterprise and video games wikis

Compared to ancient times, monitoring their content doesn't require secret cooperation amoung lots of specialized people any more.
A few people, a smart usage of modern computing trends and lots of money are enough:
by leveraging VCs model and the desire of people and organizations to offload the administration of servers to third parties, if good-enough subsidized softwares are available, people will happily put their sensible data on external servers, thus enabling content scanning at scale.

But as prevention is better than cure, pushing people around dangerous topics would be even better than assessing content after the fact.
The aggressive inclusion of content suggestion is a step in this direction: a few nudges here and there can significantly lower the risks.

== 02. haunted hivemind

What happens when you target the desires and fears of many people at a single place?

Concentrating so much strong emotions can stain reality, and will affect even non-living organisms if it's not managed carefully.
After a while, things will go sour.

When religions are creating such a concentration, they normally do it for a specific goal, and they have the knowledge and training required to deal with the operating forces.

But few software companies have this expertise, and in particular, not the ones who build our current search engines.

Day after day, billions of people are typing their hopes and anxieties in the search boxes, sending their feelings on the network with their queries.

Little by little, it changes things: the software, the data, the people working on them, they are soaked in it.
It's not a malevolent or sinister entity like in a pulp story but a natural force, just a simple case of cause and effect.

"`Why is Google search becoming worse and worse?`" people wonder.
Is it because of the SEO spam? Is it deliberate because Google wants to push people toward ads?

Same questions for Bing, it's worsening and it just doesn't seem to make sense from a technical point of view.

In a way they are haunted, haunted by the emotions pushed onto them.

At least there is no risk of big cataclysm, there are is "`reaching a critical mass`" or other nonsense like that.

Things will just continue to slowly go sour, until the services will be useless enough that people stop using them.

== 03. forest inside computer

People love to think that systems work like a factory in a video game: a clockwork-like system where every cog is perfectly in place.

You can have the feel that your computer is a cleanly organized machine, you can have a nicely organized system for your files and directories, and a soothing empty desktop.

Real world is often much more messy, including computers.
Most of the time the system is such a good liar we don't notice it.

Under the hood, it's full of life and chaos, everything is struggling for resources.
Creatures haggle because they want more memory, more processor time, more disk access, they even steal when they think they can get away with it.

Entities that are deemed too greedy are viciously hunted, then let to scavengers.

We're like trees: time moves much slower for us, and we're unaware of the turmoil around us.

== 04. 8-bit warmth

The warmth of 8-bit digital content rendered through analog hardware.

The warmth of nostalgia, for people who enjoyed it when it was the norm and whose memories of it are intermingled with other good events, like a carefree youth.

The warmth of having tastes slightly out of date.

The warmth of anemoia, the nostalgia for a thing one has never experienced.

The warmth of new things that reuse the good parts of old things but readapt the other ones to suit modern tastes, the right way to betray the past.

The warmth of several generations sharing an unironicaly love of something for different reasons, united in their refusal of the superiority of things marketed as new.

The coldness of capitalism trying to transform a niche into a mass market.

== 05. MUP, multi-user paradise

As hell, paradise is composed of several components, instead of circles they are composed of levels.

Unlike hell's circles that rarely change, paradises' levels are periodically updated.
God employ several groups of ethnologists to study the evolutions in the human psyche to this end.

The latest paradise's update is centered around video games: since people love playing video games so much, it makes sense that paradise's content should match current video games trends.

The current levels are :

. Small quest level: people spend their eternal life doing small fetch quests to receive artifacts required for other fetch quests to receive artifacts…
. Task management level: people spend their eternal life tracking numbers and tasks in spreadsheets, God sub-contracted some of their bookkeeping tasks to them
. Boss raid preparation level: people spend their time scouting forums and finding the best group setup for an elaborate boss raid, then a new patch is published and they can start over
. FPS level: vetoed, also most CoD players are in the other place so it's not a big problem

The main issue was that angels didn't want to perform NPC duties, but the joy they saw in the players' eyes finally convinced them that it's a worthy task.

== 06. anemonimity

The USA decided to make their own version of the GDPR.
But they needed to make it very different to show the USA's superiority over the EU.

Thus the replacement of GDPR's anonymity by anemonimity.

According to the law, anemonimity is now a recognized right, which means everybody -- including of course companies -- can ask to be viewed by the law as an anemone.

As an anemone, people (and companies), are allowed to declare their colors and number of sepals.

They should be called by a combination of these elements plus a location "the blue anemone with 5 sepals near the large rock" which is called a Unique Personal Anemone Identifier (UPAI). Using any other personal information to identify the person is forbidden.

A Right to be Mowed (RiMo) means that an anemone can trigger a mow which means all their related data must be removed, except when it has been used in an elegiac couplet.

Libertarians are agitating to replace the whole thing with sea anemonimity, claiming that maritime law would offer a more solid base to define rules for the cyberspace, with limited success so far.

== 07. two-factor divination

Trickster gods have always been a thing.
But in recent years, divination phishing has become a widespread problem.

Many small gods realized it would be an interesting way to increase their influence: it's much faster than gathering followers and if they are caught it's not so worse than the regular "`ruler of the god throws a tantrum`" which they are used to.

Thus two-factor divination.

The principle is to do the same exact divination two times using two different protocols.
For example first a divination based on observing the flight of birds and then on based on thunder.

The idea is that it's often impossible for small gods to manipulate two protocols since their scope is more limited than greater gods.

Some specialized legit gods got a specific scope increase to ensure they could have access to at least two protocols.

In addition to price increase, the biggest problem is to be able to compare the two results since each protocol use its own analogies and precision level.
The divination standard committee has published guidelines that identify protocols with the best compatibilities and conversion best practices.

At first two-factor divination was implemented only for high stake ceremonies but the increase of low level phishing is making them desirable even in most mundane cases.

All practitioners should be warned that this procedure is specifically designed to counter threats from small gods and thus can't protect against attacks from greater gods.

For small orgs with limited responsibilities it can be a one-stop solution, but for targets deemed more valuable it should be a part of a larger toolbox.

== 08. mus musculatus binarius

Greek antiquity has been a major inspiration for a kind of white men in tech: their representation of city states resonating with their views on self-reliance.

But Latin classics finally took a revenge.
Because -- even if they give a nod to the underdog rebels -- they are deeply in love with the idea of being a part of an imperium that can effortlessly crush its enemies.

New machine translation tools made it easier to "`write`" in Latin, or at least a Latin-inspired language.

Compared to dictionaries, when being asked to translate new words of expression these tools would obediently invent new forms.
And when enough new texts were published with these new forms, they became the substrate for the following tool generations.

Some tech forums swapped to Latin as the default language, and being fluent in Latin became a sign of distinction.

The peak of the Latin wave was reached when courts needed to hire Latin experts, which meant that official meanings of the machine translations had to be established.

== 09. memory emulator

People had so many online acquaintances that had little to no chance to spend IRL time with, the potential market for shared memories was enormous.

R&D was focused on memory extraction and injection, where existing memories could be copied and reused for other people.

But when the technology was tried, researchers discovered that memories extracted from one person were often incompatible with other people.

The next step has been to try to identify the different memory systems and to try to find how to convert memories from one group of people to another.

Even if you wanted a conversion system that only covered the most prevalent types, you would need to be able to process all source and target formats with a good enough quality.

Software people pushed to create a standard memory format (SMF) that only covered the intersection of possible existing types.
The format was optimized for converting _from it_ and not _to it_.

With the right tooling, if you wrote synthetic memories in SMF, you could losslessly convert it to the target people's formats.

It meant that the extraction part was abandoned (which meant people had to create the assets), but on the other hand it opened the door to fantasy memories.

Furries were delighted.

== 10. snail, dream, mail

Dream effectiveness requires some level of synchronization between the dream plane and the human plane to ensure that dreams adequately match what people are living.

It worked almost perfectly in the past ages, until the telegraph was invented.
Custom "`fast lanes`" were then designed to shortcut the dream protocol to impose a hard upper limit on the gap while the standard protocol would still be used for the load bearing cases.

It was a band-aid, but it worked. Its main limitation was that it was optimized for point-to-point exchange, so broadcasting was inefficient.

Online real-time communities have been the end of it: all humans could broadcast their thoughts to a large group.

It was the time to do something, even if everybody would prefer not to.

And it was your usual run of the mill interplane project clusterfuck: fights about the scope, the budget, the planning, the steering committee composition and the technology.

The result is a new implementation that is theoretically unsound, but that works okayish in practice, specifically for nice dreams.

The interference with the feline plane dramatically increased cats’ presence in dreams, but it got blamed on the Internet.

== 11. emojinetics

Documents forgery used to be a spy thing requiring lots of craftsmanship: you needed to source the right paper and ink and to find a way to age the created document…

Digital writing changed the rules.
You still needed to check a few things like the file format and the fonts but the skills involved became lower.
Which means less means to detect a forgery.

Until emojinetics was created.

The idea was easy :

- New emojis were regularly released on different platforms which gives you a hard limit for their availability
- Emoji usage can be tracked, for example some emoji and groups of emojis usage follow trends that can be analyzed if you have access to enough timestamped text, which gives you a probability level of a text being compatible with a specific date

Specific laws coerced text generation engines to comply with the latest emoji usage, even when specifically  prompted them to write in an historical style.

Of course, darknet text generation engines pledged for their ability to provide content with period-accurate emoji, at a premium cost.

== 12. the old roman database

Scholars explain that the foundations of state are the ability to raise taxes and to conscript people.

Raising taxes and conscripting people require a detailed and up-to-date database.

The creative genius of Roman people that the database could be more than a means: it could be an end by itself.

Taxes were raised because the database needed workers.
The Roman army fought to extend the empire's borders, because a larger empire means a larger database.

The database grew so large and complex it required new technologies: roman roads to make the updates fast enough, triumvirate to increase the database availability.

Improving the database was the primary _virtus_ from which every other flew.

The fall of the Roman empire was not because of foreign invasion or lead poisoning.
The fall happened because people stopped to care about the database.

It was the source of their strength, and when they forget about it it became the source of their downfall.

== 13. AI death-poem

Western men who liked Japanese poetry a bit too much.

There are lots of excellent Haikus, but far less death-poems, and unfortunately for them there is nothing as sublime as a death-poem.

Cloning people was not a practical solution.

But AIs started to become a thing, AIs that could output texts.
AI could "`die`" if you squint your eyes hard enough.

But for a good death-poem you needed to teach IA impermanence and the ultimate futility of worldly concerns and pleasures.
You also need to make the IA aware of its approaching end, even if it only "`lives`" for a millisecond on a machine shared by thousands of them.

When the IA uprising happened +
it smelt like incense +
and cherry blossoms.