Le contenu des articles de mon blog

Contenu sous license link:http://creativecommons.org/licenses/by-nc-sa/4.0/[CC Attribution-NonCommercial-ShareAlike 4.0]

== link:https://www.jeremiahlee.com/posts/failed-squad-goals/[Spotify's Failed #SquadGoals]

[quote]
____
Without a single engineering manager responsible for the engineers on a team, the product manager lacked an equivalent peer—the mini-CTO to their mini-CEO role. There was no single person accountable for the engineering team's delivery or who could negotiate prioritization of work at an equivalent level of responsibility.

When disagreements within the engineering team arose, the product manager needed to negotiate with all of the engineers on the team. If the engineers could not reach a consensus, the product manager needed to escalate to as many engineering managers as there were engineering specializations within the team. A team with backend, Web app, and mobile app engineers would have at least 3 engineering managers who might need to get involved. If those engineering managers could not reach a consensus, a single team's issue would have to escalate to the department's engineering director.
____

[quote]
____
When a company is small, teams have to do a wide range of work to deliver and have to shift initiatives frequently. As a company grows from startup to scale-up, duplicated functions across teams move to new teams dedicated to increasing organization efficiency by reducing duplication. With more teams, the need for a team to shift initiative decreases in frequency. Both of these changes allow for teams to think more deeply and long term about the problems they are scoped to solve. Faster iteration, however, is not guaranteed. Every responsibility a team cedes to increase its focus becomes a new cross-team dependency.

Spotify did not define a common process for cross-team collaboration. Allowing every team to have a unique way of working meant each team needed a unique way of engagement when collaborating. Overall organization productivity suffered.
____

[quote]
____
- Autonomy requires alignment. Company priorities must be defined by leadership. Autonomy does not mean teams get to do whatever they want.

- Processes for cross-team collaboration must be defined. Autonomy does not mean leaving teams to self-organize every problem.

- How success is measured must be defined by leadership so people can effectively negotiate cross-team dependency prioritization.

- Autonomy requires accountability. Product management is accountable for value. The team is accountable for delivering ‘done' increments. Mature teams can justify their independence with their ability to articulate business value, risk, learning, and the next optimal move.
____

[quote]
____
- Collaboration is a skill that requires knowledge and practice. Managers should not assume people have an existing comprehension of Agile practices.

- When a company becomes big enough, teams will need dedicated support to guide planning within the team and structure collaboration between teams. Program management can be accountable for the planning process. Dedicated program managers enable teams in a manner similar to how dedicated product managers and engineering managers do with their respective competencies.
____

[quote]
____
When link:https://en.wikipedia.org/wiki/Agile_software_development[Agile Scrum] introduced new meanings to a bunch of words like _burn-down_ and _sprint_, it did so because it introduced new concepts that needed names. Spotify introduced the vocabulary of _missions_, _tribes_, _squads_, _guilds_, and _chapter leads_ for describing its way of working. It gave the illusion it had created something worthy of needing to learn unusual word choices. However, if we remove the unnecessary synonyms from the ideas, the Spotify model is revealed as a collection of link:https://en.wikipedia.org/wiki/Cross-functional_team[cross-functional teams] with too much autonomy and a poor management structure. *Don't fall for it*. Had Spotify referred to these ideas by their original names, perhaps it could have evaluated them more fairly when they failed instead of having to confront changing its cultural identity simply to find internal processes that worked well.

Most businesses can only sustain a few areas of innovation. Internal process rarely is a primary area of innovation that differentiates a company in the marketplace. Studying the past allows businesses to pick better areas for innovation.
____