= À propos des entretiens d'embauche
Julien Kirch
v0.1, 2021-03-10
:article_lang: fr

== L'évaluation technique

L'idée de l'évaluation est de parvenir à déterminer les compétences de la personne qui a candidaté dans l'exercice de son travail.
Et malheureusement, le cadre des entretiens d'embauche n'est pas le même que celui de travailler avec la personne.

Quand on conçoit un exercice à utiliser en entretien, la question à se poser est donc de déterminer quelles sont les compétences qu'on veut vérifier (il peut s'agir de connaissances, de savoir-faire ou même de savoir-être), et ensuite de voir s'il existe un moyen de déterminer si la personne possède cette compétence à travers d'un exercice.

Dit autrement : on veut vérifier si la personne sait A, on ne peut pas lui demander de faire A, mais on peut lui demander de faire B, et si faire B est un bon indicateur de la capacité à faire A, alors B est un bon exercice.

Parfois la solution est d'avoir un exercice qui ressemble à quelque chose que la personne aurait faire dans le cadre de son travail, ou une version réduite mais qui permet quand même de servir de filtre.

On peut aussi avoir un exercice différent du travail typique de la personne, mais dont on pense qu'il peut servir de révélateur.
Le risque est que s'il est trop différent, la personne peut ne pas appliquer ses réflexes habituel qui sont ceux qu'on veut tester.

En tant que candidat·e face à un exercice, il faut donc vous demander ce que l'exercice est sensé tester.

L'idée n'est pas (forcément) de tricher, mais d'essayer de ne pas vous tromper sur ce qu'on attend de vous en choisissant la réponse adéquate dans la gamme des réponses possibles.

Ça peut ressembler à jouer aux échecs en 5 dimensions, mais pour quelqu'un qui travaille dans le développement, et surtout une personne expérimentée, je pense que d'essayer de comprendre ce qu'on attend de vous et de réfléchir à la manière de s'y adapter est une compétence nécessaire.

De ce point de vue, filtrer les personnes qui n'ont pas cette compétence peut dont être une bonne idée.

== La motivation