= Software manifestos
Julien Kirch; Fabien Lamarque
v0.1, 2022-02-03
:article_lang: en

== How software manifestos sounded when I was young

* EATING BURNING HOT LAVA OVER GETTING ICE CREAM
* TRANSFORMING INTO A HUMONGOUS STAR-SHAPED ENTITY OVER KEEPING YOUR HUMAN FORM
* LIVING OUTSIDE SPACE AND TIME OVER ACCEPTING PHYSICAL REALITY
* KILLING GOD WITH YOUR BARE HANDS OVER LIVING A HAPPY LIFE

WE AGREE THE ITEMS ON THE RIGHT EXIST, BUT WE'LL MOCK YOU MERCYLESSLY IF YOU THINK THEY HAVE ANY VALUE, A̴̯̲̋̀L̸͙̾͋L̶͈̦͊͘ ̵̱͎͠H̷̫̠́Ȃ̴̮͍Ḭ̶̧͊L̸̞̈ ̴̞̟̄̕T̸̟̊͝H̵̞̅É̴̯ ̸̡̜̌D̴̛̰̥̕Ȧ̴̰̺̅R̶̬̆̈K̸̩͙͝ ̸̊͒ͅL̸͙͖̉Ó̴̹̈́R̴̥̔̆Ḍ̵̨͛.

== How software manifestos sound now

* working code is nice, in some cases it may be better that non-working code
* trying to do useful things instead of things you don't need may be something to explore, but no biggie
* software development is often easier if you have a computer at your disposal, but ymmv
* this is a little fourth item, because all software manifestos should have four items

we hope you have a pleasant day, xoxo