== Fighting fake traditions and nostalgia

link:https://en.wikipedia.org/wiki/Invented_tradition[Tradition are often lies], congealing practices by presenting them as older and more widespread than they were, and even if they can increase communities' internal cohesion, they can also increase xenophobia and make social changes more difficult.

Similarly, nostalgia is an incredible way for businesses to sell overpriced goods to adults by leveraging people's feelings towards "`good old days`", but it makes introducing new products more difficult and thus reduce market innovation.

The High Council on Change meant to prevent social and technical stagnation decided to launch a new long-term initiative aimed at curbing them.

This approach will rely on the new memory snapshoting technology to ensure an adequate recording of the past.

Each year, a few people -- chosen to be representative of existing and emerging cultural groups -- will be selected to be snapshoted.

The archives will be dedicated to answer any questions regarding tradition: any appearing tradition will be compared to the memories of the relevant snapshots to separate real history from forged one.

The low usage expected rate should drastically cap the operating cost of the apparatus.

Any spotted error will be made public with a specific institutional brochure.

This should trigger a "`natural`" social response that should be strong enough to fight the disinformation operation. 