== Fighting fake traditions and nostalgia

link:https://en.wikipedia.org/wiki/Invented_tradition[Tradition are often lies], congealing practices by presenting them as older and more widespread than they were, and even if they can increase communities' internal cohesion, they can also increase xenophobia and make social changes more difficult.

Similarly, nostalgia is an incredible way for businesses to sell overpriced goods to adults by leveraging people's feelings towards "`good old days`", but it makes introducing new products more difficult and thus reduce market innovation.

The High Council on Change meant to prevent social and technical stagnation decided to launch a new long-term initiative aimed at curbing them.

This approach will rely on the new memory snapshoting technology to ensure an adequate recording of the past.

Each year, a few people -- chosen to be representative of existing and emerging cultural groups -- will be selected to be snapshoted.

The archives will be dedicated to answer any questions regarding tradition: any appearing tradition will be compared to the memories of the relevant snapshots to separate real history from forged one.

The low usage expected rate should drastically cap the operating cost of the apparatus.

Any spotted error will be made public with a specific institutional brochure.

This should trigger a "`natural`" social response that should be strong enough to fight the disinformation operation.

== Your all-in-one solution for prophecy preparation

_You're the ruler of a nation where a new prophecy has been published about a hero that will defeat the great evil, and you realize you don't know how to deal with it? WE CAN HELP!_

We're a comprehensive network of highly experienced professionals, everything you need to prepare for a prophecy in a turnkey contract, tailored to your custom needs and constraints.

Some selected profiles :

- Senior hydraulics engineer to design and manage the renovation of your capital sewers, including labyrinthine corridors and large rooms for boss fights, special price for water level changing using levers.
- Devouring flame ancient to negotiate lava quota supply with volcanic entities, ensuring a high-quality volcano level experience.
- Cursed cauldron pestilence witch to infuse your swamps with top of the shelf miasma. Swamps can feel dated, but storytellers still love them: if you want your investments to pay off in fame for centuries, horrible swamps are a must-have, don't listen to the haters.

For busy rulers, executive managers are available on an availability basis: you hate to go to the elder gods' council to report on your preparations? We can do it for you on a cost-plus basis.

For premium plus packages and above, the handover with the great evil transition team is free.
