[#GM]
= General microfictions
ifeval::["{doctype}" != "book"]
Julien Kirch
v0.1, 2023-01-15
:article_lang: en
endif::[]

== New tooth fairies EU regulations

Following many other utilities like phone, electricity and natural gas, the tooth fairies market will soon be opened to competitions.

In most EU countries, tooth fairies are a public utility, which often means a bad level of service and a high cost.

=== Overview

From January 1, 2026, the children tooth recovery market will be open to competition: tooth fairies will be allowed to create companies and establish themselves in the geographical area of their choice.

Each country will ensure the creation of an online platform allowing the companies to register themselves to allow easy consultation by parents.

=== Rules

Companies will be required to offer a "`basic plan`", which is the equivalent of the current state-provided offer, but apart from it they can offer more complex deals, including over-the-counter ones, as long as the health and sneak requirements are matched.

=== White zones

So-called "`white zones`" that are difficult to reach and/or low population density must still be covered.

To ensure this, states are allowed to use mechanisms like subsidies or one-provider zones as long as they don't infringe on the general free competition principle.

=== Essential services status

A steady stream of recent high quality teeth are required as raw materials for essential services in each EU state.

States are allowed to compel companies to sell them a part of their teeth at pre-established rates to avoid speculations and other market manipulations that would endanger this supply chain.

As a last resort mechanism, a EU strategic teeth reserve will be established to protect states against possible failures from their providers.

=== Programs and human languages

Cats don't meow at each other: they only meow at humans because they discovered that it's the best way to (sometimes) make humans obey to what they want.

It's the same for software programs and messages.

Feral software programs don't use messages to communicate between them: only domesticated programs do, or programs that were domesticated and broke free or who descend from such a program.

Programs don't understand human languages: they mimic the text fragments they can find on the computer they live in and try to combine them until they obtain the result they want.
It explains that messages are sometimes malformed or don't make sense.

== Isekaied to Isekai

You wake up.

The room is unfamiliar but comfortingly nondescript: a wood bed, a fireplace, a wood stool, a wood table and some clay pots you're tempted to break to see if they contain rupees.

You put on your nondescript boots and step outside.

You can't hear any motor, it's mostly birds singing and somebody hammering metal.

Along the road you can see a dozen small houses that look like the one you just left, and a larger building in the center of a kind of pedestrian roundabout.

There's a large arrow on the building, pointing to its entrance.

As you approach it, the door opens and someone in cleric's clothes walks out, they look at you up and down.

– Hello, do you understand what I say? +
– Yes, it seems so.

They look relieved.

– Good! I'm Bevis Tusksteel. Happy to meet you. Can you read? +
– Probably, but I'll need to see some writings to be sure.

They smile.

– Yes you're right, please follow me, there's briefing pamphlets inside, then I'll answer your questions.

The building contains a large reception desk with a pile of papers, you assume it was where the cleric was seated, and further some wooden desks and chairs.

The cleric hands you a set of pages.

– Please have a seat and read this, I'm available when you'll have finished your reading.

You take the pamphlet and choose a seat, facing the door and the desk, and start reading:

_Welcome to Isekai_

If you read this you probably just woke up in a small house, and yesterday you were living in another place.

Please be welcome to Isekai.

_Is this place really called Isekai?_

You probably heard this word before.
This small town has been called Isekai since the previous age, it's where the word comes from.

The unfortunate "`Useful scrolls for intermediate mages, 2^nd^ edition`" contains a "`Transmogrify a Person to Another Plane and Time`" entry, and its default configuration is pointing to here and now.

It's why this scroll is nicknamed "`Isekai`".

As mages are easily excited with new scrolls, many of them try the scroll without adjusting the parameters, and thus many people end up here.

The 3^rd^ edition has changed to point to a random place and time, but it's too late for the 2^nd^.

The town has struck a deal with the mage school who printed this book. To atone for their mistake, the mages are funding the facilities you see around.

We tried to convince them to trigger a post-facto rewrite of the 2^nd^ edition but they wouldn't budge.

_What will happen to you?_

You'll be provided a small sum of money, and are allowed to stay in your place of arrival for 100 days.

People that have been transmogrified here must leave the city after 100 days, and can only come back occasionally.
We want to avoid people sticking around.

The various shops and craftpeople can provide you with some apprenticeship if you want to learn new skills, but remember you'll have to leave.

_What about the sloppy person that sent me here?_

A high level scroll user should be able to identify the person or group of people responsible for what happened to you.

There are no high level scroll users living here, so if it's something you want you'll need to seek them elsewhere, and their services are not cheap.

_We sincerely hope your stay will be pleasant, good luck._