= Aimer mettre en place des solutions ou aimer résoudre des problèmes
Julien Kirch
v0.1, 2020-06-01
:article_lang: fr

[quote]
____
Les juniors aiment mettre en place des solutions, les seniors aiment résoudre des problèmes
____

J'ai beaucoup entendu cette phrase, et je pense qu'à un moment je la disais moi-même.

L'idée est que les personnes débutantes veulent surtout utiliser des outils qu'elles aiment plutôt que d'essayer de vraiment comprendre quel est le problème à résoudre, alors que les personnes expérimentées considèrent toujours le besoin et jamais leurs envies personnelles.

Elle est plaisante à dire quand on est soi-même senior, car elle exprime l'idée que quand on débute on encore un peu comme un·e enfant, alors qu'avec l'expérience on s'assagit en développant une forme d'abnégation où on se sacrifie le bien de l'organisation pour laquelle on travaille.

Puis l'entendre a commencé à m'énerver, et à la longue je pense que j'ai fini par comprendre pourquoi.

Le pourquoi est assez facile{nbsp}: c'est parce dans la majorité des cas que j'ai rencontré c'est faux.

C'est faux parce que beaucoup de personnes débutantes que j'ai rencontré aiment mettre en place des solutions mais aussi résoudre des problèmes.

C'est faux aussi parce que beaucoup de personnes expérimentées que j'ai rencontré adorent mettre en place les solutions qu'elles aiment, et qu'à la pause café elles sont intarissables sur leur marotte du moment qu'elles voudraient essayer.

La différence la plus importante que j'ai constaté entre les deux populations c'est la manière dont elles présentent les choses.

En effet, les personnes expérimentées ont appris que pour être entendues, il ne fallait pas dire ouvertement "`j'ai envie de faire des microservices ça a l'air top, est ce qu'on pourrait essayer{nbsp}?`" mais qu'il fallait dire "`j'ai l'impression que nos problèmes de montée à l'échelle et d'agilité pourraient être résolu par une approche microservices, qu'en pensez-vous{nbsp}?`".

L'idée est qu'au lieu d'exprimer son envie de faire A, il fallait trouver les bonnes raisons qui pourrait justifier de faire A (quitte à grossir le trait), et les mettre en avant de manière neutre pour que la proposition de faire A apparaisse autant que possible comme désintéressée.

Devenir senior dans ce domaine, ce n'est donc pas apprendre à sacrifier ses envies et sa curiosité, mais apprendre quels sont les arguments qui font mouche, c'est-à-dire qui sont acceptables pour l'organisation pour laquelle on travail, et apprendre à les utiliser tout en dissimulant ses sentiments.

Et ainsi présenter de l'extérieure l'attitude professionnelle qui est attendue de vous.

Si vous êtes junior, ne vous faites pas avoir, n'abandonnez pas vos envies, et n'écoutez pas tout ce qu'on vous dit.