= Loi de Brooks et jeux vidéos
Julien Kirch
v0.1, 2022-01-24
:article_lang: fr

Voici un tweet que j'ai vu il n'y pas longtemps, et dont je crois déjà vu des variations plusieurs fois{nbsp}:

[quote]
____
On est 2022 et il y a encore des responsables qui face à un projet en retard réagissent en embauchant plus de personnes pour développer, demandent aux équipent de travailler plus longtemps, et arrêtent de faire des tests. Ces trois choses vous feront prendre encore plus de retard.
____

Deux choses me font réagir dans ce mail.

= La formulation

Le mépris qui s'en dégage de la part d'une personne qui sait (et qui sait depuis longtemps à priori) et les personnes qui ne savent pas, alors qu'elle devraient savoir.

En passant, si vous non plus vous ne savez pas il s'agit de link:https://fr.wikipedia.org/wiki/Loi_de_Brooks[la loi de Brooks], qui vient du link:https://fr.wikipedia.org/wiki/Le_Mythe_du_mois-homme[Mythical Man-Month] de Frederick Brooks, comme ça vous aussi vous faites partie du club.

Tweeter ce genre de chose est je pense moyen commode de souder un groupe, ce groupe des personnes qui savent et qui se sont heurtées à des personnes qui devraient savoir (alors qu'on est quand même en 2022), on peut se reconnaitre dans ce sentiment.

Sauf que selon mon humble avis, quand on soude un groupe sur le fait de mépriser des gens qui ne savent pas, on obtient un groupe de personnes qui méprisent les gens qui ne savent pas, ou au moins pour qui mépriser les gens qui ne savent pas est une comportement qui ne pose pas problème.

(La personne en question est un "`thoughleader`" je ne me permettrait pas ce genre de commentaire sinon.)

== Le contenu

L'autre chose qui m'interpelle c'est le contenu du message.

Cela recoupe en partie ce que j'ai déjà pu écrire sur link:../appris-jeux/[les pratiques de développement des jeux vidéo].

Dans les jeux vidéos la pratique du _crunch_, c'est à dire de travailler sur des horaires étendues jusqu'à 70 heures par semaines, est une habitude quand un projet est en retard.
(Je ne dis pas que c'est une bonne chose, seulement que ça existe)

L'autre pratique habituelle est de déplacer des personne d'un projet en cours pour le mettre sur un projet en retard afin de le faire aboutir plus vite.

Je ne pense pas que les éditeurs de jeux vidéos soient des parangons de bonnes pratiques et ne se trompent jamais.
Mais d'un autre côté, si ces deux pratiques si répandues ne fonctionnaient pas, je me dis qu'elles ne seraient pas si répandues.

Alors certes Frederick Brooks est un auteur culte, et malheureusement en temps que personne qui développe on peut avoir très envie que la loi de Brooks soit vraie (c'est mon cas).

Est ce que ça signifie que cette loi n'est peut-être pas si vraie, et qu'il faudrait peut-être creuser le sujet, même au risque que la conclusion ne soit pas celle qu'on voudrait{nbsp}?

Bonne année 2022 à vous.