= Wardley Map
Julien Kirch
v0.1, 2018-06-18
:article_lang: fr

Un CEO qui se rend compte qu'il est un imposteur car il ne sait pas faire de stratégie d'une manière qui lui donne satisfaction et ne trouve aucune ressource dans les livres de stratégie.
La lecture de Sun Tzu lui apporte l'illumination, et il en conçoit un modèle de conception de stratégie basé cette lecture.

Cela donne un livre qui résume la vision de l'auteur sur la construction de la stratégie d'entreprise d'IT assaisoné de métaphores militaires de film hollywoodien.

Assez intéressant comme pour se faire une idée de quelques pratiques de stratégie d'entreprises si on peut faire abstraction du ton très "self-help pour CEO" et du ton militarisant.

Les "cartes" dont parle le livre sont en fait des schémas classiques, mais que l'auteur appelle carte car elles lui rappellent les cartes utilisées par l'armée et appaisent donc sa soif de vocabulaire militariste.

Élements qui m'ont marqué

Importance de la commoditisation et du build vs buy pour définir la stratégie d'entreprise pour éviter d'être commoditifier sans le savoir

Des divisions différentes pour l'innovation, la construction et l'industrialisation.
À l'inverse du mouvement vers les équipes qui suivent des projets tout au long de leur cycle de vie, l'auteur promeur une vision où des divisions différentes s'occupent des différentes étapes.
Son argument est que les personnes ont des affinités pour l'une ou l'autre des étapets et qu'il vaut donc mieux les dédier à celle qui leur convient.
Cela s'oppose aussi au modèle classique "innovation / industrialisation" car l'auteur prétend que a division en 3 rend la transition d'une étape à l'autre plus douce.