= Wardley Map
Julien Kirch
v0.1, 2018-06-18
:article_lang: fr

link:https://medium.com/wardleymaps[Ce livre] explique la méthode développée par Simon Wardley pour définir des stratégies d'entreprisers à l'aide de "cartes".

Au début du livre, l'auteur raconte le moment où il était CEO d'une grande entreprise qui a eu le sentiment d'être un imposteur car sa manière de faire de la stratégie ne lui donnait pas satisfaction.
Se plngeant ensuite dans les livres de stratégie d'entreprise disponible et n'y trouve pas non plus d'approche qui parvienne à le convaincre.
Au final, la lecture de Sun Tzu lui apporte l'illumination, et il en conçoit un modèle de conception de stratégie basé sur sa compréhension du livre.

Le livre déroule cette méthode, revenant par exemple plusieurs fois sur la situation initiale où l'auteur dirigait une entreprise qui voulait se lancer dans le cloud computing alors que personne autour de lui ne comprenait qu'il s'agissait de l'avenir de l'informatique.

Le livre est assez intéressant car il rassemble beaucoup de bonnes pratiques sur les stratégies possibles, notamment autour de l'IT.
L'auteur a beau dire beaucoup du mal de ce que font les autres, il n'en cite pas moins beaucoup de patterns classiques.

Le texte est facile à lire avec un ton très énergique et bavard façon "self-help pour CEO".

L'auteur met l'accent sur deux éléments :

D'abord la question du build vs. buy et de la commoditisation, lié à la résistance au changement dans les grandes entreprises.
Pour l'auteur les entreprises ont du mal à identifier là où leurs produits vont être commoditisé et là où il faut investir pour être différenciant. Toute une partie de sa méthode de construction de carte est ainsi basée sur les chaînes de valeurs à identifier

Ensuite l'importance de séparer la création de produit en trois phases : l'innovation, la construction et l'industrialisation.
À l'inverse du mouvement vers les équipes qui suivent des projets tout au long de leur cycle de vie, l'auteur promeur une vision où des divisions différentes s'occupent des différentes étapes.
Son argument est que les personnes ont des affinités pour l'une ou l'autre des étapes et qu'il vaut donc mieux les dédier à celle qui leur convient.

Trois choses m'ont posé problème dans le livre.

Tout d'abord l'auteur semble fasciné par l'armée : après Sun Tzu l'auteur poursuit son ton militarisant tout le long du livre, du choix des métaphores jusqu'aux exemples pris chez des fabriquants d'armes.
Cela a rendu ma lecture désagréable.

Ensuite au début du livre il se moque beaucoup des consultants qui vont d'un endroit à l'autre en déroulant des méthodes "tout-terain" alors que c'est exactement l'approche qu'il suit lui-même : il a construit sa méthode sur des convictions après une illumination personelle, il explique qu'elle s'applique à tous les contextes et qu'on peut mapper une entreprise en quelques heures, et il est désormais consultant en "mapping Wardley".
Cela ne signifie pas que son approche n'est pas bonne, mais son ton moqueur et suffisant nuisent à la crédibilité de ce qu'il dit.

Enfin le livre est très haut-niveau et du coup l'auteur passe un peu vite sur la mise en œuvre alors que c'est parfois là que sont les difficultés. Ainsi vouloir constuire une organisation "cellulaire" facile à adapter ou limiter le gaspillage en limitant la duplication entre projets sonne très bien, mais sans détail sur le comment on a parfois l'impression d'une suite de bonnes intentions génériques.

Au final : le livre n'est pas inintéressant mais j'ai eu du mal à le prendre au sérieux.