= Memo en cas de copie de données
Julien Kirch
v0.1, 2018-05-28
:article_lang: fr
:article_description: Une checklist de questions à se poser quand on copie des données entre deux systèmes

Une checklist de questions à se poser quand on copie des données entre deux systèmes.

Répondre à ces questions ne vous garantit pas tout se passera bien, mais ne pas y répondre c'est la quasi-certitude que vous aurez des mauvaises surprises.

Voir link:http://archiloque.net/blog/copies-donnee/[ici] pour savoir repérer tous les cas de copies.

* Comment allez-vous monitorer l'ensemble du système{nbsp}?
* Qui sera chargé de faire que ça fonctionne{nbsp}?
* La source peut-elle modifier les données{nbsp}?
** Si oui que se passe-t-il quand le renvoi au système source échoue{nbsp}?
** Si oui comment le tester de manière automatique{nbsp}?
* Quel est le délai de retard acceptable dans la copie{nbsp}? 
** Que se passe-t-il quand ce délai est dépassé{nbsp}? 
** Comment le tester de manière automatique{nbsp}?
* Est-il possible de perdre des informations lors de la copie{nbsp}? 
** Si oui quels sont les conséquences{nbsp}?
** Si oui comment le tester de manière automatique{nbsp}?
** Si non je vous propose de revérifier au cas où pour être bien certain.
* Est-il possible que le mécanisme de transfert de donnée provoque des duplications de message{nbsp}?
** Si oui quels sont les conséquences{nbsp}?
** Si oui comment le tester de manière automatique{nbsp}?
* Quel moyens et conditions (durée, conséquences sur les performances{nbsp}…) pour refaire une copie "from scratch" de la source (vous en aurez besoin un moment où à un autre){nbsp}? 
** Comment le tester de manière automatique{nbsp}?
* Que se passe-t-il quand le format de donnée change{nbsp}?
* Que se passe-t-il quand des données sont supprimées{nbsp}?
* Le nombre de copies peut-il augmenter{nbsp}?
** Si oui quel en est l'impact{nbsp}?
* Que se passe-t-il en cas d'indisponibilité de la source{nbsp}?
* Le mécanisme de copie est-il compatible avec le système de gestion de disponibilité de la source (bascule actif-passif ou autre){nbsp}?
* Si des copies proviennent de plusieurs sources comment gérer que les informations n'arriveront pas dans le bon ordre{nbsp}?
* La sécurité des données est-elle du même niveau dans les systèmes copies que dans la source{nbsp}?