= Microfictions
Julien Kirch
v0.1, 2023-01-15
:article_lang: en

In older projects, senior projects managers had features sacs where features requests grown.

When a feature request was ready, it was expelled through the PM's extensible mouth and let to dry for a few days before being shown to the development team.

'''

The best way to deal with people complaining about features being removed in a software update is to include a brain-cleansing module in your code: when the module is loaded into a user's browser, any memory of the deleted feature is removed from the user' brains.

'''

When a line of code is written, it captures some of the writer's psychic energy.

When a line of code is deleted, this energy is discharged.
This discharge will affect all people near the peripheral used for editing.

Deleting a lot of code at one can be dangerous.

Using a remote desktop or other technical isolation can reduce the impact, depending of the protocol, but the recommended method is to have a cat sit near the machine during the refactoring since they can harmlessly feed on this energy.

'''

Using automated tools to remove some types of bugs mean the ecological pressure is lower on nastier bugs because competition for food is less harsh.
These harder to fix bugs will probably grow steadily, making software development more difficult.
