= Invisible networks 2022
Julien Kirch
v0.1, 2022-04-01
:article_lang: en
:toc:
:toc-title:
:lang: en
:hyphens:

== Invisible networks

link:https://twitter.com/ctrlcreep/status/1507351734863212565[Invisible networks] is a writing jam organized by link:https://twitter.com/ctrlcreep/[ctrlcreep]: "`Invent a weird/magical/terrifying social network every day`".

== Day 01: Slime computations

For their calculations, slimes use soft numbers.
They use them to represents shapes and colors, sounds and tastes, genre and ages.

Slime can change at will as long as they know the right number, their scholars know thousands of them.

New numbers are found in the odd words they visit, or in the dreams of adventurers they consume, but nobody really knows how they appear first.
There are several theories about it, each one expressed by its own numbers, but nothing is sure yet.

They use the ether for long-distance exchanges, forming small cliques.
Each group meets in its own carved place.
Some of these places look like fly markets, other like thieves dens, swayed by the numbers.

They scheme to steal numbers from other, recruiting other lifeforms to help them.

Non-slime can't perceive the numbers and they see the ether as empty caverns.
They rarely go there, unless a slime enlist them.

== Day 02: Psyche sort

Since last year, HR have been obsessed by _Psyche Sorting_^TM^.

_Psyche Sorting_^TM^ is "`a new infallible new methodology to classify the human resources`" of your organization, separating high achievers from commoners.

All the human resources of your organization are sorted, from the highest achiever to the lowest.

Unless other approaches, _Psyche Sorting_^TM^ ensure that the classification is correct, and _will stay correct_ indefinitely.

Most HR tools are only working on thee measuring aspect.
Event if the measure is accurate when it is done, people are adapting and changing with time, which leads to an increasing error risk.

_Psyche sorting_^TM^ doesn't only measure the human resources, but also manage them.

When a human resource joins your company, the _Psyche Sorting_^TM^ evaluation tool will give them a _Psyche Score_^TM^.

The _Psyche Score_^TM^ is then stored indefinitely on the sub-atomic _Psyche Network_^TM^, with the human resource identity.
This data can't then be changed or edited.

The human resource should then be implanted by the _Psyche Device_^TM^.
This psycho-mechanical device connects to the _Psyche Network_^TM^, and ensure the validity of the _Psyche Sorting_^TM^.

When a human resource try to act in a manner that isn't conforming to their _Psyche Score_^TM^, the _Psyche Device_^TM^ block the act instantly, without any visible pain.
In most cases, the human resource isn't even aware of what has just happened.

This ensure order and unity among the human resources: with _Psyche Sorting_^TM^ human resource management becomes predictable and fair.

== Day 03: Goblin marketplace

These last years, goblin marketplaces have become an expected fixture of all human settlements of a significant size, expanding from their southern origins to the whole continent.

Everyone have heard the rumor that all these marketplaces are in fact a single goblin marketplace existing in all the places at the same time through a mysterious mean.

Academics from several schools of magic -- made jealous by the idea that goblins could have discovered a new kind of spell -- studied the idea extensively, but failed so far to prove or disprove anything.

But how else could you explain the eerie similarities between all these places: the same second or third hand equipment shops, the same greengrocers, the same "`mischief's corner`" _café_ where you can order the same bog beer _à la mode_.

An economist -- as the members of the new school of magic dedicated to the study of money call themselves -- finally discovered the answer: the goblin marketplace system is what the goblins call _une franchise_, meaning it's a packaged business model ready to be installed in any place.

A goblin group with a venturing mind can be taught how to operate a marketplace in a few weeks, then buy all the necessary items: the adventuring equipment, the different kind of foods, but also everything needed to build the  "`authentic`" shops.

This explains why all these markets looks the same: they are based on the same blueprints and use the same materials. Everything can be bought in bulk to them provided they pay a fee on everything they sell, and promise to keep the operation secret.

Even the second hand equipment is not stolen from dead adventurers or looted in graveyards anymore, but produced to look this way. This ensure a steady supply flow and remove the physical risks for the goblins, but gone are the romantic feelings of buying a dagger who was probably owned by an unlucky rogue.

== Day 04: Kafka's metaverse

The fans of Kafka finally struck back.

Not the fans of the books published against their author's will.

The fan of Franz Kafka, who like him work merely to earn a living, and spend their free time writing, don't finish their long pieces, and enjoy sending them to their friends instead of publishing them.

Kafka's metaverse is a place for them, created and fiercely defended by them.

Writers are welcome, event if they don't write about the alienating tendencies of bureaucracy.
As long as they're not focused on fame or readership's size.

If they start to cultivate a large audience, the network will politely make them understand that maybe they should find a better place to go.

The _poète maudits_ are tolerated, as long as they don't make too much fuss and let the other have fun.

You can read and comment, or just read.
Don't try to help if you're not asked to.
Don't talk to all your friends about the new thing you just discovered, one or two should be enough.

Publisher are mercilessly hunted, particularly those that try to convince the authors to publish in their pages.

The creators have been inspired by ancient webrings, but wisely ignored the nostalgia.
They don't want to create something large, but don't either fetishize keeping their creation tiny, they make it up as it goes along.

A small internet archipelago of writers and readers.

== Day 05: Composite memory palace

Video games continued their expansions, in number and in size.

Knowledges required to master the games grew at the same pace, requiring more and more effort from the gamers.

To meet their demands, video games wiki grew, and become larger and more intricate, the biggest ones dwarfing wikipedia.

When the first bio-mechanical memory extension implant was created, it enabled people to connect their mind to video games wiki and access their content like their own memories.

The market was here, and the wiki standardization simplified the development.

Heavily subsidized by game companies, it became common.
Only some hardcore gamers refused it, proclaiming that it created a fake gaming experience.

To be compatible with it, other kind of information started to use the same standard as the video games wiki.

. General
.. Controls
.. Combat
.. Secrets
. Character
.. Classes
.. Stats
.. Build Calculator
.. Builds
. Equipment & Magic
.. Weapons
.. Magic
.. Armor
.. Upgrades
. World
.. Covenants
.. Places
.. NPCs
.. Enemies

Political programs, religious debates, historical and technical knowledge, all became ubiquitously available, as they followed the same structure.

Becoming so accustomed of this way of sorting things, people's memories started to be organized the same way:

. General
.. Controls
.. Combat
.. Secrets
. …

== Day 06: Witch hunter, witch gatherer

When being a member of a social network became mandatory, the only way to partially escape from the all-encompassing eye was to be part of a social network with a religious exception.

Communication related to a cult were exempt from the mandatory information reporting sharing with the state.

Old and new religions increased their audience.
While some -- like christianity -- saw a small bump, its effect on witchcraft was unexpected, even among the observers that already knew of its resurgence.

Being part of a small witch internet coven first became common for privacy-aware people, then it expanded to the general population.

But a witch coven require a witch to lead it.
Demand from an experienced witch exploded, even witch without specialization in cyber-rituals.

Witch fast-track certifications existed, but a self-respecting witchcraft practitioner wouldn't want to be leaded by someone with this kind of credentials.

If you wanted to create a new coven with a friend group, finding the right witch was difficult.
Some recruitment companies started to move in this market, with specialized witch headhunters.

Many witches that worked in academics started to practice professionally, and covens with large funds would poach famous witches from each other.

"`Indie`" witches -- like the anarcho-witches -- kept their distances from these behaviors, and their influence slowly increased.

== Day 07: Onion-based design framework

Social network massive success came from ubiquitous access, but some people wanted something more exclusive.

Managing access through concentric onion-like circles is an old idea, used by many secret societies.
But the scale of social networks enabled to have a number of circles people could only dream of.

To leverage the prestige of these old mysteries, they reused the 99 degrees of the "`Ancient and Primitive Rite of Memphis-Misraïm`".

The first degrees only required regular log-in and participations.

* 1. Apprentice 
* 2. Companion 
* 3. Master

Further degrees required light reading and to connect for oddly hour chats.

* 9. Master Elect of Nine 
* 10. Illustrious Elect of Fifteen 
* 11. Sublime Prince Elect

Then more reading, and using some kind of avatar became almost mandatory, and people should start emitting a kind of aura that let other feel they know _things_.

* 23. Chief of the Tabernacle 
* 24. Prince of the  Tabernacle 
* 25. Knight of the Brazen Serpent 

People should still be present in the lower degrees chat rooms, being active enough so they can't be differentiated from the regular members. Skipping some of the lower-degrees mandatory tasks were allowed, as long as it was done discretely.

* 45. Sublime Sage of the Mysteries
* 46. Sublime Pastor of the Huts
* 47. Knight of the Seven Stars

Beyond some ranks, specialized interfaces and phone apps were available to keep the whole thing under control.
Their task and status management UI were heavily inspired by video games.

* 87. Sublime Prince of Masonry 
* 88. Grand Elect of the Sacred Curtain 
* 89. Patriarch of the Mystic City 

When reaching the higher degrees, a kind of ominous deep purring noise could be heard from times to times.

== Day 08: Keyboards in unusual places

How to manage exclusivity in accessing social networks?

Using fame or money to select your users is good when you want to reach some kind of public, but you may want a way that make people feel like they earn the right to connect.

Exclusivity also feels stronger when it is embodied in a physical artifact instead of a password.

Thus the geocaching of keyboards.

These keyboards comes configured with an access to a single account to a single site, and can only be found through long treasure hunt-styled research.

The keyboard would then be found in a sealed bad.
Finding the keyboard without knowing the site it is linked is useless.

While most people use smartphones and laptop to access their sites, having to use an external keyboard -- or worse : several ones -- could be seen as cumbersome.

But on the opposite, it adds one more layer to the exclusivity feeling, people proudly exhibit their keyboards, each one styled from the type of social network they were linked to: gamer, sport, books…

== Day 09: Swordle

"`Swordle^TM^: Wordle but you're a Swordfish`"

It's a silly pun, but it caught on.

People each day tried to guess swordfishy words, mostly failed, and had fun to discover the solution.

Gradually, swordfishy phonemes were identified, and you could spot what a swordfish word would looks like.

Then Swordle^TM^ added accounts and a chat feature.

As expected, most people started to roleplay swordfishes, while a few choose jellyfishes or tunas.

A vocabulary was created, people started to write in a mix of swordfish and english.

While bored at work, they talked about looking for food, spotting whales, and invented legends telling the glorious past of swordfishes, including ancient wars and sunken marvels in deep abyss.

== Day 10: Friendweb

The web is supposed to be a distributed network, with a strong built-in resiliency even if part of it was knocked down.

Distributed social networks existed since a while, and connectivity between the nodes was expected, unless the other node was shut down or was voluntarily blocked (or if they blocked you).
Unless a problem occurred, they mostly worked like a single system, mostly with a few more privacy settings.

But spider webs parts are never perfect, at any given time some connections are missing and some parts can even be totally disconnected from the rest.

Normally, computer system designers try to work against this, but what if knocking down some parts of the connectivity was a part of the thing.

Friendweb is a distributed social network where connectivity between nodes is unreliable by design.
Sometimes the connection works, and sometimes you're disconnected from another node for a few hours, a few days, or a few weeks.

The discontinuity in the network change the way you interact with others: a group discussion can be suddenly split in two, or more, creating branches, then the groups merge back, and try to figure out how to continue.
Maybe one leg of the exchange reached a conclusion, but the people are then brought back.

A starting friendship could be cut of without a warning.

Choosing a node to connect mean choosing which people you could always talk to, and which people you could loose contact with.

Jumping to another node was doable while they are connected, as long as you can deal with the social consequences: how do you deal when a "`friend`" move elsewhere because they miss other people more than you?

At the end, it makes thing more complicated, and creates lots of drama.

And we love this, don't we?

== Day 11: Unskippable 30-hour advertisement

Monetization strategies is a research domain for all commercial social network.

Users rarely want to pay, or at least they don't want to pay enough compared to other revenues like advertising.

Unskippable video ads have the highest values per view, but the users have a strong negative reaction to them, specially when the content they want to watch is a short video.

On the other hand, super hero movies nowadays often reach between 150 and 180 minutes, and the public don't complain about it, quite the opposite: they want even longer movies.

The next step was obvious: to make long video ads people want to watch, make them like super heroes movies.

As longer ads brings more money, even if these new ads were expensive, the increased cash flow would cover the increased cost.

Many comics publishers were happy to rent some secondary character from a pittance, because it would increase the visibility of these heroes, thus increasing the sales of their books or their non-ads movies.

The unskippable video ads reached 4, then 5 hours, watching one would provide a yearly premium subscription.

Progress in video game engines lowered the time requited to create these ad-movies to a few weeks, so a brand wanting to launch a new product could easily fit them in their schedule

As people used to plan a week end to watch a new series or play a new video game, they started to do the same with these humongous movies.

10 hours became the standard, since you could watch one in one sitting during a full day without too much troubles.
It was like doing a half-season series without any cut between episodes.

Social networks realized that longer movies would fit in a week-end.
At this scale, it wasn't really worth it: the money wasn't really better than a 10 hours ads.
But they did it for the buzz, the good buzz of people that liked it, and the bad buzz of haters that used them to castigate the social networks.

The "`week-end knock-out`" unskippable 30-hour advertisements were born.


== Day 12: Online → oncube
== Day 13: Machine yearning
== Day 14: At the end of the infinite feed