= Invisible networks 2022
Julien Kirch
v0.1, 2022-04-01
:article_lang: en
:toc:
:toc-title:

== Invisible networks

link:https://twitter.com/ctrlcreep/status/1507351734863212565[Invisible networks] is a writing jam organized by link:https://twitter.com/ctrlcreep/[ctrlcreep]: "`Invent a weird/magical/terrifying social network every day`".

== Day 01: Slime computations

For their calculations, slimes use soft numbers.
They use them to represents shapes and colors, sounds and tastes, genre and ages.

Slime can change at will as long as they know the right number, their scholars know thousands of them.

New numbers are found in the odd words they visit, or in the dreams of adventurers they consume, but nobody really knows how they appear first.
There are several theories about it, each one expressed by its own numbers, but nothing is sure yet.

They use the ether for long-distance exchanges, forming small cliques.
Each group meets in its own carved place.
Some of these places look like fly markets, other like thieves dens, swayed by the numbers.

They scheme to steal numbers from other, recruiting other lifeforms to help them.

Non-slime can't perceive the numbers and they see the ether as empty caverns.
They rarely go there, unless a slime enlist them.

== Day 02: Psyche sort

Since last year, HR have been obsessed by _Psyche Sorting_^TM^.

_Psyche Sorting_^TM^ is "`a new infallible new methodology to classify the human resources`" of your organization, separating high achievers from commoners.

All the human resources of your organization are sorted, from the highest achiever to the lowest.

Unless other approaches, _Psyche Sorting_^TM^ ensure that the classification is correct, and _will stay correct_ indefinitely.

Most HR tools are only working on thee measuring aspect.
Event if the measure is accurate when it is done, people are adapting and changing with time, which leads to an increasing error risk.

_Psyche sorting_^TM^ doesn't only measure the human resources, but also manage them.

When a human resource joins your company, the _Psyche Sorting_^TM^ evaluation tool will give them a _Psyche Score_^TM^.

The _Psyche Score_^TM^ is then stored indefinitely on the sub-atomic _Psyche Network_^TM^, with the human resource identity.
This data can't then be changed or edited.

The human resource should then be implanted by the _Psyche Device_^TM^.
This psycho-mechanical device connects to the _Psyche Network_^TM^, and ensure the validity of the _Psyche Sorting_^TM^.

When a human resource try to act in a manner that isn't conforming to their _Psyche Score_^TM^, the _Psyche Device_^TM^ block the act instantly, without any visible pain.
In most cases, the human resource isn't even aware of what has just happened.

This ensure order and unity among the human resources: with _Psyche Sorting_^TM^ human resource management becomes predictable and fair.

== Day 03: Goblin marketplace

These last years, goblin marketplaces have become an expected fixture of all human settlements of a significant size, expanding from their southern origins to the whole continent.

Everyone have heard the rumor that all these marketplaces are in fact a single goblin marketplace existing in all the places at the same time through a mysterious mean.

Academics from several schools of magic -- made jealous by the idea that goblins could have discovered a new kind of spell -- studied the idea extensively, but failed so far to prove or disprove anything.

But how else could you explain the eerie similarities between all these places: the same second or third hand equipment shops, the same greengrocers, the same "`mischief's corner`" _café_ where you can order the same bog beer _à la mode_.

An economist -- as the members of the new school of magic dedicated to the study of money call themselves -- finally discovered the answer: the goblin marketplace system is what the goblins call _une franchise_, meaning it's a packaged business model ready to be installed in any place.

A goblin group with a venturing mind can be taught how to operate a marketplace in a few weeks, then buy all the necessary items: the adventuring equipment, the different kind of foods, but also everything needed to build the  "`authentic`" shops.

This explains why all these markets looks the same: they are based on the same bluprints and use the same materials. Everything can be bought in bulk to them provided they pay a fee on everything they sell, and promise to keep the operation secret.

Even the second hand equipment is not stolen from dead adventurers or looted in graveyards anymore, but produced to look this way. This ensure a steady supply flow and remove the physical risks for the goblins, but gone are the romantic feelings of buying a dagger who was probably owned by an unlucky rogue.

== Day 04: Kafka's metaverse

The fans of Kafka finally struck back.

Not the fans of the books published against their author's will.

The fan of Franz Kafka, who like him work merely to earn a living, and spend their free time writing, don't finish their long pieces, and enjoy sending them to their friends instead of publishing them.

Kafka's metaverse is a place for them, created and fiercely defended by them.

Writers are welcome, event if they don't write about the alienating tendencies of bureaucracy.
As long as they're not focused on fame or readership's size.

If they start to cultivate a large audience, the network will politely make them understand that maybe they should find a better place to go.

The _poète maudits_ are tolerated, as long as they don't make too much fuss and let the other have fun.

You can read and comment, or just read.
Don't try to help if you're not asked to.
Don't talk to all your frends about the new thing you just discovered, one or two should be enough.

Publisher are mercilessly hunted, particularly those that try to convince the authors to publish in their pages.

The creators have been inspired by ancient webrings, but wisely ignored the nostalgia.
They don't want to create something large, but don't either fetishize keeping their creation tiny, they make it up as it goes along.

An small internet archipelago of writers and readers.
