= Invisible networks 2022
Julien Kirch
v0.1, 2022-04-01
:article_lang: en
:toc:
:toc-title:

== A new social network every day

link:https://twitter.com/ctrlcreep/status/1507351734863212565[Invisible networks] is a writing jam created by link:https://twitter.com/ctrlcreep/[ctrlcreep]: "`Invent a weird/magical/terrifying social network every day.`"

== Day 01: Slime computations

For their calculations, slimes use soft numbers.
They use them to represents shapes and colors, sounds and tastes, genre and ages.

Slime can change as will as long as they know the right number, their scholars know thousands of them.

New numbers are found in the odd words they visit, or in the dreams of adventurers they consume, but nobody really know how they appear first.
There are several theories about it, each one expressed by its own numbers, but nothing is sure yet.

They use the ether for long-distance exchanges, forming small cliques.
Each group meets in its own carved place.
Some of these places looks like fly markets, other like thieves dens, swayed by the numbers.

They scheme to stole numbers from other, recruiting other lifeforms to help them.

Non-slime can't perceive the numbers and they see the ether as empty caverns.
They rarely go there, unless a scheming slime enlist them.

== Day 02: Psyche sort

Since last year, HR have been obsessed by _Psyche Sorting_^TM^.

_Psyche Sorting_^TM^ is "`a new infallible new methodology to classify the human resources`" of your organization, separating high achievers from commoners.

All the human resources of your organization are sorted, from the highest achiever to the lowest.

Unless other approaches, _Psyche Sorting_^TM^ ensure that the classification is correct, and _will stay correct_ indefinitely.

Most HR tools are only working on thee measuring aspect.
Event if the measure is accurate when it is done, people are adapting and changing with time, which leads to an increasing error risk.

_Psyche sorting_^TM^ doesn't only measure the human resources, but also manage them.

When a human resource join your company, the _Psyche Sorting_^TM^ evaluation tool will give them a _Psyche Score_^TM^.

The _Psyche Score_^TM^ is then stored indefinitely on the sub-atomic _Psyche Network_^TM^, with the human resource identity.
This data can't then be changed or edited.

The human resource should then be implanted by the _Psyche Device_^TM^.
This psycho-mechanical device connects to the _Psyche Network_^TM^, and ensure the validity of the _Psyche Sorting_^TM^.

When a human resource try to act in a manner that isn't conforming to their _Psyche Score_^TM^, the _Psyche Device_^TM^ block the act instantly, without any visible pain.
In most cases, the human resource isn't even aware of what has just happened.

This ensure order and unity among the human resources: with _Psyche Sorting_^TM^ human resource management becomes predictable and fair.