= Invisible networks 2022
Julien Kirch
v0.1, 2022-04-01
:article_lang: en

== Day 01: Slime computations

For their calculations, slimes use soft numbers.
They use them to represents shapes and colors, sounds and tastes, genre and ages.

Slime can change as will as long as they know the right number, their scholars know thousands of them.

New numbers are found in the odd words they visit, or in the dreams of adventurers they consume, but nobody really know how they appear first.
There are several theories about it, each one expressed by its own numbers, but nothing is sure yet.

They use the ether for long-distance exchanges, forming small cliques each meeting in its own carved place.
Some of these places looks like fly markets, other like thieves dens, swayed by the numbers.

They scheme to stole numbers from other groups, recruiting other lifeforms to help them.

Non-slime can't perceive the numbers and they see the ether as empty caverns so they rarely go there, unless a scheming slime enlist them.