= Spécification ou pas{nbsp}: qui a accès à l'information{nbsp}?
Julien Kirch
v0.1, 2021-11-01
:article_lang: fr
:article_image: 
:article_description: 

Spécification{nbsp}: un document pérenne écrit dans un langage non informatique documentant une partie non triviale d'un logiciel informatique avec un niveau de détail suffisant pour permettre de répondre suffisamment souvent à des question sur le fonctionnement de cette partie du logiciel sans avoir à consulter le code.

La spécification n'a pas forcément exactement le même niveau de détail que le code (elle peut se permettre de ne pas être exhaustive alors que le code doit nécessairement l'être), mais elle doit avoir un niveau de détail permettant d'être un substitut acceptable.

Dans les discussions sur la valeur des spécifications et par extension sur le fait d'en avoir ou pas, 
on parle beaucoup du temps passé à rédiger et à les maintenir en cohérence avec le code dont elles décrivent le comportement.

J'ai l'impression qu'un sujet dont on parle moi c'est l'accès à l'information, et plus particulièrement qui  

Mais un autre sujet est la capacité d'avoir accès à l'information.

