= Software development microfictions
Julien Kirch
v0.1, 2023-01-15
:article_lang: en

As Gregor Samsa awoke one morning from uneasy dreams he found himself isekaied into the enterprise wiki.

'''

== New tooth fairies EU regulations

Following many other utilities like phone, electricity and natural gas, the tooth fairies market will soon be opened to competitions.

In most EU countries, tooth fairies are a public utility, which often means a bad level of service and a high cost.

=== Overview

From January 1, 2026, the children tooth recovery market will be open to competition: tooth fairies will be allowed to create companies and establish themselves in the geographical area of their choice.

Each country will ensure the creation of an online platform allowing the companies to register themselves to allow easy consultation by parents.

=== Rules

Companies will be required to offer a "`basic plan`", which is the equivalent of the current state-provided offer, but apart from it they can offer more complex deals, including over-the-counter ones, as long as the health and sneak requirements are matched.

=== White zones

So-called "`white zones`" that are difficult to reach and/or low population density must still be covered.

To ensure this, states are allowed to use mechanisms like subsidies or one-provider zones as long as they don't infringe on the general free competition principle.

=== Essential services status

A steady stream of recent high quality teeth are required as raw materials for essential services in each EU state.

States are allowed to compel companies to sell them a part of their teeth at pre-established rates to avoid speculations and other market manipulations that would endanger this supply chain.

As a last resort mechanism, a EU strategic teeth reserve will be established to protect states against possible failures from their providers.
