ifeval::["{doctype}" != "book"]
= Software development microfictions
Julien Kirch
v0.1, 2023-01-15
:article_lang: en
endif::[]

ifeval::["{doctype}" == "book"]
'''
endif::[]

As Gregor Samsa awoke one morning from uneasy dreams he found himself isekaied into the enterprise wiki.

'''

== New tooth fairies EU regulations

Following many other utilities like phone, electricity and natural gas, the tooth fairies market will soon be opened to competitions.

In most EU countries, tooth fairies are a public utility, which often means a bad level of service and a high cost.

=== Overview

From January 1, 2026, the children tooth recovery market will be open to competition: tooth fairies will be allowed to create companies and establish themselves in the geographical area of their choice.

Each country will ensure the creation of an online platform allowing the companies to register themselves to allow easy consultation by parents.

=== Rules

Companies will be required to offer a "`basic plan`", which is the equivalent of the current state-provided offer, but apart from it they can offer more complex deals, including over-the-counter ones, as long as the health and sneak requirements are matched.

=== White zones

So-called "`white zones`" that are difficult to reach and/or low population density must still be covered.

To ensure this, states are allowed to use mechanisms like subsidies or one-provider zones as long as they don't infringe on the general free competition principle.

=== Essential services status

A steady stream of recent high quality teeth are required as raw materials for essential services in each EU state.

States are allowed to compel companies to sell them a part of their teeth at pre-established rates to avoid speculations and other market manipulations that would endanger this supply chain.

As a last resort mechanism, a EU strategic teeth reserve will be established to protect states against possible failures from their providers.

=== Programs and human languages

Cats don't meow at each other: they only meow at humans because they discovered that it's the best way to (sometimes) make humans obey to what they want.

It's the same for software programs and messages.

Feral software programs don't use messages to communicate between them: only domesticated programs do, or programs that were domesticated and broke free or who descend from such a program.

Programs don't understand human languages: they mimic the text fragments they can find on the computer they live in and try to combine them until they obtain the result they want.
It explains that messages are sometimes malformed or don't make sense.
