= Links - 4^th^ June 2023
Julien Kirch
v1.0, 2023-06-04
:article_lang: en
:figure-caption!:
:article_description: What would you fix next, notes apps, technologizing our way out, building large technical projects

== link:https://exple.tive.org/blarg/2023/05/27/brown-mms/[Brown M&Ms]

[quote]
____
The Brown M&Ms I mentioned, when I`'m sizing up a software shop, are pretty straightforward.

* What`'s the most interesting thing you`'ve discovered in a retro recently, and what did you do about it?
* How do you manage pager duties?
* How do you validate a rollback?
* What would you fix next if you had the resources?
* Do you use agile processes, and can you describe them?
____

[quote]
____
"`What would you fix next if you had the resources`" might as well read "`does your org have a shared understanding of its backlog and priorities`", but nobody will say "`lol no`" to that question. But if you get a bunch of different answers to this from different people or teams, it`'s very likely your organization has leadership and communications gaps that need urgent attention. Even "`how would you make that decision`" is informative; can you draw a straight line from organizational goals to the the top of your backlog? What would need to have, for you to have that?
____


== link:https://www.reproof.app/blog/notes-apps-help-us-forget[Notes apps are where ideas go to die. And that`'s good.]

[quote]
____
We don`'t write things down to remember them. We write them down to forget.

Like a hunter/gatherer stashing their prey, the ideas and the links we stumble upon feel valuable, rare, something worth saving. We ascribe value to the time we spend discovering things online. Surely that time wasn`'t in vain.

Then we`'re burdened with our findings. It`'s tough to focus on something new when you`'re still holding the old in your mind.
____

== link:https://erinkissane.com/tomorrow-and-tomorrow-and-tomorrow[Tomorrow & tomorrow & tomorrow]

[quote]
____
In the machine, we are always forgetting, chasing the same discourses and panics in circles. Instead of making restitution, we wait for the cycle to erase the screen and carry on as before. Stay long enough and everything rhymes with something that gave you scars, but that everyone else has forgotten. Resolution eludes us online even more than off. But then, the paradox: Nothing stays gone, either. Fast search resuscitates archives without even a bump in load time. Screenshots jump networks and decades; we have the receipts. Somewhere between the continual etch-a-sketch and structurally eidetic memory, the provisional and crucial ties of solidarity recede, always just out of reach.

[…]

We won`'t technologize our way out of the ghost machine.
____

== link:https://mitchellh.com/writing/building-large-technical-projects[My approach to building large technical projects]

[quote]
____
This is the phase where experience helps the most. Engineers with more experience are usually able to more effectively paint the picture of the rough shape a project will take. They can identify various subcomponents with more accuracy and see how they pieces fit together. With less experience, or in a domain I`'m unfamiliar with, I just take a best guess and expect there is a higher likelihood I`'ll throw my work away at some point.
____
