= Les devs et leurs outils de développement
Julien Kirch
v0.1, 2022-06-15
:article_lang: fr

Une proportion significative des devs aiments leurs outils de développement, leurs outils de développement qu'iels ont choisi.

Même si ça n'est pas mon sujet aujourd'hui, je dis "`une proportion significative`", car même si cela est assez courant et même link:../pris-au-serieux[valorisé], ce n'est pas le cas de tous les devs.

D'ailleurs je pense que se préoccuper de ses outils n'est pas un indicateur de compétence technique ni dans un sens (se préoccuper de ses outils est un signe de compétence) ni dans l'autre (ne pas se préoccuper de ses outils est un signe d'incompétence){nbsp}: j'ai rencontré suffisament de contre exemple des deux types pour m'en convaincre.

Donc certain·e·s devs ont dess préférences, et dans le cadre de mon travail, en tant que responsable technique il faut que je détermine quelle doctrine appliquer dans ce sujet.

Mes besoins sont les suivants{nbsp}:

- Dans la mesure où cela n'est pas une gène significative je voudrais que les personnes soient aussi libres que possible dans le choix de leurs outils, cela peut ainsi vouloir signifier utiliser un formateur standard raisonablement efficace disponible sur de nombreux outtils plutôt que le formateur intégré à un outil particulier même s'il est plus puissant.
- Pour les personnes n'ayant pas d'avis, il me semble souhaitable qu'il y ait un choix raisonable par défaut à leur proposer, et si elles choisissent cet outil elles doivent pouvoir compter sur un certain niveau de support.
- Même si je ne suis pas redevable de la productivité individuelle des dev de l'équipe, si les personnes ne sont pas efficaces à cause d'un outil qu'elles utilisent parce que je l'ai proposé alors c'est de ma faute, par contre la productivité des personnes qui choisissent leur propre outil est leur problème.

Le fait d'avoir un outil par défaut a aussi l'avantage de définir aussi un étalon en terme de productivité permise par l'outil.
Quand je parle de productivité d'outils de développement cela ne signifie pas seulement la capacité à éditer du code mais aussi à naviguer, accéder à de la documentation, à débugguer…

Dans le monde Java, les choses sont assez simples{nbsp}: les IDEs sont la norme, les outils sont compatibles entre eux et tout le monde sait ce dont on peut attendre des outils.

Mais actu