= 29/04/2018
Julien Kirch
v1.0, 2018-04-29
:article_lang: en

===== link:https://danielmiessler.com/blog/continuous-asset-management-security/[If You’re Not Doing Continuous Asset Management You’re Not Doing Security]

[quote]
____
For most companies, the single best thing they could do for their security program is to hire a dedicated person to maintain a near-realtime list of company assets.
____

===== link:https://brandur.org/redis-cluster[Scaling a High-traffic Rate Limiting Stack With Redis Cluster]

[quote]
____
Philosophically, there’s a lot to like about Redis Cluster’ design – simple, yet powerful. Especially when it comes to distributed systems, many implementations are exceedingly complicated, and that level of complexity can be catastrophic when encountering a tricky edge in production.
Redis Cluster is scalable, and yet with few enough moving parts that even a layperson like myself can wrap their head around what it’s doing. Its design doc is comprehensive, but also approachable.
____
