= Encore l'agile : des prerequis pour un manifeste qui me parle
Julien Kirch
v0.1, 2019-04-01
:article_lang: fr

* Se situer : on peut proposer des choses en étant consultant·e, mais je pense qu'un manifeste rédigé par des consultant·e·s a ses spécificités propres (probablement en bien et/ou en mal), et qu'il faut y penser

* Qu'il soit inclusif de manière intersectionnel

* Prendre en compte que la plupart des grosses boites ont probablement déjà subi plusieurs transformations agiles (ou digitales) qui ont plutôt empirer les choses

* Proposer une approche qui ne suppose pas la bonne foi mais qui prenne en compte la réalité des personnes (qui sont par exemple capable de manipulation, ou qui ne suivront pas forcément l'intérêt du groupe quand il est contraire à leur intérêt propre)

* Qu'il pense aussi les différentes postes présents dans une équipe sous l'angle des rapports de force

* Prendre en compte les conditions de travail (matérielles et morales)

* Ne pas rendre nécessaire d'avoir des personnes passionnées par leur travail (que ça soit des personnes réellement passionnées, ou qu'on demande aux personnes de faire semblant)

* Qu'il soit -- autant que possible -- résistant à la récupération

* Être réaliste sur ce qu'il est possible de faire

* Résister aux formes d'exotismes comme la fascination pour le Japon