= Suite de l'agile : une liste de course pour de nouvelles méthodes
Julien Kirch
v0.1, 2019-04-01
:article_lang: fr
:article_description: Avril c'est le moment parfait pour préparer sa liste au père Noël

Cet article est la suite de link:../agile-questionnement-institution/[celui-là].

Suite à mes expériences, voici une liste de choses dont je pense qu'elles devraient être prises en compte pour l'élaboration d'une nouvelle méthode d'organisation.

Ce texte est un travail en cours et une sorte d'aide-mémoire de mes réflexions, je vais continuer à l'enrichir, et à extraire certains éléments dans des articles séparés pour les détailler comme link:../professionnalisme/[celui-là].

== D'où parlez-vous ?

La position qu'occupe une personne a une influence sur le contenu méthodes qu'elle peut proposer.

Par exemple beaucoup de méthodes d'organisations sont proposées par des personnes qui vendent du conseil en organisation.

C'est logique car c'est leur métier, et que ça leur permet de se faire identifier donc d'avoir du travail.

Je ne veux pas dire qu'une personne qui vend du conseil en organisation ne peut pas proposer de nouveaux modes d'organisations, mais que le fait d'être consultant ou consultante influe nécessairement sur le contenu de ce qui est proposé.

Je ne dis pas que cette influence est forcément négative, mais qu'elle peut l'être -- dans le contenu de ce qui est proposé, ou dans ce qui est oublié -- et qu'il faut donc se poser la question.

== Inclusivité

Une méthode d'organisation doit à mon sens être inclusive au plus grand nombre de personnes possibles.

Cela veut dire qu'il faut prendre soin d'y penser dans le choix des activités et du vocabulaire.

L'exemple qui revient le plus souvent est celui du _stand-up_ qui ignore les personnes qui ont des difficultés à se tenir debout.

== "Encore une transformation agile ?"

La plupart des grandes organisations ont déjà subies de nombreuses transformations agiles, digitales, _lean_, _kaisen_ et autres joyeusetés.

Les personnes n'attendent plus grande chose de la transformation suivante, elles espèrent juste que ça n'empire pas trop.

Donc n'espérez pas de l'enthousiasme, au contraire il va falloir expliquer pourquoi vous pensez réussir là où tant d'autres idées ont échoué (pour de bonnes ou de mauvaises 
raisons).

De même il faut éviter de promettre la lune, même si c'est pour donner envie, mais au contraire rester modeste dans vos objectifs pour être crédible.

== Les conditions de travail

Une méthode qui prétend donner des réponses pour améliorer la qualité et la productivité devrait traiter des conditions de travail des personnes.

Je ne parle pas d'écrire des tests, mais par exemple du niveau sonore, de l'équipement fourni, ou de l'organisation spatiale (disposition des bureaux …).

Cela rejoint aussi le point précédent : proposer changer la couleur des post-it sans parler de de la question du bruit et du travail en open-space vous rendra difficile à entendre.

== Ambitions et les rapport de force

Toute proposition d'organisation pour des structures classiques (par exemple des entreprises) doit prendre en compte la réalité du fonctionnement de ces organisations, et notamment celle des ambitions des personnes et des rapports de force.

Par exemple une équipe auto-organisée ne peut fonctionner, en général, que si toutes les personnes y trouvent un intérêt personnel.

Ou alors on ne peut pas supposer la bonne fois permanente de toutes les parties-prenantes d'un projet, qu'il s'agisse de manipulation volontaire ou de biais inconscient.

== La passion ça suffit

On ne peut pas demander à toutes les personnes d'une organisation d'être à chaque instant rempli d'enthousiasme.

On peut seulement exiger qu'elles fassent semblant, pour donner satisfaction au management et aux personnes qui les coachent.

link:../professionnalisme/[Je me répète] mais pour moi une méthode efficace doit être adaptées à des personnes qui sont là pour faire leur travail.

== Plus d'exotisme

Depuis link:https://fr.wikipedia.org/wiki/Études_postcoloniales[les années 80], on a forgé des outils permettant de déconstruire la vision exotique de l'orient véhiculée en occident et les clichés qui l'accompagne.

S'intéresser à ce qui ce fait ailleurs peut être riche d'enseignements, mais on peut le faire sans fascination pour un ailleurs étranger et en prenant en compte la réalité derrière le mythe.

== Accepter le désordre

La réalité est complexe et désordonnée.

Il est normal qu'une methode puisse vouloir organiser les choses.

Par contre il y a différence entre vouloir ajouter de l'ordre et faire comme si la complexité n'existait pas en proposant des approche monolithiques et des solutions miracles.

== C'est tout pour le moment

Je suis preneur de vos suggestions sur les éléments existant ou sur l'ajout de nouvelles entrées.
