= Links - 11^th^ December 2022
Julien Kirch
v1.0, 2022-12-11
:article_lang: en
:figure-caption!:
:article_description: Software & hardware, locality of behaviour, social media management on the fediverse, city building simulations, fuck nuance, antimemetics division

== link:https://queue.acm.org/detail.cfm?ref=rss&id=3570921[The elephant in the room]

[quote]
____
Software and hardware have followed a random walk over the history of computing, much like two drunks trying to keep each other from falling over as they wander down the street. Hardware often leads and software often follows, although from time to time, software has forced itself upon the hardware side to get new ideas to execute at the speed of the hardware.
____


== link:https://htmx.org/essays/locality-of-behaviour/[Locality of behaviour]

[quote]
____
Locality of Behavior is the principle that:

[quote]
_____
The behaviour of a unit of code should be as obvious as possible by
looking only at that unit of code
_____
____

[quote]
____
LoB is a subjective software design principle that can help make a code base more humane and maintainable. It must be traded off against other design principles and be considered in terms of the limitations of the system a code unit is written in, but, as much as is it is practical, adherence to this principle will increase your software maintainability, quality and sustainability.
____

== link:https://eiara.nz/posts/2022/Dec/09/a-case-study-on-raspberry-pis-incident-on-the-fediverse/[A case study on Raspberry Pi`'s incident on the Fediverse]

[quote]
____
On the Fediverse there is no singular entity such as Twitter, Inc. that
financially benefits from the presence of a brand, or benefits from the
extra engagement and associated ad sales that controversy will generate.

There is no incentive for other administrators to retain a brand if that
brand misbehaves.

As a result, social media managers, going forward, will need to be
extremely cognizant of the brand damage they can do not just in the
immediate term, but also in the longer term by causing the business
account to be banned or the business instance to be defederated.

The business instance being defederated will be a huge blow to any reach
that might have been gained, as administrators and moderators seeking to
ensure safety for their users are able to remove tens of thousands of
their users in a few clicks.

If the brand account is on a hosted instance without their own domain
name, such as brand@fediverse.au, an admin or moderator seeing the
behaviours demonstrated by Raspberry Pi would almost certainly have
banned their account very quickly, as the threat of the full instance
being defederated would be extremely high.

Brands seeking to join the Fediverse will need to invest not just in a
social media manager, but competent and long-time administration for the
instance that is aware of the political dynamics of the Fediverse, in
order to ensure that they are able to _stay_ on the fediverse.
____


== link:https://cohost.org/chiaki747/post/573485-the-endgame-of-city[The endgame of city building simulations]

[quote]
____
Thus, the utopic endgame of city building simulators is to have a highly
educated high wealth citizenry who predominantly work in white-collar
jobs, and often times that is only achievable by sweeping away any
vestige of the "`global south`". When everyone in your city is too well
educated and too rich, they refuse to take jobs at manufacturing
industries in town. So the more your city loses its industrial base, the
more it assumes that its goods are being furnished by an invisible
generator of materials no longer of concern for your city. And this is
true in modern American society, as much of its consumer goods, food and
luxury items are produced totally outside the context of its consumers`'
lives.
____

== link:https://kieranhealy.org/publications/fuck-nuance/[Kieran Healy, "`Fuck Nuance.`" _Sociological Theory_ 35:118-127]

[quote]
____
Nuance is not a virtue of good sociological theory. Sociologists typically use nuance as a term of praise. Almost without exception, when nuance is mentioned it is because someone is asking for more of it. I argue that, for the problems facing sociology at present, demanding more nuance typically obstructs the development of theory that is intellectually interesting, empirically generative, or practically successful.

As alleged virtues go, nuance is superficially attractive. Isn`'t the mark of a good thinker the ability to see subtle differences in kind or gracefully shade the meaning of terms? Shouldn`'t we cultivate the ability to insinuate overtones in our concepts? Furthermore, isn`'t nuance especially appropriate to the difficult problems we study? Our research problems are complex, rich, and multifaceted. When sophisticated thinkers face a rich and complex world, how can nuance not be the wisest approach?
____

[quote]
____
It is the act of making -- or the call to make -- some bit of theory "`richer`" or "`more sophisticated`" by adding complexity to it, usually by way of some additional dimension, level, or aspect, but in the absence of any strong means of disciplining or specifying the relationship between the new elements and the existing ones. Sociologists do this to themselves, and they demand it of others. Sometimes they see it as one of the discipline`'s comparative virtues. I contend that it is typically a holding maneuver. It is what one does when faced with a question for which one does not yet have a compelling or interesting answer. Thinking up compelling or interesting ideas is difficult, so it is often easier to embrace complexity than to cut through it.
____

[quote]
____
This is most obvious with the nuance of the connoisseur. Connoisseurs call for the contemplation of complexity almost for its own sake or remind everyone that things are subtler than they seem. The attractive thing about this move is that it is always available to the person who wants to make it. Theory is founded on abstraction, abstraction means throwing away detail for the sake of a bit of generality, and so things in the world are always "`more complicated than that`" -- for any value of "`that`". Connoisseurship gets its aesthetic bite from the easy insinuation that the person trying to simplify things is a bit less sophisticated a thinker than the person pointing out that things are more complicated.
____

[quote]
____
Free-floating calls for nuance, unconstrained by rules of method or logic, inhibit the process of abstraction that makes theory valuable.
____

== link:https://scp-wiki.wikidot.com/antimemetics-division-hub[Antimemetics division hub]

[quote]
____
An antimeme is _an idea with self-censoring properties_; an idea which, by its intrinsic nature, discourages or prevents people from spreading it.

_Antimemes are real_. Think of any piece of information which you wouldn`'t share with anybody, like passwords, taboos and dirty secrets. Or any piece of information which would be difficult to share even if you tried: complex equations, very boring passages of text, large blocks of random numbers, and dreams…

But anomalous antimemes are another matter entirely. How do you contain something you can`'t record or remember? How do you fight a war against an enemy with effortless, perfect camouflage, when you can never even know that you`'re at war?

Welcome to the Antimemetics Division.

No, this is not your first day.
____
