On Cohost link:https://cohost.org/MiserablePileOfWords[Miserable Pile Of Words] posts a link:https://cohost.org/Making-up-Monsters/tagged/monster%20person[daily prompt] about monsters.

== Monster who is something of a… what was your thing again? Anyway, that. They're something of a that themselves.

It's always the same with over-ambitious and under-organized monsters: they become over-confident and after some time they take too many assignments compared to what they can deal with and start mixing things.

Even monsters can bite off more that they can chew.

Most entities aren't really strict about the monsters' requirements, the fact that the entities that the monster have to deal with are often not the customer also helps with hiding mistakes.

But it's not always the case, especially when things are going south enough, entities can file a complaint.

I don't know anybody or anything that loves to deal with the compliance officers, and it's the same with monsters, claws or fangs won’t help them with the bureau.

== Monster who is a psychopomp, and do they have some bad news for you

A dark bedroom at night.

Some soft white noise, and a faint smell of ozone.

Then a portal opens above the bed, and a form appears out of it and boy slam on the bed.


– DAMN IT, I ALREADY TOLD YOU TO NOT POUNCE ON ME FROM A PORTAL! +
– B… +
– AND IT'S FUCKING 3AM!
– YOU WILL CALM DOWN, HUMAN! +
– OK sorry, but what the fuck, explain yourself! I told you that you're welcome here whenever you want, but not like this! +
– It's Mittens.+
– What happens to them? +
– You know I'm a psychopomp. +
– Mittens died? +
– No, no, silly thing, as cats with heterochromia have a link to the afterlife, psychopomps can connect to them. +
– And it explains why you mauled me? +
– Well I made a contract with Mittens, and they called me. +
– You … made … a … contract … with … the … fucking … cat? +
– I wanted to have regular news about you, and you sometimes take a long time to answer my messages. +
– My cat is spying on me for you? I'm so glad! +
– You make it sound creepy, I just want to know what's happening to you. +
– And? +
– And Mittens called me urgently. +
– As part of the contract? +
– As part of the contract. +
– And ? +
– The squeaky mouse toy…

The human started to facepalm, they knew they wouldn't be able to deal with the next words.

… is stuck under the sofa.
