[#MuM]
= Making Up Monsters
ifeval::["{doctype}" != "book"]
Julien Kirch
v0.1, 2023-01-01
:article_lang: en
endif::[]

On Cohost link:https://cohost.org/MiserablePileOfWords[Miserable Pile Of Words] posts a link:https://cohost.org/Making-up-Monsters/tagged/monster%20person[daily prompt] about monsters.

== Monster who is something of a… what was your thing again? Anyway, that. They`'re something of a that themselves.

It`'s always the same with over-ambitious and under-organized monsters: they become over-confident and after some time they take too many assignments compared to what they can deal with and start mixing things.

Even monsters can bite off more that they can chew.

Most entities aren`'t really strict about the monsters`' requirements, the fact that the entities that the monster have to deal with are often not the customer also helps with hiding mistakes.

But it`'s not always the case, especially when things are going south enough, entities can file a complaint.

I don`'t know anybody or anything that loves to deal with the compliance officers, and it`'s the same with monsters, claws or fangs won’t help them with the bureau.
