= Un modèle pour comprendre les choix dans l'IT et comment les influencer
Julien Kirch
v0.1, 2020-04-05
:article_lang: fr
:ignore_files: base.xml, prepare.rb

Quel langage ou framework utiliser{nbsp}? Microservices ou monolithe{nbsp}? Rénover une base de code existante ou la réécrire{nbsp}?
Beaucoup de choses ont été écrites sur les aspects technique et organisationnel de ce type décisions.

Mais j'ai l'impression qu'un autre aspect l'est beaucoup moins{nbsp}: celui des intérêts des personnes qui sont impliquées.
Car quand une décision implique plusieurs partie prenantes, il est normal que leurs intérêts ne soient pas forcément les mêmes.

Dans certaines organisations, c'est un sujet dont on préfère ne pas parler, ou du moins pas directement.
Ainsi, dire que dans une décision, les intérêts des personnes qui développent sont différents de l'intérêt de l'organisations pour qui elles travaillent, il y a plein d'endroit où ça ne se fait pas, ou alors seulement entre personnes de confiance.

Cela signifie que des décisions prises sont parfois mauvaises car on préfère ne pas prendre en compte ces éléments, mais aussi que les personnes qui n'ont pas conscience de ces sujets peuvent passer à côté d'une partie de ce qui se joue.

Avec le temps j'avais accumulé certaines idées sur ce sujet et j'ai cherché un moyen de les synthétiser d'une manière lisible.

Mon objectif est tout d'abord de faire comprendre les intérêts en présence lorsqu'un choix est fait, et les différents cas qui peuvent se produire lorsque ces intérêts se croisent.
Ensuite je parlerai de la manière dont on peut influer sur ces différents intérêts.

J'ai construit le modèle en ayant en tête le type de choix dont je parle au début de l'article{nbsp}: choix de technologie, ou modèle de développement.
Il peut probablement s'appliquer à d'autres situations, mais je vais me concentrer sur ceux-là dans mes exemples.

== Les zones

Lors d'une prise de décisions, j'ai identifié cinq zones d'intérêt qui sont en jeu.

Le modèle présente le point d'une vue d'une personne impliquée dans la décision.
Certaines des zones sont communes à différentes personnes, d'autres sont dépendantes de chaque personne.

=== L'envie

image::01-envie.svg[]

image::02-carriere.svg[]

image::03-recompense.svg[]

image::04-bon.svg[]

image::05-conseille.svg[]

image::06-complet.svg[]

== Quelques croisements intéressants

== Les influences possibles