[#MuC]
= Make Up A Criminal
ifeval::["{doctype}" != "book"]
Julien Kirch
v0.1, 2023-01-01
:article_lang: en
endif::[]

On Cohost link:https://cohost.org/SaidLikeCaleen[Cailín Grace Brown] posts link:https://cohost.org/spy-thief-assassin-who/tagged/make%20up%20a%20criminal[prompts] about criminals.


== Mob Boss who doesn't care what it is, along as it sells

<During the monthly mob steering committee meeting>

– Next item on the agenda is about middle-managers' complaints about the new catgirl catnip business line we're currently testing in the south district. +
– They always complain, specially when the yearly review are approaching, but is this about: not enough customers? They should know that new stuff takes some time to ramp up some times. +
– No boss, it's about the secondary effects. +
– Secondary effects? With all the things they sell they complain about the secondary effects of this? If they are not happy they should consider working something else that for the mob, idiots! +
– No, it's the secondary effects on our people. +
– Are they stupid enough to use the shit we sell? They should now what how we deal with people who do this. +
– No no, but after they started to spend some time with catgirls… +
– THEN WHAT? +
– They started to wear cat ears, and to go "`nya`" when they think nobody is listening to them.