= Links - 3^rd^ September 2023
Julien Kirch
v1.0, 2023-09-03
:article_lang: en
:figure-caption!:
:article_description: Emails, design, normcore, watefall, HTML ordered lists, capital is dead

== link:https://cohost.org/love/post/2450234-what-if-there-was-a[Button]

[quote]
____
What if there was a button that could inflict unimaginable suffering to someone in the world, but also they had access to a button that could do the same thing back to you? Would it be worth the risk? Would you press the ✉️ **Send email** button?
____


== link:https://normadesign.it/en/log/nothing-special/[Nothing special]

[quote]
____
An essay about how buying a table is impossible, and why we should all stop wanting to be "`designers`".
____

== link:https://libbymarrs.net/post-authentic-sincerity/[Post-authentic sincerity]

[quote]
____
A truly post-authentic sincere attitude is synonymous with "`normcore`", as originally defined in K-HOLE`'s trend report Youth Mode, a timely and groundbreaking publication released in 2013 as the last embers of Hipsterism were fading.To crudely summarize highlights of the analysis: The opposite of mass authenticity-seeking, which they name "`Mass Indie`", is the normcore attitude. The normcore derives value from popularity and recognition, not scarcity. The pursuit of uniqueness is devalued; dynamicism and flexibility are more important than originality, because originality itself is unattainable. One of the first declarations in the publication is "`Normcore is about adaptability, not exclusivity`". Adaptability is the key characteristic of the normcore attitude, the true post-authentic attitude.
____

== https://www.amazingcto.com/why-we-always-endup-with-waterfall-even-scrum/[Why we always end up with waterfall]

[quote]
____
Those stakeholders drive the product, madly pulling the steering wheel to the right and left. These external stakeholders want predictability, because they don`'t care about the product but see the product as a tool for their goals. When will it be ready? These external stakeholders want to solve a problem for them not learn about the market. The stakeholders queue up in a long line. And just like in Disneyland where it says “60 min from here” they want to know when "`their`" feature is developed. This drives waterfall. To coordinate and communicate about the queue product management draws up roadmaps.
____

[quote]
____
But waterfall is handy, I can work on my own says the developer plus I don`'t need to talk to people. Win-Win. People who don`'t work as a team can work in different orgs, product management and development. Then it`'s even more efficient with waterfall.
____

== https://siderea.dreamwidth.org/1819759.html[I blame the W3C`'s HTML standard for ordered lists]

[quote]
____
I start with a single HTML tag and end with the downfall of civilization.
____

== link:https://www.versobooks.com/en-gb/products/887-capital-is-dead[Capital is dead: is this something worse?]

[quote]
____
Critical theories of the culture industry tend to stop short of thinking through the extent to which the production of critical theory itself is now a minor genre within the culture industry.
____

[quote]
____
The hacker class was supposed to be a privileged one, shielded from proletarianization by its creativity and technical skill. But it too can be made casual and precarious.
____

[quote]
____
The free creation of information would be alternately policed and encouraged: policed where it infringed on corporate monopolies; encouraged where free labor or nonlabor could be captured as information that had value.
____

[quote]
____
The Man of Letters leaves it to somebody else to type them and post them. His inheritors can`'t even put up their own blog posts in WordPress.
____
