= 18/02/2018
Julien Kirch
v1.0, 2018-02-18
:article_lang: en

===== link:https://queue.acm.org/detail.cfm?id=3185224[Containers Will Not Fix Your Broken Culture (and Other Hard Truths)]

[quote]
____
Dunbar's number, a cognitive limit on the number of people with whom an individual can maintain stable social relationships, is demonstrably valid. If working in a larger organization, you'll need to communicate in smaller groups, but those groups should be cross-functional to eliminate bottlenecks and misunderstandings. Communication doesn't just mean talking with our human voices or replying to interminable email threads, either; much like Consul's gossip protocol, we need cross-talk in our orgs to keep communication flowing.
____

[quote]
____
Nobody is doing résumé-driven development with shell scripts; I'm willing to bet that all the janky bash ever written was meant to solve a real problem.
When we start getting fancier, there are often motivations less pure than "Let's do this well," and even if there aren't, intention alone doesn't create maintainable software. 
____
