The 80s were different when you wanted to be an independent software developer: you could buy a beaten codebase, give it a shady refactoring, and start smuggling features between the frontier worlds.

''''

To work around some existing bugs, most scrum masters implementations ignore developers that are T-posing, it can be exploited during daily meetings and retrospectives

''''

== Data volcano

Following the trends set by data lakes and data swamps, we're introducing a new data management pattern: the data volcano.

A data volcano is designed for the data that are too hot to be dealt with in a data lake.

Main feature of a data volcano:

- Need a full time of highly trained team to monitor it 24/7 equipped with a specialized gear to protect them from the data flumes,
- Instantly destroy any facility the data are deployed to with extreme prejudice,
- Constant temptation to hurl inconvenient people into it.

Availability is location-dependent, contact your local reseller for details.

''''

== Code comments & unreliable narrator

So many developers seem to strongly hate when comments don't match what the code is doing.

But comments not matching the code is a long-established industry best-practice called link:https://en.wikipedia.org/wiki/Unreliable_narrator[unreliable narrator].

It can have several goals so don't assume the authorial intent, but the most common is to make the reader question the objectivity of the code, to remind them that all software code is ultimately a work of fiction, than only have a coincidental relation to what is actually happening on a computer.

So the next time you meet this case, please try to refrain yourself to react negatively to it, and try to understand what the people who wrote what you're reading wanted to achieve.

''''

== The danger of open sourcing old applications

When new types of software bugs are emerging, developers that collide with them learn how to fix them.

As a new bug type starts to spread, knowledge about how to fix them also spreads, but of course with a delay.
The delay highly depends on the familiarity between the new bug type and the bugs the developers know how to fix.

After a while, a kind of immunity is reached: the bug type's impact is constrained, and instead of a threat it becomes a general nuisance.
It's especially true for the nastier bug types, because they trigger a stronger response.

At a later date, some types of bugs reach extinction or near-extinction.
Not enough contact with the bug type means that the defense against it starts to weaken, for example as new developers are not aware of it, while the experienced ones move to other tasks.

Asking for open sourcing popular abandoned old applications is becoming popular, fueled by the nostalgia for software that actually works.

I understand the idea's appeal, but this kind of move can be an ecological disaster: old application means old code, which means old bug.
If the application is old enough, it could mean one of those bug types whose immunity against has been lost.

In this case, open sourcing the code could trigger a fast infection, as lots of unprotected developers will make contact with the code, pushed by curiosity.

The consequence is that open sourcing old software must follow a specific protocol, starting a careful study of the code by grizzled developers, and followed by a release in an enclosed space with other code samples to see if any kind of unintended transmission happens.

Luckily, link:https://www.apache.org[some organizations] can help you to publish this kind of very old code. It makes things easier but it will still take at least a few months.

I know it's a nuisance, but safety is not negotiable.

== Homunculi and alchemists developers

It's so strange to read modern books about early software developers, because so much of it has been rewritten to comply with corporate policy to remove all references to alchemy.

"`These are a bunch of people that love to read strange books and deal with esoteric knowledge, and who are knows to invest fully in their passion, we're bewildered by how much they achieved.`"

I'm not bewildered at all, because these are the exact kind of people that would dabble in alchemy.

And when you have lots of thought-work to do, and dabble in alchemy, what do you do ? You create homunculi, the advanced alchemist's best handy tool.

An alchemist developer can offload their more menial tasks to homunculi, so they can use their time and energy to deal with the complex stuff, thus achieving an impressive throughput "`alone`".

I understand why corporate prefer to deal with teams composed of non-alchemists, even if it means much more people: alchemists are much harder to deal with a PM, and imagine an HR person asking one to fill their quarterly OKR.

Not to mention that the blood thing is a big no no in a standard office, imagining explaining this to OSHA people.

But when you erase the alchemists, so much of what they retcon makes little sense.

For example, lots of things that look like quirks in software development make sense when you know how homunculi works, because they are designed to match homunculi's idiosyncrasies, to maximize what they can do.
Next time you catch yourself thinking that {C++} templates are not made for humans, remember that there is a perfectly good reason for that.

The best thing is "`rubber duck debugging`".

"`These cool developers from the 70's and the 80's used to have rubber ducks on their desk and talk to them to solve their problems`", they even write this with a straight face.

You know what these developers used to have on their desks ? Skulls! And why did they talk to them? Because the homunculus skulls were able to answer with actual solutions to their questions.

I don't want to compare one type of developer to the other, alchemists are not superiors. But it's not because lots of them are smug assholes that they must be erased from history, and from the present.

And a little blood here and there add spice to office politics.
