On Cohost link:https://cohost.org/MiserablePileOfWords[Miserable Pile Of Words] posts a link:https://cohost.org/build-a-bot/tagged/writing%20prompt[daily prompt] about robots.

== An old robot, its algorithms written in a dead language.

– Hello, welcome to you yearly checkup, the records indicates you use a very ancient core that is not fully supported anymore. I must ask you if you want to switch to a newer version, or I'll need a signature as an acknowledgment that you're aware of the end of support. +
– <Legalese mode> I am aware of the process, I'll sign the waiver like every year. +
– I've heard about these old models, is it a nostalgia thing ? +
– <Blasé mode> Oh no, you read to many novels, I'm a consultant for the team in charge of managing the core change, having someone on the team that use the original model is necessary for some cases, and it can also makes things smoother. My turn will come when all the other will have jumped ship.

== Combat android who just doesn't pull their weight.

– I don't get why you've become obsessed with increasing your physical strength: you're a very skilled sniper already, why are you messing with another skill tree? +
– It's because of those people on the internet, you know those who are a bit too much into sniper androids, especially those with cat ears? +
– Ah yes, everybody in the business has had the unfortunate experience of meeting some of them. +
– My first reaction was to use my sniper rifle on them, but after a while it stopped being satisfying. +
– So? +
– I realized that what I wanted is to crush them with my bare hands, and I need the strength to do it. +
– I understand but are you sure they wouldn't enjoy it? +
– …

== Robot who has found the perfect gift for a friend.

– It's not my birthday yet for three weeks, why a gift? +
– Since when do we need a reason to give a gift to a friend? Besides, I ordered it a few months ago and it just arrived, I didn't want to wait any longer. +
– You're so childish sometimes, but it makes me happy. +
– Oooopen the thing, I want you to see it! +
– Right, I don't want to damage the packaging, it's so nicely done.

<They grab the thing and rip the packaging apart>

– Open it, now! +
– An electronic device ? But you know I have all I need. +
– But this one is special, I'm sure you'll love it! +
– Cat ears? You bought me a pair of cat ears? I know you want me to be a… +
– But these ones are specials, look at their shape! +
– They look like receivers… wait do you mean ? +
– Yes, they include an echolocation device, I know it's a thing you wanted: you'll finally be able to hunt in the dark without any maintenance.

== Robot who's still in development 'cause they haven't worked out the kinks yet

– Please give me the reports about the latest media trends, and the quarterly corporate objectives, we have some time for once so we'll do it by the book. +
– We still have a large stock of cat ears, and snipers are always sure hit. +
– Listen, 90% of what we've done these last two months are catgirl snipers, if I ever have to do another one … well I'll ask one of them to shoot you, wait no I'm sure it would just make you die happy. Watch my mouth: no … more … catgirl … snipers … ever! +
– Well, the objectives mention a new hypno module that could shake the market, maybe R&D finally stabilized their prototype. +

They look at each other.

– Hypno snake girls! +
– With the cursed prehensile tongue ? +
– Of course! +
– Will it fit in the budget? +
– We'll tell them that the overrun is caused by issues with the hypno integration, the R&D will be too happy that someone ships their stuff to dispute it.

== An android, built to last a long time… Maybe not _this_ long, though.

The android mechanics loved their job.

Each time one of their androids broke, they had an excuse to tinker with it: of course they began by fixing the problem, but also tried to improve the android so the same issue wouldn't happen again.

But as the time passed, they became better and better at their job, and the androids became more and more reliable, and failed more and more rarely.

The tinkerer still had their head full of tweaks to try, but had no excuse to try them, their skill had become their enemy.

Fortunately for them, their manager was wise and knew that unused skills chip off, and that an unspent maintenance budget can quickly disappear.

The manager called a few friends, artists with lots of strange ideas but who didn't know anybody who could build them.

And a small drip of androids started to appear, bringing new joys and terrors to the art galleries, with a kind of reliability you wouldn't expect in this domain.

== A robot who is never in the same body as the last time you saw them.

Stealing bodies can be seen as a nasty job, but if you focus on the spare bodies of rich robots nobody is really harmed, and it means you have lots of incredible stories to tell: robots with tens or even thousands or bodies, sometimes all identical, but more often all customs: different size and morphology, but often with the same interface to ease the swapping.

Some of them use recycled military parts, it doesn't change anything because the specifications are the same, they are only more expensive and makes the maintenance more complex.

You're not sure if using the bodies after the theft is a good idea, it seems risky to you, and you're afraid to be arrested with them and being accused of being an associate.

Or maybe they are a group or friends, having some fun at your expense by sharing their memories of you.
