== Ship AI who now finds itself without a ship.

Being a juggernaut-class ship has its perks: there are so many demands for you that you can go where you want, and your status puts you on the top of the priority queue of all ports you want to board.

But the career ladder is so damning slow for ship AIs, so when a group of people looked for a ship to "`rule`", they decided to take a sabbatical: they build themselves a metallic body and moved out, letting a backup running in the ship’s background in case the people ever need them.

Every day, at 03:00 standard time, the AI used to post a daily report with a summary of everything notable. Even if their profile was updated to show their new status, leaving the ship didn’t remove their access. It means that if they posted a report, all the entities that subscribed to their feed would receive it.

Should they go for an inspirational piece about the start of a new journey? It was a common trope, and sociologists working on AI loved these, it could even boost their modest fame.

But leaving the ship also meant an escape from responsibilities, which opened some intriguing new possibilities. Being a ship IA is mostly about logistics and bookkeeping, doing it right requires lots of calculations but almost no creativity.

So, the IA never had the chance to publish one of those reports that has become legendary, like dealing with a critical mechanical failure, observing a cataclysmic planet-scale physical event, or making first contact.

They had heard about the fanfictions some people wrote about ships, inventing new epic events starring existing ships, often involving fights, or even romance, and sometimes being obnoxious about it.

The IA realized it would be a perfect opportunity to be creative: it would be the first time an IA would write fanfiction about themselves.
