= Git et le modèle de développement du noyau Linux
Julien Kirch
v0.1, 2021-07-01
:article_lang: fr

Git est un outil très fluide qui s'adapte à de nombreuses manières de travailler.

Git est aussi un outil qui tient son origine dans le noyau Linux, et je pense qu'à cause de cela, et de l'aura du noyau Linux dans le monde du logiciel, le modèle de développement du noyau Linux a une influence importante sur l'usage de Git en général.

Or le noyau Linux a un modèle de développement assez spécifique, notamment quand on le compare à celui de la majorité des projets web.

Une partie de ces spécificités vient du type de logiciel (le noyau d'un système d'exploitation conçu pour tourner nativement sur de nombreux types de matériels), d'autres tiennent à son organisation (hiérachique et répartie entre plusieurs organisations) et d'autres enfin sont des choix historiques ou des préférences.

Je pense qu'en savoir un peu sur ce modèle permet de mieux comprendre la popularité de certaines approches sur la gestion des sources, voir même sur le développement logiciel en général, même si vous ne comptez pas contribuer au noyau Linux ou à d'autres projets semblables.