= Links - 11^th^ March 2018
Julien Kirch
v1.0, 2018-03-11
:article_lang: en
:article_description: Fennel, alignment

== link:https://github.com/bakpakin/Fennel[Fennel]

[quote]
____
Fennel (formerly fnl) is a lisp that compiles to Lua. It aims to be easy to use, expressive, and has almost zero overhead compared to handwritten Lua. It's currently a single file Lua library that can be dragged into any Lua project.
____

== link:https://medium.com/@skamille/are-you-out-of-alignment-a7b193ab7fc4[Are you out of alignment?]

[quote]
____
There are a lot of obvious ways people are misaligned to their companies. The classic "`not a cultural fit`" is one. If you fight against every process, decision, person around you, even if you're right, that alignment mismatch will hurt you.

The more subtle way that most of us get out of alignment is by being unwilling to admit that we don't understand what's important to the company. We maybe don't want to understand. We want to do things that are fun and challenging and interesting to us and have that work out to be the important thing. But for the fun things to be the important thing effortlessly is pretty rare. At a certain level, creating the alignment between projects that are interesting for you and what is needed by the company is a big part of your job.
____
