desc 'Create tasks'
task :create_tasks do
  require_relative 'task_engine'
  100.times do
    # As tasks has no parameters and the default status is `waiting`
    # we don't need to pass any parameter
    TaskEngine::Task.create
  end
end
