On Cohost link:https://cohost.org/EarthShaker[it's Shaker,!?] posts link:https://cohost.org/Making-Up-Adventurers/tagged/make%20up%20an%20adventurer[prompts] about adventurers.

== Cleric who's in the market for a new deity.

Juniors have it easier: the senior cleric who is in charge of teaching them generally introduces them to their own deity.

It's easy for them to find a deity, but it doesn't mean the deal terms are good for them or that they'll be treated properly.

But when you're experienced, it's not the same thing.

First it rarely happens: if you disappoint your deity they won't leave you or fire you, instead they'll try to make you behave, if it fails something bad will happen to you.

When deities disappear, they generally have deals with other entities that automatically transfer your contract to them.

The deities that don't, well they have nastier arrangement in place.

So when I contact a deity and tell them my previous pact ended after an amicable separation they don't believe me.

And of course I don't have a letter of recommendation.

Another cleric could try to rely on their past successes, but most of the things I did are under a strict NDA, and it's probably for the better.

I could try to push for a deal with creating a large enough debt, but it's something I'd like to avoid if possible because it means I would have the lower hand when discussing the terms.

Maybe I should contact the clerics I met near the extinct volcano, sleeping in a bed and spending my days doing some paperwork would be a good change.

And not having to deal with blood all the time, yes les blood would definitely be good.

== Self-assured adventurer with a pleasant, upbeat piano jazz leitmotif.

This new Isekai feels like it could be fun: being about to hear the background music of what's happening.

After 3 hours the default theme started to become stale, but your brain learnt how to tone it down.

When you had to choose a shop to buy the equipment, you avoided the nice looking store on the main road because when you approached it the music sounded a bit creepy.

The shady store nearby with neutral music had the tools you wanted at a good price.

After booking a room at the inn, you toured the main pub.

The lonely cleric in a corner triggered an intriguing complex tone.
You suppose it means that talking to them will trigger the main quest, so you keep it for later.

You tried to spot candidates for your group.
The bearded blue knight seemed like a good candidate, but not luck.

You didn't expect this young thin trader to be one of them, until you noticed how their right hand absentminded toyed with three coins.
Traders are rarely so agile with their fingers, and you tried how they would look if the coins were replaced with lock picking tools.

A tall barbarian woman in red armor was leaning against the bar, an unusually large hammer tied to her waist.

Everybody in the place was having sneak peek at her when they thought she wouldn't notice it, and it seems like she enjoyed it.

You could have bet what would happen when you moved near her to order a drink.
The love interest theme started.
