= Links - 1^st^ October 2023
Julien Kirch
v1.0, 2023-10-01
:article_lang: en
:figure-caption!:
:article_description: WordPress and bloggers, turing completeness from two RISC instructions, align incentives, writing strategies

== link:https://flameeyes.blog/2023/09/24/wordpress-kills-the-blogger-star/[WordPress kills the Blogger star]

[quote]
____
What I'm trying to say here is reiterating that Automattic has effectively stopped looking at bloggers, particularly semi-pro bloggers (who can pay, but can't reconcile the cost of their full offerings) as their target and customers.

Indeed, the vast majority of those Semi-Pro bloggers appear to have migrated, over the past fifteen years, to Medium at first, and to Substack more recently. And while the latter still allows you to read the content over RSS feeds (unless paywalled), it also shows what other of these semi-pros blogger have started doing: owning the relationship with the readers, in form of newsletters that you need to explicitly subscribe to. Even Jetpack tries to upsell you on paid newsletters as you post your blog!
____

== link:https://kellanclark.github.io/2023/09/18/armfuck/[ARMfuck: Turing completeness from two RISC instructions]

[quote]
____
Thanks to making the program counter a general purpose register (henceforth referred to as `pc` or `r15`) and showing its actual (i.e. pipelined) value instead of the address of the current instruction, the ARM architecture has many rather “fun” edge cases. The `LDM` and `STM` instructions in particular are so bad that they've become a meme on the emudev Discord server. A couple of us have realized and joked about how they're even turing complete, but that never went beyond a funny thought experiment until now.
____

== link:https://cutlefish.substack.com/p/tbm-244-we-just-need-to-align-incentives[TBM 244: We JUST need to align incentives]

[quote]
____
A simplistic take on this might be that you can use incentives to "`design`" a system. "`Get the incentives right, and the rest takes care of itself!`" A more nuanced take is that while incentives can be designed and implemented (we certainly can decide on a benefits package or "`reward good behavior`"), more often than not, incentives _emerge, clash, interact, and morph_.
____

== link:https://lethain.com/solving-the-engineering-strategy-crisis/[Solving the engineering strategy crisis]

[quote]
____
Interestingly, Uber and Stripe are well-known technology companies, and I wrote a bit above about their technology strategies were, but neither were particularly proactive at writing their strategies down.

I've come to believe that:

* Most companies _do_ have an engineering strategy
* Awareness of that engineering strategy is often inconsistent
*  It's very rare for a company to have a written engineering strategy

This is the first really important takeaway from this talk: _you can solve half the engineering strategy crisis by just writing stuff down_.
____
