= Wytchwood, writing code and game worse than work
Julien Kirch
v0.1, 2022-05-06
:article_lang: en

My job is about software development. When writing code, you’re not supposed to repeat yourself: a piece of code is written once, then can be called as many times as needed.

In games I love some types of repeating menial grinding tasks.

Wytchwood’s gameplay is centered about crafting magic recipes, which need ingredients. Starting recipes' ingredients can be gathered, like herbs.

The result of starting recipes are the ingredients of more complex ones, and so on on several levels. The game shows your inventory and the recipes' ingredients, but you can’t track a recipe’s dependencies on several levels.

First it was fun to remember what I needed, especially as I was still exploring the locations.

[source]
----
Skeleton Key = 3 Grave Bone + 1 Mummified Head + 1 Skeeter Snoot
Mummified Head = 1 Spirit Salts
Spirit Salts = 3 Embalming Salts + 1 Unveiling Powder
Unveiling Powder = 1 Hagshroom + 1 Impeye Nut + 2 Seeker Vine
Skeeter Snoot = 1 Smoke Pellet
Smoke Pellet = 3 Clay + 1 Forest Herb + 2 Frog Slime
----

After a while, there are several recipes to fulfill at the same time. It meant trying to keep track of the ingredients in my head while optimizing my travels.

And I couldn’t reach my "`grind zone`" because there are too many tasks and the complexity is imposed by the game. Some games with crafting provide a mechanic to simplify the gatherings of components, so they can add advanced recipes without increasing the efforts to be done.

[source]
----
Love Potion = 5 Black Rose + 1 Dryad Fruit + 1 Oceanic Oil
Dryad Fruit = 1 Cinderbox
Cinderbox = 1 Campfire Ember + 3 Firefly + 1 Rodent Lard
Rodent Lard = 1 Snap Trap
Snap Trap = 1 Impeye Nut + 1 Wickerwork
Wickerwork = 1 Reedy Twine + 2 Twig
Oceanic Oil = 10 Algae + 4 Barnacle + 1 Deep One
Deep One = 1 Tidal Tincture
Tidal Tincture = 2 Skipper Scale + 1 Soothing Rune + 1 Wyrd Water
Skipper Scale = 1 Crab Trap
Crab Trap = 1 Barnacle + 2 Wickerwork
Wickerwork = 1 Reedy Twine + 2 Twig
Soothing Rune = 3 Cobblestone + 1 Soporific Potion + 1 Spirit Salts
Soporific Potion = 1 Impeye Nut + 1 Jar of Water + 2 Lethe Cap
Jar of Water = 1 Empty Jar
Empty Jar = 1 Campfire Ember + 3 Clay
Spirit Salts = 3 Embalming Salts + 1 Unveiling Powder
Unveiling Powder = 1 Hagshroom + 1 Impeye Nut + 2 Seeker Vine
Wyrd Water = 2 Bug Ichor + 2 Hagshroom + 1 Jar of Water
Bug Ichor = 1 Bait Stick
Bait Stick = 1 Meaty Morsel + 1 Toxic Thistle + 1 Twig
Meaty Morsel = 1 Snap Trap
Snap Trap = 1 Impeye Nut + 1 Wickerwork
Wickerwork = 1 Reedy Twine + 2 Twig
Jar of Water = 1 Empty Jar
Empty Jar = 1 Campfire Ember + 3 Clay
----

Then there were too many things to remember them all. I started to ponder if I should start to use paper or even a spreadsheet. Both of these would break the immersion, and the actual gathering would still take more and more time.

[source]
----
Key to my Heart
= 1 Love Potion + 1 Skeleton Key
= 5 Black Rose + 1 Dryad Fruit + 3 Grave Bone + 1 Mummified Head + 1 Oceanic Oil + 1 Skeeter Snoot
= 10 Algae + 4 Barnacle + 5 Black Rose + 1 Cinderbox + 1 Deep One + 3 Grave Bone + 1 Smoke Pellet + 1 Spirit Salts
= 10 Algae + 4 Barnacle + 5 Black Rose + 1 Campfire Ember + 3 Clay + 3 Embalming Salts + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 1 Rodent Lard + 1 Tidal Tincture + 1 Unveiling Powder
= 10 Algae + 4 Barnacle + 5 Black Rose + 1 Campfire Ember + 3 Clay + 3 Embalming Salts + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 1 Hagshroom + 1 Impeye Nut + 2 Seeker Vine + 2 Skipper Scale + 1 Snap Trap + 1 Soothing Rune + 1 Wyrd Water
= 10 Algae + 4 Barnacle + 5 Black Rose + 2 Bug Ichor + 1 Campfire Ember + 3 Clay + 3 Cobblestone + 2 Crab Trap + 3 Embalming Salts + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 3 Hagshroom + 2 Impeye Nut + 1 Jar of Water + 2 Seeker Vine + 1 Soporific Potion + 1 Spirit Salts + 1 Wickerwork
= 10 Algae + 2 Bait Stick + 6 Barnacle + 5 Black Rose + 1 Campfire Ember + 3 Clay + 3 Cobblestone + 6 Embalming Salts + 1 Empty Jar + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 3 Hagshroom + 3 Impeye Nut + 1 Jar of Water + 2 Lethe Cap + 1 Reedy Twine + 2 Seeker Vine + 2 Twig + 1 Unveiling Powder + 4 Wickerwork
= 10 Algae + 6 Barnacle + 5 Black Rose + 2 Campfire Ember + 6 Clay + 3 Cobblestone + 6 Embalming Salts + 1 Empty Jar + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 4 Hagshroom + 4 Impeye Nut + 2 Lethe Cap + 2 Meaty Morsel + 5 Reedy Twine + 4 Seeker Vine + 2 Toxic Thistle + 12 Twig
= 10 Algae + 6 Barnacle + 5 Black Rose + 3 Campfire Ember + 9 Clay + 3 Cobblestone + 6 Embalming Salts + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 4 Hagshroom + 4 Impeye Nut + 2 Lethe Cap + 5 Reedy Twine + 4 Seeker Vine + 2 Snap Trap + 2 Toxic Thistle + 12 Twig
= 10 Algae + 6 Barnacle + 5 Black Rose + 3 Campfire Ember + 9 Clay + 3 Cobblestone + 6 Embalming Salts + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 4 Hagshroom + 6 Impeye Nut + 2 Lethe Cap + 5 Reedy Twine + 4 Seeker Vine + 2 Toxic Thistle + 12 Twig + 2 Wickerwork
= 10 Algae + 6 Barnacle + 5 Black Rose + 3 Campfire Ember + 9 Clay + 3 Cobblestone + 6 Embalming Salts + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 4 Hagshroom + 6 Impeye Nut + 2 Lethe Cap + 7 Reedy Twine + 4 Seeker Vine + 2 Toxic Thistle + 16 Twig
----

Then I realized it didn’t felt like fun but like work, or even worse than work: my work is about finding ways to not do complex repetitive tasks and I like this. And I’m playing a video game where I should do the opposite.

Such a nice world that can only be explored through worse than work feels sad.

image::recipes.svg[The game's recipes]