= Wytchwood, writing code and games that feels like work
Julien Kirch
v0.1, 2022-05-06
:article_lang: en

My work involves writing software code.
When writing code, repeating tasks are supposed to be rare: a piece of code is written once,
then can be called as many times as needed, then you can adapt it to deal with other cases by making more general or by copying and tweaking it.

On the other hand, some kind of games love to make the player to do repeating tasks, like killing enemies for experience or doing simple fetch quests.

Some repeating tasks are fun to me, and I think it's primary when I can lose myself in the meniality, like "`run in a circle until it triggers an encouter, kill the monsters with two attckes, repeat`".

I'm playing Wytchwood, whose gameplay is centered about crafting.

As often the crafting requires materials.
Starting recipes requires components that can be gathered.
More advanced recipes' component can comes from simpler recipes, and so on on several levels.

The game shows your inventory and the different recipes, but don't provide a way to track the dependencies of a recipe (and even make a joke about having no on-screen map).

At the beginning it was fun to track what you need, as I was still exploring the locations so I didn't know yet exactly where to go to find specific items.

[source]
----
Skeleton Key = 3 Grave Bone + 1 Mummified Head + 1 Skeeter Snoot
Mummified Head = 1 Spirit Salts
Spirit Salts = 3 Embalming Salts + 1 Unveiling Powder
Unveiling Powder = 1 Hagshroom + 1 Impeye Nut + 2 Seeker Vine
Skeeter Snoot = 1 Smoke Pellet
Smoke Pellet = 3 Clay + 1 Forest Herb + 2 Frog Slime
----

After a while, there are several recipes to deal with a the same time, each with its own depencencies.

It meant I try to track the components in my head, trying to optimize my travels to batch the gathering to avoid going back and forthing.

The movements and craft are not exactly slow and they match the tone of the game,
but when your checklist becomes longer, it's becoming tedious.
I didn't provide the fun I have with repetitive tasks in other games probably because the game is too slow and the tasks require too much tracking effort.

Some games simplify complex crafting, for exemple by lifting the requirement to gather a ressource once you reach a milestone.
This way the game can add more interesting recipes without increasing the efforts to be done by the players.
Like in programming, where repetitive tasks can be automated, and the automated version can be leveradged to do more complex things.

[source]
----
Love Potion = 5 Black Rose + 1 Dryad Fruit + 1 Oceanic Oil
Dryad Fruit = 1 Cinderbox
Cinderbox = 1 Campfire Ember + 3 Firefly + 1 Rodent Lard
Rodent Lard = 1 Snap Trap
Snap Trap = 1 Impeye Nut + 1 Wickerwork
Wickerwork = 1 Reedy Twine + 2 Twig
Oceanic Oil = 10 Algae + 4 Barnacle + 1 Deep One
Deep One = 1 Tidal Tincture
Tidal Tincture = 2 Skipper Scale + 1 Soothing Rune + 1 Wyrd Water
Skipper Scale = 1 Crab Trap
Crab Trap = 1 Barnacle + 2 Wickerwork
Wickerwork = 1 Reedy Twine + 2 Twig
Soothing Rune = 3 Cobblestone + 1 Soporific Potion + 1 Spirit Salts
Soporific Potion = 1 Impeye Nut + 1 Jar of Water + 2 Lethe Cap
Jar of Water = 1 Empty Jar
Empty Jar = 1 Campfire Ember + 3 Clay
Spirit Salts = 3 Embalming Salts + 1 Unveiling Powder
Unveiling Powder = 1 Hagshroom + 1 Impeye Nut + 2 Seeker Vine
Wyrd Water = 2 Bug Ichor + 2 Hagshroom + 1 Jar of Water
Bug Ichor = 1 Bait Stick
Bait Stick = 1 Meaty Morsel + 1 Toxic Thistle + 1 Twig
Meaty Morsel = 1 Snap Trap
Snap Trap = 1 Impeye Nut + 1 Wickerwork
Wickerwork = 1 Reedy Twine + 2 Twig
Jar of Water = 1 Empty Jar
Empty Jar = 1 Campfire Ember + 3 Clay
----

But Wytchwood doesn't.

After a while when the dependencies has increase too much to remember them.
I started to ponder if it's better to have some inefisciencies or if I should start using some paper to track them, or even a spreadheet.

Both of these would break the immersion, require some efforts, and still wouldn't have an impact on the time to be spend on the actual gathering.

[source]
----
Key to my Heart
= 1 Love Potion + 1 Skeleton Key
= 5 Black Rose + 1 Dryad Fruit + 3 Grave Bone + 1 Mummified Head + 1 Oceanic Oil + 1 Skeeter Snoot
= 10 Algae + 4 Barnacle + 5 Black Rose + 1 Cinderbox + 1 Deep One + 3 Grave Bone + 1 Smoke Pellet + 1 Spirit Salts
= 10 Algae + 4 Barnacle + 5 Black Rose + 1 Campfire Ember + 3 Clay + 3 Embalming Salts + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 1 Rodent Lard + 1 Tidal Tincture + 1 Unveiling Powder
= 10 Algae + 4 Barnacle + 5 Black Rose + 1 Campfire Ember + 3 Clay + 3 Embalming Salts + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 1 Hagshroom + 1 Impeye Nut + 2 Seeker Vine + 2 Skipper Scale + 1 Snap Trap + 1 Soothing Rune + 1 Wyrd Water
= 10 Algae + 4 Barnacle + 5 Black Rose + 2 Bug Ichor + 1 Campfire Ember + 3 Clay + 3 Cobblestone + 2 Crab Trap + 3 Embalming Salts + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 3 Hagshroom + 2 Impeye Nut + 1 Jar of Water + 2 Seeker Vine + 1 Soporific Potion + 1 Spirit Salts + 1 Wickerwork
= 10 Algae + 2 Bait Stick + 6 Barnacle + 5 Black Rose + 1 Campfire Ember + 3 Clay + 3 Cobblestone + 6 Embalming Salts + 1 Empty Jar + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 3 Hagshroom + 3 Impeye Nut + 1 Jar of Water + 2 Lethe Cap + 1 Reedy Twine + 2 Seeker Vine + 2 Twig + 1 Unveiling Powder + 4 Wickerwork
= 10 Algae + 6 Barnacle + 5 Black Rose + 2 Campfire Ember + 6 Clay + 3 Cobblestone + 6 Embalming Salts + 1 Empty Jar + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 4 Hagshroom + 4 Impeye Nut + 2 Lethe Cap + 2 Meaty Morsel + 5 Reedy Twine + 4 Seeker Vine + 2 Toxic Thistle + 12 Twig
= 10 Algae + 6 Barnacle + 5 Black Rose + 3 Campfire Ember + 9 Clay + 3 Cobblestone + 6 Embalming Salts + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 4 Hagshroom + 4 Impeye Nut + 2 Lethe Cap + 5 Reedy Twine + 4 Seeker Vine + 2 Snap Trap + 2 Toxic Thistle + 12 Twig
= 10 Algae + 6 Barnacle + 5 Black Rose + 3 Campfire Ember + 9 Clay + 3 Cobblestone + 6 Embalming Salts + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 4 Hagshroom + 6 Impeye Nut + 2 Lethe Cap + 5 Reedy Twine + 4 Seeker Vine + 2 Toxic Thistle + 12 Twig + 2 Wickerwork
= 10 Algae + 6 Barnacle + 5 Black Rose + 3 Campfire Ember + 9 Clay + 3 Cobblestone + 6 Embalming Salts + 3 Firefly + 1 Forest Herb + 2 Frog Slime + 3 Grave Bone + 4 Hagshroom + 6 Impeye Nut + 2 Lethe Cap + 7 Reedy Twine + 4 Seeker Vine + 2 Toxic Thistle + 16 Twig
----

Than I realized it didn't felt like fun but like work, or even worse than work: I have the opportunity to have a job where I don't have to deal with this kind of tasks, where not dealing with this kind of tasks is the essence of the job.

And I bought a video game where most of the gameplay is something I would prefer not to do at work even if I was paid to do.

I guess it's time to stop playing.

image::recipes.svg[alt]