= 01/10/2017
Julien Kirch
v1.0, 2017-10-01
:article_lang: en

===== link:http://journals.sagepub.com/doi/10.1177/1461444817715020[Voodoo software and boundary objects in game development: How developers collaborate and conflict with game engines and art tools]

[quote]
____
This article describes how game developers successfully ‘pull off’ game development, collaborating in the absence of consensus and working with recalcitrant and wilful technologies, shedding light on the games we play and those that make them, but also how we can be forced to work together by the platforms we choose to use. The concept of ‘boundary objects’ is exported from Science and Technology Studies to highlight the vital coordinating role of game development software. Rather than a mutely obedient tool, game software such as Unity 3D is depicted by developers as exhibiting magical, even agential, properties. It becomes ‘voodoo software’. This software acts as a boundary object, aligning game developers at points of technical breakdown. Voodoo software is tidied away in later accounts of game development, emphasizing how ethnographies of software development provide an anchor from which to investigate cultural production and co-creative practice.
____
