= Culte du cargo, innovation, consulting et baby-foot

Des entreprises “traditionnelles” se mettent à installer des baby-foots pour leur personnel.
Elles le font pour faire comme les starts-ups, dont beaucoup on des baby-foots, des tables de ping-pong, ou des consoles de jeux-vidéos.

Leur idée est qu'en faisant "comme les starts-ups", c'est à dire en reproduisant des choses qu'on y observe, elles pourront en tirer des bénéfices : "en ayant un baby-foot comme Google, je deviendrai aussi innovant qu'eux".

Ce phénomène a un nom : link:https://fr.wikipedia.org/wiki/Culte_du_cargo[le culte du Cargo]:

[quote]
____
Le culte du cargo est un ensemble de rites qui apparaissent à la fin du xix^e^ siècle et dans la première moitié du xx^e^ siècle chez les aborigènes, notamment en Mélanésie (Océanie), en réaction à la colonisation. Il consiste à imiter les opérateurs radios américains et japonais commandant du ravitaillement (distribués par avion-cargo) et plus généralement la technologie et la culture occidentale (moyens de transports, défilés militaire, habillement, etc.), en espérant déboucher sur les mêmes effets, selon ce qu'on a qualifié de croyances « millénaristes ». En effet, les indigènes ignorent l'existence et les modalités de production occidentale ; dès lors, ils attribuent l'abondance et la sophistication des biens apportés par cargo à une faveur divine.
____

Le culte du cargo est au cœur du consulting en organisation : 

. observer des systèmes qui ont une caractéristique désirable (être innovant, être efficace …) ;
. déterminer quelles sont les causes de cette caractéristique (pourquoi est ce qu'ils sont innovants ?) ;
. vendre cette analyse à leurs client·e·s et les aider à la reproduire.

La démarche théorique ne produit pas nécessairement des cultes du Cargo, mais la manière dont elle est mise en œuvre le fait :

. observer des systèmes qui ont une caractéristique désirable (être innovant, être efficace …) ;
. déterminer quelles sont les causes de cette caractéristique _qu'on pourrait reproduire facilement chez nos clients_ (pourquoi est ce qu'ils sont innovants ?) ;
. vendre cette analyse à leurs client·e·s et les aider à la reproduire.

La conséquence de ce biais est que lorsque les causes réelles ne sont pas facile à reproduire, on se rabat sur d'autres causes qui le sont, même si elles n'ont que peu ou pas l'effet escompté.
La link:https://fr.wikipedia.org/wiki/Pensée_magique[pensée magique] fait le reste.

Le cas du baby-foot est remarquable, mais pour le comprendre il faut connaître le fonctionnement réel des start-ups.
Une start-up installe un environnement de détente pour de compenser des conditions de travail qui seraient sans cela inacceptables : instabilité du travail, inconnues sur l'avenir de l'entreprise, stress.
Le baby-foot ne les aide pas à devenir plus innovants, mais les aides à tenir le coup dans un environnent de travail très mouvant.

Il s'agit donc d'une sorte de culte du cargo inversé : on ne reproduit pas les signes du succès, mais les signes de douleur.

Je ne suis pas certain que ça soit la meilleure façon d'innover.

_Merci à link:https://twitter.com/ToF[Christophe Thibaut] pour les éclaircissements et les formulations._
