= Le culte du cargo, l’innovation et le baby-foot

- [observation] on observe que des entreprises “traditionnelles” se mettent à installer des baby-foots pour leur personnel
- [théorie épousée] ces tactiques imitent en cela la mode des start-ups dans lesquelles les éléments de “loisirs” sont intégrés à l’espace de travail
- [besoins sous jacents] elles ont pour objectifs affichés d’attirer des jeunes ingénieurs innovants et énergiques en signalant un environnement innovant, ouvert et “cool”.
- [principes en action] en réalité la start up installe un environnement de détente afin de compenser des conditions de travail qui seraient sans cela inacceptables, dans une stratégie qui vise à inciter les jeunes employées à rester plus longtemps sur le lieu de travail. Le baby-foot est donc non pas un signe positif que l’environnement de travail est propice à l’épanouissement, mais au contraire un signe que ce dernier requiert des “compensations”
- [analogie ] on a donc un cargo cult inversé : une culture s’empare des signes d’insuccès d’une autre culture afin de transférer magiquement le succès imaginé de la  culture en question. [un exemple comportemental : l’adolescent joue à l’adulte et imite un “adulte qui s’assume” en se mettant à l’alcool et aux cigarettes. Mais ces élément de la vie adultes sont des “cop outs” signalant un manque existentiel]
- [décision] regardez autour de vous: quels éléments de l’environnement avez-vous “emprunté” superficiellement à une culture différente ? Quelle est la portée et la signification réelles de ces éléments dans leur culture d’origine ?
