= « Si on n'a pas de techno à la mode, on ne trouve personne »
Julien Kirch
v0.1, 2019-01-31
:article_lang: fr
:article_description: Gnagnagnagna

== Ce que peuvent chercher les personnes qui développent

Dans mon expérience, les personnes qui développent peuvent chercher des choses différentes dans leur travail, par exemple :

* Un certain niveau de salaire
* Une certaine ambiance, par exemple sécurisante ou au contraire stressante
* Une domaine qui les intéresse
* Certaines technologies
* Le sentiment de faire une différence
* Une capacité d'évoluer dans leur poste et d'apprendre de nouvelles choses
* Le sentiment de se retrouver dans un groupe qui leur ressemble
* …

D'une personne à l'autre, l'importance donnée aux différents critères ne va pas être la même.
Chez une même personne elle pourra même varier dans le temps.

== Ce que j'entends

Quand on discute recrutement, j'ai l'impression d'entendre des sons de cloches très différents suivant à qui je parle, mais il y en a deux qui se détachent du lot.

[quote]
____
On fait du Java et du php et quand on cherche une personne de plus on trouve rapidement par le bouche à oreille des gens qui conviennent bien.
____

[quote]
____
Les personnes qui développent ne s'intéressent qu'aux nouvelles technologies, du coup sur les nouveaux projets on fait du Go ou du Node.js parce que sinon on ne trouve personne.
____

J'entends beaucoup la deuxième phrase dans les grandes organisations et les startups, alors que la première vient plutôt des structures de taille plus moyenne.

== Il y a comme un soucis

L'écart entre les deux cas pose problème :
si certaines organisation parviennent à trouver des personnes développant en Java, cela signifie que ces personnes existent.

Si certains personne attachent beaucoup d'importance au fait de développer dans une technologie "hype", ce n'est pas le cas de tout le monde.

Si des exemples mettent en défaut une assertion, c'est qu'elle est fausse.

== Explicitations

Mon hypothèse est que l'assertion est fausse, parce qu'elle contient des sous-entendus implicites.
En explicitant ces sous-entendu, on devrait pouvoir la rendre vraie, et ça nous donnera des idées pour avancer sur ce sujet.

Mon approche est guidée par ce que je connais du fonctionnement de ces organisations et des personnes qui développent.
Je ne prétend pas à l'impartialité.

Point de départ :

[quote]
____
Les personnes qui développent ne s'intéressent qu'aux nouvelles technologies, du coup sur les nouveaux projets on fait du Go ou du Node.js parce que sinon on ne trouve personne.
____

Tout d'abord, les personnes qui cherchent à recruter portent un jugement sur les personnes qui candidatent chez eux, pas sur l'ensemble des personnes.

Même si tout le monde a l'impression de recruter les meilleur·e·s, dans la réalité chacun et chacune ne peur recruter que les meilleur·e·s parmi les personnes qui candidatent chez eux.

Pour revenir sur le début de l'article : une personne qui a certains critères pour choisir son travail, et qui pense qu'un offre de poste n'y répondra pas a des chances de ne pas y candidater.

Ainsi, si les seules personnes qui candidatent quelque part sont seulement intéressée par des technologies "hypes", c'est peut-être que toutes les autres personnes qui cherchent autre choses ne candidatent pas.

[quote]
____
Les personnes qui développent _et qui candidatent chez nous_ ne s'intéressent qu'aux nouvelles technologies, du coup sur les nouveaux projets on fait du Go ou du Node.js parce que sinon on ne trouve personne.
____

Ensuite, quand on recrute, on ne retient généralement que les avis des personnes qu'on considère comme correspondant à ce que l'on recherche.

Dit autrement : si on estime qu'une personne n'a pas le niveau ou les compétences requises, on n'écoutera pas ce qu'elle a à dire.

[quote]
____
Les personnes qui développent, qui candidatent chez nous _et qui nous semblent correspondre à ce dont nous avons besoin_ ne s'intéressent qu'aux nouvelles technologies, du coup sur les nouveaux projets on fait du Go ou du Node.js parce que sinon on ne trouve personne.
____

Puis viens le problème de savoir si ce qu'on recherche est bien ce dont on a besoin.
Par exemple si on ne cherche que des link:../ovin-a-5-pattes/[ovins à 5 pattes].

[quote]
____
Les personnes qui développent, qui candidatent chez nous et qui nous semblent correspondre _à ce que nous pensons avoir besoin_ ne s'intéressent qu'aux nouvelles technologies, du coup sur les nouveaux projets on fait du Go ou du Node.js parce que sinon on ne trouve personne.
____

Finalement, quand quelqu'un nous critique, il est toujours plus facile d'entendre les remarques sur lesquelles on sait qu'on peut faire quelque chose.
En tous cas, il n'est jamais certain que ce qu'on retient correspond à l'intégralité de ce qui est dit.

[quote]
____
_Ce qu'on retient_ des personnes qui développent, qui candidatent chez nous et qui nous semblent correspondre à ce que nous pensons avoir besoin ne s'intéressent qu'aux nouvelles technologies, du coup sur les nouveaux projets on fait du Go ou du Node.js parce que sinon on ne trouve personne.
____

== De là on peut avoir des idées

Si la dernière version est bien plus longue que la première, elle donne plein d'idées sur ce qu'il serait possible de faire pour changer la situation :
peut-être le problème est-il la sélection des candidats, peut-être que c'est ce qu'on leur propose, l'environnement de travail … ?

Probablement même qu'il y a d'autres sous-entendus implicites dans la phrase qui permettraient d'ouvrir encore le champs des possibilités.

Suivant le contexte, il n'est probablement pas possible d'agir sur tous les axes, par exemple celui du domaine dans lequel vous travaillez, peut-être même qu'aucun des axes n'offre de solution facile à mettre en œuvre.

Mais peut-être que, même si elle n'est pas facile, elle est meilleure que la situation actuelle.

Les organisations devraient arrêter de se plaindre d'être dans une situation bloquée alors qu'en fait elle l'est probablement beaucoup moins que ce qu'elles pensent.

Mais cela demande un retour sur soi, et d'admettre ses propres biais et contraintes.

_Je précise que je n'ai rien contre Go ou Node.js, ou les personnes qui aiment développer avec ces outils._