= L'architecture de SI dans un cadrage

==== Cible

Avoir une liste courte de questions simples permettant d’avoir rapidement une idée macroscopique du niveau d’effort et d’expertise en architecture de SI dont on va avoir besoin sur un cadrage 360°. 

==== Dans quels buts ?

- Avoir une idée du temps à passer sur l’archi pendant le cadrage
- Pouvoir identifier les compétences à avoir pour trouver la bonne personne (qu'elle soit architecte ou non)

==== Les questions

. Avec combien d’autre applications faut-il se connecter ?
* [ ] 0
* [ ] 1
* [ ] 2
* [ ] Plus que deux
* [ ] Plus que deux et en utilisant des technologies différentes (ex : REST, SOAP, fichiers, messages)

. Cette intégration se fait-elle avec des outils ou des formats legacy et/ou exotiques (ex : CORBA) ?
* [ ] Non
* [ ] Oui

. Le projet nécessite-t-il des modifications dans d’autres projets (changement de code ou de configuration) ?
* [ ] Non
* [ ] Oui

. Quel est le nombre d’équipes à coloration "techniques" avec lesquelles il faudra interagir (ex : équipes d'architectes, de production, de sécurité) ?
* [ ] 1 ou 2
* [ ] 3 ou 4
* [ ] Plus que 4

. Faut-il rédiger un document formalisé type "dossier d’architecture" ?
* [ ] Non
* [ ] Oui
* [ ] Oui et il fait l’objet d’une soutenance formelle devant un comité d’architecture

. Le projet nécessite-t-il une technologie qui n’est pas encore présente dans le SI du client ?
* [ ] Non
* [ ] Oui
* [ ] Oui, et il faut le faire valider par les personnes en charge de l’architecture et/ou de la production et/ou de la sécurité
* [ ] Oui, dont un nouveau langage de programmation
* [ ] Oui, pour plusieurs technologies

. Le projet s’appuie-t-il sur un outil de persistance legacy et/ou exotiques (ex : base de données non connue) ?
* [ ] Non
* [ ] Oui

. Le projet nécessite-il de faire évoluer les process et/ou l’organisation de développement, d’intégration ou de déploiement du client (ex : itérations courtes) ?
* [ ] Non
* [ ] Oui
* [ ] Oui et il faut faire valider ce processus par les personnes en charge de la production
* [ ] Oui et cela a des impacts sur d'autres projets (ex : pour pouvoir faire des tests d’intégration à chaque itération)

. Le projet nécessite-il de faire évoluer les technologies de développement, d’intégration ou de déploiement du client (ex : intégration continue, industrialisation, conteneurs) ?
* [ ] Non
* [ ] Oui
* [ ] Oui et il faut faire valider ce processus par les personnes en charge de la production
* [ ] Oui et cela a des impacts sur d'autres projets

. Le projet a-t-il des contraintes de disponibilité différentes (ex : ouverture 24/7) ou de volumétrie (ex : nombre de requêtes ou de messages par seconde) de celles dont le client a l’habitude ?
* [ ] Non
* [ ] Oui

. Le projet manipule-t-il des données avec des cycles de vie différents (ex : données “froides” qui bougent peu et données “chaudes” qui sont souvent modifiées) ?
* [ ] Non
* [ ] Oui

. Le projet présente-t-il des contraintes de sécurité spécifiques (ex : PCI-DSS, RGS, ruptures de protocoles, gestion de certificats) ?
* [ ] Non
* [ ] Oui

