= Pas de process pour adapter les process
Julien Kirch
v0.1, 2017-01-28
:article_lang: fr
:article_description: Alors on attend la prochaine réorganisation

[quote, Un dialogue que j'ai souvent entendu]
____
– Et comment ça se passe sur les projets{nbsp}? +
– On a des process très lourds pour le démarrage. Le temps qu'on commence à développer il faudrait que le projet soit déjà terminé. Et entre temps on a changé d'idée. Du coup on bosse à l'arrache et le résultat c'est pas ce qu'on aurait voulu. +
— Et c'est comme ça pour tous les projets{nbsp}? +
— Non heuresement{nbsp}! Quand on veut qu'un projet aboutisse, on nomme comme responsable quelqu'un qui a suffisamment de poids pour ignorer les process, et qui fait ce qu'il faut pour que ça fonctionne. +
— Et les autres projets{nbsp}? +
— Ben ils se passent mal. +
— Et vous n'avez pas essayé de changer vos process{nbsp}? +
— Euhh{nbsp}…
____

Les grandes entreprises savent où sont les problèmes, mais si la résolution demande de changer leur manière de travailler, en général il ne se passe rien.

Ce qui peut arriver à long terme c'est que de plus en projets ignorent les règles.
Mais les règles existent toujours, de même que les personnes chargées de les mettre en œuvre.
Car on a des process, mais pas de process pour changer les process.

Les chef·fe de projet qui ont du succès et sont donc récompensées sont celles qui ont les bons contacts et font de la politique.

Quand l'information se diffuse, tout le monde essaie de faire pareil.
Lors du démarrage de chaque projet, une énergie considérable est alors dépensée pour trouver des arguments justifiant de déroger au process standard.

Souvent la solution passe par des consultants et une réorganisation{nbsp}:

. Les consultants diront ce que tout le monde sait déjà, mais d'une manière officielle.
. L'entreprise fera alors semblant de tomber des nues, car de dire qu'on savait déjà impliquerait de poser la question "mais pourquoi n'a-t-on rien fait{nbsp}?".
. L'entreprise mettra à l'œuvre un plan de réorganisation, avec de nouveaux process qui colleront plus ou moins aux besoins existants. Cela passe d'autant mieux que ce plan est marketé avec le buzzword du moment comme "agile" ou "digital".
. Cette nouvelle organisation ne prévoira pas de méta-process permettant de changer ces process.
. Trois ou cinq ans plus tard, retour à la case départ.

Je pense qu'il est très difficile qu'une organisation d'une certaine taille sache ou apprenne à s'adapter de manière continue.
La meilleure solution envisageable est alors de se réorganiser régulièrement, en tous cas avant que les problèmes ne soient trop graves, et d'essayer de faire en sorte que ces réorganisations fassent plus de bien que de mal.
