== Assassin who is getting paid by a lot of different people to kill you

The lack of people wanting to pay for high-level contracts had become an important topic for the assassins' guild because it meant that:

* Training highly-skilled members was difficult because there wasn't enough real-life contracts for them to learn
* Retaining those highly-skilled members was incredibly difficult because they would be poached by other cities with better incentives, as the saying goes "`running an assassins' guild is a cut-throat business`".

The guild first tried to contact the university to explore if it would be possible to obtain a grant under the auspice of "`vital skills`" that a city should maintain as part of its socioeconomical requirements.

It would even have triggered some tax exemptions for earmarked donations.

But some city councilors vetoed the initiative.
The same councilors that never left their house without a group of hired guards to protect them against the guild's members.

Their answer emerged during executive seminar last year: the guild decided to create "`killstarter`": the first crowdfunding site for high-reward assassinations.

People would setup pages about candidates, with details explaining all the crimes that would justify hiring one of the guild's member, the guild would specify a price, then everyone could pledge funds until the amount would be reached.

The specific non-profit status of the guild meant that they weren't allowed to sell or rent it to guilds in other cities but were only able to provide it free of charge.

The political consequences of its rapid adoptions among the continent will be covered in our next lesson.