[#MuC]
= Make Up A Criminal
ifeval::["{doctype}" != "book"]
Julien Kirch
v0.1, 2023-01-01
:article_lang: en
endif::[]

On Cohost link:https://cohost.org/SaidLikeCaleen[Cailín Grace Brown] posts link:https://cohost.org/spy-thief-assassin-who/tagged/make%20up%20a%20criminal[prompts] about criminals.


== Mob Boss who doesn't care what it is, along as it sells

<During the monthly mob steering committee meeting>

– Next item on the agenda is about middle-managers' complaints about the new catgirl catnip business line we're currently testing in the south district. +
– They always complain, especially when the yearly reviews are approaching, but is this about: not enough customers? They should know that new stuff takes some time to ramp up. +
– No boss, it's about the secondary effects. +
– Secondary effects? With all the things they sell they complain about the secondary effects of this? If they are not happy they should consider working something else than for the mob, idiots! +
– No, it's the secondary effects on our people. +
– Are they stupid enough to use the shit we sell? They should know how we deal with people who do this. +
– No, no, but after they started to spend some time with catgirls… +
– THEN WHAT? +
– They started to wear cat ears, and to go "`nya`" when they think nobody is listening to them.

== Spy who refuses to admit there's nothing nefarious going on here

– Is it the first time you've been to the Khamoth embassy? +
– Yes, remember I'm an attaché here since only one month. +
– Yes, so let's take a look, the party should go on until the morning, so takes your time and tell me what you see. +
– I can already feel something is wrong here, very very wrong. +
– So soon? +
– Yes, do you see these electrical outlets on the top of the bar ? +
– Yes. +
– They should be farther from the faucet. +
– Ahh and…? +
– These lateral doors on the side of the main stairs. +
– What about them? +
– They are too narrow, accessibility requirements means you need wider doors in a public building. +
– Errhm, can you tell me what you did before becoming … an attaché, because it's not your first job, right? +
– Ah yes, I've been a building inspector for 10 years, now let me tell you about the fire extinguishers.
