= Making Up Robots
Julien Kirch
v0.1, 2023-01-15
:article_lang: en

[quote]
____
Combat android who just doesn't pull their weight.
____

– I don’t get why you’ve become obsessed with increasing your physical strength: you’re a very skilled sniper already, why are you messing with another skill tree? +
– It’s because of those people on the internet, you know those who are a bit too much into sniper androids, especially those with cat ears? +
– Ah yes, everybody in the business has had the unfortunate experience of meeting some of them. +
– My first reaction was to use my sniper rifle on them, but after a while it stopped being satisfying. +
– So? +
– I realized that what I wanted is to crush them with my bare hands, and I need the strength to do it. +
– I understand but are you sure they wouldn't enjoy it? +
– …

[quote]
____
Robot who has found the perfect gift for a friend.
____

– It’s not my birthday yet for three weeks, why a gift? +
– Since when do we need a reason to give a gift to a friend? Besides, I ordered it a few months ago and it just arrived, I didn’t want to wait any longer. +
– You’re so childish sometimes, but it makes me happy. +
– Oooopen the thing, I want you to see it! +
– Right, I don’t want to damage the packaging, it’s so nicely done.

<They grab the thing and rip the packaging apart>

– Open it, now! +
– An electronic device ? But you know I have all I need. +
– But this one is special, I’m sure you’ll love it! +
– Cat ears? You bought me a pair of cat ears? I know you want me to be a… +
– But these ones are specials, look at their shape! +
– They look like receivers… wait do you mean ? +
– Yes, they include an echolocation device, I know it’s a thing you wanted: you’ll finally be able to hunt in the dark without any maintenance.
