= Links - 8^th^ January 2023
Julien Kirch
v1.0, 2023-01-08
:article_lang: en
:figure-caption!:
:article_description: HTTP in 2022, OSS supply chain, marketplace of rationalizations, tools for thought, capitalizing engineering costs, Elden Ring ecology, Panasonic Jungle

== link:https://blog.cloudflare.com/the-state-of-http-in-2022/[The state of HTTP in 2022]

[quote]
____
So what happened at all of those working group meetings, specification documents, and side events in 2022? What are implementers and deployers of the web`'s protocol doing? And what`'s coming next?
____

== link:https://www.softwaremaxims.com/blog/not-a-supplier[I am not a supplier]

[quote]
____
What it means is that there is no supply chain here. Because there is no
supplier. I am not providing you something that you bought from me.
There is no relationship. I put something online because I wanted to.
The fact you made your product depend on it is _your responsibility_.
Not mine. Not the one of the providers. We provide libraries. We do not
supply them. You cannot apply rules to me.
____

== link:https://www.cambridge.org/core/journals/economics-and-philosophy/article/marketplace-of-rationalizations/41FB096344BD344908C7C992D0C0C0DC[The marketplace of rationalizations]

[quote]
____
A widespread demand for rationalizations creates an opportunity to profit from producing and selling them. Rationalization producers are those who seize this opportunity and devote time, energy, and other resources to producing information useful for justifying beliefs that people want to hold for non-epistemic reasons. As with other cases, such attempts at satisfying consumer demand should be viewed through the lens of competition: from the perspective of consumers, it is beneficial to shop around for the highest quality rationalizations provided at the lowest price, which means that producers will be able to sell their rationalizations only if they produce and sell rationalizations with these characteristics. One should thus expect rationalization markets to involve the resource-efficient effects of competition, including the delegation of production to those for whom it is most profitable to produce, the consequent division and specialization of labour, and the selection for high-quality, low-cost goods.
____

== link:https://borretti.me/article/unbundling-tools-for-thought[Unbundling tools for thought]

[quote]
____
So I often wonder: what do other people use their personal knowledge
bases for? And I look up blog and forum posts where
link:https://obsidian.md/[Obsidian] and link:https://roamresearch.com/[Roam] power
users explain their setup. And most of what I see is junk. It`'s never
the link:https://en.wikipedia.org/wiki/Zettelkasten[Zettelkasten] of the next
Vannevar Bush, it`'s always a setup with tens of plugins, a daily note
three pages long that is subdivided into fifty subpages recording all
the inane minutiae of life. This is a recipe for burnout.

People have this aspirational idea of building a vast, oppressively
colossal, deeply interlinked knowledge graph to the point that it almost
mirrors every discrete concept and memory in their brain. And I get the
appeal of maximalism. But they`'re counting
link:https://www.cs.utexas.edu/users/EWD/transcriptions/EWD10xx/EWD1036.html#:~:text=wrong%20side%20of%20the%20ledger[on the wrong side of the ledger]. Every node in your knowledge graph is a
_debt_. Every link doubly so. The more you have, the more in the red you
are. Every node that has utility -- an interesting excerpt from a book, a
pithy quote, a poem, a fiction fragment, a few sentences that are the
seed of a future essay, a list of links that are the launching-off point
of a project -- is drowned in an ocean of banality. Most of our thoughts
appear and pass away instantly, for good reason.
____

[quote]
____
There`'s this pervasive idea that a tool for thought -- a hypermedia
database with bidirectional links -- can be a universal database of "`you`",
and other apps can be built on top of that data, using plugins.

[…]

But the main drawback is: _you don`'t need it_. The idea of having this
giant graph where all your data is hyperlinked is cute, but in practice,
it`'s completely unnecessary. Things live in separate apps just fine. How
often, truly, do you find yourself wanting to link a task in your todo
list app to a file in Dropbox? And if you do manage to build this vast
web of links: how often is each link actually followed?

(Aside: in the web, it makes sense that links should reflect
_potential_, since you don`'t know what people reading your document will
want to follow. But in a personal database it makes a lot more sense
that links should follow _usage_: they should be a crystallization of
the trails you`'ve followed, rather than an a-priori structure that you
impose before usage.)
____

== link:https://lethain.com/capitalize-engineering-costs/[How to capitalize engineering costs]

[quote]
____
Capitalization approaches

Although you can solve this problem in many different ways, most
organizations end up going with one of four approaches:

* _Ticket-based_: track capitalization status and time for each ticket.
Establish a default for tickets without a capitalization status (likely
that it will be expensed), and then sum hours of capitalizable work
across tickets for each engineer, multiplied by hourly cost, to
determine capitalizable engineering costs
* _Project-based_: track hours for each project, and determine a
capitalization weighting for each project (80% capitalized, 0%
capitalized, etc) based on the nature of the work. Finance then combines
this with a synthetic hourly engineering cost based on average team or
organization hourly rate
* _Role-based_: set a fixed percentage of time for each role. For
example, 80% of product engineer time should be capitalized, 0% of
infrastructure engineering time should be capitalized, etc
* _Vendor-specific_: There are also a number of vendors, including
link:https://jellyfish.co/[Jellyfish], that provide methodologies for
capitalization
____

== link:https://stevenzwahl.com/2022/08/26/ecology-review-elden-ring/[Ecology Review – Elden Ring]

[quote]
____
When making art, humans pull from what they know, reaching into what
they have studied and experienced. When these experiences are always
fleeting, what comes out?

I think a lot of games lack in how they represent the natural world
(among other things), possibly because making landscapes is a
requirement and not a passion for making certain genres. An Ecology
Review is my attempt to make sense of a game`'s relationship with Earth
through an eco-critical lense as they meet this challenge, examining
the presented mechanics and symbols pulled from the ethereal stuffing of
a roomful of nerds. For example, my humble debut the
link:https://birdmachine.games/2021/12/13/ecology-review-halo-infinite/[Halo:
Infinite review], developed simply into sections from a thesis of scope
and fidelity failing to come up to anything natural or novel, going
topic by topic on how it failed to match real landscapes.

I like to keep an unreasonably high standard for this exercise, but as
you could have guessed, today`'s topic is _Elden Ring_, which has proven
more difficult to talk about cohesively. Its merits go a lot further (as
my hours clocked on Steam or online theories may illustrate) and I had
to let go of a lot to write this review, which in reality warrants a
small novel.
____

== link:https://cohost.org/QuestForTori/post/789591-who-remembers-the-pa[Who remembers the Panasonic Jungle?]

[quote]
____
For a very brief period in late 2010, Panasonic decided enough time had passed since they were dabbling in games as a 3DO licensee, and it was time to announce a handheld supposedly designed for playing MMOs on the go.

The whole project was a string of very strange decisions which made it not at all surprising that the handheld never saw the light of day. First off, the good: The system seems to be sensible enough to include controls that at least make sense for MMOs, namely a d-pad, mouse touchpad, and a qwerty keyboard. The clamshell design on the prototype doesn`'t even look too bad when closed, though when opened it looks closer to a cheap panini press -- even the promising allegedly-720p screen looks like it was held in with gobs of glue. There was even a 3G model planned for the Jungle -- a smart idea for an online-only handheld!
____
