= 22^nd^ October 2017
Julien Kirch
v1.0, 2017-10-22
:article_lang: en

== link:https://cstack.github.io/db_tutorial/[Let's Build a Simple Database]

[quote]
____
Writing a sqlite clone from scratch in C

How Does a Database Work?

* What format is data saved in? (in memory and on disk)
* When does it move from memory to disk?
* Why can there only be one primary key per table?
* How does rolling back a transaction work?
* How are indexes formatted?
* When and how does a full table scan happen?
* What format is a prepared statement saved in?

I’m building a clone of sqlite from scratch in C in order to understand, and I’m going to document my process as I go.
____

== link:http://asciidoctor.org/docs/convert-asciidoc-to-epub/[How to Convert AsciiDoc to EPUB3 with Asciidoctor]

[quote]
____
Asciidoctor EPUB3 is a set of Asciidoctor extensions for converting AsciiDoc documents directly to the EPUB3 and KF8/MOBI e-book formats.
____

== link:https://medium.com/mammon-machine-zeal/you-are-everything-playing-god-in-a-strange-universe-3b0cc2fee6f[You are Everything: Playing God in a Strange Universe]

[quote]
____
The first time I visited Los Angeles, I felt deja vu for streets I had never seen before. Well, I had driven down these roads — just not in this world. I had spent enough time traveling the streets of Grand Theft Auto V that my mind confused the asphalt of L.A. for the pixels of Los Santos; I suddenly found myself in a borderland between the real world and a virtual representation of it.

As these man-made digital spaces begin to bleed into our world on an ever deeper level, it seems an interesting time to reflect upon our newfound creative potential. Now that we have the ability to create worlds in whatever image we choose, how are we reflecting and distorting our own reality into these collectively-imagined virtual spaces? What philosophies are — consciously or unconsciously — guiding their construction? And for us as players, as these lines between reality and virtual reality blur, just how radically can our time spent in digital worlds shift our perceptions of the world around us?
____
