= La calamité des _ice breakers_
Julien Kirch
v1.0, 2019-06-18

== C'est quoi un icebreaker ?

Quelque chose qu'on trouve au début des sessions de travail ou au début de formation, particulièrement quand la personne qui l'organise se sent des envies de coaching

La forme classique est de demande à chacun et chacune de dire quelque chose de personnel

Par exemple de prendre une carte parmi un tas disposé sur une table et de dire ce qu'elle évoque pour elle

Forme de manipulation dont le but de fabriquer un lien entre les personnes et de créer une implication des personnes dans le groupe afin d'améliorer l'efficacité du moment passé ensemble

== "`Détendez vous !`"

Pour un certain nombre de personnes, dont moi, l'effet est tout à fait inverse.

Recevoir une injonction à dire quelque chose de personnel, surtout dans un cadre professionnel me confronte à l'image que je projette de moi-même et provoque instantanément une désimplication de ma part.

La question initiale "`qu'est ce que cette carte évoque pour moi ?`" est alors remplacée par "`qu'elle image suis-je supposé ou ai-je envie de projecter, et que dois-je répondre pour essayer d'y parvenir ?`"

En effet dans le cadre professionnel qui est celui de la plupart des organisations, où on est en permanence dans une situation de jeu de pouvoir et de rapports de force, il est toujours question de savoir quelle image on projette.
Comme link:../measuring-and-managing-performance-in-organizations/[pour les évaluations], tout ce que vous exprimez pourra être retenu contre vous.

Alors que j'essaie de me comporter de manière professionnel pour produire un travail efficace, le fait d'essayer de mobiliser artificiellement une implication personnelle a donc l'effet de me démobiliser.

== Les energizer

Cas encore pire : quand on demande une implication physique, particulièrement d'avoir un contact physique avec d'autres participants et participantes.

Je n'aime pas avoir de contact physique avec des personnes dont je ne suis pas proche.

Là il s'agit d'avoir à le faire dans une réunion de travail ou une formation, soit avec des personnes qu'on ne connaît pas, soit des collègues avec qui on ne se sent pas forcément à l'aise.

De nouveau cela a un effet de me désinvestir vis à vis du groupe face à une manipulation qui essaie de mobiliser mon corps pour accroire ma productivité, plutôt qu'un engagement professionnel.

== "`Mais tu peux refuser !`"

Une réponse qui m'a été souvent faite est qu'il est possible de refuser de participer, par exemple en passant son tour.

Mais bien entendu, refuser demande d'annoncer à tout le monde qu'on ne fait pas partie du groupe, qu'on ne veut pas "`jouer le jeu`" proposé par la personne en charge d'animer la séance.

Je le formule ainsi pour mettre en avant la force de l'injonction qui est ressentie.

== Que faire ?

Renoncer à vouloir créer de l'implication à travers ce genre de manipulation qui est excluant pour une partie des personnes

En tant que coach ou animateur il faut apprendre à créer de l'implication en vous passant de ce genre de recette