= Fichiers de configuration
Julien Kirch
v0.1, 2021-05-25
:article_lang: fr
:source-highlighter: pygments
:pygments-style: friendly

Vous écrivez un programme, et vous décidez de mettre en place un système basé sur un fichier de configuration pour le paramétrer.

Si vous ajoutez des fonctionnalités à votre programme, la configuration va se complexifier peu à peu, mais partons du début.

== Le début

La première étape est en général de définir une série de clé-valeur, pour remplacer une trop longue série de variables d'environnement ou de paramètres en ligne de commandes.

[source,ini]
----
property_1=value_1
property_2=value_2
----

Jusque là tout va bien.

Il peut être nécessaire de pouvoir utiliser des `=` dans les valeurs, ce qui signifie permettre des échappements.

[source,ini]
----
property_1="val=ue1"
property_2="va=lu\"e_2"
----

Ensuite, on peut vouloir que certaines valeurs ne soient pas seulement des chaînes de caractères, mais aussi parfois des listes ou des dictionnaires (c'est-à-dire que les valeurs puissent elles-mêmes un ensemble clé-valeur).

[source,ini]
----
property_1=["val=ue1", "val=ue11"]
property_2={"va=lu\"e_2": "a", "va=lu\"e_22": "b"}
----

Quand le nombre d'entrées devient trop grand, et pour pouvoir réutiliser les noms de clés, on peut vouloir organiser le contenu du fichier en définissant des sections.

[source,ini]
----
[section 1]
property_1=["val=ue1", "val=ue11"]
property_2=value3

[section 2]
property_1=🐰
property_2={"va=lu\"e_2": "a", "va=lu\"e_22": "b"}
----

== La limite sans fichier de configuration

On a ici dépassé ce qu'on peut faire confortablement avec des paramètres ou des variables d'environnements.
Il reste possible de passer des listes dans des chaînes de caractères et d'utiliser des préfixes pour simuler les sections, le résultat est moins lisible, surtout s'il y a de nombreuses entrées.

== La factorisation ou la compilation pour les fichiers de configuration

Quand le fichier de configuration s'allonge et que le contenu se répète, le réflexe quand on travaille dans le développement est de vouloir faire de la factorisation.
Par exemple en attribuant un nom à un certain contenu, et en utilisant ce nom pour inclure ce contenu ailleurs dans le fichier

[source,ini]
----
&🐱=nya

property_1=*🐱
property_2=*🐱
----

Dans ce cas le contenu que vous éditez n'est plus directement celui qui sera utilisé par le programme car le fichier va subir un traitement qui va modifier son contenu.
Cela ressemble grosso-modo à une phase de compilation (ou de transpilation).

Pour certaines investigation, il peut devenir utile de pouvoir avoir accès au contenu traité tel qu'il sera visible depuis le programme.

Dans l'exemple ci-dessus, cela signifie être en mesure d'obtenir ce contenu{nbsp}:

[source,ini]
----
property_1=nya
property_2=nya
----

Si votre fichier de configuration utilise une syntaxe normalisée, les personnes éditant le fichier peuvent peut-être s'appuyer sur des outils existants.
Dans le cas contraire c'est à vous de le fournir.

Si votre format de fichier de configuration ne permet pas ce genre de factorisation, il est possible que les personnes se retrouvent à répondre à leur besoin dans ce domaine en générant leurs fichiers de configuration à partir d'un outil de templating.

== En passant{nbsp}: le templating

Mais en fait, même si votre format de configuration fournit des fonctionnalités avancées de factorisation, il est assez probable que des personnes vont vouloir générer ces fichiers à partir d'un autre outil.

Pour un outil utilisé par des serveurs, cela peut être pour des raisons d'industrialisation de déploiement, mais le besoin se fera probablement sentir même pour un outil réservés aux postes de travail.

Cela signifie que plus votre format de fichier sera facile à templatiser, plus vous simplifierez ces cas d'utilisation.

Dans mon expérience, deux choses sont à prendre en compte pour cela{nbsp}:

. le fait d'avoir une syntaxe régulière avec un nombre d'exceptions limitées{nbsp};
. le fait d'utiliser des règles d'échappement standard.

La deuxième règle étant bien plus importante que la première car implémenter une gestion des échappements demande du code assez minutieux et bien testé, c'est-à-dire quelque chose qu'on préfère en général éviter quand on le peut.

== La factorisation{nbsp}: nécessaire ou pas alors{nbsp}?

Si proposer une capacité de factorisation dans une syntaxe de configuration est utile, je suis partagé sur le fait de savoir si le jeu en vaut la chandelle à cause de la complexité que cela ajoute.

Je suis probablement partial en tant que développeur et du fait qu'utiliser du templating est facile pour moi, mais d'un autre côté je soupçonne que beaucoup des personnes qui utilisent la factorisation seraient aussi en mesure d'utiliser du templating.

== Les comportements dynamiques

La dernière étape dans la complexité d'un fichier de configuration est d'avoir des comportements dynamiques, c'est à dire qui dépendent de l'exécution du programme.

Par exemple avoir des conditions{nbsp}:

[source,ini]
----
if animal == cat
then nya
----

Par rapport à la factorisation, les comportements dynamiques ne sont pas une optimisation d'écriture des fichiers mais permettent des comportements qui sinon sont impossibles.

Si on peut continuer à voir cela comme un fichier de configuration, le comportement s'apparente véritablement à du code.

De même que la factorisation rend utile d'avoir accès à une version développée du fichier, avoir un comportement dynamique rend utile de pouvoir observer d'une manière ou d'une autre le fonctionnement du logiciel (par exemple via des logs détaillés), et même idéalement de pouvoir le débugger.

Il y a quelques années, il y avait une certaine logique à développer son propre système pour cela, soit à inventer sa propre syntaxe à ajouter à un format de fichier existant.

Par exemple avec link:https://ant.apache.org[ce genre de choses]{nbsp}:

[source,xml]
----
<if>
    <equals arg1="${condition}" arg2="true"/>
    <then>
        <copy file="${some.dir}/file" todir="${another.dir}"/>
    </then>
    <elseif>
        <equals arg1="${condition}" arg2="false"/>
        <then>
            <copy file="${some.dir}/differentFile" todir="${another.dir}"/>
        </then>
    </elseif>
    <else>
        <echo message="Condition was neither true nor false"/>
    </else>
</if>
----


''''

À rédiger :

Quand on a factorisation en cascade, on se retrouve à avoir du mal à suivre ce qui se passe, parfois on a ajoute l'équivalent de logs en écrivant des contenus intermédiaires pour pouvoir suivre ce qui se passe, et on aimerait bien pouvoir débugger dans les cas extrême.

On a un traitement => c'est un programme qu'on execute.

Suite : les conditions, et les boucles.

Dans ce cas on a clairement un comportement dynamique.

Souvent on a du mal à se dire qu'on veut du code car on voit ça comme de la configuration, mais ce n'est pas différent d'une phase de compilation.

Il y a quelques années c'était difficile d'utiliser un langage de programmation pour ça mais ça n'est plus le cas.

Je pense même qu'il est souhaitable d'avoir un langage de programmation statique, qui permette de faire de la vérification de format et le typage sur le contenu. L'équivalent des validation de schéma en XML.

On peut le faire depuis le code qui utilise la configuration, mais l'avoir dans le langage de configuration permet d'avoir de la validation dans l'éditeur.