= Fichiers de configuration
Julien Kirch
v0.1, 2021-05-25
:article_lang: fr
:source-highlighter: pygments
:pygments-style: friendly

Vous écrivez un programme, et vous décidez d'utiliser un fichier de configuration.

== Jusqu'ici tout va bien

La première étape est de définir une série de clé-valeur, c'est-à-dire l'équivalent de ce qu'on pourrait trouver dans des paramètres ou des variables d'environnements.

[source,ini]
----
property_1=value_1
property_2=value_2
----

Jusque là tout va bien.

Il peut être nécessaire de pouvoir utiliser des `=` ou des `"` dans les valeurs, il est nécessaire de pouvoir gérer les échappements.

[source,ini]
----
property_1="val=ue1"
property_2="va=lu\"e_2"
----

Ensuite, on peut vouloir que certaines valeurs ne soient pas seulement des chaînes de caractères, mais aussi parfois des listes ou des dictionnaires.

[source,ini]
----
property_1=["val=ue1", "val=ue11"]
property_2={"va=lu\"e_2": "a", "va=lu\"e_22": "b"}
----

Et pour finir on peut vouloir organiser le contenu du fichier en définissant des sections pour faciliter le fait de grouper des propriété qui vont ensemble.

[source,ini]
----
[section 1]
property_1=["val=ue1", "val=ue11"]
[section 2]
property_2={"va=lu\"e_2": "a", "va=lu\"e_22": "b"}
----


On a ici dépassé ce qu'on peut faire directement avec des paramètres ou des variables d'environnements (s'il reste possible de passer des listes dans des chaînes de caractères et d'utiliser des préfixes pour simuler les sections, cela reste des contournements qui n'offrent pas le même niveau de lisibilité).

Cette étape correspond pour moi au point d'utilité maximale des fichiers de configuration : on est capable de saisir du contenu avec une certaine expressivité et aucun traitement n'est apporté ensuite au contenu, ce qui fait que le contenu visible est exactement celui qui sera utilisé.

(En réalité ce n'est pas exactement le cas à cause des échappements, mais je pense que sauf en de très rare situations il n'est pas possible de s'en passer.)

== Ça commence à ne plus aller

Quand le fichier de configuration s'allonge et se répète, le réflexe quand on travaille dans le développement est de vouloir factoriser le contenu.
Par exemple en attribuant un nom à un certain contenu, et en utilisant ce nom pour inclure ce contenu ailleurs dans le fichier

[source,ini]
----
&🐱=nya

property_1=*🐱
property_2=*🐱
----

Dans ce cas le contenu que vous éditez n'est plus celui qui sera utilisé car le fichier va subir un traitement qui va modifier son contenu.
Il peut devenir intéressant de pouvoir avoir accès au contenu traité tel qu'il sera visible depuis le programme qui va l'utiliser.

Dans l'exemple ci-dessus, cela signifie être en mesure d'obtenir ce contenu :

[source,ini]
----
property_1=nya
property_2=nya
----

Cela signifie s'appuyer sur un programme externe s'il s'agit d'une syntaxe normalisée et que de tels outils existent, ou de fournir cette capacité via ce programme.

''''

À rédiger :

Quand on a factorisation en cascade, on se retrouve à avoir du mal à suivre ce qui se passe, parfois on a ajoute l'équivalent de logs en écrivant des contenus intermédiaires pour pouvoir suivre ce qui se passe, et on aimerait bien pouvoir débugger dans les cas extrême.

On a un traitement => c'est un programme qu'on execute.

Suite : les conditions, et les boucles.

Dans ce cas on a clairement un comportement dynamique.

Souvent on a du mal à se dire qu'on veut du code car on voit ça comme de la configuration, mais ce n'est pas différent d'une phase de compilation.

Il y a quelques années c'était difficile d'utiliser un langage de programmation pour ça mais ça n'est plus le cas.

Je pense même qu'il est souhaitable d'avoir un language de programmation statique, qui permette de faire de la vérification de format et le typage sur le contenu. L'équivalent des validation de schéma en XML.

On peut le faire depuis le code qui utilise la configuration, mais l'avoir dans le langage de configuration permet d'avoir de la validation dans l'éditeur.