== Dominique Bunier

Dominique Bunier est entrée à OCTO en juillet 1999.
Elle y a exercé différents métiers : consultante, ingénieure d'affaire, directrice des opérations, directrice commerciale puis directrice de l'assurance puis l'entité banque-assurance.
Depuis deux ans elle occupe à nouveau des reponsabilité transverse, nottamment dans la link:https://blog.octo.com/immersion-dans-la-skool-laccelerateur-de-carriere-a-la-sauce-octo-15/[Skool] facilitant l'intégration des jeunes OCTOs.




Je suis rentrée à OCTO en juillet 1999, donc ça fait 19 ans.
Au tout début j'étais entrée avec un job pas déterminé, parce qu'à l'époque on rentrait chez OCTO, c'est tout.
J'étais la numéro 15 à l'époque à rentrer.
Petit à petit j'ai fais des métiers différents chez OCTO.
J'ai été consultante pendant quelques mois, après j'ai été ingénieure d'affaire mais comme on n'était pas très nombreux je faisais pas mal de choses, j'ai faisles premiers petits déjeuners, du recrutement, de la RH, plein plein de choses.
Après j'ai été directtrice des opérations pendant quelques années.
Après j'ai repris du métier côté ingénierie d'affaire, j'étais directrice commerciale.
Après j'ai repris toute l'entité assurance puis l'entité banque-assurance.
Et là ça fait deux ans que je suis de nouveau en transverse.

*Te souviens-tu de la manière dont tu voyais l'agile et les agilistes avant qu'ils n'arrivent à OCTO ?*

En c'est c'est particulier parce que je pense que par rapport à ton introduction, on n'a jamais de faire une transformation agile ou d'aller vers l'agile.
C'est pas quelque chose qui a été conscientisé.
Moi je trouve qu'il y a eu plusieurs faisceaux.
Un premier faisceau qui était technique et qui vient entre autre je pense de, on faisait un gros projet à la BNPP qui s'appellait AceTP, sur lequel il y avait Vincent Massol qui avait introduit jUnit et les tests unitaires.
Je me souviens en 2000-2001 j'allais voir des clients en disant chez OCTO on code différement car on fait des tests unitaires.
C'était en 2000-2001 donc vraiment il y a très très longtemps.
En et fait à l'époque ce qui avait le vent en poupe c'est tout ce qui tournait autour de l'XP.
En fait, par ces gens qui étaient un peu tech est arrivée un peu ces méthodes où tu réfléchis à ton test.
Un moment donné on a recruté un extra-terretre qui s'appellait Emmanuel Gaillot.
On a démarré avec Emmanuel Gaillot qui est un profil assez particulier : bon dans la tech mais je pense que c'est lui qui a commencé à nous pikouzer un tout petite peu avec l'agile.
Moi à l'époque j'étais ingénieure d'affaire et je me souviens avoir fait des avants-ventes avec Emmanuel où on expliquait au client ce que c'était que l'agile, qu'il n'y avait plus besoin de spécifications et ainsi de suite, qu'on faisait des cycles itératifs, qu'on était tout le temps en prod, ce genre de chose.
Et les clients nous disaient "vous êtes gentil c'est joli mais pas chez moi".
On a pu faire un nombre d'avant-vente où on présentait ça, on disait "vous ne voulez pas essayer juste un petite peu ?" et ils nous disaient non.
Et en fait en parallèle de ça, ce qu'on a fait souvent chez OCTO, et je pense que c'est PP qui est à l'origine de ça, on s'est dit on va tester nous-mêmes sur un projet, et à l'époque Pierre il avait un projet de micro-crédit qu'il avait eu envie de lancer en interne OCTO, et je crois qu'on a essayé l'agile la première fois sur ce projet là.
Et le projet d'après sur lequel on a fait l'agile c'était Octopod.
Donc avant vraiment de se sentir solide pour aller en parler avec les clients, on avait déjà eu ces expérimentations en interne.
Si je ne me trompe pas.
Donc en fait on a eu plusieurs fasceaux : c'est arrivé par la tech, c'est arrivé par des gens qui se trouvaient très inspirés par ce qui se faisait aux USA, ces méthodes. Emmanuel a ramené Christophe, a ramené Bernard Notariani.
Après on a embauché des gens qui n'étaient pas du tout dans l'agile, style quelqu'un qui a beaucoup compté après qui s'appellait Olivier Pizzato.
Je me souviens parce que c'était moi qui l'avait recruté à l'époque.
Il était tech et il est resté architecte pendant même pas un an et puis il a tout de suite viré vers le lean vers l'agile.
Il était complètement emballé.
À l'époque aussi on avait des gens qu'on avait embauchés comme jeunes consultants architectes et qui sont venus petit à petit à la méthodo.
Il y aussi un truc c'est qu'à l'époque on commençait à en avoir marre d'avoir des projets en V, qui ne sortaient pas ainsi de suite.
Nous on n'était pas dans le projet à l'époque, on ne faisait pas de delivery, on faisait vraiment du conseil en architecture, et en fait on faisait du conseil, on faisait de belles archi, on faisait de beaux POCS, parfois on allait un petit peu plus loin que le POC par exemple sur AceTP où on aidait les clients à développer.
Mais en fait à l'époque quand on développait on développait les parties techniques comme les frameworks techniques.
Et à ce moment là on a commencé à mettre en place des usines de développement mais on n'était absolument pas dans des équipes de delivery classiques.
Et on voyait que les équipes de delivery classique elles en bavaient c'était hyper compliqué pour elles, et on se rendait compte que les projets n'aboutissaient pas.
Nous on était sur la partie consulting technique, framework technique et c'était insupportable pour nous.
Donc c'est là, pour moi ça a été un des marqueurs, c'est con, on construit de belles archis et en fait on ne va pas jusqu'au bout parce que nous-mêmes on ne va pas dans le delivery parce qu'on n'aime pas les méthodo qui son appliquées et pourtant on entend qu'on a de belles méthodos à côté, donc est ce qu'on ne commencerait pas à se les appliquer ?
C'est un peu l'histoire que j'ai : différents faisceaux.
Parce qu'au tout début d'OCTO on ne faisait pas du tout de delivery, par contre on avait tout le temps les mains dans le cambouis, c'est à dire qu'on faisait du code technique, on faisait du framework, on faisait des comparaisons de filières ce genre de choses.

*Est ce que tu te souviens des premières réactions à OCTO quand les premiers agilistes sont arrivés, comment ça s'est passé ?*

En fait c'est marrant parce que pour moi j'appellerai ça moins des agilistes que des coachs, et en fait ça ne s'est pas bien passé.
Je pense qu'il y a eu différents courants.
Ce qui ne s'est pas bien passé c'est que les coachs à un moment donné ont eu une posture assez donneuse de leçon et assez "y'a qu'à faut qu'on" et assez "ce qu'ont fait les autres c'est de la merde" ou ce genre de choses et du coup il y avait une confrontation fachement forte
À la fois c'était intéressant ce qu'ils apportaient et puis techniquement on voyait les changements.
Mais à côté de ça il y avait une posture assez "je ne mets plus les mains dans le code" et d'ailleurs c'était assez marqué : ils avaient un TACE juste dégeulasse, parce qu'on n'arrivait pas à les staffer, ils étaient trop en avance, ils étaient dans des postures trop marquées.
Et il y a des gens comme Marc, je me souviens très bien de Marc parce qu'au tout début je travaillais sur la SGIB et Marc dans les tous premiers projets qu'il a fait, il bossait à la SGIB et il était consultant architecte J2EE au départ il faisait du Java, et petit à petit il s'est mis à coder différement, et petit à petit il s'est mis à faire de l'agile dans les projets.
On on a vu effectivement un certain nombre d'OCTOs qui sont venu du dev et qui progressivement se sont mis à l'agile, mais de manière beaucoup plus progressive et sans posture trop forte.
Il y avait un autre agiliste à l'époque mais on ne l'a pas gardé longtemps parce qu'il avait des postures …
C'était incroyable parce que l'agile on parlait d'ouverture, on parlait de choses différentes et ils avaient une approche ayatolesque, et c'était très marqué.

*Ce n'était pas le cas des architectes ?*

En fait il y avait une grosse différence c'est que les architectes ils étaient en mission, ils étaient sur le terrain, ils étaient avec les clients, ils faisaient des propales, ils faisaient des missions, ils faisaient des livrables.
En fait ils étaient dans les faire. Et à l'époque les agilistes étaient beaucoup dans l'incantatoire. "Il faudrait faire, il faudrait ceci, il faudrait qu'on, gnagnagna"
Et au début il y avait peu de missions agiles, donc peut-être que les architectes avaient des positions très tranchées, mais moi mon sentiment ou peut-être que je refabrique l'histoire, j'avais l'impression que c'était pragmatique et je ne pense pas que les architectes avaient des postures anti-méthode, je crois qu'ils avaient surtout envie que les agilistes retroussent leur manches et qu'ils aillent sur le terrain concret.
Et quand je dis "les agilistes", c'est effectivement la petite catégorie Yves Bizeul, Bernard Nottariani, Olivier Pizzato il était un peu concret au départ, au bout d'un moment il est parti un peu en live.

*Comment as-tu vécu cette période ?*

En fait on la voyait très peu.
Il y avait effectivement un peu ce frittage là parce que…
C'est une époque aussi où les agilistes ils nous avaient dit "laissez nous expérimenter à notre façon, on veut se piloter différement" et chez OCTO on est toujours orienté expérimentation donc on leur avait dit "OK, expérimentez votre truc" un petit peu comme quelques années après on a dit à CHAK "rebootez votre tribu et pilotez là comùme vous voulez", ça faisait partie des expérimentation.
Le seul truc c'est qu'à l'époque c'était très très précurseur donc il y avait très peu de clients pour commencer à faire ça.
Donc ce qui nous interpelait nous c'était qu'ils étaient dur à staffer, c'est dur de leur trouver des missions.

*Et avec les clients, comment passait le mélange architecte / agiliste ?*

Je n'ai pas de souvenir dans un sens ni dans l'autre. Je ne suis pas sure d'avoir vécu des choses marquantes.

*Combien de temps pour que vous trouviez un équilibre, il y a eu plusieurs phases ?*

Je ne sais pas combien de temps ça a pris.
Mais en tout cas ce que je sais c'est que ça a pris quand des architectes se sont mis à faire de l'agile.
C'est à dire quand des gens sont venus à faire le pont entre les deux.
C'est pour ça que je te parlais de Gilles Laborderie, d'Ismael … 
Après tu as des plus jeunes, tu vas trouver des Fabrice Robini, tu vas avoir des gens comme ça aussi qui s'y sont mis.
C'était des gens qui faisaient plutôt du conseil en archi et qui petit à petit, c'est à l'époque où on a, un peu avant qu'on lance ISMO, commencé à travailler avec des clients et qu'on avait envie d'aller plus loin que simpleme t de la presta de conseil où on lance un PPT.
Et ces architectes qui ont eu envie de faire un petit peu plus, eux se sont mis à adopter les méthodes agiles.
Moi j'ai le sentiment que c'est vraiment à partir de ce moment là que ça a vraiment diffusé.
L'équipe des Christophe, Emmanuel Gaillot, ils étaient inspirants dans la théorie, dans l'explication, à quoi ça sert et tout, mais ça s'est vraiment diffusé quand on a commencé à avoir des gens qui étaient des faiseurs.

*Rétrospectivement, qu'auriez-vous pu faire pour que ça se passe mieux ?*

Je ne sais pas pas.
En fait on a commencé avec l'agile, on a été je pense une des toutes premières boites en France à faire de l'agile.
Donc c'est compliqué : tu testes un truc.
Maintenant l'agile tout le monde en fait.
Mais à l'époque on ne savait pas du tout si …
On avait des convictions on trouvait que ça faisait du sens et tout mais on ne savait absolument pas on allait faire basculer nos clients, on ne savais pas du tout s'il fallait qu'on cpntinue dans cette voie là.
On le sentait mais on ne le conceptualisait pas en se disant "c'est notre stratégie, on y va à fond".
C'est compliqué de ne pas réécrire non plus l'histoire donc.
Je pense que aujourd'hui on a chez OCTO une maturité et des techniques de facilitations d'ateliers, du fait que les gens se parlent encore plus et se confrontent.
Avec nos outils d'aujourd'hui d'animation d'équipe remis 10-14 ans en arrière je pense qu'on aurait eu ça beaucoup plus facilement.
À l'époque tout ce qui était PG, ça n'existait pas, c'est arrivé à peu près à cette époque là les notions de perfection game tout ça.
Toutes ces histoires de rétrospectives on ne les avait pas ces outils là d'animation.
Provoquer le fait que les gens aillent plus se parler, s'échanger, étudier les douleurs, faire des Keep Drop Start.
Ces outils là aujourd'hui on aurait pu les appliquer mais on ne les avait pas à l'époque, on ne les connaissait pas.

*Est ce que vous auriez pu faire mieux avec les moyens que vous connaissiez à l'époque ou est ce que c'était le mieux qu'on pouvait faire ?*

J'ai du mal à dire.
L'agile s'est très vite diffusé chez OCTO parce que les gens ont pris les pratiques agiles.
Et tu avais effectivement les agilistes qui étaient dans une posture de coaching agile et tu avais les gens qui voulaient développer, qui faisaient les projet qui faisaient de l'agile.
C'était vraiment ces deux postures là, un petit peu différentes.
Et puis avec des coachs agiles un peu perchés avec énormément de convictions, qui les défendaient.

*Après tout ce temps, qu'est-ce que tu n'as toujours pas compris chez les agilistes ?*

En fait le terme agiliste me gène beaucoup, parce ce que je ne sais pas ce qu'on met derriere.
Maintenant on parle de dev agile, à l'époque on ne parlait pas de dev agile, maintenant on en parle parce que les développeurs travaillent en mode agile.
Le tech lead c'est quelqu'un qui fait de l'agile.
Après l'agiliste est ce que c'est le coach agile sur un projet mais en fait on n'en a plus chez OCTO des coachs de projet.
À une époque on en avait, ce qu'on aurait appellé Scrum Master mais comm on n'avait jamais voulu se mettre l'étiquette Scrum Master on appelait ça des coachs agiles.
Le tech lead va avoir le rôle de s'assurer que les rituels agiles aient bien lieu mais on ne va pas le positionner en tant que coach agile.
Aujourd'hui nos agilistes sont plutôt des agilistes qui sont sur SCALE et qui vont travailler plutôt sur l'agile à grande échelle.
Même s'ils le font encore parfois sur quelques projets mais leur objectif quand ils le font sur quelques projets c'est pour passer à l'échelle, le déployer sur plus.
À l'époque au tout début oui on avait pour le coup ce qu'on aurait appelé des Scrum Master. 

L'image que j'en garde s'est effectivement une petite équipe d'agilistes un peu barrés, très inspirants.
Pierre était très très inspiré par eux et du coup il était vraiment porte-voix.
Et au bout d'un moment ça a diffusé dans les équipes.

Eux ne se sont pas beaucoup déplacés car eux s'étaienrt déplacés avant, globalement ils venaient tous de la tech, ils avaient tous ce background tech, ils ont découvert la méthodo le coaching et c'était vachement bien pour eux.
Eux ils étaient déjà là et pour le coup ils avaient laché la tech c'était plus vraiment leur sujet.
Mais après c'était pas des bagarres, il y avait des échanges musclés.
Le truc qui me marquait c'est que c'était pas une posture que je qualifierai aujourd'hui de donneur de leçon.
Ce qui nous marquait beaucoup c'est qu'ils n'avaient pas de TACE et que ça nous gonflait qu'ils nous donnent des leçons alors que c'étaient les autres qui faisaient bouillir la marmite.
Mais on l'a laissé faire, on l'a laissé vivre, et puis tu vois Christophe est toujours là et tu as des gens fabuleux qui se sont transformés comme Marc qui a fait un parcours absolument incroyable de dev à tech lead à coach agiel à coach tout court.

_Le 3 avril 2018_
