== Quand les agilistes sont entrés à OCTO 2/5 : Laurent Brisse

Laurent Brisse est un des architectes historique d'OCTO.
Aujourd'hui il est coordinateur architecture chez link:https://www.lectra.com/fr[Lectra], un client d'OCTO.

*Comment s'est passée l'arrivée de l'agile à OCTO ?*

J'étais centré sur l'architecture donc l'agile n'était pas dans mes préoccupation principales.
Mes premiers souvenirs portent plutôt sur les nouvelles façons de faire et les nouvelles méthodes de coaching que sur les aspects purement agiles.
Je me suis appliqué ces méthodes pour réduire la boucle de feedback et travailler plus sur l'équipe que sur les personnes : travailler de manière collaborative, faire mieux participer nos clients aux ateliers …

*Qu'à donné le mélange des deux à OCTO ?*

Ce que je retiendrais de la fusion entre l'agilité et l'architecture c'est le passage du Dossier d'Architecture Générale au Cadrage 360°.
C'est l'aboutissement des échanges entre des architectes qui voulaient tout cadrer dès le début et des agilistes qui voulaient commencer les développements immediatement.

Le cadrage 360° c'est de dire qu'au lancement d'un projet le seul engagement qu'on peut prendre est qu'en deux ou trois semaines on peut faire une première estimation, même si pas définitive ou engageante.
Une des forces d'OCTO ça a été de dire qu'on ne ferait pas de développement sans commencer par ce type de cadrage, et c'est devenu un reflexe.

*Comment s'est passé le changement pour les clients ?*

Jusqu'à ce moment nous faisions de l'architecture, des POCs ou des projets techniques.
L'agilité est arrivée en même temps que la volonté de faire du développement projet.
À ce moment là 7 personnes sont parties.
Vendre du coaching agile était alors compliqué, c'est grâce au développement qu'on a pu vendre de l'agile et plus tard de l'UX.

*Qu'est ce qui manque encore sur l'approche agile ?*

La gestion des moyens.
Dans mon expérience on travaille toujours avec un budget et il faut un minimum de prévisibilité.
Les réticences des agilistes face aux estimations est cohérentes : leur objectif premier est d'apporter de la valeur.
Mais un projet ce sont des priorités budgétaires et des personnes avec des carrières, je ne peux pas juste avancer de deux semaines en deux semaines.
Pour moi la manière de s'y prendre en agile n'est pas encore très claire, le link:http://videos.ncrafts.io/video/167699026[_no estimates_] pourrait être une façon d'en sortir mais c'est très difficile de convaincre nos interlocuteurs.

_Le 26 mars 2018_

