== Marc Cherfi

Marc Cherfi est arrivé à OCTO en 2004 en tant qu'architecte logicielle et architecte de SI. Il a travaillé avec Pierre Pezziardi à la direction technique.
Avec l'arrivée des agilistes l'a amené à expérimenter de nouvelles pratiques sur ses missions d'architectures.
En 2007 il a commencé à aborder le sujet du changement sur d'autres angles que celui de l'agilité pour aujourd'hui travailler sur le link:https://blog.octo.com/rencontres-avec-un-culture-hacker-marc-cherfi/[culture hacking].

*Comment s'est passée l'arrivée des agilistes à OCTO ?*

Comme une phase d'émulation, parfois agressive dans les débats sur l'agilité ou pas l'agilité, l'architecture ou pas l'architecture, les bleus et les gris…
Plein de débats avec plus ou moins de mauvaise foi, des trolls qui pouvaient être poussés loin dans les mailing-list et puis parfois des pépites.
Ça m'a beaucoup inspiré et parfois aussi heurté.

[quote]
____
On interprétait le discours des agilistes comme des trolls parce que ce qu'ils disaient nous piquait, parce qu'au fond leurs diagnostiques étaient justes.
Cette phase parfois un peu chaotique montrait bien qu'on était en train de basculer, même si c'était parfois en trollant ou un peu agressivement.
____

J'ai beaucoup apprécié les premiers link:https://www.octo.academy/fr/formation/145-l-atelier-du-changement[ateliers du changement] par Emmanuel Gaillot, ça m'a permis de nouer des liens puis de m'appuyer sur ces personnes de temps en temps en même temps que de les regarder et de s'inspirer d'eux.
En agile tout était à faire : on n'avait rien et le métier de coach n'était pas reconnu en tant que tel.
On ne nous appelait pas en mission pour ça.

À cette époque j'ai basculé dans l'agilité, tout seul dans mon coin.
Par exemple dans un audit d'architecture et de pratiques de développement, j'ai commencé à me mouiller en mettant en place une dynamique d'organisation plutôt agile et collaborative.

*Qu'est ce qui faisait que les choses avançaient ?*

On avait une capacité à l'époque de faire descendre la violence des échanges par de l'informel : prendre des bières ensemble, se croiser en mission ou s'envoyer des petits messages.
Par exemple j'ai été deux ou trois fois chahuté parce que j'avais une approche un peu plus ouverte et souple, par exemple sur les cellules d'architectures, et souvent ensuite il y avait des excuses informelles.

[quote]
____
Il y avait des régulations, c'est à dire cette capacité de ramener du feedback négatif, de ramener à la norme c'était à dire le lien, parce qu'on voulait préserver le lien malgré tout.
On pouvait donc se lâcher et en même temps quand on voyait qu'on dépassait les bornes on avait cette capacité de régulation où on nous invitait à l'avoir.
____

Un des éléments clés était que nous n'étions pas très nombreux à l'époque car cela permettait des régulations directes.

[quote]
____
Je pense qu'à l'époque, même si la communication était parfois maladroite, on savait mettre en conflit les choses.
____

Assumer ce conflit était une marque de fabrique d'OCTO, Ludovic Cinquin contre Pierre Pezziardi en était une représentation à l'échelle de la direction.
Je ne dis pas que Pierre avait raison et que Ludovic n'avait pas raison car ce n'était pas l'essentiel, l'essentiel était le fait d'assumer ce conflit.
Ce conflit créait de la variété et au final on appréciait tout ce qui se passait, on ne nous disait pas "choisissez votre camp ou disparaissez".
Aujourd'hui il y a plus d'homogénéité, on se prive donc de la puissance de la confrontation.

Le troisième aspect c'était l'envie de faire du nouveau, même s'il était variable d'une personne à l'autre.
Elle était déjà dans la construction d'OCTO avant même l'arrivée des agilistes, sinon on n'aurait pas embauché des gens comme ça.

*Comment as-tu vécu cette période ?*

Je pouvais monter dans les tours à l'époque, ou être indigné à ma manière.
Souvent ça voulait dire le garder pour moi, car je ne suis pas du genre troll, mais il m'est arrivé de répondre aussi ou de critiquer, d'être un peu cynique, voire méchant.

Sur la tendance je pense que je le vivais très bien, car c'était hyper stimulant, ça m'a incité à aller voir : je n'ai pas participé à l'atelier du changement par hasard.

Je suis content qu'on m'ait fait violence, parce que ça veut dire que ça me transformait et grâce à ça j'ai changé de métier et je ne le regrette pas aujourd'hui.

*Et avec les clients, comment passait le mélange entre architecte et agiliste ?*

Ça ne se passait pas toujours bien je crois.
Dans certains missions le client critiquait nos démarches ou les OCTOS se critiquaient entre eux.
Les missions sur l'agile n'étaient pas très nombreuses au début : on cherchait le marché et le marché n'était pas du tout réceptif.

Les agilistes ont été des pionniers dans leur discours.
Certains se sont épuisés, fatigués à convaincre.

Des gens comme moi se sont inscrits dans leur sillage : nous testions des trucs dans des missions qui n'étaient pas forcément agiles au sens strict sans forcément vouloir tout révolutionner.
La question était de faire autrement un métier de conseil et d'apporter une nouvelle dimension au regard d'architecte.

La conclusion de tout ça c'est que ce sont les architectes qui ont le mieux vendu l'agilité, les architectes de l'époque dont certains ont shifté depuis.

Après des succès ont confirmé notre approche puis le fait de faire des projets a permis de l'emporter.

*Qu'est-ce que ça a changé à l'architecture ?*

On ne fait plus les missions de la même manière, il y a beaucoup plus de mise en conversation, de coconstruction.
L'agilité a apporté l'idée qu'un plan fait dans son coin ne sert à rien, ça a commencé avec la déconstruction de l'architecte "tour d'ivoire".
Quand je me retrouvais dans une cellule d'architecture au dernier étage de la tour d'ivoire et que je proposais d'aller faire du binommage pour aller expliquer aux équipes projets les frameworks qu'on préconisait on me regardait avec de grands yeux.

Ensuite dès l'origine le métier d'architecture est un boulot d'abord organisationnel.
Les architectes devraient donc être les premiers à pousser les approches collaboratives, ce qui n'est pas toujours le cas.

Faire de l'architecture en s'affranchissant de cet aspect mais ça veut dire prendre le risque que le plan termine dans un placard ou, pire, soit mis en œuvre et détruise les compétences et les envies des uns et des autres.

_Le 3 avril 2018_
