== Marc Cherfi

Je suis arrivé en 2004, j'ai fait pas mal d'archi, j'ai travaillé avec PP à la direction technique, j'étais référent sur certaines technos. L'archi logicielle me plaisait plus que l'archi de SI mais j'ai fais un peu d'archi de SI, j'aimais beaucoup ça.
Ensuite il y a eu l'arrivée des agilistes qui sont venus après moi, il y a eu toute une phase d'émulation, parfois aggressive aussi dans les débats sur l'agilité, pas l'agilité, l'archi pas l'archi, les bleus, les gris.
Plein de débats avec plus ou moins de mauvaise fois, de trolls et puis parfois avec des pépites.
J'étais beaucoup inspiré par ça, parfois heurté aussi et puis au final très riche, la conclusion que j'en tira aujourd'hui, c'était encore à l'époque, au dela des trolls qui existent toujours encore qui pouvaient être poussés loin dans les mailing-list
Le chemin a été tracé, c'est à dire que cette phase parfois un peu cahotique montrait bien qu'on était en train de basculer quoi qu'il arrive sous l'inspiration des inspirateurs comme Manu Gaillot, CTH à sa manière et puis d'autres, et puis PP qui était un peu le suiveur de ça et en même temps inspirateur puisqu'il était patron et puis très intéressé, il ne les a pas fait venir pas hasard
de l'autre côté les archis classiques, kery, marc, un peu moins marc car j'étais pas une grande gueule, laurent brisse, tout ça dans des débats des ajustements
on a réussi je pense après-coup à dégonfler un peu le conflit, les égos pour aller plus loin, et de toutes façon c'était lancé, c'était parti, je le dis après-coup mais je pense que c'était trop tard et c'est ça qui est bien, le fait de recruter des gens qui lancent des trucs mêmes si c'est trollé, même si c'est parfois aggressif, même si les retours qu'on leur fait sont parfois aggressifs c'était déjà en mutation
ça c'est que je dis après-coup
moi j'ai basculé dans ces époques là vers l'agilité tout seul dans mon coin, un peu comme hervé lourdin a fait des choses
ce qu'il faut savoir c'est que c'était pas du tout le cœur de métier d'OCTO donc vendre des missions agiles ça n'avait pas de sens, soit tu les faisais dans les contextes où tu étais, moi j'étais archi, j'étais tech-lead et j'ai commencé à me mouiller et c'est comme ça qu'on apprenais sur l'épaule, avec le soutien
le fait de nouer des liens au delà des débats qui pouvaient crisper
rapidement j'ai noué des liens, j'ai beaucoup apprécié les premiers ateliers du changement par Manu Gaillot, ça permettait de nouer des liens avec ces personnes là et de s'appuyer sur eux de temps en temps, et surtout de les regarder et de s'inspirer d'eux, s'inspirer d'eux c'est aussi faire dans son coin au travers des missions.
l'agilité c'était pas un _cargo cult_, tout était à faire, ce qui était intéressant c'est qu'on avait rien et que c'était un métier que les personnes ne reconnaissaient pas en tant que tel il fallait inventer, tester, apprendre. Moi j'ai trouvé ça super appréciable, ma 1ere mission où j'étais tech lead et je faisais un audit d'archi et de pratiques de dev, dans lequel je mets en place une dynamique d'organisation plutôt agile et collaborative, c'était comme ça, c'était pas des missions où on nous appellait pour ça
ensuite j'ai basculé, je suis sorti de l'agilité au fur et à mesure du temps pour aborder le sujet du changement donc ça c'était plus vers 2007, 2008 ou j'ai commencé à basculer tout en continuant l'agilité pendant longtemps c'était d'essayer de l'aborder de manière très très différente parce que ça commencer à m'ennuyer un peu et je me rendais compte qu'il y avait d'autres sujets dèrrière l'agilité : la prise de décision, la qualité de la communication toutes ces choses là qui étaient déjà en filigramme dans l'esprit des premiers, Gaillot, CTH, Bernard, avec plus ou moins de force, parce que eux-même je pense que, ce qui intéressant c'est je pense qu'on a progressé dans le temps

et puis il y a eu d'autres schismes, c'est à dire que je me rends compte que les bleus et les gris aujourd'hui le débat ce serait scale contre tchak : très process oriented vs interractions / communications oriented, c'est l'équivalent du débat de l'époque
aujourd'hui c'est plus doux, on arrive à bosser ensemble, mais en même temps on ne va pas aussi loin qu'on pourrait aller
à l'époque il y avait plus de débat et plus de trolls mais au final on a été peut-être plus loin
c'est tout un enjeux qui pourrait expliquer aujourd'hui les choses : ces schismes là qu'il y avait à l'époque étaient annonciateurs d'une mutation d'OCTO, aujourd'hui on a le même schisme un petit peu entre l'agilité classique ou à l'échelle de scale vs ce que fais chak
et en même temps aujourd'hui c'est plus policé je pense entre nous mais c'est moins productif

je pense que à l'époque on savait mettre en conflit les choses
il y a eu des trolls un peu dur parfois, on était maladroit du point de vue de la communication mais globalement assumer ce conflit là c'était une marques de fabriques d'OCTO et la représentation symbolique de ça c'était Ludo vs PP qui était une réprésentation à l'échelle de la direction
aujourd'hui au niveau de la direction je ne suis pas sur qu'on ait ces conflits là ou aussi saillant ou aussi crispants il y a beaucoup d'homogénéité, plus d'homogénéité
je ne suis pas en train de dire que pp avait raison et que ludo n'avait pas raison, c'était pas le débat, le débat était le conflit et le fait d'assumer ce conflit et qu'il se retraduise, je pense qu'on pourrait toujours faire les choses avec une meilleure qualité de communication et assumer toujours ces conflits mais avec une meilleure qualité de communication
aujourd'hui on assume moins ces conflits là du coup il y a une sorte d'évidence qui se dégage même s'il y a des vrais différences
donc on privilégie l'illusion de l'homogénéité à la puissance de la confrontation et du conflit, du coup on va moins loin car on privilégie l'illusion de l'homogénéité, on se sépare, on fait des choses chacun dans son coin tant qu'il n'y a pas de vagues ça va, je trouve qu'on pourrait aller beaucoup plus loin évidemment, et c'est ce qu'il y avait à cette époque là

*Est ce que tu te souviens de la manière dont tu voyais les architectes et l'architecture de SI avant d'arriver à OCTO ?*

individuellement agréables et intéressants, par contre du point de vue de la communication je les trouvait vindicatifs un peu rentre-dedans et ultra surs d'eux donc manque de consensus un peu, beaucoup de certitudes parfois
mais en même temps agréable indivisuellements et même très pertinents parce que ça je l'ai vu tout de suite c'est ça qui m'enmerdais le plus c'est qu'il lançaient pafois, ils ne lançaient pas, c'est nous qui interprétions aussi des éléments qu'ils nous donnaient comme des trolls
on les interprétait c'est ça qui est important, ils marquaient le changement ils étaient le changement
on interprétait comme des trolls, à juste titre parfois, mais individuellement quand je discutais avec eux ils étaient très agréables très pertinents, parfois un peu cyniques, mais surtout ils piquaient car quelque part ce qu'ils dénonçaient ou ce qu'ils posaient était juste et ça nous piquait

*Qu'est ce qui a été le plus compliqué au début ?*

je me souviens de troll ou de threads à ralonge sur les ML, je me souviens parfois qu'ils étaient fragilisés parce qu'il y avait beaucoup de critiques à leur égard, genre "ils font chier, ça ne sert à rien ce qu'ils font, nous on fait du dur eux ils font du vent" un genre de position très rigides dans le fond vis à vis de personnes
je me souviens aussi de réactions parfois aggacées de leur part qui viraient à une forme d'enfantillage dans l'interprétation qu'on en faisait c'est à dire "hé les mecs vous n'êtes pas des gamins, c'est pas parce qu'on n'est pas d'accord avec vous que c'est grave" et en même temps certaines positions fermes chez nous, je me souviens d'un thread sur "il ne faut plus coder en java vs Ruby", Ruby c'était dans le sillage des agilistes des languages souples que tout le monde peut appréhender, et il y a eu un gros débat pour la refonte d'octopod à l'époque avec Kerny tout ça et des trolls par moment, je faisais encore de l'archi même si je faisais de l'agilité à côté, j'étais encore sur des missions de tech-lead et d'archi et je me souviens d'un débat où on disait, CTH disait "les développeurs Java c'est de la merde", c'est comme ça qu'on l'interprete, il n'a jamais dit ça, c'est pour te dire
et derrieriere Rails c'est vraiment la nouvelle vague et puis on s'écartait de la question qui était de savoir si pour Octopod on fait du Rails avec les momes, dans ce débat il y avait un peu de violence dans ce débat, ça a été un moment un peu cristant mais qui en même temps a été hyper constructif

je ne regrette pas ces moments, je pense que avec le recul, je trouve que c'est le chaos, c'est un peu la violence à certains égard, ce qui fait violence, on avait une capacité à l'époque de faire descendre cetet violence par de l'informel, par une biniouze, par le petit message derriere "ouais je ne voulais pas t'emmerder"
j'ai été deux ou trois fois chahuté sur des prises de positions, dans ma souplesse, dans l'accompagnement même archi, par Kerny dès fois et des gens qui ne comprennaient pas que j'avais une approche un peu plus ouverte que top dogmatique sur les cellules d'archi tout ça, et je souviens avoir été chahuté par un Kerny, mais souvent derriere ça il y avait des excuses informelles
comme à aujourd'hui un peu chez OCTO, mais c'est moins visible il y avait des régulations, c'est à dire cette capacité de ramener du feedback négatif, c'est à dire de ramener à la norme, la norme étant le lien, parce qu'on voulait préserver le lien malgré tout
donc on pouvait se lacher et en même temps quand on voyait qu'on dépassait les bornes, revenir à… 
on avait cette capacité de régulation où on nous invitait à le faire parfois

mais très riche comme période, très riche, et encore une fois je t'ai donné un parallèle avec la période d'aujourd'hui qu'on vit, les tribus ont créé de la densité des sujets des clivages ce qui ets très bien, mais elles oublient cette régulation, c'est pas qu'elles l'oublient mais on a été trop loin dans, c'est très bien les tribus car ça nous permet de partir sur nos sujets d'expertise et de ne pas attendre les autres pour avancer et du coup "viens avec moi qui veux" et c'est super, et en même temps aujourd'hui on manque de confrontation sur des positions, et ça c'est une vraie différence avec avant

*Comment as-tu vécu cette période ?*

parfois un petit peu mal, mais ça durait 10 secondes le temps de répondre au mail, et d'y mettre mon coup de troll aussi, ou de ne rien dire, et de discuter derriere en disant "ho lui il est con"
sur la tendance je pense que je le vivais très bien, car c'était hyper stimulant, et que ça m'a invité, tu vois ça n'es pas par hasard que j'ai été à l'atelier du changement, pourquoi j'aurais été si j'étais contre, en fait je pense que je le vivais super bien
par contre je pouvais monter dans les tours, à l'époque, ou être indigné à ma manière, c'est à dire le garder pour moi bien souvent, car je ne suis pas du genre troll, mais il m'est arrivé de répondre aussi ou de critiquer, d'être un peu cynique, voire méchant

*Combien de temps pour que vous trouviez un équilibre ?*

C'est venu tout seul, faut le voir comme une construction progressive, la régulation elle est venue par le fait que, elle existait, ce schisme il existait au plus haut dans le fond, et l'équilibre est venu parce que pp, au moins jusqu'à un certain temps, parce qu'après pp s'est barré et je pense que ça a été un peu plus violent, mais ça ne remettait pas en cause l'agilité tout ça car c'était déjà ancré
le fait d'assumer les positions, le fait que FHI laisse assumer ça, car quelque part ça créait de la variété et que au final on appréciait, je pense que chez les uns et les autres, avec plus ou moins d'intensité, on appréciait tout ce moment là
le 2eme aspect c'est qu'on n'était pas hyper nombreux donc ça permettait des régulations directes c'est un élément clé, des régulations directes d'appaisement informelles, la biniouze, le petit message, se croiser en mission et du coup ça ça jouait
le 3eme c'est qu'on était clairement sur quelque chose de nouveau, et quelque part de nouveau et dans les genes d'OCTO qui était d'être franc tireur, d'être en avance car de toutes façons on serait mort depuis si on avait fait comme les autres, donc il y avait aussi un instinct de survie lié à l'envie des OCTO même si c'est très variable d'une personne à l'autre, CTH tout ça n'a pas du tout le parcours des archis classiques, Manu Gaillot pareil, donc c'est très variable en intensité cette volonté du nouveau, mais globalement c'est elle qui l'emportait parce qu'elle était déjà dans la construction d'OCTO avant même qu'ils n'arrivent et ça faut pas l'oublier, c'est à dire qu'on n'aurait pas embauché des gens comme ça si on n'avait pas été un peu fou
et pp a porté ça de main de maître, avec son bagout, sa gouaille, et sa qualité et sa mauvaise foi

*Et avec les clients, comment passait le mélange architecte / agiliste ?*

en fais ça ne se passait pas toujours bien je crois, il y avait des missions où, soit entre OCTO ça se critiquait soit le client critiquait ces démarches de fou-furieux il y a eu tout ça oui, ça ne se passait pas toujours très bien, il n'y avait pas en plus beaucoup de missions comme ça
on cherchait le marché et le marché n'était pas du tout réceptif
après il y a eu quelques expériences qui ont confirmé, il y a eu l'arrivée du delivery qui a permis de faire des choses, qui l'a emporté
donc on a créé notre marché là dessus
des gens comme moi, un peu plus discret peut-être, on testait des trucs dans des missions telles qu'elles étaient sans forcément faire les grands soirs et forcément vendre une mission d'agilité stricto sensu
on a été des débroussailleurs, dans la ruée vers l'or avec un or qui était de type "faire autrement un métier de conseil et apporter une nouvelle dimension au regard d'architecte" moi j'ai été un continuateur de ce qu'ils ont posé mais peut-être même plus concret
donc en gros la conclusion de tout ça c'est que ce sont les architectes qui ont le mieux vendu l'agilité, les anciens architectes, puisqu'ensuite on a shifté, certains sont resté archis
on a été ceux qui, moi je m'estime être dans les sillage des CTH, Gaillot, pp qui ont été les pioniers dans le discours, dans tout ça, il faut des gens qui créent sur le terrain, et je pense qu'eux ils ont essayé sur le terrain, mais nous aussi, et je pense que la bascule c'était quand c'était plus eux qui portaient le discours
et ça c'est un enseignement qu'on peut tirer aujourd'hui mais qu'on avait pas à l'époque, ils se sont pour certains épuisés, fatigués à convaincre et il aurait fallu qu'ils … mais en même temps ils ont créé le cercle qui allait bien 

*Rétrospectivement, qu'auriez-vous pu faire pour que ça se passe mieux ?*

Non, non rétrospectivement il faut continuer à faire comme ça, il faut que ça fasse violence
Moi je suis content qu'on m'ait fait violence, parce que je me rends compte que j'ai changé de métier grâce à ça et je ne le regrette pas aujourd'hui
et en fait ça m'a fait violence ça veut dire que ça m'a transformé
je me suis transformé, j'ai accepté d'être transformé et de me tranformer
j'ai pris des risques, moi je me souviens dans des missions qu'on ne vendais pas pour ça d'avoir expérimenté des choses, testé des choses et je pense que c'est un véritable enseignement parce que tu es seul à ce moment là, même si tu as une communauté derrière, mais tu es seul dans le sens où tu prends des risques, le client ne te l'a pas demandé et je trouve ça génial
éventuellement un peu plus de douceur, mais ça ne veut rien dire, aujourd'hui on est plus vieux on sait faire des feedbacks un peu mieux mais en même temps ça fait violence par définition
ce qu'il faut c'est un climat _safe_, et du coup chez OCTO il y avait ce climat safe au final, on pouvait rester chez OCTO, c'était pas une position où pp ou Ludo ou François nous disaient "non choisissez votre camp ou disparaissez", ça c'est un climat safe, qu'on a encore un peu chez OCTO, ce climat où le débat est possible, c'est un gène d'OCTO d'une certaine manière mais il est rendu possible aussi par le pas que chacun fait vers l'autre un moment donné, et je pense que les agilistes le premier l'ont fait avec plus ou moins d'agilité, plus ou moins de compassion ou d'empathie mais il l'ont fait
en inversement les architectes, un certain nombre, l'ont fait

*Aujourd'hui penses-tu qu'on puisse être architecte SI sans faire d'agile ?*

Je ne fais plus d'architecture de SI donc c'est difficile pour moi de répondre à cette question
ce que j'observe néanmoins c'est que tout le monde sait en parler.
tout le monde, notament côté archi, bon je pense qu'il y a encore du boulot, mais globalement côté archi, on ne fait plus les missions de la même manière, il y a beaucoup plus de mise en conversation d'un plan, de coconstruction de plan, même si on pourrait faire beaucoup mieux un schéma directeur, je pense objectivement que cette dose, qui n'est pas venue de l'agilité je crois, elle est venur des transformations successives, par exemple ce qu'on a apporté avec chack sur la facilitation a permi d'apporter des choses.
Mais avant avec l'agilité ça a permi aussi d'appporter l'idée qu'un plan fait dans son coin ne sert à rien, mais ça a commencé même avant avec le déconstruction qui a eu lieu de ce qu'on appelait l'architecte "tour d'ivoire", à la SGIB tout ça
Moi j'ai commencé, à l'époque j'allais en Inde, faire du binnomage avec des devs, pour sortir de ma tour d'ivoire et quand je me retrouvais à la SGIB dans la cellule d'archi top top niveau dernier étage tour d'ivoire, quand je disais aux gens "le truc qu'on peut faire c'est d'aller faire du bionnage pour aller leur expliquer les frameworks qu'on a préconisé et les aider, les former, les mecs me regardaient avec des yeux" je me souviens à l'époque j'étais avec Kerny encore qui était là il me disait "non vas y continue" voila la différence, je me souviens d'un ancien OCTO qui était architecte en chef à la SGIB qui disait "c'est génial, on se se mettait un ordi sur le coin pour se dire, ça c'est le confluence partagé où on met les codes sources où on partage des exemples de code pour aider"
voila la logique, donc elle existait déjà avant, même dans le métier au cœur de l'archi, c'est pour ça que je pense que ça n'aurait pas marché si les architectes n'avaient pas basculé et ils ont basculé parce que c'était dans les gènes d'OCTO de recruter des gens souples, même si ça a beaucoup crispé au final. L'un n'empêche pas l'autre.

*Et l'inverse ?*

Je ne suis pas certain, je n'expliquerai pas ça en ces termes.
Je pense qu'il y a quelque chose de précieux dans l'architecture de SI, ça dépend comment il est fait.
Si c'est fait avec une position dogmatique très urbaniste, très "je ne me mouille pas mais je préconise", ce que j'appelle les archi légalistes, ou tu n,e fais pas, si tu ne respectes pas les règles je te tappe dessus ou les archis prescripteurs qui est une version un peu édulcorée mais qui restent quand même rigide, non je pense qu'il faut s'en passer.
par contre si ce sont des archis qui ont une verritable connaissance du SI et des problématiques, les intégrer dans l'agilité et trouver les moyens, ce qui est toujours très compliqué, c'est un enjeux important, dans les grands SI
mais l'enjeux est des deux côtés, savoir entendre les inquiétudes ou les préconnisation, et savoir être concret et pratique et savoir offrir, faire de l'architecture une solution plutôt qu'un problème

*Ce que m'a dit pp c'est qu'une vision qu'on les architecte et qui est utile aux agiliste c'est la vision des invariants, de ce qui est facile à changer et de ce qui ne l'est pas*

Tout le travail qu'il avait fait sur l'APM à l'époque avait cette vocation.
Mais du coup c'était une position qui était minoritaire chez les archis et chez lies clients.
Dans ce travail il faisait de l'architecte quelqu'un qui était vraiment actif et pas que préconisateur.
Le deuxième point c'est que si on regarde le métier d'architecture, même dès l'origine mais aujourd'hui encore plus vrai c'est que c'est un boulot organisationnel d'abord.
Et donc dans des contextes de collaboration ça devrait être les premiers à pousser ça, ce qui n'est pas toujours le cas.
L'évolution aussi elle est naturellement vers la dimension « quelle est la forme organisationelle qui a créé ce monstre technologique ?» je je puis dire, ou inversement.
Donc avoir cette dimension là, comme pas un exemple un architecte du batiment ou de manière générale s'intéresser à l'urbanisation, c'est à dire les flots, les flux de voyage,la verdure, la vie, le vivant.
Or les architextes se sont déplacés vers du non vivant.
Aujourd'hui l'architecte dans un contexte agile et de collaboration c'est un architete au sens de l'urbanisation c'est à dire quelqu'un qui s'intéresse à sa vie dans sa globalité c'est un permaculteur si je puis dire, mais de la ville et pas de la campagne, ancré dans la cité et qui assume la dimension profondément antropo-sociale du sujet.
Aujourd'hui tu sais c'est quoi ce métier d'archi ? Il est splitté entre soit des super techos soit des designers, aujourd'hui la voie, ce qui est amusant c'est que les designer ont supplanté les architectes dans cette dimension dans le fait d'assumer cette dimension anthropo-sociale de la technologie.
Ce que je veux dire que aujourd'hui quand les designers réfléchissent à une évolution technologique, quand ils le font bien car là aussi il y a du bullshit sur le design. Le design)thinking étant un des éléments du bullshit, ils s'intéressent à cette dimension « quel est l'impact sur les gens ?» et donc ils s'intéressent à la dimension anthropo-sociale de tout changement : technologique, applicatif, de SI, de service.
C'est pour ça qu'on parle de _service design_ plus que de product design.
Et ce qui est intéressant c'est que c'est pas tant les architectes qui ont pris cette place là, ce sont les designers, qui est un métier tout récent.
Ça montre bien que la bascule complète vers l'archi on l'a plus ou moins bien réussie chez OCTO, on l'a pas du tout réussi chez les clients : les architectes restent des technos ou des urbanistes legalistes, on a du mal chez les lcients à aller vers cette place qui était nécessaire et qui a été prise par les prospectiveurs, les futurologues ou les designers.

Quand on faisait de l'agilité moi j'étais mandaté pour faire une usine de développement automatisée et je me retrouvais à accompagner des rituels de rétrospective ou de stand-up. C'est pas parce que c'est dur que voila. C'est une question de convition.
Je susi un peu dur mais ça n'est pas une critique vis-à-vis des architectes, je pense que c'est l'air du temps qui est comme ça, et la nature n'aimant pas le vide on a des designers qui émergent comme nouveau métier.

Le 2eme point làa dessus c'est que pour une boite comme OCTO ça fait partie du challenge. Ce débat n'est pas nouveau, mois je l'ai eu avec certains archis chez OCTO en leur disant « arrêtez les schémas directeurs à dix ans, proposez des facilitations avec une dimenssion technologique, c'est à dire une dimension d'expertise, donc ça peut être une binome ». 
Donc il y a eu ce débat, il n'a jamais vraiment percé chez OCTO mais, faisons des binomes, avec une dimension sociale du changement et une co-construction du plan à dix ans, pour arriver à sortir du slideware de 150 slides que tout le monde lit et met dans un placard de préconisation ou au contraire qu'on suit le plan bête et méchant, même puntion et allons vers l'alignement.
Faisons ce qui est faisable et arrêtons de préconiser des choses qui sont infaisables.
S'affranchir de ces questions tu as le droit mais ça veut dire que ton plan va finir dans le placard ou dans un plan bête et méchant qui va détruire les compétences et les envies des uns et des autres.

Je pense que des profils comme eux, à l'époque, détonnaient par rapport à la masse. Je pense aujourd'hui qu'on a peu de profil comme ça, et qui restent, qui détonnent face à la masse.
Je pense paradoxalement que j'en fais partie même si je suis là depuis longtemps, j'ai appris à détonner mais sans le vouloir parce que j'ai pas un tempérament … je suis assez introverti j'ai pas un tempérament comme ça.
Je pense que l'enheux d'OCTO il est double, il est à la fois la variété, toujours, et je pense que certains ont en conscience chez OCTO, LCI en a conscience, et il est toujours triste de voir des gens partir un peu différents, et on en a pas mal qui ont parti qui sont très différents parce qu'ils n'ont pas trouvé leur place, parce que la force du TACE tout ça fait que c'était compliqué, pour plein de bonnes et de mauvaises raisons.
Le deuxième enjeux est de faire de cette variété non pas des positions figées dans leur coin mais du conflit et de la création.
C'est un double enjeux du changement aujourd'hui, facile à dire avec le recul mais c'est le but de l'exercice.
Et je pense qu'aujourd'hui on a ce double enjeux qui devant nous encore, qui n'est pas derriere. à nous d'en faire quelque chose.


_Le 3 avril 2018_