= Quand les agilistes sont entrés à OCTO 2/5 : Pierre Pezziardi

Je suis un des cofondateurs d'OCTO en 1998, en 2012 je me suis lancé dans des activités entrepreneuriales pour pouvoir avoir niveau d'impact supérieur.
En 2013 j'ai abandonné ces mandats pour fabriquer les link:https://beta.gouv.fr/startups/[Startup d’État] où je coache des équipes qui travaillent sur des problèmes de politiques publique sur un mode lean startup.

*Est-ce que tu te souviens de la manière dont tu voyais les agilistes et l'agile avant que les agilistes n'arrivent à OCTO ?*

Je savais bien que cette culture était extérieure à la notre.
Nous avions une culture très technique. Une culture d'architectes c'est à dire une culture d'assembleurs de briques.
L'essentiel de notre offre était polarisé sur cette capacité à décrire des univers complexes, à les architecturer, à mettre les bonnes briques ensembles, à faire les bons choix technologiques.
Poiur autant on faisait face à des problèmes récurrents de productivité, on voyait bien que tout ça ne résolvait pas tout, les serveurs d'applications les serveurs d'intégration répondaient à des vrais problèmes de productivité dans les grandes organisations informatiques mais à la fin on se demandait si vraiment…

Ces 1eres années de la création d'OCTO qu'on ne regrette pas, où on était très maqués avec des éditeurs, est ce que c'était ça au fond qui permettait de répondre à notre objet social qui était un cabinet de conseil, en conseil d'efficacité.

J'étais un peu à la recherche d'un nouveau souffle et j'ai vu des gens qui me sont plutôt apparus comme des barbus ou des orthodoxes ou des illuminés qui avaient des pratiques bizarres, qu'il a fallu accepter parce que le …

J'en ai recruté une petite demi-douzaine parce qu'un changement ça se produit avec les gens ça ne se produit pas par prescription, on devait être en 2001-2002 un truc comme ça.

L'agilité c'était une petite conférence qui réunissait 20 personnes, un manifeste aux USA, des développeurs comme Martin Fowler, une littérature qui était peu connue : le mythical man month, Weinberg, des gens qui étaient des penseurs mais qui au fond n'avaient pas d'audience dans les DSI qui étaient des geeks.

Notre système était très strucruré entre les penseurs et les faiseurs. Des faiseurs qui pensaient ça ne marche pas, on ne les voyaient pas aux conférences de Gartner.
C'est à ce moment là qu'on a fait l'Université du Système d'Information dans cette meme période.

On avait cette méme idée que pour que ces discours arrivent aux cerveaux des dirigeants faut remettre les geeks et les boss ensemble, cette idée de déclousonement elle nous colle bien à la peau, elle remet aussi cette exigence que nous ont mis les agilistes de recréer des équipes, de pas penser jour-homme, de pas penser tâches, de pas penser découpages de systèmes complexes en petits éléments.
Les systèmes complexes sont unmodélisables, on peut arriver à les approcher par itérations successsives, par incréments en restant bien compacts.

L'histoire il y a eu 3 puis 6 personnes qui ont rejoins et ça ne s'est pas passé sans heurs.

*Quelles ont été tes premières réactions lorsque la rencontre a eu lieu ?*

Je les ai recruté car c'était souhaitable qu'ils viennent donc on a fabriqué une offre, et on a vendu cette offre.
Cette offre on la vendait bien, très cher.
Après elle se heurtait dans les tensions entre ce qu'on voulait faire, c'est à dire des équipes autonomes etc et les contextes, qu'est ce qu'ils permettaient vraiment de faire.
On avait des contextes où les gens étaient terrorisés par l'autonomie qu'ils pouvaient concéder aux équipes et ça créait beaucoup de friction quand vous faites confiance à des gens.
D'autre part même quand ça marchait on se heurtait à un dernier plafond de verre qui était la finalité.
On a rendu cette équipe productive mais ça ne sert à rien ce qu'on fait.
J'ai fais des trucs, les SI bancaires Bale 2 ne servaient à rien.
On a avancé avec des gens qui étaient très engagés et qui souhaitaient obtenir des résultats mais on a eu des déceptions, des difficultés.
Avec ces 3 niveaux de plafond de verre, celui du mais attend on ne va pas tout vous permettre ici il y aura des chiffrages des cahiers des charges des penseurs et des faiseurs, il y aura encore la maitrise d'ouvrage donc tout un tas de conflits organisationnels sur le questionnement même de "peut-on héberger une quipe autonome et responsable ?" et puis même quand on arrivait à avoir ça un questionnement sur la finalité, qui à la fin de l'histoire m'a fait partir.

La devise qu'on avait immaginée en 2008 sur les SI qui transforment nos sociétés, c'était tout de même assez compliqué, les SI ne transforment pas les sociétés, les SI renforcent l'ordre établi par défaut.

*Et avec les clients, comment passait le mélange architecte / agiliste ?*

Non ça ne passe pas, ça passe jamais, c'est comme toute innovation ça génère un rejet, ça génère une peur du déclassement de la part de la caste des _incumbents_, des gens qui tiennent le business.
On était une société de tech, d'architectes, avec une forte dose de conseil, donc des costumes et là on avait des gens d'une autre obédience et ça a créé des conflits, on a modélisé le conflit on appelait ça les bleus et les gris à l'époque.
Je ne pense pas que j'ai gagné le prix du manager de l'année à ce moment.
Ce conflit on l'avait modélisé, on l'avait intégré et on avait essayé de le désamorcer en maintenant bien une dialectique du ET c'est à dire c'est pas parce qu'il y a des agilistes que ça va détruire les architecte et c'est pas facile à entendre, surtout quand un des chefs s'occupe beaucoup des aglistes et moins des architectes parce qu'il accompagne l'innovation plus qu'il n'accompagne le business qui tourne.
Il y a une sorte de défiance des troupes historiques à l'égard de cette nouvelle offre, maintenant elle s'est implantée à la fin en disant le champs des compétences que pouvait acquérir un OCTO, c'est à dire qu'on pouvait être architecte et agiliste et que la double compétence elle était très valorisée et souhaitable.

*Combien de temps pour que vous trouviez un équilibre ?*

Plusieurs années, ça a mis trois ans. Ça il faut l'accepter. Ces gens qui sont venus avaient une maturité sur la lecture des organisation, la lecture du changement qu'il était important qu'on acquiert, que les architectes acquierrent.
Les architectes eux avaient une vision assez prescriptive des choses, et il suffit que je fasse un plan pour vous dire c'est le bien.
Ils ont du eux-même faire le deuil de la solution magique qui n'en était pas.
C'est ça qui est dur, ça oblige à un regard introspectif sur soi en fait, l'arrivée d'un étranger.
Cette lecture elle est salutaire mais elle est difficile.
Moi je préféererai tenir avec mon beau costume et mes tarrifs à 1100€ la journée je vous fais un dossier d'architecture générale et vous allez voir ce que vous allez voir, la vie est plus simple, je rentre chez moi le soir et tout est plus simple.

*Comment as-tu vécu cette période ?*

Comme une période habituelle, on commençait à esquisser la théorie générale qu'on a tiré de ça, une politique pour le SI avec un paragraphe qui s'appelle la frontière qu'on a écrit à ce moment là. Il y a toujours une frontière c'est à dire il y a toujours une zone de rationalisation et une zone d'inovation.
Ce que je fais aujourd'hui dans l'état c'est la même chose.
C'est très compliqué d'innover au cœur d'OCTO c'est très compliqué d'innover au cœur d'une administration, au cœur de la SG.
Si vous voulez innover il faut faire un pas de côté.
Loin des règles des usages des coutumes des dispositions des tabous de ce qu'a constitué la structure et admettre qu'il y a deux légitimités qui vont s'affronter et que c'est comme ça.
Si vous voulez lire un livre lisez pourquoi j'ai mangé mon père de Roy Lewis.

*Est ce que rétrospectivement, il y a quelque chose que vous auriez-vous pu faire pour que ça se passe mieux ?*

J'ai fais du mieux que j'ai pu en fonction de mes connaissances, de mon talent et de mon absence de talent, c'est incontestable on n'est pas des fainéants.
C'est probablement pas le mieux qui…
Pour autant, pour rejouer cette affaire là dans l'État ici j'ai pas de nouvelles recette que la frontière. Donc ce qu'on avait modélisé à l'époque, on va faire une offre à part, vous allez continuer à facturer, vous allez nous regarder jalousement ou bizarrement, vous allez critiquer.
Tout truc nouveau on dit d'abord c'est pas possible, ça n'existe pas, ensuite vous n'y arriverez jamais et ensuite c'était un projet facile.
Ces phases là c'est un process c'est humain, la disruption.
Ce que j'ai amélioré là c'est une plus grande empathie de ceux qu'on pourrait juger comme conservateurs ou réactionnaires, c'est à dire d'être capable de m'adresser à eux.
Les discours que je fais pour le compte de l'État je leur dit vous savez c'est pas la lute des méchants conservateurs contre les gentils barbares innovateurs qui vont améliorer le service public. C'est pas ça la vérité, c'est une double légitimité. Vous êtes légitimes à tenir la boutique tel qu'elle est, elle est imparfaite mais tous les jours ce dont on vous tient compte c'est "est ce que ça marche ? est ce que les avis d'imposition sont partis, est ce que le RSA a été payé est ce que les chomeurs ont reçu le SMS de notification…" c'est ça.
Moi jai été DSI de la BRED j'ai vite compris l'injonction paradoxale d'un DSI, un DSI n'a qu'un métier c'est la prod, le reste c'est des blagues.
On me dit Pierre quand même ce projet d'innovation il a 18 mois de retard blablabla et puis on rebois un coup.
Mais putain Pierre le fichier des paiment pôle emploi il est pas passé hier on va passer pour des cons sur la place.
Ce qui prévaut pour quelqu'un qui est dans le système c'est de le faire tourner c'est sa mission principale.
Le faire évoluer, oui bon.
C'est peut-être le discours à l'égard de ceux que je viens disrupter que j'ai poli un petit peu mais ça ne marche pas plus rapidement pour autant.
Je pense qu'il faut bien retenir la leçon que les individus sont inquiets, légitimement.

*Aujourd'hui penses-tu qu'on puisse être agiliste sans faire d'architecture de SI ?*

Pour faire un SI il faut en embrasser la complexité, comprendre la technique, à la fois les protocoles qui vous nous permettre de nous rabouter mais aussi la politique.
C'est quoi la bonne frontière entre le service compta… ce sont ausis des lectures qui manquent à des architectes qui ont une lecture très technique qui ne voient pas ces questions
Si on veut faire de l'agile à un niveau organisationnel il va faloir aussi comprendre la politique pour comprendre quelles sont les bonnes frontière et comment on créé de l'agilité dans tous les blocs et comment on créé une pulsation de tous ces blocs et comment on gère ces bocs les plus compliqués, les communs. Ce qui appartient à tout le monde, les référentiels, les infrastructures, comment on les rend un peu plus open source c'est à dire moins monopole.
Ils ont tous tendance à se transformer en monopole dysfonctionnels, quand on a mis en place de l'EAI à l'époque sans s'en rendre compte en a mis en place des équipes de flux, dédiés qui sont devenus des goulets de tous les SI. C'était l'inverse de ce qu'on voulait produire. et on l'a fait de bonne foi; naïvement.
Les gens qui veulent faire de l'archi de SI doivent de l'ingénieur pour modéliser les systèmes complexes, de l'agilité c'est à dire de la sociologie humaine, mais aussi de la politique.

*Après tout ce temps, qu'est-ce que tu n'as toujours pas compris chez les agilistes ?*

C'est la communauté qui m'a le plus irrigué ces dernières années. Tout ce qui est l'édition logicielle est un paquebot à la dérive, et il reste l'agilité et l'open-source.
Vous avez un devoir de mutabilité, vous vendez de la productivité aux grandes organisations informatiques vous avez intérêt à vous remettre en question et c'est très salutaire.

_Le 26 mars 2018_