= Quand les agilistes sont entrés à OCTO 2/5 : Pierre Pezziardi

Je suis un des cofondateurs d'OCTO en 1998, en 2012 je me suis lancé dans des activités entrepreneuriales pour avoir niveau d'impact supérieur.
En 2013 j'ai abandonné ces mandats pour aller fabriquer les link:https://beta.gouv.fr/startups/[Startup d’État] où je coache des équipes qui travaillent sur des problèmes de politiques publique sur un mode lean startup.

*Est-ce que tu te souviens de la manière dont tu voyais les agilistes et l'agile avant que les agilistes n'arrivent à OCTO ?*

Je savais bien que cette culture était extérieure à la notre.
Nous avions une culture très technique, une culture d'architectes, c'est à dire d'assembleurs de briques.
L'essentiel de notre offre était polarisé sur cette capacité à décrire des univers complexes, à les architecturer, à mettre les bonnes briques ensembles, à faire les bons choix technologiques.
Cela permettait de répondre à des vrais problèmes de productivité mais ça ne résolvait pas tout.

Les premières années d'OCTO était très proche des éditeurs, mais est ce qu'au fond cela permettait de répondre à notre objet social qui était un cabinet de conseil qui visait à améliorer l'efficacité de nos clients ?
J'étais un peu à la recherche d'un nouveau souffle, et j'ai vu des gens qui me sont plutôt apparus comme des barbus ou des orthodoxes ou des illuminés qui avaient des pratiques bizarres.

L'agilité c'était une petite conférence qui réunissait vingt personnes, un manifeste aux USA, des développeurs comme link:https://martinfowler.com[Martin Fowler], une littérature qui était peu connue : le link:https://fr.wikipedia.org/wiki/Le_Mythe_du_mois-homme[__mythical man-month__], link:https://leanpub.com/u/jerryweinberg[Weinberg], des gens qui étaient des penseurs mais qui n'avaient pas d'audience dans les DSI.
Notre système était très structuré entre les penseurs et les faiseurs. Des faiseurs qui pensaient nos clients ne les entendaient pas.

J'ai recruté une petite demi-douzaine d'agilistes en 2001-2002 parce qu'un changement ça se produit avec les gens ça ne se produit pas par prescription, ça ne s'est pas passé sans heurs.

C'est à ce moment là qu'on a fait l'Université du Système d'Information.
Pour que ces discours arrivent aux cerveaux des dirigeants il fallait mettre les geeks et les boss ensemble.

*Quelles ont été les premières réactions lorsque la rencontre a eu lieu ?*

On était une société de tech, d'architectes, avec une forte dose de conseil, donc des costumes et là on avait des gens d'une autre obédience et ça a créé des conflits.
Ce conflit on l'avait modélisé - on appelait ça les bleus et les gris -, on l'avait intégré et on avait essayé de le désamorcer en maintenant bien une dialectique du "et" c'est à dire c'est pas parce qu'il y a des agilistes que ça va détruire les architecte mais ce n'est pas facile à entendre.

Il y avait une sorte de défiance des troupes historiques, l'agile s'est imposé quand on a réalisé qu'on pouvait être architecte et agiliste et que cette double compétence était très valorisée et souhaitable.

*Comment s'est passé l'arrivée des agilistes chez les clients ?*

On a fabriqué une offre, et on a vendu cette offre, elle se vendait bien, très cher, mais elle se heurtait à deux difficultés.

D'une part elle se heurtait dans les tensions entre ce qu'on voulait faire - c'est à dire des équipes autonomes - et les contextes - qu'est ce qu'ils permettaient vraiment de faire.
Dans certains contextes les gens étaient terrorisés par le fait de donner de l'autonomie aux équipes.

D'autre part même quand ça marchait on se heurtait à la finalité de ce qu'on faisait : rendre une équipe productive ne sert à rien si le projet n'a pas de sens.

*Combien de temps pour que vous trouviez un équilibre ?*

Les agilistes avaient une maturité sur la lecture des organisations et du changement qu'il était important que les architectes acquièrent.
Les architectes ont du faire leur deuil de leur posture prescriptiviste et des solutions magiques qui n'en étaient pas.
L'arrivée d'un étranger oblige à un regard introspectif sur soi et ce changement est difficile.

Ça a mis trois ans, et il faut accepter cette durée.

Moi je préférerai venir avec mon beau costume et mes tarifs à 1100€ la journée je vous fais un dossier d'architecture générale et vous allez voir ce que vous allez voir, je rentre chez moi le soir et tout est plus simple.

On en a tiré la théorie de la frontière qu'on trouve dans link:https://www.octo.com/fr/publications/4-une-politique-pour-le-systeme-d-information[une politique pour le SI].
L'idée c'est qu'il y a toujours une zone de rationalisation et une zone d'inovation séparés par une frontière.

Aujourd'hui je fais la même chose pour l'État.
Ce que je fais aujourd'hui dans l'état c'est la même chose.
C'est très compliqué d'innover au cœur d'OCTO, c'est très compliqué d'innover au cœur d'une administration ou au cœur d'une grande banque.
Si vous voulez innover il faut faire un pas de côté, loin des règles et des usages de ce qu'a constitué la structure, admettre qu'il y a deux légitimités qui vont s'affronter et que c'est comme ça.

*Est ce que rétrospectivement, il y a quelque chose que vous auriez-vous pu faire pour que ça se passe mieux ?*

Pour rejouer la même affaire ici dans l'État je n'ai pas de nouvelles recette que la frontière.
Ces phases là c'est un process c'est humain, la disruption.

Ce que j'ai amélioré c'est une plus grande empathie de ceux qu'on pourrait juger comme conservateurs ou réactionnaires.
Ce n'est pas la lute des méchants conservateurs contre les gentils barbares innovateurs qui vont améliorer les choses.
C'est une double légitimité : vous êtes légitimes à tenir la boutique tel qu'elle est, elle est imparfaite mais tous les jours on vous demande des comptes pour savoir si le système fonctionne.
La mission principale de quelqu'un dans le système c'est de le faire tourner.

J'ai peut-être poli mon discours à l'égard de ceux que je viens disrupter mais le changement ne se fait pas plus rapidement.
Il faut bien retenir la leçon que les individus sont inquiets, légitimement.

*Aujourd'hui penses-tu qu'on puisse être agiliste sans faire d'architecture de SI ?*

Si on veut faire de l'agile à un niveau organisationnel il faut comprendre la politique pour comprendre quelles sont les bonnes frontière : comment créer de l'agilité dans tous les blocs et surtout dans les blocs communs.
Ces blocs comme les référentiels et les infrastructures qui appartiennent à tout le monde ont tous tendance à se transformer en monopole dysfonctionnels.

_Le 26 mars 2018_