== Quand les agilistes sont entrés à OCTO : Pierre Pezziardi

Pierre Pezziardi a cofondé OCTO en 1998.
Au début des années 2000 il est directeur technique et l'un de ceux qui font venir les agilistes.
En 2012 il est lancé dans des activités entrepreneuriales.
Depuis 2013 aux link:https://beta.gouv.fr/startups/[startups d’État] il coache des équipent qui travaillent sur des problèmes de politiques publique sur un mode _lean startup_.

*Comment voyais-tu les agilistes et l'agile avant que les agilistes n'arrivent à OCTO ?*

Je savais qu'ils avaient une culture était extérieure à la nôtre.
Nous avions une culture très technique d'architectes, c'est à dire d'assembleurs de briques.
L'essentiel de notre offre était polarisé sur cette capacité à décrire des univers complexes et à faire les bons choix technologiques.
Cela permettait de répondre à des vrais problèmes de productivité mais ça ne résolvait pas tout.

J'étais un peu à la recherche d'un nouveau souffle, et j'ai vu des gens qui me sont plutôt apparus comme des illuminés qui avaient des pratiques bizarres.
L'agilité c'était alors en France une petite conférence qui réunissait vingt personnes, un manifeste aux USA, des développeurs comme link:https://martinfowler.com[Martin Fowler], une littérature qui était peu connue : le link:https://fr.wikipedia.org/wiki/Le_Mythe_du_mois-homme[__mythical man-month__], link:https://leanpub.com/u/jerryweinberg[Weinberg].

Un changement ça se produit avec les gens alors j'ai recruté une petite demi-douzaine d'agilistes en 2001-2002.
Ça ne s'est pas passé sans heurts.

Les agilistes avaient une maturité sur la lecture des organisations et du changement qu'il était important que les architectes acquièrent.
Les architectes ont du faire leur deuil de leur posture prescriptiviste et des solutions magiques qui n'en étaient pas.

*Quelles ont été les premières réactions lorsque la rencontre a eu lieu ?*

On était une société de d'architectes en costume qui faisaient du conseil, et là on avait des gens d'une autre obédience donc ça a créé des conflits.
On avait modélisé ce conflit : on appelait ça les bleus et les gris.
On avait essayé de le désamorcer en insistant que ça n'est pas parce qu'il y a des agilistes que ça va détruire les architectes, mais ce n'est pas facile à entendre, surtout quand un des chefs s'occupe beaucoup des aglistes et moins des architectes parce qu'il accompagne l'innovation plus qu'il n'accompagne le business qui tourne.

Il y eu une sorte de défiance des troupes historiques.
Au final l'agile s'est imposé quand on a réalisé qu'on pouvait être à la fois architecte et agiliste, et que cette double compétence était même très valorisée et souhaitable.

*Comment s'est passé l'arrivée des agilistes chez les clients ?*

On a fabriqué une offre, elle se vendait bien mais se heurtait à deux difficultés.

D'une part elle se heurtait dans les tensions entre ce qu'on voulait faire - c'est à dire des équipes autonomes - et les contextes - qu'est-ce qu'ils permettaient vraiment de faire ?
Dans certains contextes les gens étaient terrorisés par le fait de donner de l'autonomie aux équipes.
Les innovations génèrent du rejet, une peur du déclassement de la part de la caste des personnes qui tiennent les rênes.

D'autre part même quand ça marchait on se heurtait à la finalité de ce qu'on faisait : rendre une équipe productive ne sert à rien si le projet n'a pas de sens.
On a avancé avec des gens qui s'impliquaient et voulaient obtenir des résultats mais pour des projets qui ne servaient à rien. C'est ce qui a fini par me faire partir.

*Combien de temps pour que vous trouviez un équilibre ?*

L'arrivée d'un étranger oblige à un regard introspectif sur soi et ce changement est difficile.
Le changement a mis trois ans, et il faut accepter cette durée.

On a tiré de cette expérience tiré la théorie de la frontière qu'on trouve dans link:https://www.octo.com/fr/publications/4-une-politique-pour-le-systeme-d-information[une politique pour le SI].
L'idée c'est que dans une organisation il y a toujours une zone de rationalisation et une zone d'innovation séparés par une frontière.

Aujourd'hui je fais la même chose dans l'État.
C'est très compliqué d'innover au cœur d'OCTO, c'est très compliqué d'innover au cœur d'une administration ou au cœur d'une grande banque.
Si vous voulez innover if faut admettre qu'il y a deux légitimités qui vont s'affronter et que c'est comme ça.

*Est-ce que rétrospectivement, il y a quelque chose que vous auriez pu faire pour que ça se passe mieux ?*

Une plus grande empathie de ceux qu'on pourrait juger comme conservateurs ou réactionnaires.
Ce n'est pas la lutte des méchants conservateurs contre les gentils barbares innovateurs qui vont améliorer les choses.
C'est une double légitimité : vous êtes légitimes à tenir la boutique tel qu'elle est, elle est imparfaite mais tous les jours on vous demande des comptes pour savoir si le système fonctionne.
La mission principale de quelqu'un dans le système c'est de le faire tourner.

J'ai peut-être poli mon discours à l'égard de ceux que je viens disrupter mais le changement ne se fait pas plus rapidement.
Il faut bien retenir la leçon que les individus sont inquiets, légitimement.

_Le 26 mars 2018_

