= Quand les agilistes sont entrés à OCTO
:BEN: Bernard Notarianni
:CTH: Christophe Thibaut
:DOM: Dominique Buinier
:LBR: Laurent Brisse
:PKE: Philippe Kernévez
:PPE: Pierre Pezziardi

Pitch : aujourd'hui OCTO et l'agile ça va de soi et on pourrait croire que ça a toujours été le cas.

Pas du tout : OCTO au début était une entreprise d'architectes de SI.
Certains des anciens parlent encore du grand bouleversement qu'a représentée l'arrivée des agilistes.

Si l'eXtreme Programming avait rapidement suscité l'intérêt, au point que de déclencher l'embauche d'agilistes, l'agilisation qui a suivi ne s'est pas faite en un jour ni sans heur.

Un morceau de l'histoire d'OCTO qui vous montrera que même chez nous les transformations ne sont pas toujours simples.

Pour vous servir de pères castors j'ai interviewé six personnes présentes aux moments des faits :

{BEN}

{CTH}

{DOM}

{LBR}

{PKE}

{PPE}

Que fais-tu maintenant ?

Période à OCTO ?

Agilistes : Te souviens-tu de la manière dont tu voyais les architectes et l'architecture de SI avant d'arriver à OCTO ?
Agilistes : Qu’est-ce qui t’a fait venir chez OCTO à l’époque, qui se revendiquait comme un cabinet de conseil en architecture de SI ?

Architectes : Te souviens-tu de la manière dont tu voyais l'agile et les agilistes avant qu'ils n'arrivent à OCTO ?


Tous : Quelle a été tes premières réactions lorsque la rencontre a eu lieu ?

Tous : Qu'est ce qui a été le plus compliqué au début, peut-être as-tu une anecdote ?

Tous : Comment as-tu vécu cette période ?

Tous : Qu'est-ce qu'ils t'ont appris, et qu'est-ce que ça a changé à ta manière de travailler ?

Tous : Et à OCTO, ça a changé quoi ?

Tous : Combien de temps pour que vous trouviez un équilibre, il y a eu plusieurs phases ?

Tous : Et avec les clients, comment passait le mélange architecte / agiliste ?

Tous : Rétrospectivement, qu'auriez-vous pu faire pour que ça se passe mieux ?

Architecte : avec le recul, penses-tu que l’arrivée des agilistes chez OCTO a été bénéfique ?

Tous : Aujourd'hui penses-tu qu'on puisse être architecte SI sans faire d'agile ?

Tous : Et l'inverse ?

Agilistes : Après tout ce temps, qu'est-ce que tu n'as toujours pas compris chez les architectes ?
Architectes : Après tout ce temps, qu'est-ce que tu n'as toujours pas compris chez les agilistes ?

Tous : Quelque chose à ajouter ?
