= Quand les agilistes sont entrés à OCTO
:CTH: Christophe Thibaut
:DOM: Dominique Buinier
:LBR: Laurent Brisse
:PKE: Philippe Kernévez
:PPE: Pierre Pezziardi

Pitch : aujourd'hui OCTO et l'agile ça va de soi et on pourrait croire que ça a toujours été le cas.

Pas du tout : OCTO au début était une entreprise d'architectes de SI.
Certains des anciens parlent encore du grand bouleversement qu'a représentée l'arrivée des agilistes.

Si l'eXtreme Programming avait rapidement suscité l'intérêt, au point que de déclencher l'embauche d'agilistes, l'agilisation qui a suivi ne s'est pas faite en un jour ni sans heur.

Un morceau de l'histoire d'OCTO qui vous montrera que même chez nous les transformations ne sont pas toujours simples.

Pour vous servir de pères castors j'ai interviewé cinq personnes présentes aux moments des faits : {CTH}, {PPE}, {LBR}, {PKE}, {DOM}.

Mise en perspective historique

conflits enflammés sur les mailing list mais peu d'impacts chez les clients, surtout le problème de vendre l'agile.

include::CTH.asciidoc[]
include::PPE.asciidoc[]
include::LBR.asciidoc[]