= Links - 6^th^ October 2024
Julien Kirch
v1.0, 2024-10-06
:article_lang: en
:figure-caption!:
:article_description: Reading, game design, unplanned blog post, platform engineering

== link:https://www.baldurbjarnason.com/2024/the-promise-and-the-distraction/[The promise and distraction of productivity and note-taking systems]

[quote]
____
What the various systems mean by "`understanding`" a book is always quite vague and subjective. But when you trawl through the essays, blog posts, and forums where people share the complex magic spells they call "`process`", you find out it mostly boils down to "`action items`" -- productivity bullshit that pretends that books are road maps towards replicating the envy-baiting theatrics that "`successful`" people portray as their lives and careers -- or "`big ideas`" -- cognitive shortcuts that extract and portray book points and conclusions free from their original argument like green beans suspended in jell-O.

Good books, those that are worth reading, do not have big ideas. They have big arguments. The "`big idea`" is never on the page but in your head -- the thoughts that engaging with the argument inspired.

Books are maps to territories that are completely internal to the reader. By focusing so heavily on extracting the surface symbology of the map itself, these process-heavy note-takers risk losing sight of the territory. A book's territory is the reasoning and argument that the book presents to you as a path you take through your own psyche. The goal isn't to remember everything the book contains. Remembering a book's contents is useless. The book exists to contain what it contains. If the contents are important, you keep a copy of it for you to look things up again.

But that isn't the point of reading. The purpose of reading is to _be changed_. Sometimes the change is trivial and temporary -- a piece of fiction that brings some joy in your life. Sometimes the change is profound -- a shift in your perspective on life. "`Action items`" from a book are external and forcing yourself to follow through on them is exhausting.
____

== link:https://azhdarchid.com/the-ten-principles-of-good-game-design/[The ten principles of good game design]

[quote]
_____
Good game design is obtrusive. Games must push back on the player. Games must include friction. A game is not a tool and it is not there to be easily manipulated by the player.
_____

[quote]
_____
Good game design is dishonest. The player is there to have their perceptions manipulated. Good game design embellishes; good game design makes a system seem more alive than it truly is. Good game design relies on apophenia and magician's tricks.
_____

== link:https://hikari.noyu.me/blog/2024-10-02-the-algorithm-is-killing-twitter-and-its-driving-me-insane.html[the algorithm is killing twitter and it's driving me insane]

[quote]
____
i am Upset about something right now, and i gotta get it off my chest in the way only an unplanned blog post can achieve, so here goes.
____

== link:https://skamille.medium.com/platform-engineering-beyond-cfengine-daa9268c9c5b[Platform engineering beyond CFEngine]

[quote]
____
To wrap this up, Platform Engineering done well is more than configuration management and infrastructure provisioning. It is doing the hard work to identify, build, and operate abstractions that allow application teams spend less time on the underlying technology and more on solving problems for their business. Instead of thinking about how you can support the scripting and automation of infinite variations, think about the products you can build to cover the most common archetypes in a way that goes beyond the act of provisioning and deployment.
____
