= Links - 19^th^ November 2023
Julien Kirch
v1.0, 2023-11-19
:article_lang: en
:figure-caption!:
:article_description: What executives do, wikis, Kai Krause`'s software UI, practice guide for computers

== link:https://apenwarr.ca/log/20190926[What do executives do, anyway?]

[quote]
____
To paraphrase the book, the job of an executive is: to define and enforce culture and values for their whole organization, and to ratify good decisions.

That`'s all.

Not to decide. Not to break ties. Not to set strategy. Not to be the expert on every, or any topic. Just to sit in the room while the right people make good decisions in alignment with their values. And if they do, to endorse it. And if they don`'t, to send them back to try again.
____

[quote]
____
If the executive chooses not to be involved in conflicts that are "`not important enough; you figure it out`": political power games ensue. Whoever can force their way will win, killing morale. Or half the people do one thing and half do the other, and the company loses focus.
____

== link:https://cohost.org/teioh/post/3502576-you-know-at-first-i[Any thoughts on MediaWiki?]

[quote]
____
But one of the political implications behind MediaWiki (or hypertext or the memex) as a metaphor for the brain is that there is intentionality in how we relate information to each other. After all, MediaWiki products are tightly edited and controlled and created with intentionality; each link is made by someone else who thought of the link.

But I know my brain does not work that way. I did not choose to link emotional care of archives through a long chain that leads me the treatment of Chinese labourers in World War I; those links came about organically and with very little intention. Nor do I necessarily _want_ to deal with these massive webs constantly activating as I write or talk or think. My neurodivergence gives me, I realize now, insights that others don`'t necessarily see, but it also comes with it the heavy burden of a mind that can`'t turn off, that is easily distracted and easily bored, that struggles to focus and remember with intentionality and plan ahead. I don`'t have a choice in this; this is just what I have to work with.
____

== link:https://mprove.de/script/99/kai/[The interface of Kai Krause`'s software]

[quote]
____
KPT Spheroid Designer is meant to create collections of special looking orbs. Different controls allow the definition of light or to select a special surface structure for the orbs. The KPT users manual notes that Spheroid Designer may seem to resemble glass balls dropped into mud, but actually it`'s meant to be glass balls embedded in an "`old stale brownie`".
____


== link:https://codeberg.org/oneirophage/practice-guide-for-computer/raw/branch/main/guide.pdf[Practice guide for computer]

[quote]
____
I will be kind to myself

. It is only _computer_
. No matter my level of development in _computer_, how good or bad i think i am, it is only _computer_ and I am a beautiful person.
____
