= Links - 4^th^ March 2018
Julien Kirch
v1.0, 2018-03-04
:article_lang: en
:article_description: Crafting interpreters, OSS tool for parsing and analyzing SQL

== link:http://www.craftinginterpreters.com[Crafting interpreters]

[quote]
____
A handbook for making programming languages.

This book contains everything you need to implement a full-featured, efficient scripting language. You'll learn both high-level concepts around parsing and semantics and gritty details like bytecode representation and garbage collection. Your brain will light up with new ideas, and your hands will get dirty and calloused. It's gonna be a blast.

Starting from main(), you'll build a language that features rich syntax, dynamic typing, garbage collection, lexical scope, first-class functions, closures, classes, and inheritance. All packed into a few thousand lines of clean, fast code that you will thoroughly understand because you wrote each one yourself.

You can read the whole book, for free, online
____

== link:https://eng.uber.com/queryparser/[Queryparser, an open source tool for parsing and analyzing SQL]

[quote]
____
In early 2015, Uber Engineering migrated its business entities from integer identifiers to UUID identifiers as part of an initiative towards using multiple active data centers. To achieve this, our Data Warehouse team was tasked with identifying every foreign-key relationship between every table in the data warehouse to backfill all the ID columns with corresponding UUIDs.

Given the decentralized ownership of our tables, this was not a simple endeavor. The most promising solution was to crowdsource the information by scraping all the SQL queries submitted to the warehouse and observing which columns were joined together. To serve this need, we built and open sourced Queryparser, our tool for parsing and analyzing SQL queries.

In this article, we discuss our implementation of Queryparser, the variety of applications it unlocked, and some problems and limitations encountered along the way.
____
