== They started it, and now -- years later, a world away, face and name unrecognizable -- it's time for you to begin to end it.

An RPG campaign that has been started must be finished, no matter how long since it started, whatever the cost and the consequences.

== Of the five things on the table, you are permitted to pick any three for your exile.

No the cat is not part of the things, they are not a "`thing`", they just love laying here.

You can take them with you if you can convince them, and if you promise to take good care of them.

If you don't we'll know.

== These corridors, featureless science-fiction white, have never heard such sounds before.

There are unwritten rules, enforced tacitly by the group until someone is brave enough to disregard them.
And then everyone can happily act as the rule never existed.

Serving the Imperial Inquisition in the Deathwatch always changed marines, often in a dark way.

When the veteran techmarine Zalthach Berist returned to the _Left Elbow of the Emperor_ battle barge after their tour of duty, their battle sibling didn't know what to expect.

The report announcing their comeback was as bureaucratic as expected, briefly listing their achievements that escaped censorship, and in long details the technical improvements they did that have been officially validated.

Zalthach has been assigned an isolated room, until their new assignment would be decided.

While they were still unpacking their stuff, Mittens appeared on the control deck, with a collar matching the chapter's colors.

<Nyaaaaa>

The battle barge's machine spirit added a new record to its database `first time a Felis catus meowed on the deck`.

== The tea and the company are very good. The impending assassination, somewhat less so.

As you moved from startup to startup, specializing in an esoteric field not widely known but highly valued by those who need it, two things changed:

- The strategic goals of the companies
- The perks

Having to work on interesting problems and being well paid was enough when the company's goals sounded like the usual corporate word salad: _leveraging_ this or _synergizing_ that, maybe even _unleashing an untapped potential_.

But then they were replaced by _tormenting_, _hexing_ or _full spectrum haunting_.
You thought they were only the new generation of shibboleth you need to display to prove to the VCs that you're aware of the latest trends.

But the perks also changed, instead of _Friday's green detox smoothies_, you got _Thursday's deep hell French macaroons_ and _Tuesday's inscrutable mixture_.

_Impending assassination_ was the first perk mentioned on the job offer, but nobody mentioned it during the interview process.
At first, it sounded like an inside joke, and you expected somebody to explain it to you during your first days or the later orientation course.

But nobody did.

So you wait, and observe.

== A thing-in-a-bottle of unknown age and provenance; glass murky, fluid murkier, shape unclear.

– What is written on the description? +
– "`Cultural object, possibly of religious importance`". +
– Isn't it what they write when they don't have clue about something is about? +
– Indeed, the same exact sentence, every time. +
– This bottle is so fascinating to me, I want to study it for my next project, I nearly finished the grant proposal. +
– What do you find so fascinating? +
– How the bottle looks like, and the mysterious text engraved on it: "`gamer girl bath water`"
