ifeval::["{doctype}" != "book"]
= Impressions of Detail
Julien Kirch
v0.1, 2023-01-01
:article_lang: en
endif::[]

== They started it, and now -- years later, a world away, face and name unrecognizable -- it's time for you to begin to end it.

An RPG campaign that has been started must be finished, no matter how long since it started, whatever the cost and the consequences.

== Of the five things on the table, you are permitted to pick any three for your exile.

No the cat is not part of the things, they are not a "`thing`", they just loves laying here.

You can take them with you if you can convince them, and if you promise to take good care of them.

If you don't we'll know.

== These corridors, featureless science-fiction white, have never heard such sounds before.

There are unwritten rules, enforced tacitly by the group until someone is brave enough to disregard them.
And then everyone can happily act as the rule never existed.

Serving the Imperial Inquisition in the Deathwatch always changed marines, often in a dark way.

When the veteran techmarine Zalthach Berist returned to the _Left Elbow of the Emperor_ battle barge after their tour of duty, their battle sibling didn't know what to expect.

The report announcing their comeback was as bureaucratic as expected, briefly listing their achievements that escaped censorship, and in long details the technical improvements they did that have been officially validated.

Zalthach has been assigned an isolated room, until their new assignment would be decided.

While they were still unpacking their stuff, Mittens appeared on the control deck, with a collar matching the chapter's colors, the head of protocol let out a long sigh.

<Meowwwwww>