= L'informatique manque d'irrespect
Julien Kirch
v0.1, 2018-04-07
:article_lang: fr

[quote, Gavin Craig, 'link:https://unwinnable.com/2019/04/02/culture-vs-canon/[Culture vs. Canon]']
____
The problem is that too many of our stories have stopped being stories and started to function as brands. We cannot help by to be shaped by the stories we love, but we give up something when we become part of a brand, if for no other reason than that stories change when we need them to change, but brands change (or do not) at the whim of the rights holder. I think you’re exactly right that it’s good when we push against canon, I just think that we’re better off when we stop spending our energy fighting over what canon should be (and, too often, which communities’ voices do and do not matter in determining canon) and realize that canon, especially in terms of storytelling franchises, is temporary, arbitrary, and illusory. It isn’t ours, and it isn’t for us. It is, at best, a starting point, and we are better off the sooner we move on.
____
