= Agile et professionnalisme
Julien Kirch
v0.1, 2022-06-11
:article_lang: fr

Deux articles résonnent dans ma tête ces dernières semaines : link:https://logicmag.io/clouds/agile-and-the-long-crisis-of-software/[celui-ci] sur l'agile et link:https://medium.com/@teioh/we-are-all-professionals-now-or-how-did-grocery-workers-become-heroes-4cba3ffcc034[celui-là] sur le professionnalisme, (dont vous pouvez une traduction libre link:https://fabien-lamarque.eu/C'est-quoi-être-professionnel/[ici]).

Dans le premier article, j'ai été frappé par cet essai (traduction de ma part){nbsp}:

[quote]
____
Étant donné la pénurie de développeurs, on aurait pu s'attendre à ce que les pros de la technologie demandent des concessions plus directement matérielle, comme un syndicat ou de bénéficier de leur propriété intellectuelle.
À la place, iels ont demandé de modifier leurs conditions de travail pour pouvoir produire un travail de meilleure qualité et d'être plus efficaces.
En effet, comme l'indique l'auteur Michael Eby, cette révolte contre le management est différente des précédentes 
manifestations de mécontentement vis à vis de conditions de travail{nbsp}: plutôt que des améliorations matérielle, les personnes qui travaillent dans la tech ont créé "`un nouvel esprit`" basé sur des cultures, des principes, des hypothèses, des hiérarchies et des éthiques qui ont intégrées les plaintes de la critique artistique.
C'est-à-dire que le manifeste a attaqué directement la bureaucratie, l'infantilisation et le sens de la futilité que les devs déploraient.
Les devs ne demandaient pas un meilleur salaire mais d'être traités différemment.
____

Vouloir être considéré·e comme des pro, c'est être pris·e au sérieux en montrant qu'on a fait sien les besoins de l'organisation pour laquelle on travaille. Et donc qu'on peut vous faire confiance pour officiellement ne pas faire passer vos besoins propres devant ceux du système.

Par contre à l'inverse de l'auteur, je ne pense pas que les devs ne demandaient pas aussi de meilleures conditions de travail.

Tout d'abord je pense qu'obtenir un meilleur statut est déjà une amélioration des conditions de travail, par exemple le fait d'être traité en égal par les autres corps de métiers plutôt que comme un exécutant est un changement significatif.

Ensuite, en gagnant un meilleur statut, demander de meilleure condition de travail se fait sur un mode différent{nbsp}: pour obtenir quelque chose il faut trouver une justification qui explique que vous ne demandez pas cette chose pour vous mais pour le bien de votre travail.

Par exemple dans le link:https://fr.wikipedia.org/wiki/Planning_poker[planning poker], le fait que seul·e·s les dev aient la parole pour estimer les fonctionnalités car ce sont les mieux placé·e·s est aussi une manière de pouvoir influer sur la quantité de travail qui leur est demandée, même si le discours officiel est de jouer le jeu et pas d'en faire le moins possible.

L'opposition est moins directe que des ouvrier·ère·s qui demandent de travailler moins ou de simplement maîtriser leur rythme de travail, mais c'est tout de même la même chose qui se joue.

Il est plus difficile pour l'organisation de dire non qu'à des demandes "`standard`", car si elle accepte l'argumentation fourni avec la demande, cela revient à refuser quelque chose qui est bon pour elle.

L'enjeu est donc de trouver des arguments crédibles pour justifier les demandes.
Attention à bien choisir son approche, car quand une demande de se type est réfutée pour mauvaise fois ("`vous dites que c'est pour l'organisation, mais en fait c'est uniqument pour vous`"), le risque est de perdre la fasse et que tout le statut s'écroule.

L'inconvénient de la posture de pro est qu'il est beaucoup plus difficile de faire des demandes qui ne correspondent pas au bien de l'organisation, car un·e pro n'est pas sensé avoir ce type de demande{nbsp}: tout ce qu'iel est sensé vouloir doit l'être pour le bien commun.

La seule exception est celle du salaire, tant qu'elle se fait dans les formes convenues.