desc 'Create tasks'
task :create_tasks do
  require_relative 'task_engine'
  100.times do
    TaskEngine::Task.create
  end
end

namespace :db do
  desc 'Run migrations'
  task :migrate, [:version] do |t, args|
    require 'sequel/core'
    Sequel.extension :migration
    version = args[:version].to_i if args[:version]
    Sequel.connect('postgres://task_engine@localhost/task_engine') do |db|
      Sequel::Migrator.run(db, 'migrations', target: version)
    end
  end
end
