= Fenêtre d'Overton et consulting
Julien Kirch
v0.1, 2018-05-25
:article_lang: fr

[quote, 'link:https://fr.wikipedia.org/wiki/Fenêtre_d%27Overton[Wikipedia]']
____
La fenêtre d'Overton, aussi connue comme la fenêtre de discours, est la gamme d'idées que le public acceptera. Elle est utilisée par les médias polémistes.
Ce terme est un dérivé du nom de son auteur, Joseph P. Overton (1960-2003), un ancien vice-président de la Mackinac Center for Public Policy, qui, dans sa description de sa fenêtre a affirmé l'idée que la viabilité politique d'une idée dépend principalement du fait qu'elle se situe dans la fenêtre, plutôt que des préférences individuelles des politiciens.

Selon la description d'Overton, sa fenêtre comprend une gamme de politiques considérées comme politiquement acceptables au regard de l'opinion publique existante, et qu'un politicien peut donc proposer sans être considéré comme trop extrême, pour gagner ou conserver une fonction publique.

Après la mort d'Overton, d'autres ont examiné le concept d'ajustement de cette fenêtre d'idées acceptables, par la promotion délibérée d'idées en dehors de cette fenêtre (ou d'idées situées à la « frange externe ») avec l'intention de rendre acceptables, par comparaison, des idées jusqu'alors considérées comme marginales.
____