= Organigrammes et décisions
Julien Kirch
v0.1, 2018-12-29
:article_lang: fr
:ignore_files: orga.mmd

== Organigrammes

contraintes : 

* efficacité de la concentration : compétences regroupées
* efficacité de l'autonomie : compétences différents dans une même équipes

== PPMC (plus petit manager commun)

Problème du PPMC : quand une décision implique deux équipes et qui ne peut pas être prise au niveau des équipes, par exemple par ce qu'elles ont des objectifs différents, 

.Le PPMC des équipes vertes et rouge est la personne en orange
image::orga.svg[]

Il est normal que ça arrive, mais il faut que ça n'arrive pas suffisament souvent pour que ça soit une gène.

D'autant plus que le PPCM est élevé.

Deux manière de le faire :

- s'organiser pour que ça n'arrive pas ;
- s'organiser pour que le PPMC soit le plus bas possible

== La dette organisationnelle

Quand le système ou l'environement a évolué mais pas l'organisation

- modèle concentration vs. autonomie 
- le PPMC n'est pas le bon car le découpage pose problème

== Décisions régaliennes & externalités

Certaines décisions ne doivent pas être prises par une équipe : parfois un PPMC est utile quand il s'agit de décisions avec des externalités

Ça peut reposer sur une responsabilisation de l'équipe, ou par du gatekeeping.

== Les équipes hybrides

Quand on mélange dans une équipe des personnes avec des raccrochement différents

== Les modèles matriciels

Raccrocher des personnes ou des équipes à plusieurs manager qui ont des objectifs différents, pour faire en sorte que les besoins opposés 