= Standards ouverts ou pas ?
Julien Kirch
v0.1, 2021-01-01
:article_lang: fr

Le web est basé sur des standard ouverts : HTML5, JavaScript, HTTP, DNS ainsi que de nombreux formats d'images, de sons et de vidéosfootnote:[Excepté par exemple ceux qui sont utilisés sur les sites de streaming comme Netflix pour leur permettre de contrôler l'utilisation de leurs contenus] sont basés sur des formats dont la documentation est accessible gratuitement, et que tout le monde peut implémenter sans contrainte technique ou financière.

Mais il n'existe à l'heure actuelle que trois moteurs de navigateurs web compatibles avec la grande majorité des sites : Chrome, Firefox et Safarifootnote:[Chrome étant lui-même un fork de Safari].

Comme le disait un tweet effacé depuis : que veut dire que le web est "`ouvert`" si personne n'est en mesure de créer un nouveau moteur de navigateur, il s'agit d'une illusion d'ouverture.

En effet l'écriture et l'évolution d'un navigateur web demande un travail énorme, même en tenant compte des nombreux outils open-source sur lesquels on peut s'appuyer, de sorte que seule une grande organisation peut se le permettre.

Dans la mythologie de l'informatique, si dans l'écosystème qu'on utilise il nous manque un outil implémentant un certain standard, il devrait suffire de quelques heures, par exemple pendant un week-end, pour en développer un, même minimaliste.

C'est vrai pour certains types d'outils, mais ce n'est pas le cas pour d'autres, et j'ai le sentiment que c'est de moins en moins vrai.

En plus 