graph LR

Start[What contains the target cell?]
NoWall[Can't go there]
Nothing[Can go there]
Rock[Can the rock move?]
NoRock[Can't go there]
YesRock[Can go there]
Flag[\o/ Found a solution !]

Start -->|A wall|NoWall
Start -->|Nothing|Nothing
Start -->|A rock|Rock
Rock -->|No| NoRock
Rock -->|Yes|YesRock
Start -->|A flag|Flag
