graph TD

Start[Start]

Wall[Target cell contains a wall?]
YesWall[Can't go there]

Empty[Target cell is empty?]
YesEmpty[Can go there]

Rock[Target cell contains a rock?]

MoveRock[Can the rock move?]
NoMoveRock[Can't go there]

Flag[Target cell contains a flag?]
YesFlag[\o/ Found a solution !]
NoFlag[Can go there]

Start --> Wall
Wall --> |Yes|YesWall
Wall --> |No|Empty

Empty --> |Yes|YesEmpty
Empty --> |No|Rock

Rock --> |Yes|MoveRock
Rock --> |No|Flag

MoveRock --> |Yes|Flag
MoveRock --> |No|NoMoveRock

Flag --> |Yes|YesFlag
Flag --> |No|NoFlag
