= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://www.devever.net/~hl/stringtemplates[Producing HTML using string templates has always been the wrong solution]

[quote]
____
There are broadly two approaches used to generate (X)HTML in web
applications today:

* string templating systems;
* AST-based representation, transformation and serialization;

Historically, the majority of server-side web applications have tended
to produce HTML output using string templating systems. String template
approaches remain vastly more popular than AST-based approaches.

This is unfortunate, as I've come to the conclusion for some years now
that the use of string templating systems to generate HTML is
fundamentally the wrong approach.
____


== link:https://hachyderm.io/@stargirl/109697057391904145[So you want to solve Python packaging: a practical guide]

[quote]
____
Fundamentally these users do not want to think about this shit, and they're a _huge_ group of users. You know who does think about this shit? Web developers, and every time someone comes along with "Python packaging sucks and someone should fix it" they're a web dev.

That's because web devs have different expectations. They _expect_ to work with a packaging tool. They expect to find and install dependencies. They don't expect to work with a ton of native dependencies. They don't have the same problems.
____

== link:https://css-tricks.com/the-great-divide/[The great divide]

[quote]
____
The divide is between people who self-identify as a (or have the job title of) front-end developer, yet have divergent skill sets.

_On one side_, an army of developers whose interests, responsibilities, and skillsets are heavily revolved around JavaScript.

_On the other_, an army of developers whose interests, responsibilities, and skillsets are focused on other areas of the front end, like HTML, CSS, design, 
____

== link:https://cohost.org/lifning/post/855402-blockquote-style-m[Game design coding perverts love dwarf fortress]

[quote]
____
The reason all the game design coding perverts love dwarf fortress is because tarn Adams succeeded where every single one of us has failed: he made a weird procgen system that does solely what he wants to do and is never focused on User Friendliness and rather focused on "`can I simulate an entire world's history`" and cares more about what weird shit he wants to add then about best coding practices and is the sort of project where you spend 3 months researching plants to try and figure out what makes them edible so that you can decide how to generate a garden better without ever considering how the user will interface with the garden

and people loved it and bought it

everyone wants to do exactly this sort project of project where they never have to consider "game design" or "win conditions" or such dumb things and instead be called cool and sexy for the way that they made weather randomly come about because of their atmospheric conditions simulation

only he, god among game devs, has succeeded at making his weird personal expiriment sexy like that and we're all jealous and in awe
____

== link:https://cohost.org/mcc/post/765838-i-spent-my-new-years[I spent my New Years Eve in VR (unsuccessfully)]

[quote]
____
This will be relevant in the story I'm about to tell. _You can't just enter a VRChat space._ Even events _intended to be public_ involve misdirection, Discords pointing to other Discords, and fliers with coded language and implied access mechanisms. I think of the elaborate rituals gay subcultures used in link:https://everything2.com/title/Gay+subcultures+in+eighteenth+century+Europe[eighteenth-century cruising routes] to ensure the person they were propositioning was a fellow queer and not a police informant, except instead of trying to solicit gay sex, they are trying to have a normal human interaction. Maybe some of them have gay sex afterward, I don't know. It doesn't seem to be the focus.
____
