= Links - Soon
Julien Kirch
v1.0, 2024-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://blog.liw.fi/posts/2022/05/07/unix-cli/[Unix command line conventions over time]

[quote]
____
This blog post documents my understanding of how the conventions for Unix command line syntax have evolved over time. It’s not properly sourced, and may well be quite wrong. I’ve not been using Unix until 1989, so I wasn’t there for the early years. Maybe someone has written a proper essay on this, with citations. I’m too lazy to dig them up.
____

== link:https://www.datagubbe.se/gnomefiles/[Gnome Files: A detailed UI examination]

[quote]
____
Note the many distinct-looking icons in the toolbar. From left to right we have three stacked dots, three stacked dots and lines, and three stacked lines. Pretty obvious what they're all about, right? 
____

== link:https://cutlefish.substack.com/p/tbm-308-boundary-of-safely-challenged[TBM 308: Boundary of safely challenged assumptions]

[quote]
____
"The shop floor (or gemba) is not visible in the same way it is in some other industries," link:https://www.linkedin.com/feed/update/urn:li:ugcPost:7235679970662961153?commentUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A7235679970662961153%2C7235715144394121216%29&replyUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A7235679970662961153%2C7236022642246316033%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287235715144394121216%2Curn%3Ali%3AugcPost%3A7235679970662961153%29&dashReplyUrn=urn%3Ali%3Afsd_comment%3A%287236022642246316033%2Curn%3Ali%3AugcPost%3A7235679970662961153%29[writes Tiani Jones]. "`An exaggerated way I think about it is that [software development feels like] a magical world where people meet in teams and then go away and code appears.`" Even in the case of synchronous, in-person work, all you see is a group of people sitting at computer screens who occasionally get up and have a conversation (or get a snack or use the restroom). The work and "tools" are virtual. The backlog isn't a mountain of parts sitting on the shop floor alongside all the unfinished projects and open threads. To top it off, we do a lot of our best "work" while taking a walk or riding a bike—we're not even in "`the office`" (physical, virtual, or otherwise).
____