= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://cohost.org/tef/post/1877226-why-i-think-rpc-suck[why i think rpc sucks ass]

[quote]
____
_yet another special interest topic infodump_

rpc sucks, and it's not because it's not "`restful`" or whatever flavour of the month crap's in fashion. be it corba or dcom, json-rpc or grpc, sunrpc or soap, the same problems always come up
____

== link:https://cohost.org/tef/post/1927855-practice-mostly-tu[how'd u get so good at writing? practice, mostly]

[quote]
____
don't be afraid to write fragments of a post, as sometimes you can glue them together into something more cohesive later
____

[quote]
____
edit 2: the one other tip i forgot? sometimes you just need to ramble until you sum up your point, and then delete the prose that got you there
____

== link:https://lethain.com/gelling-engineering-leadership-team/[Gelling your Engineering leadership team.]

[quote]
____
In this article, we’ll discuss:

* Debugging the Engineering leadership team after stepping into a new role
* Gelling your leadership into an effective team
* What to expect from your direct reports in that leadership team
* Diagnosing conflict within your team
____

[quote]
____
When it’s possible, it’s well worth your time to consider including one or two senior engineers to report to you, as opposed to only managing engineering managers. An engineering executive is responsible for blending the technical and managerial perspectives of engineering, and that’s most easily done when both perspectives are represented within your leadership team.

In some cases, this will be difficult to accomplish. You may have too many direct reports already, and feel it will be overwhelming to include more. In that case, work to establish a group of senior engineers that you interact with frequently to ensure you’re hearing their perspectives. This is frequently an architecture team or the senior-most engineer from each business unit.
____

[quote]
____
The next common challenge is team members who’ve learned bad habits in bureaucratic or shrinking companies. Those environments often teach the implicit leadership lesson that it’s more effective to capture existing capacity within the company than to create new capacity for the company. Leaders immersed in that lesson often view success as a zero-sum game. Your goal is to convince them that today’s capacity represents a small fraction of the future capacity. By instead focusing on the capacity that can be collaboratively created in the future, they’ll have significantly more opportunity.
____
