= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://www.pastemagazine.com/games/idle-games?post_type=article&p=356661[Idle threat: what incremental games say about our relationship to work]

[quote]
____
On the other hand, Mat Jones asks in his essay on free-to-play
link:https://www.rockpapershotgun.com/let-it-die-free-to-play-is-good-actually[Let it die] "`What even are videogames if not perverse, unintentional
exercises in alienation?`" Idle games situate us in patterns of
production, and nature sim versions take that one step further by
implying that the process of producing things that produce other things
is relaxing. You're focused mainly on development and accumulation, two
processes that have been troubled in the city-building conversation.
This is the darkness at the heart of my floating zen garden: at its
base, _Garden Galaxy_ is a (one-time payment based) gacha that is framed
as a zen garden for relaxation.

To play any game, you need to do _something_ to progress. You can walk
around and look at flowers or talk with NPCs all day, but the majority
of the time you have to wake up and participate in some system or
another. The difference is that _Garden Galaxy_ and games like it use
loops that were created in much more work-centered, sometimes even
predatory games. Can these more pleasant versions ever get out from
under that shadow?

None of these questions takes away from the fun I had with _Garden
Galaxy_. But as we've done with genres like the city builder and the
strategy game, it's worthwhile to examine the roots of the idle game and
treat its descendents to the same examination, so we can reimagine how
to really use games to trouble processes of work and production—and
maybe, in the spirit of idleness's earlier definition, truly relax.
____
