= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://izzys.casa/2023/06/everything-you-never-wanted-to-know-about-cmake-redux/[Everything you never wanted to know about CMake (Redux)]

[quote]
____
As a brief aside, I would argue that simply knowing about Hyrum’s Law turns it into a self-fulfilling prophecy. In other words: As the number of developers aware of Hyrum’s Law increases, so too will the number of developers using it as an excuse to exploit every observable behavior. If that number ever reaches 0, assume I am dead.
____

== link:https://nabeelqu.substack.com/p/notes-on-puzzles[Notes on puzzles]

[quote]
____
The lesson I found the most striking is this: _there’s a direct correlation between how skilled you are as a chess player, and how much time you spend falsifying your ideas_. The authors find that grandmasters spend longer falsifying their idea for a move than they do coming up with the move in the first place, whereas amateur players tend to identify a solution and then play it shortly after without trying their hardest to falsify it first. (Often amateurs, find reasons for playing the move -- "`hope chess`".)

Call this the "`falsification ratio`": the ratio of time you spend trying to falsify your idea to the time you took coming up with it in the first place. For grandmasters, this is 4:1 -- they’ll spend 1 minute finding the right move, and another 4 minutes trying to falsify it, whereas for amateurs this is something like 0.5:1 -- 1 minute finding the move, 30 seconds making a cursory effort to falsify it. 
____

[quote]
____
Complacency hits especially hard in king and pawn endgames, when king moves that seem "`good enough`" can in fact be losing or drawing, and you really have to calculate each and every move very exactly to figure out a win. You have to be _unreasonably thorough_ and check every single move, to a degree that seems quite pedantic.

I notice this in people who are good at science, too: they are really, really thorough and check every edge case.
____

== link:https://commoncog.com/accelerated-expertise[Accelerated expertise]

[quote]
____
They conclude, tentatively, that perhaps it is only possible to accelerate _proficiency between senior apprentice and junior journeyman levels (or between senior journeyman and junior expert levels)_. They present the following stylised growth curve:

Perhaps, the authors say, overall mastery still takes 10 years in the field, and there’s nothing we can do about that.

But what we _do_ know is this: the set of successful accelerated training programs that currently exist enable accelerated proficiency, not accelerated mastery.
____

[quote]
____
. Learning is the active construction of knowledge; the elaboration and replacement of mental models, causal stories, or conceptual understandings.
. All mental models are limited. People have a variety of fragmentary and often reductive mental models.
. Training must support the learner in overcoming reductive explanations.
. Knowledge shields lead to wrong diagnoses and enable the discounting of evidence.
. Reductive explanation reinforces and preserves itself through misconception networks and through knowledge shields. Flexible learning involves the interplay of concepts and contextual particulars as they play out within and are influenced by cases of application within a domain.

* _Therefore_ learning must also involve unlearning and relearning.
* _Therefore_ advanced learning is promoted by emphasising the interconnectedness of multiple cases and concepts along multiple conceptual dimensions, and the use of multiple, highly organised representations.
____
