= Links - Soon
Julien Kirch
v1.0, 2024-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://cutlefish.substack.com/p/tbm-285-shared-teams-and-apples-to[TBM 285: Shared Teams and Apples-to-Oranges Priorities]

[quote]
____
Cage Match. Have their "`customer`" teams fight for their capacity by forcing some kind of sequenced queue or similar (if escalated, this could include a leader being the tie-breaker or prioritizing lists of projects). Pros: great for sequencing. Cons: you’re pegged as a "`service`" team because you’re hands-off, and the teams resent you for making them fight each other. Leaders resent having to be the tie-breaker. Teams just work around you.
____

[quote]
____
Another interesting thing starts to happen. If a team can’t force a shared team to focus on their thing, or if those teams are impossibly slow to help, they often just work around other teams and finish whatever they can get done autonomously. Go Really Rogue. This leads to a dynamic whereby global output doesn’t match priorities, and people start second-guessing the whole system. At the same time, everyone points at those teams and says, "`See, why can’t you show initiative and ship like Team X? They take matters into their own hands!`"
____

== link:https://dbushell.com/2024/05/07/modern-wordpress-themes-yikes/[Modern WordPress - Yikes!]

[quote]
____
So to recap, the flagship WordPress theme has:

* CSS in front matter
* CSS in PHP
* CSS in JSON
* CSS in _HTML-JSON_
* CSS in HTML `+<style>+` elements
* CSS in HTML `+style+` attributes
* CSS in external stylesheets

No _CSS-in-JS_ for the complete set sadly.
____
