= Soon
Julien Kirch
v1.0, 2019-01-01
:article_lang: en

== link:http://okmij.org/ftp/kakuritu/logic-programming.html[HANSEI as a Declarative Logic Programming Language]

[quote]
____
Classical Prolog is an elegant language that concisely represents the fundamental concepts of term algebra, non-determinism, unification, counter-example driven search, and the separation of logic and control.
The ability to run a program forwards and backwards is uncanny.
However, real Prolog programs are replete with cuts, FFI calls, committed choice and unexpected divergence -- defiling the Classical purity.

Classical Prolog is an enchanting misconception.
It ought to be studied, for its ideas and lessons.
One lesson is that guessing -- non-determinism -- is fundamental, but should not be the default mode of execution.
One should guess, but guess lazily.
____

== link:https://www.reddit.com/r/programming/comments/bgw2a3/your_cs_degree_wont_prepare_you_for_angry_users/elo94fm/[Your CS Degree Won’t Prepare You For Angry Users, Legacy Code, or the Whims of Other]

[quote]
____
The tendency to want to "fix" things is sometimes part of the problem.
It's called lava flow pattern, and it's when your codebase is programmed in waves of different guiding design and architecture.
One of the best things you can do in an old codebase is just follow existing patterns and design, even if you don't agree with them.
If you're going to refactor anyway, make it very obvious where the line is between old and new, so that others know which design to follow where.
Preferably putting the new stuff into a separate namespace or even library.
____

== link:https://shop.jcoglan.com/building-git/[Building Git]

[quote]
____
Every time multiple pieces of your program have an implicit agreement that’s not enforced, that’s an opportunity for a maintainer to change one piece of code without changing others that depend on it.
This, rather than eliminating literal duplication of lines of code, is the essence of the DRY principle 
____

== link:http://www.firstpersonscholar.com/fix-my-post-apocalypse/["`Fix my post-apocalypse`"]

[quote]
____
In place of a world overflowing with or predestined to human meaning, _Fallout 76_ advances a more pessimistic view of post-catastrophe in which human significance is eroded.
While humans continue to act in _Fallout 76_’s post-future, their actions no longer correlate to transcendent purpose, but only occur in response to the immanent events and challenges of the post-apocalyptic milieu.
This shift is important in that it rethinks survival as less "`__what we do to the world__`" than the more misanthropic question of "`__what the world does to us__`".

The survivor of _Fallout 76_ is condemned to scavenge the detritus of civilizational ruin for resources in order to navigate and survive in a more strikingly ambivalent _Fallout_ world.
Withdrawing the unifying narrative figured elsewhere in the centralizing significance of "`family`" in _Fallout 4_, or the quest for "`truth`" in _Fallout: New Vegas_, _Fallout 76_ postulates a horrific image of post-nuclear existence in which humanity no longer shapes the world, but in a more basic ontological mode of survival, _reacts_ to it.
Here, _Fallout 76_ touches upon the horror of surviving in an increasingly alien and antagonistic world by remitting the image of human superiority and presenting instead an ambivalent and strikingly nihilistic reality.
Herein, the world of _Fallout 76_ displaces the image of human exceptionalism and so too, the idea that the fall of civilization will catalyze the rise of a new human civilization, or what Colebrook footnote:[Colebrook, C. (2013). The death of the posthuman: Essays on extinction, Vol. 1. Ann Arbor, MI: Open Humanities Press.] calls the presupposition of the polis _after-humans_.
Contrary to the idea that future will be a human one, _Fallout 76_ confronts the player with a posthuman after-future in which humans no longer figure as an ideological or causal center.
____
