= Links - Soon
Julien Kirch
v1.0, 2021-01-01
:article_lang: en
:figure-caption!:
:article_description:

== link:https://press.invincible.ink/cursed-knowledge/[Cursed knowledge]

[quote]
____
The basic idea, I think of "`cursed`" in the context of Extremely Online Twitter Speakers is the way that an idea can persist in you and bother you, not necessarily in an anxiety spiral kind of way, but just in an analytical, reflective way, things that we might _rather not have known_. Things that don’t actually change our behaviours or impede the way we are, but now you know them, you might be reminded of them at times when you’d rather not think about it.

There is an uneasiness in knowing some things. Our brain is an association engine. Sometimes if we know something and it’s strange and weird, that can mean that we forget it, and it lays under the waves of our mental process most of the time. And then, something that stirs that memory, and suddenly it’s there, and you’re back confronting that unpleasantness. Not painful, not traumatic, just… unpleasant. Like a fart in your ear.

To put it simpler, _cursed knowledge_, in a useful way, is _knowledge that you can’t know for sure you’d rather not know_. The only way to know is to learn it; the only way to learn the effect it has on you is to know it. But there’s a recognisable risk in how it works. This isn’t just curses of the vulgar and the body. There’s a mild curse associated with knowing the structure of Gustav Holst’s _The Planets_, and suddenly you see the underlying structure in every movie score across several genres. Maybe if you can recognise the Four Chords, every pop song sounds more similar, the world seems narrower. And maybe that’s something you’d rather not _know_, if you had the luxury.

But you didn’t know that you didn’t want to, before you knew it.
____
