= Links - Soon
Julien Kirch
v1.0, 2024-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://cohost.org/bruno/post/5322687-the-more-proficient[Tool proficiency]

[quote]
____
A particular thing that these old customizable GUIs were good for -- still seen in a lot of professional software, eg Photoshop -- was just hiding irrelevant affordances. Not everything needs to be visible or accessible by default; some features have niche uses, users have different levels of engagement and proficiency. You could go into the menu and toggle aspects of the UI on or off depending on whether you used them.

Discord doesn't give itself the affordances to selectively veil parts of its UI, and as a result _every_ user sees _every_ change to _every_ feature. Often a change that is welcomed by the users who embrace a given feature appears as just a pointless alteration for the users who don't use the feature. This, again, contributes to the sense of instability.
____

== link:https://yosefk.com/blog/managers-have-no-human-rights.html[Managers have no human rights]

[quote]
____
Here are some thoughts which are often basically correct:

* Every time I try to do the right thing here, it's like the place actively resists it. Actually, forget "`the right thing`" -- it's whenever I try to do pretty much _anything_.
* Yesterday's "strategic" thing I toiled over just got tossed into the dumpster. And they expect me to be all excited about the new "strategy" they coughed up?
* My "`colleagues`" attack me overtly and covertly all the time, all the while maintaining a "`professional`" and even cheerful demeanor -- in effect, a gaslighting tactic. And in this sewage lagoon, I'm supposed to get work done?
* The deadline is impossible, and everybody knows it. Why are we all pretending that we're trying to meet it, when we're actually busy rehearsing our speeches blaming the inevitable failure on each other?
____

