= Links - Soon
Julien Kirch
v1.0, 2021-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://arcove.substack.com/p/null-call[Null Call]

[quote]
____
No matter how hard you try to perceive a leaf on a tree, your eyeballs are only sending extremely noisy sensory data to your brain. Your subconscious mind creates a _mental model_ of what is happening, and continuously updates it. It needs to filter, smooth, and distort the new incoming sensory information to fit the model, so that your conscious mind is able to make sense of it. If you see something that violates your mental models too extremely, it literally becomes the case that you _can’t believe your eyes_, and you are left stumbling around, Velma-like, in search of a new mental model of the situation.

Through a handy invention called "`language`", human beings are able to share mental models with each other. These models are on a continuum from "`metaphorical`" (as in stories, myths) to “literal” (as in folk theories, scientific hypotheses). These shared mental models all come together to form a _worldview_, which is at the heart of what we call "`culture`". This allows the tribe to understand the world and each other.

The _shaman_’s job, then, is to:

. Understand the tribe’s existing mental models
. Update shared mental models over time to reflect the changing environment and evolving needs of the tribe
. When _spooky shit_ starts happening that falls outside of the "`shared reality operating system`", it is the shaman’s role to _debug_.
____
