= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:http://www.takingnotes.co/blog/2020/07/01/accessibility-engineering/[Accessibility engineering and low end disruption]

[quote]
____
what matters here, what sets apple apart, is that they figured out how to go last and contain the risk enough to avoid a revolt from other teams or executive leadership. it costs them a lot to do so, has significant, measurable downsides, and requires a significant rethink of what it means to build good software.
____

[quote]
____
apple has a team whose only job is to make things accessible and they have infrastructure that lets that team mostly avoid people who have a different job saying no to them. put those together and you have the most successful accessibility software team (imho) on planet earth.
____

== link:https://cohost.org/mononcqc/post/3647311-paper-you-want-my-p[Paper: you want my password or a dead patient?]

[quote]
____
This week's paper is a draft from Ross Koppel, Sean Smith, Jim Blythe, and Vijay Kothari titled link:https://www.cs.dartmouth.edu/~sws/pubs/ksbk15-draft.pdf[Workarounds to Computer Access in Healthcare Organizations: You Want My Password or a Dead Patient?] First of all, great title. This paper is a work of ethnography, where the authors sat and studied how people in medical settings did their work interacting with computers, and denoted all sorts of workarounds they'd take to bypass security rules that they judge are a hindrance to their work.

The idea behind the paper is that clearly, people behind the computer systems are not working from a realistic understanding of what medical professionals have to contend with to do their job. And maybe, just maybe if they sat and figured out how said professionals do their work, it may be different.
____
