= Links - Soon
Julien Kirch
v1.0, 2024-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://blog.lauramichet.com/why-you-should-not-make-your-games-writers-sprint/[Why you should not make your games writers sprint]

[quote]
____
Iterating adds functionality to code. Iteration adds quality to writing. These are super, super different things.

This means that the first draft of anything will probably be the lowest-quality version of it. Everyone _believes_ themselves capable of judging the quality of writing, so writers often get extremely harsh and incompetent feedback from people who simply do not know what they are talking about. If a writer shares a rough first draft, they may suddenly find all sorts of random, panicked people from all disciplines and seniority levels swooping down on them to criticize their work - or even demanding to do some writing themselves.

Creative leaders in particular often judge writers harshly for showing real WIP assets. I have worked on games where an executive gave me line edits on an early draft script, panicking because it wasn't done yet. I've seen executives who had never written a story in their life tell me they could critique my team's work because they'd read _Save The Cat._ These are people who no idea what's acceptable in an early draft and what's not. They do not know when a script is "done," and they panic when they see anything that isn't final, because they're worried it will never get any better.

I've found that many writers' work practices are strongly affected by the fragility and anxiety of creative leadership. While writers in a very emotionally supportive, protected environment may be comfortable with widely sharing rough first drafts and iterating on them in the Agile process, they will refuse if they are vulnerable to _coordinated attack by feral executive_.
____

[quote]
____
The big difference between a deadline and an Agile-style points-costing system is that a deadline _tells the writer how much work to do on the draft._ Games writing is often "functional" within the game's feature set at every draft stage (or has the potential to be functional once implemented). If you can read it, you could ship it if you _had_ to - or at least push what you have into a build, or send a sub-par script to VO records.
____

== link:https://maybeelse.site/words/the-problem-of-witches/[The problem of witches]

[quote]
____
"`What is true power`" is supposed to be one of those deep, philosophical questions with no real answer. It—and the thought experiments which grow on it like clinging weeds—are meant to become a mirror to the speaker's biases, to reveal how they think about the world. Let that be so.

To my mind, the answer is simple: true power is control of the context in which the world is understood. It is the ability to say "`this is what the world is`", and be heard.
____
