= Links - Soon
Julien Kirch
v1.0, 2022-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://thagomizer.com/blog/2017/09/29/we-don-t-do-that-here.html[We don't do that here]

[quote]
____
If no one has told you yet, as your career in tech progresses you will
eventually become a "`custodian of culture.`" If you run a meetup or a
team, if you lead an open source project, or if you organize an event
people will be looking to you to know what is and isn't okay in that
space. You get this responsibility whether you want it or not. You don't
have to be internet famous to have this responsibility. If there are
people you work with who have been around for less time than you, then
you are going to help set the culture for them.

Setting culture is hard. It is hard when you are officially the boss or
the leader. It is hard when you are just another person on the team
trying to create an environment that welcomes all types of people.
Setting boundaries for acceptable behavior can be scary, and it can have
both personal and professional consequences. Because it is scary, I
fought my responsibility to set the culture of my groups for a long
time. I didn't want to be the one telling folks to knock it off and
treat others with respect.

This is when I pull out "`we don't do that here.`" It is a conversation
ender. If you are the newcomer and someone who has been around a long
time says "`we don't do that here`", it is hard to argue. This sentence
doesn't push my morality on anyone. If they want to do whatever it is
elsewhere, I'm not telling them not to. I'm just cluing them into the
local culture and values. If I deliver this sentence well it carries no
more emotional weight than saying, "`in Japan, people drive on the left.`"
"`We don't do that here`" should be a statement of fact and nothing more.
It clearly and concisely sets a boundary, and also makes it easy to
disengage with any possible rebuttals.

[quote]
_____
Me: "`You are standing in that person's personal space. We don't do that
here.`" +
Them: "`But I was trying to be nice.`" +
Me: "`Awesome, but we don't stand so close to people here.`" +
_____
____
