= Links - Soon
Julien Kirch
v1.0, 2022-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://cohost.org/cathoderaydude/post/572330-i-do-no-t-care-about[i do no t care about the current raspi discourse but the raspi annoys me so much because it fouled the market]

[quote]
____
this is a kind of crime that i regularly assign to Products. the problem
with the Raspberry Pi is that it came out at a time when _the thing that
it is_ had more or less just become feasible - meaning, something _else_
could have filled the gap, but the pi got there first, and anyone who
was thinking of competing just turned away in disinterest

no, i don't care about the beagleboard or some other thing. come on.
_come on_, don't bullshit me, you know how this works. if you want:

* a price low enough to buy one on a whim
* the ability to google problems relating to the underlying hardware
* regular software updates
* access to a wide variety of hardware addons

then you buy _the one, single thing_ that the market has decided "filled
the gap." There is not a second thing, only second-class things. The Pi
is _the_ tiny single-board computer, and trying to use anything else
_casually_ - that is, not writing your own goddamn kernel drivers - is
going to be a worse experience.

I call this "`fouling the market`": there can only be one Canonical Single
Board Computer, and it is the Pi. Nobody is ever going to create a
competitor, because it's a foregone conclusion that it will never have
more than 1% of the market share. There was one bite at the hook, and
the raspi took it. The problem is that the Pi bit at the _wrong_ hook.
It's a terrible SBC, because it's not meant to be one.
____
