= Links - Soon
Julien Kirch
v1.0, 2022-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://gankra.github.io/blah/deinitialize-me-maybe/[Destroy all values: designing deinitialization in programming languages]

[quote]
____
The nasty thing with programming languages is that good design is often a _holistic_ property. Certain features only make sense in the presence (or absence!) of other features. We're going to be exploring a lot of different concepts in this post, and it's important to keep in mind that they don't work in a vacuum. They solve specific problems caused by solutions to _other_ specific problems, caused by solutions to **other other** problems.
____

== link:https://logicmag.io/beacons/[Holding to account: Safiya Umoja Noble and Meredith Whittaker on duties of care and resistance to big tech]

[quote]
____
One thing we rarely discuss is how AI research and development's dependence on corporate resources worked -- and continues to work -- to shape and in some cases co-opt knowledge production. In other words, to "`do AI`" as defined in the current "`bigger is better`" paradigm, you increasingly need resources that are controlled by these handful of companies. You need access to really expensive cloud compute, you need access to data that is hard and sometimes impossible to get. You can't just go to the data market and buy it -- you often need to get access from the data's creators or collectors, who are often the tech companies. It's fair to say that academic computer science disciplines underwent a kind of soft-capture, in which as a condition of doing "`cutting edge`" AI research, over the last decade they became increasingly dependent on corporate resources, and corporate largesse.

This dynamic led to practices like dual affiliation, where professors work at a tech company but have a professorial title and produce research under their university affiliation. It's led to tech companies moving whole corporate labs into the middle of universities -- like Amazon's machine vision lab at Caltech. We have a structural imbrication between a massive, consolidated industry and knowledge production about what that industry does. And this compromised entanglement has bled into the fairness and ethics space, in many cases without anyone commenting on it. There are many forces working against our recognition of how captured the technical disciplines are at this time, and how easy it is for them to extend this capture into fairness, ethics, and other disciplinary pursuits focused on the consequences and politics of tech.
____

