= Links - Soon
Julien Kirch
v1.0, 2020-01-01
:article_lang: en

== link:https://culturemachine.net/vol-18-the-nature-of-data-centers/the-data-center-as/[The Data Center as Technological Wilderness]

[quote]
____
A recurring feature in images and imaginations of the data center is the complete absence of human beings. Drawing from ethnographic fieldwork conducted in the data center industry, this essay approaches the visual form of the depopulated data center through the analytic of "`wilderness`". Often connoting a domain of "`pure nature`" uncorrupted by human presence, the concept of wilderness productively resonates with the representational strategies of the data center industry, where the visual elimination of human workers optically configures the data center as a posthuman "`pure machine`". Through the experimental juxtaposition of "`natural`" and "`technological`" wildernesses, this essay explores how the infrastructure fiction of the depopulated data center intersects with fantasies and futures of technological progress, nonhuman security, automation and data objectivity.
____