= Links - Soon
Julien Kirch
v1.0, 2021-01-01
:article_lang: en
:figure-caption!:
:article_description: Miracle of the commons

== link:https://aeon.co/essays/the-tragedy-of-the-commons-is-a-false-and-dangerous-myth[The miracle of the commons]

[quote]
____
In December 1968, the ecologist and biologist Garrett Hardin had an essay published in the journal _Science_ link:https://science.sciencemag.org/content/162/3859/1243[called] "`The Tragedy of the Commons`". His proposition was simple and unsparing: humans, when left to their own devices, compete with one another for resources until the resources run out. "`Ruin is the destination toward which all men rush, each pursuing his own best interest`", he wrote. "`Freedom in a commons brings ruin to all`". Hardin's argument made intuitive sense, and provided a temptingly simple explanation for catastrophes of all kinds -- traffic jams, dirty public toilets, species extinction. His essay, widely read and accepted, would become one of the most-cited scientific papers of all time.

Even before Hardin's "`The Tragedy of the Commons`" was published, however, the young political scientist Elinor Ostrom had proven him wrong. While Hardin speculated that the tragedy of the commons could be avoided only through total privatisation or total government control, Ostrom had link:https://dlc.dlib.indiana.edu/dlc/handle/10535/3581[witnessed] groundwater users near her native Los Angeles hammer out a system for sharing their coveted resource. Over the next several decades, as a professor at Indiana University Bloomington, she link:https://www.thecgo.org/research/the-environmental-optimism-of-elinor-ostrom/[studied] collaborative management systems developed by cattle herders in Switzerland, forest dwellers in Japan, and irrigators in the Philippines. These communities had found ways of both preserving a shared resource -- pasture, trees, water -- and providing their members with a living. Some had been deftly avoiding the tragedy of the commons for centuries; Ostrom was simply one of the first scientists to pay close attention to their traditions, and analyse how and why they worked.
____
