= Links - Soon
Julien Kirch
v1.0, 2024-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://cutlefish.substack.com/p/tbm-268-going-deep[TBM 268: "`Going Deep`"]

[quote]
____
Respect existing reporting lines, but bring the teams closer to senior leaders at least occasionally to encourage the flow of information and model the discipline (and safety and respectful feedback) needed to navigate the current reality. It isn't about "`flattening`" the org chart but rather about ensuring people who can discuss reality are in the room.
____

== link:https://dl.acm.org/doi/10.1145/3639443[DevEx in Action: A study of its tangible impacts]

[quote]
____
Most developers know they need good DevEx to do their
best work. Furthermore, because so many companies today
are software-driven, their ability to be profitable depends on
their developers' ability to be productive and creative, and
write and maintain high-quality software, with low technical
debt. Even a company's ability to innovate and be profitable
depends on DevEx -- because if it's too hard to do daily work,
it's definitely too hard to innovate.

Knowing intuitively the importance of DevEx, however,
is not always enough to make a compelling case to upper
management. When management rightfully asks if DevEx
has an impact on business, this study can provide an
answer, showing that DevEx affects the performance of
individual developers, teams, and organizations. Further,
our analysis clearly indicates which factors should be
given priority for teams to achieve positive outcomes. This
evidence can justify a DevEx initiative, as well as provide
actionable insights to guide a DevEx intervention.
Now that you are sold on improving DevEx, how can
____
