= Links - Soon
Julien Kirch
v1.0, 2021-01-01
:article_lang: en
:figure-caption!:
:article_description:

== link:https://www.baldurbjarnason.com[Making Colophon Cards]

[quote]
____
There are tasks that computers are good at. And there are tasks where they aren’t. One driver of the evolution of the personal computer, laptops, mobile phones, and all forms of mobile computing has been the desire to increase their range: do more; in a smaller package. Many in tech and software are addicted to riding this wave of new capabilities, however long it will last, to work on and create new software. To extend the reach of the computers in our lives.

Innovation’s the word. Pushing the boundaries. You know the phrases. Usually spouted by _that_ dude at the party.

The other side is _also_ interesting. We are now in a place where we have entire genres of software that have decades of history, are backed by stacks of new and old research, have dozens of successful, well-made exemplar apps, and a broad enough conceptual space to allow for new variations on the theme.
In short, we have genre software and we have avant-garde software
____

== link:https://www.baldurbjarnason.com/2021/the-group-think-hoot/[Nobody gives a hoot about groupthink]

[quote]
____
If you ever wondered why so many people use their email to organise all of their work, this is why. It’s the only user-subjective information management tool at their disposal.
____
