= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://www.pastemagazine.com/games/idle-games?post_type=article&p=356661[Idle threat: what incremental games say about our relationship to work]

[quote]
____
On the other hand, Mat Jones asks in his essay on free-to-play
link:https://www.rockpapershotgun.com/let-it-die-free-to-play-is-good-actually[Let it die] "`What even are videogames if not perverse, unintentional
exercises in alienation?`" Idle games situate us in patterns of
production, and nature sim versions take that one step further by
implying that the process of producing things that produce other things
is relaxing. You're focused mainly on development and accumulation, two
processes that have been troubled in the city-building conversation.
This is the darkness at the heart of my floating zen garden: at its
base, _Garden Galaxy_ is a (one-time payment based) gacha that is framed
as a zen garden for relaxation.

To play any game, you need to do _something_ to progress. You can walk
around and look at flowers or talk with NPCs all day, but the majority
of the time you have to wake up and participate in some system or
another. The difference is that _Garden Galaxy_ and games like it use
loops that were created in much more work-centered, sometimes even
predatory games. Can these more pleasant versions ever get out from
under that shadow?

None of these questions takes away from the fun I had with _Garden
Galaxy_. But as we've done with genres like the city builder and the
strategy game, it's worthwhile to examine the roots of the idle game and
treat its descendents to the same examination, so we can reimagine how
to really use games to trouble processes of work and production—and
maybe, in the spirit of idleness's earlier definition, truly relax.
____

== link:http://peter.eisentraut.org/blog/2023/04/04/sql-2023-is-finished-here-is-whats-new[SQL:2023 is finished: Here is what's new]

[quote]
____
SQL:2023 has been wrapped. The final text has been submitted by the
working group to ISO Central Secretariat, and it's now up to the ISO
gods when it will be published. Based on past experience, it could be
between a few weeks and a few months.

In the meantime, we can look at what is new. The changes can be grouped
into three areas:

. Various smaller changes to the existing SQL language
. New features related to JSON
. A new part for property graph queries

Let's look at each one.
____

== link:https://dx.tips/whats-your-dark-matter-strategy[What's your dark matter strategy?]

[quote]
____
With the most optimistic take, summing across ALL of these audiences (no
overlap), you only capture ~33% of the market. Meaning if you, as a
developer content creator, _reached every conventional audience there is
on every platform there is_, _you still would not be reaching two thirds of developers_. And those you _could_ reach would be majority newer
developers who have the time and desire to spend on your content.

The other 2/3 of developers aren't spending their free time at meetups
or watching livestreams. They'll maybe go to one conference every three
years. They don't care about the hot takes. They have to look up the
acronyms you take for granted. They don't know what new framework is
obviously the future, and which code pattern was _so yesterday_.
____

== link:https://gist.github.com/raysan5/909dc6cf33ed40223eb0dfe625c0de74[Custom game engines: a small study]

[quote]
____
A couple of weeks ago I played (and finished) link:https://store.steampowered.com/app/752590/A_Plague_Tale_Innocence[A Plague Tale], a game by link:https://en.wikipedia.org/wiki/Asobo_Studio[Asobo Studio]. I was really captivated by the game, not only by the beautiful graphics but also by the story and the locations in the game. I decided to investigate a bit about the game tech and I was surprised to see it was developed with a custom engine by a relatively small studio. I know there are some companies using custom engines but it's very difficult to find a detailed market study with that kind of information curated and updated. So this article.
____

