= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://medium.com/nice-work-from-active-voice/hey-designers-theyre-gaslighting-you-e02e5a4d9cff[Hey designers, they're gaslighting you.]

[quote]
____
Here are some statements I've heard one too many times in this cursed year:

* We need you to do more with less.
* Always be helpful. Never miss an opportunity to demonstrate value.
* You need to stretch across the full product surface area until we get more headcount.

This advice might sound reasonable on its face, but it doesn't work. Doing more with less doesn't give us power -- and it doesn't produce good design work, either. Instead, we get overloaded and overcommitted. We feel personally responsible for keeping all the plates in the air.

We also get shallow work -- because we're prioritizing juggling it all over doing anything really well. And you know what that does? It teaches our partners that that's our full value: quick fixes. Firefighting. Smoothing out the rough edges. It also makes it even easier for the organization to keep understaffing our teams. Why would we add headcount if everything's covered?
____
