= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://rachelbythebay.com/w/2020/08/14/jobs/[We are a spectrum of jobs, not just one]

[quote]
____
This has become excruciatingly clear in the realm of reliability. Jobs are posted, people sign up, and then they find out that it's not actually based around what they think of as "engineering". It's actually just scurrying around, tidying up after vendor stuff.

I realize now that we need to label this properly. It's "`managed vendor stuff ops`", as a friend called it. When I read that off the window of my chat client a few minutes ago, it was like a bomb went off in my head. This is it! This explains so much!

It's VendorOps. You are hired to tend the vendor's stuff.

The mess we've all gotten into is thinking these are all the same job. They aren't! If you see them as different jobs, then you quickly realize that comparing the abilities of people in one vs. the other is folly. It's an apples and oranges situation: they aren't based around the same things.

The problem is that people think it's the same job. It's not!
____
