= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://www.devever.net/~hl/stringtemplates[Producing HTML using string templates has always been the wrong solution]

[quote]
____
There are broadly two approaches used to generate (X)HTML in web
applications today:

* string templating systems;
* AST-based representation, transformation and serialization;

Historically, the majority of server-side web applications have tended
to produce HTML output using string templating systems. String template
approaches remain vastly more popular than AST-based approaches.

This is unfortunate, as I've come to the conclusion for some years now
that the use of string templating systems to generate HTML is
fundamentally the wrong approach.
____


== link:https://hachyderm.io/@stargirl/109697057391904145[So you want to solve Python packaging: a practical guide]

[quote]
____
Fundamentally these users do not want to think about this shit, and they're a _huge_ group of users. You know who does think about this shit? Web developers, and every time someone comes along with "Python packaging sucks and someone should fix it" they're a web dev.

That's because web devs have different expectations. They _expect_ to work with a packaging tool. They expect to find and install dependencies. They don't expect to work with a ton of native dependencies. They don't have the same problems.
____

== link:https://css-tricks.com/the-great-divide/[The great divide]

[quote]
____
The divide is between people who self-identify as a (or have the job title of) front-end developer, yet have divergent skill sets.

_On one side_, an army of developers whose interests, responsibilities, and skillsets are heavily revolved around JavaScript.

_On the other_, an army of developers whose interests, responsibilities, and skillsets are focused on other areas of the front end, like HTML, CSS, design, 
____
