= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://normadesign.it/en/log/nothing-special/[Nothing special]

[quote]
____
An essay about how buying a table is impossible, and why we should all stop wanting to be "`designers`".
____

== link:https://libbymarrs.net/post-authentic-sincerity/[Post-authentic sincerity]

[quote
____
A truly post-authentic sincere attitude is synonymous with "`normcore`", as originally defined in K-HOLE’s trend report Youth Mode, a timely and groundbreaking publication released in 2013 as the last embers of Hipsterism were fading.To crudely summarize highlights of the analysis: The opposite of mass authenticity-seeking, which they name "`Mass Indie`", is the normcore attitude. The normcore derives value from popularity and recognition, not scarcity. The pursuit of uniqueness is devalued; dynamicism and flexibility are more important than originality, because originality itself is unattainable. One of the first declarations in the publication is "`Normcore is about adaptability, not exclusivity`". Adaptability is the key characteristic of the normcore attitude, the true post-authentic attitude.
____
