= Links - Soon
Julien Kirch
v1.0, 2021-01-01
:article_lang: en
:figure-caption!:
:article_description:

== link:https://logicmag.io/distribution/the-access-doctrine/[The access doctrine]

[quote]
____
The access doctrine decrees that the problem of poverty can be solved through the provision of new technologies and technical skills, giving those left out of the information economy the chance to catch up and compete.

Like other forms of political common sense, the access doctrine mixes factual claims with ideological ones. It is clear, for example, that finding a job without an internet connection and a PC is difficult—just try filling out an application to work for CVS, let alone using USAJobs, on your phone. It is less clear that there are plenty of good tech jobs out there, just not enough coders to fill them. Economic reality is more complicated than political slogans might admit. Getting online and learning to code won't change the rest of the labor market by itself. 
____

[quote]
____
The skills-gap narrative shifts the responsibility for training away from business owners and toward young individuals at the beginning of their working lives, as well as toward the public institutions that train them: universities, community colleges, and local and state governments. As management researcher Peter Cappelli has shown, what little evidence we have suggests that employers today devote very little time to on-the-job training relative to the postwar "`golden era`" of long-term, single-firm employment. 
____
