= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://snarfed.org/2023-03-24_49619-2[Content negotiation considered harmful]

[quote]
____
* Most web developers are not aware that conneg exists. This is usually
fine, since it's uncommon, but can be an unpleasant surprise when they
first hit it and don't understand it.
* The `Accept` header is notoriously complicated to parse, generate, and
fully comply with. Imo much of that complexity is unneeded in practice.
* It often breaks caching when it's first introduced. Internal and
external caches generally ignore Content-Type and Accept (etc) by
default, so when conneg is first introduced, clients often get the wrong
response type. Developers learn the hard way that they need to add
Accept to Vary and to their framework's cache.
* URLs leak across contexts. They may start out within a single service
or API, but they gradually proliferate into user-visible links, object
identifiers in other systems, add-on services, third party tools, etc.
These generally don't know the original conneg requirements, which
causes unpleasant surprises.
____

== link:https://norasandler.com/2017/11/29/Write-a-Compiler.html[Writing a C Compiler, Part 1]

[quote]
____
This is the first post in a series on writing your own C compiler. Here
are some reasons to write a compiler:

. You'll learn about abstract syntax trees (ASTs) and how programs can
represent and manipulate other programs. Handy for working with linters,
static analyzers, and metaprogramming of all sorts.
. You'll learn about assembly, calling conventions, and all the gritty,
low-level details of how computers, like, do stuff.
. It seems like an impossibly hard project (but isn't!), so writing one
will make you feel like a badass.
____

== link:https://blog.glyph.im/2023/03/incompetent-but-nice-response.html[A response to Jacob Kaplan-Moss’s “Incompetent but nice”]

[quote]
____
What can managers do about employees who are easy to work with, and are
trying their best, but can't seem to get the job done?
____
