= Links - Soon
Julien Kirch
v1.0, 2024-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://utcc.utoronto.ca/~cks/space/blog/tech/OpenSourceCultureAndPublicWork[Open source culture and the valorization of public work]

[quote]
____
This view runs deep in open source culture, which valorizes public work even at the cost of stress and time. Open source culture on the one hand tacitly assumes that everyone has those available, and on the other hand assumes that if you don't do public work (for whatever reason) that you are less virtuous or not virtuous at all. To be a virtuous person in open source is to contribute publicly at the cost of your time, energy, stress, and perhaps money, and to not do so is to not be virtuous (sometimes this is phrased as "`not being dedicated enough`").

(Often the most virtuous public contribution is "`code`", so people who don't program are already intrinsically not entirely virtuous and lesser no matter what they do.)

Open source culture has some reason to praise and value "`doing work that scales`", public work; if this work does not get done, nothing happens. But it also has a tendency to demand that everyone do it and to judge them harshly when they don't. This is the meta-cultural issue behind things like link:https://utcc.utoronto.ca/~cks/space/blog/tech/BugReportExperienceObligation[the cultural expectations that people will file bug reports], often no matter what the bug reporting environment is like or if filing bug reports does any good (link:https://utcc.utoronto.ca/~cks/space/blog/tech/BugReportBenefit[cf]).

I feel that this view is dangerous for various reasons, including because it blinds people to other explanations for a lack of public contributions. If you can say "`people are not contributing because they're not virtuous`" (or not dedicated, or not serious), then you don't have to take a cold, hard look at what else might be getting in the way of contributions. Sometimes such a cold hard look might turn up rather uncomfortable things to think about.
____
