= Links - Soon
Julien Kirch
v1.0, 2021-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://www.geepawhill.org/2021/04/27/on-agile-methods/[On agile methods]

[quote]
____
No current "Agile" method can create high-performing software development teams.

I don't endorse any of them. I don't sell them. I don't coach them. I actively advocate against adopting them.

I said I wasn't ready yet to propose a positive view, and I'm not. But.

I can tell you what things I will demand of any future method before I even consider embracing it.

. It must focus explicitly on the development of what I have called community -- active, dynamic, mutually beneficial, and healthy relationships between human beings.
. It must describe multi-option multi-variant multi-step paths from a number of "`heres`" to the "`there`" it proposes.
. It must address causation as multi-source, multi-effect, multi-directional and multi-layer, rather than the naive mechanical models with their single causes always arising in single directions from a single "`above`".

I won't accept less than that, and I will most likely want more, much more. I would hope that the whole trade would join me in this.
____
