= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://blog.jim-nielsen.com/2023/user-feedback/[User feedback]

[quote]
____
It made me think of the different kinds of software I use and how I am willing to deal with difficult, obtuse software if it means I can get the thing I ultimately want which is often beyond the software itself. The software is often merely a means to an end.

For example, booking a flight. If there is only one flight in and out of a specific area with a specific airline, and that flight will save me time and energy and headache, I will do whatever it takes to buy that flight, no matter how crappy the website.

Or, as another example, sometimes I’ll look for something very specific online and I’ll search and search and search until I finally find it from some obscure website run by a ma and pa shop whose fulfillment system happens through individual email correspondence. Convenience falls by the wayside in contexts of scarcity.

And this idea was reiterated to us through our users. It allowed us the opportunity to rethink the kinds of projects we took on, to ask ourselves: "`Is our time really best spent making this GUI wizard one step shorter? Or would we be better off doing something else for our users? Perhaps even something not software related?`" It was often the latter.
____

[quote]
____
As we delved further into their responses, we often found they would be much happier using things in their current state with just a few minor UI adjustments (rather than an entire UI refactor). Small quality of life fixes. And with the time we saved not building what we had showed them, they suggested we talk to the people in department X, Y, or Z and help them fix the processes which were causing them real pain.
____

== link:https://ieeexplore.ieee.org/document/8543381[BP: formal proofs, the fine print and side effects]

[quote]
____
Here we discuss, with the aid of a set of Venn diagrams, possible relationships between these kinds of side effects on the system induced by the proof, on the one hand, and _those that improve the system’s security by stopping real-world attacks_, on the other. At first glance one might reasonably expect the set of effects on the system induced by the proof to _necessarily_ improve the system’s resilience to real-world attacks. As we will argue, this position is far from clear.
____

[quote]
____
The area of P that doesn’t intersect A accounts for changes made for the sake of the proof that do not stop real-world attacks. These changes are side effects of the proof that don’t actually lead to a real-world improvement of security. Instead they might impose performance penalties, or restrict functionality. If the number of such changes required for a proof is large, one might reasonably question the additional cost imposed on the system _by the proof process itself_.
____

[quote]
____
As noted, a common form of side effect of formal verifi- cation is _deployment constraints_ imposed on a system, e.g., to reflect environmental assumptions encoded in the formal proofs or the model over which they are carried out. Often these restrictions are sensible and arguably enhance security in many scenarios. Yet for other reasonable threat models the restrictions might be overkill.
____
