= Links - Soon
Julien Kirch
v1.0, 2021-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:http://okmij.org/ftp/Algorithms/grasping-all-apples-at-once.html[Grasping `all-the-apples-at-once']

[quote]
____
A comment cited earlier hits the nail on the head: to describe an algorithm, one needs vocabulary. A large part of programming is building -- learning or constructing -- vocabulary to talk about common (sub)problems, e.g., run-length-encoding, groupBy, mapping, accumulating, filtering, etc. Learning, finding and naming the "`right`" abstractions is the core mathematical activity -- as explicated in the "`Notation as a tool of thought`".

A natural language is also a tool of thought. Building vocabulary and understanding when and how to use a particular word is the hardest part of learning a language. That natural and formal languages have a lot in common is the idea with a long pedigree -- famously and forcefully articulated by Montague in 1970s. Keith Smillie, in his paper about array languages cited earlierfootnote:[Keith Smillie: "`My Life with Array Languages`". October 2005] further argues that teaching programming ought to adapt the best ideas of teaching foreign languages.

Both in programming and natural languages, one can acquire basics relatively quickly. Fluency takes decades. There doesn't seem to be anything better than constant practice, speaking and listening, writing and rewriting. 
____

== link:https://software.rajivprab.com/2021/07/11/the-law-of-net-design-costs/[The Law of Net Design Costs]

[quote]
____
No Substitute for Judgement

It is very tempting to cling to catchphrases or cargo-culted best practices. They promise a simple and universal answer, without the need for messy judgement calls. To their credit, aphorisms like YAGNI are very useful as a way to curb our tendency to overengineer things. And popular best practices from larger companies help make us aware of the problems we may run into in future, and how we can solve them. But when it comes time to make an actual decision for your project, these general suggestions will need to be adapted to fit your specific circumstances.

There will arise occasions when you will have to choose between planning ahead, or doing the simplest possible thing today. When such dilemmas arise, take the time to think through the long-term consequences of your decision… as well as the likelihood of those consequences actually materializing. There is ample role for judgement and experience in making the right decision.
____

== link:https://www.jpattonassociates.com/mindset-that-kills-product-thinking/[The Mindset That Kills Product Thinking]

[quote]
____
The biggest missing value statement in the agile manifesto is:

Successful outcomes over efficient delivery
Just like the manifesto, the thing on the right is valuable. In fact it’s necessary. But, the thing on the left matters more.
____