= Links - Soon
Julien Kirch
v1.0, 2024-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://cohost.org/bruno/post/5322687-the-more-proficient[Tool proficiency]

[quote]
____
A particular thing that these old customizable GUIs were good for -- still seen in a lot of professional software, eg Photoshop -- was just hiding irrelevant affordances. Not everything needs to be visible or accessible by default; some features have niche uses, users have different levels of engagement and proficiency. You could go into the menu and toggle aspects of the UI on or off depending on whether you used them.

Discord doesn't give itself the affordances to selectively veil parts of its UI, and as a result _every_ user sees _every_ change to _every_ feature. Often a change that is welcomed by the users who embrace a given feature appears as just a pointless alteration for the users who don't use the feature. This, again, contributes to the sense of instability.
____

== link:https://yosefk.com/blog/managers-have-no-human-rights.html[Managers have no human rights]

[quote]
____
Here are some thoughts which are often basically correct:

* Every time I try to do the right thing here, it's like the place actively resists it. Actually, forget "`the right thing`" -- it's whenever I try to do pretty much _anything_.
* Yesterday's "strategic" thing I toiled over just got tossed into the dumpster. And they expect me to be all excited about the new "strategy" they coughed up?
* My "`colleagues`" attack me overtly and covertly all the time, all the while maintaining a "`professional`" and even cheerful demeanor -- in effect, a gaslighting tactic. And in this sewage lagoon, I'm supposed to get work done?
* The deadline is impossible, and everybody knows it. Why are we all pretending that we're trying to meet it, when we're actually busy rehearsing our speeches blaming the inevitable failure on each other?
____

== link:https://www.cookiecookiecookie.com[Cookie cookie cookie]

[quote]
____
We use cookies to ensure you get the best experience on our website. If you continue to use this site we will assume that you like cookies. Everybody likes cookies.
____

== link:https://www.softwaremaxims.com/blog/economics-developer-tools[The economics of developer tooling]

[quote]
____
On the other hand, you have larger organizations that invested heavily in their developer tooling. Google, Facebook, LinkedIn, Microsoft themselves, and Bloomberg, are examples brought up regularly. The world outside these giant organizations have benefited from this multiple time. But there is also a reality that the context and needs of these organizations may simply not be the same as the one of the rest of the world. The maintainer of a FOSS fundamental library, which is a 30-year-old codebase, with a few hours per week maximum to spend on it, has fairly different needs from the member of the Start Menu team at Microsoft.
____

[quote]
____
The impact of this landscape is that even if some organizations had the money to invest into better DX for the FOSS maintainer and could accept to wait for a few years to see a return on investment… There is a knowledge and skill gap. For the past 30 years, the only people that developed that skill were in extreme niches, already flooded with demand and work in their chosen domain, or working in a context that does not match the needs of the general developer population. The industry of developer tooling for small organizations, small teams, and FOSS does not exist. This means that the techniques needed to conduct user research, define needs and requirements, port an academic prototype and ideas to a usable tool, and then iterate on it with users feedback need to be rediscovered every time one of these projects manages to happen. There is a really limited amount of institutional knowledge about these.
____

== link:https://www.softwaremaxims.com/blog/open-source-hobbyists-turf[You are all on the hobbyists maintainers' turf now]

[quote]
____
You are the one that depends on us. You do not know the rules. You do not know the systems. You do not understand its sharp edges. You need us. You need the 60%. Everyone in this world now depends, one way or another, on us.

And we know that. And we are terrified of this. Because we know how broken it is. How fragile. That I could wake up tomorrow and discover that the whole world is on fire because of my code. We don't like it, trust us.

We are not shunning responsibilities. If we did _we would not keep the world running_. Respect our work, please. But yes. We need help. We want help. We want you here to help us.

What we ask you, while we are growing the part that we maintain for all of you, because yes, that percentage is growing every year, is to start by understanding us. We want your help, but it needs to be helpful. Otherwise, it is just more stuff we need to handle in 1h per month, on top of keeping the world running.
____
