= Links - Soon
Julien Kirch
v1.0, 2021-01-01
:article_lang: en
:figure-caption!:
:article_description:

== link:https://twitter.com/fakebaldur/status/1473612527313506305?s=21[Trauma & growth]

[quote]
____
I don’t know who needs to hear this but in case it’s one of you: trauma and developing mechanisms to cope with trauma isn’t growth. Anybody telling you that you need to join a traumatic environment or workplace to grow in your job or as a person is doing you a huge disservice.
____

== link:https://github.com/nodegui/nodegui[A library for building cross-platform native desktop applications with Node.js and CSS]

[quote]
____
Build performant, native and cross-platform desktop applications with Node.js and CSS like styling.

NodeGUI is powered by Qt5 which makes it CPU and memory efficient as compared to other chromium based solutions like Electron.
____

== link:https://advancedweb.hu/a-categorized-list-of-all-java-and-jvm-features-since-jdk-8-to-17/[A categorized list of all Java and JVM features since JDK 8 to 17]

== link:https://devblogs.microsoft.com/oldnewthing/20211229-00/?p=106061[You can’t copy code with memcpy; code is more complicated than that]

[quote]
____
The idea is that they want to inject some code into a target process, so they use `Virtual­Alloc` to allocate some memory in that process. The first part of the memory block contains some data that they want to pass. The second part of the memory block contains the code bytes that they want to execute, and they tell `Create­Remote­Thread` execution at those code bytes.

I’m just going to say it right now: The entire idea that went into this code is fundamentally flawed.
____

== link:https://apenwarr.ca/log/20211229[The gift of it's your problem now]

[quote]
____
Here's the thing about gifts: the sender chooses them, not the recipient. We can have norms around what gifts are appropriate, and agreements to not over-spend, and wishlists, and so on. But I won't always get the exact gift I want. Sometimes I didn't even want a gift. Sometimes the gift interprets JNDI strings in my log messages and executes random code from my LDAP server. This is the nature of gifts.
____

[quote]
____
Many developers and companies have been disappointed to learn that just uploading your code to GitHub doesn't make a community of developers appear. (It does make it more likely that AWS will fork your product and make more money from it than you do.)
____
