= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://www.tedinski.com/2019/02/27/end-to-end-principle.html[The end-to-end principle in distributed systems]

[quote]
____
In the figure above, we have a typical "`accidental database`" scenario. The trouble is that the system (consisting of a server and its backing database, together) has effectively become a database on its own.
____

[quote]
____
Everybody just loves to accidentally start implementing a database, and it’s always just queues isn’t it?
____

== link:https://www.tedinski.com/2018/10/02/two-sides-to-every-coin.html[The insides and outsides of abstractions]

[quote]
____
There’s a long tradition of believing that you can bring non-programmers in to do programming if only X wasn’t standing in the way, whatever X is. This has never worked. The one place it has ever had the appearance of working is spreadsheets. But spreadsheets are really just _also programming_, and we just don’t really give them the credit they deserve. Spreadsheets are a friendly way to dip your toe into (yes, real) programming. But a lot of these other kinds of tools seem to think it’s syntax that’s the problem, and it’s not. You have to think abstractly and be able to write, test, and debug code. Programming is programming, regardless of syntax.
____
