= Links - Soon
Julien Kirch
v1.0, 2022-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://gankra.github.io/blah/deinitialize-me-maybe/[Destroy all values: designing deinitialization in programming languages]

[quote]
____
The nasty thing with programming languages is that good design is often a _holistic_ property. Certain features only make sense in the presence (or absence!) of other features. We're going to be exploring a lot of different concepts in this post, and it's important to keep in mind that they don't work in a vacuum. They solve specific problems caused by solutions to _other_ specific problems, caused by solutions to **other other** problems.
____

== link:https://logicmag.io/beacons/[Holding to account: Safiya Umoja Noble and Meredith Whittaker on duties of care and resistance to big tech]

[quote]
____
One thing we rarely discuss is how AI research and development's dependence on corporate resources worked -- and continues to work -- to shape and in some cases co-opt knowledge production. In other words, to "`do AI`" as defined in the current "`bigger is better`" paradigm, you increasingly need resources that are controlled by these handful of companies. You need access to really expensive cloud compute, you need access to data that is hard and sometimes impossible to get. You can't just go to the data market and buy it -- you often need to get access from the data's creators or collectors, who are often the tech companies. It's fair to say that academic computer science disciplines underwent a kind of soft-capture, in which as a condition of doing "`cutting edge`" AI research, over the last decade they became increasingly dependent on corporate resources, and corporate largesse.

This dynamic led to practices like dual affiliation, where professors work at a tech company but have a professorial title and produce research under their university affiliation. It's led to tech companies moving whole corporate labs into the middle of universities -- like Amazon's machine vision lab at Caltech. We have a structural imbrication between a massive, consolidated industry and knowledge production about what that industry does. And this compromised entanglement has bled into the fairness and ethics space, in many cases without anyone commenting on it. There are many forces working against our recognition of how captured the technical disciplines are at this time, and how easy it is for them to extend this capture into fairness, ethics, and other disciplinary pursuits focused on the consequences and politics of tech.
____

==link:https://www.baldurbjarnason.com/2022/i-cant-keep-up-with-web-dev/[How to keep up with web development without falling into despair]

[quote]
____
People say that web development is unique because of the fast pace and volume of changes in the field. And, since most of us have at least a tangential awareness of other fields through our friends and families (and, in my case, former fields of study), we know that web development seems unique in invoking this feeling of _helplessness_.
____

== link:https://urbanpolicy.net/wp-content/uploads/2015/06/Rittel-Webber_1973_DilemmasInAGeneralTheoryOfPlanning.pdf[Dilemmas in a General Theory of Planning]

[quote]
____
During the industrial age, the idea of planning, in common with the idea of professionalism, was dominated by the pervasive idea of _efficiency_. Drawn from 18th century physics, classical economics and the principle of least-means, efficiency was seen as a condition in which a specified task could be performed with low inputs of resources. That has been a powerful idea. It has long been the guiding concept of operations research; and it still pervades modern government and industry. When attached to the idea of planning, it became dominating there too. Planning was then seen as a process of designing problem-solutions that might be installed and operated cheaply. Because it was fairly easy to get consensus on the nature of problems during the early industrial period, the task could be assigned to the technically skilled, who in turn could be trusted to accomplish the simplified end-in-view.
____

[quote]
____
For any given tame problem, an exhaustive formulation can be stated containing all the information the problem-solver needs for understanding and solving the problem -- provided he knows his "`art`", of course.

This is not possible with wicked-problems. The information needed to _understand_ the problem depends upon one’s idea for _solving_ it. That is to say: in order to _describe_ a wicked-problem in sufficient detail, one has to develop an exhaustive inventory of all conceivable _solutions_ ahead of time. The reason is that every question asking for additional information depends upon the understanding of the problem -- and its resolutions -- at the same time. Problem understanding and problem resolution are concomitant to each other. Therefore, in order to anticipate all questions (in order to anticipate all information required for resolution ahead of time), knowledge of all conceivable solutions is required.
____

[quote]
____
The classical systems-approach of the military and the space programs is based on the assumption that a planning project can be organized into distinct phases. Every textbook of systems engineering starts with an enumeration of these phases "`understand the problems or the mission`", "`gather information`", "`analyze information`", "`synthesize information and wait for the creative leap`", "`work out solution`", or the like. For wicked problems, however, this type of scheme does not work. One cannot understand the problem without knowing about its context, one cannot meaningfully search for information without the orientation of a solution concept, one cannot first understand, then solve. The systems-approach "`of the first generation`" is inadequate for dealing with wicked problems. Approaches of the "`second generation`" should be based on a model of planning as an argumentative process in the course of which an image of the problem and of the solution emerges gradually among the participants, as a product of incessant judgment, subjected to critical argument. The methods of Operations Research play a prominent role in the systems-approach of the first generation, they become operational, however, only _after_ the most important decisions have been made, i.e. after the problem has already been tamed.
____

[quote]
____
In the sciences and in fields like mathematics, chess, puzzle-solving or mechanical engineering design, the problem-solver can try various runs without penalty. Whatever his outcome on these individual experimental runs, it doesn’t matter much to the subject-system or to the course of societal affairs. A lost chess game is seldom consequential for other chess games or for non-chess-players.

With wicked planning problems, however, _every_ implemented solution is consequential. It leaves "`traces`" that cannot be undone. One cannot build a freeway to see how it works, and then easily correct it after unsatisfactory performance. Large public-works are effectively irreversible, and the consequences they generate have long half-lives. Many people’s lives will have been irreversibly influenced, and large amounts of money will have been spent -- another irreversible act. The same happens with virtually all public-service programs. The effects of an experimental curriculum will follow the pupils into their adult lives.

Whenever actions are effectively irreversible and whenever the half-lives of the consequences are long, _every trial counts_. And every attempt to reverse a decision or to correct for the undesired consequences poses another set of wicked problems, which are in turn subject to the same dilemmas.
____
