= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://surma.dev/things/ditherpunk/[Ditherpunk -- The article I wish I had about monochrome image dithering]

[quote]
____
I always loved the visual aesthetic of dithering but never knew how it’s done. So I did some research. This article may contain traces of nostalgia and none of Lena.
____


== link:https://www.devever.net/~hl/pics[Memoirs from the old web: IE's crazy content rating system]

[quote]
____
Today, Internet Explorer has been consigned to the dustbin of history,
yet its quirks and peculiar features remain an interesting area of
discussion from a historical perspective. There was one particular
feature of IE which not only now seems comically naive, but also
completely impractical: namely, IE tried to pioneer a system of content
rating.

This was essentially a standardised "`parental controls`" system. The idea
was that a webpage could be rated in terms of the profanity, nudity,
sex, violence, etc. that it contained.
____
