= Links - Soon
Julien Kirch
v1.0, 2024-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://www.patreon.com/posts/97024525?utm_campaign=postshare_fan[LTP #1: Something in the dirt (2022)]

[quote]
____
When someone experiences something unnatural, when the world behaves in ways they're told it does not, it freaks people out. There are traumatic elements to it and people's lives can be upended. Some people try to rationalize it, never to acknowledge it again. But there are many people are driven by the need to validate their experience. Lone seekers often believe they are looking for proof but really what they are looking for is a way to make sense of a world that they no longer recognize. There is a sprawling effect to this, where a person's pattern seeking facilities have the power to impose themselves on one's reality. More than ever, its obvious that we make our own worlds that we want to live in. 
____

[quote]
____
The more you dig, the more you find, but what you find may distract you from what you were looking for in the first place. If there is anything to learn from this film, it's that you can't let your ego get in the way. It's possible for the things you lack to consume you because mere promise of answers implies that those holes can be filled. The investigator who survives the paranormal is the one who has fun with it. Who can approach the hunt with a sense of playfulness and unpredictability.
____
