= Links - Soon
Julien Kirch
v1.0, 2022-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://glazkov.com/2022/02/23/the-cost-of-opinion/[The cost of opinion]

[quote]
____
Frameworks and libraries are like layers, +
and these layers accrete.

Every layer has a vector of intention, +
pointing toward some idealized value to users, +
determined by the author of the layer.

Opinion, +
or the difference +
between the vectors of intention of two adjacent layers, +
always comes at a cost.

Opinion costs compound +
and are, directly or indirectly, +
shouldered by users.
____

== link:https://pluralistic.net/2022/08/21/great-taylors-ghost/[Pluralistic: 21 Aug 2022 the shitty technology adoption curve reaches apogee]

[quote]
____
If you want to do something terrible with technology, you can't just
roll it out on people with money and social capital. They'll complain
and your idea will tank. Successful shitty tech rollouts start with
people you can abuse with impunity (prisoners, kids, migrants, etc) and
then work their way up the privilege gradient. I call it the Shitty
Technology Adoption Curve.

The point of the Shitty Technology Adoption Curve is to normalize
technological oppression, one group at a time. 20 years ago, if you were
eating your dinner under the unblinking eye of a video-camera, it was
because you were in a supermax prison. Now, thanks to "`luxury
surveillance`", you can get the same experience in your middle-class home
with your Google, Apple or Amazon "smart" camera. Those cameras climbed
the curve, going from prisons to schools to workplaces to homes.
____

== link:https://rambling.malignat.us/2022-08-27/lowstakes-and-highstakes-metrics[Low-stakes and high-stakes metrics]

[quote]
____
I believe it's best explained by looking at the stakes attached to
metrics, and more generally the culture around what these numbers
represent.

When metrics are low stakes, when they stay inside the team, they are
beneficial. They are instituted, monitored, and acted upon by the people
that are subject to them. This is the _Diagnostic_ or _Improvement
Paradigm_.

On the other side, where stakes for the metrics are high, there is the
_Accountability Paradigm_. Here, measures and metrics are not
necessarily for improvement or finding issues, they are for making sure
that people do what they are supposed to. The fundamental purpose of
capturing the numbers is for accountability, and
"`transparency`".
____
