= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://cutlefish.substack.com/p/tbm-242-the-simplicity-fetish[TBM 242: The Simplicity Fetish]

[quote]
____
In both stories, we find an "`impedance mismatch`" between the complexity of the problem and the systems or time allocated to solve them. No matter how hard we try, we cannot bend a problem or situation requiring nuanced communication into a purely transactional, stable, and unchanging problem. The harder we try to do that (or the more we are forced by our environment, incentives, skills, etc.), the harder it becomes to find a way forward. What might have been difficult but within reach now becomes intractable. 

Try as we might -- and as uncomfortable as this makes driven managers leaders -- we can't cheat the physics of complex, socio-technical systems. We can "`dance`" with the system, but we can't bend the system to our will (thank you, Donella Meadows). 
____

[quote]
____
In a sense, impedance mismatches, where we experience efforts at summarization and simplification that break things, are signals that something needs changing. It isn't realistic to firehose information everywhere, but at the same time, it isn't helpful to try to crunch it down beyond recognition.

You need effective interfaces acknowledging that localized complexity—dynamic and vibrant collaboration and communication—can be highly beneficial, and "`simple`" messages between parts of the system are necessary. But you can't, unfortunately, cheat physics and solve the problem of leaking complexity with oversimplification—no matter how much we fetishize simplicity.

This is one of the big work problems we need to solve in the "modern workplace." The level of information load and "`information process`" is incredibly draining and saps creativity and outcomes. 
____
