= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://blog.cloudflare.com/the-state-of-http-in-2022/[The state of HTTP in 2022]

[quote]
____
So what happened at all of those working group meetings, specification documents, and side events in 2022? What are implementers and deployers of the web’s protocol doing? And what’s coming next?
____


== link:https://www.softwaremaxims.com/blog/not-a-supplier[I am not a supplier]

[quote]
____
What it means is that there is no supply chain here. Because there is no
supplier. I am not providing you something that you bought from me.
There is no relationship. I put something online because I wanted to.
The fact you made your product depend on it is _your responsibility_.
Not mine. Not the one of the providers. We provide libraries. We do not
supply them. You cannot apply rules to me.
____

== link:https://www.cambridge.org/core/journals/economics-and-philosophy/article/marketplace-of-rationalizations/41FB096344BD344908C7C992D0C0C0DC[The marketplace of rationalizations]

[quote]
____
A widespread demand for rationalizations creates an opportunity to profit from producing and selling them. Rationalization producers are those who seize this opportunity and devote time, energy, and other resources to producing information useful for justifying beliefs that people want to hold for non-epistemic reasons. As with other cases, such attempts at satisfying consumer demand should be viewed through the lens of competition: from the perspective of consumers, it is beneficial to shop around for the highest quality rationalizations provided at the lowest price, which means that producers will be able to sell their rationalizations only if they produce and sell rationalizations with these characteristics. One should thus expect rationalization markets to involve the resource-efficient effects of competition, including the delegation of production to those for whom it is most profitable to produce, the consequent division and specialization of labour, and the selection for high-quality, low-cost goods.
____
