= Links - Soon
Julien Kirch
v1.0, 2021-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://arcove.substack.com/p/null-call[Null Call]

[quote]
____
No matter how hard you try to perceive a leaf on a tree, your eyeballs are only sending extremely noisy sensory data to your brain. Your subconscious mind creates a _mental model_ of what is happening, and continuously updates it. It needs to filter, smooth, and distort the new incoming sensory information to fit the model, so that your conscious mind is able to make sense of it. If you see something that violates your mental models too extremely, it literally becomes the case that you _can’t believe your eyes_, and you are left stumbling around, Velma-like, in search of a new mental model of the situation.

Through a handy invention called "`language`", human beings are able to share mental models with each other. These models are on a continuum from "`metaphorical`" (as in stories, myths) to “literal” (as in folk theories, scientific hypotheses). These shared mental models all come together to form a _worldview_, which is at the heart of what we call "`culture`". This allows the tribe to understand the world and each other.

The _shaman_’s job, then, is to:

. Understand the tribe’s existing mental models
. Update shared mental models over time to reflect the changing environment and evolving needs of the tribe
. When _spooky shit_ starts happening that falls outside of the "`shared reality operating system`", it is the shaman’s role to _debug_.
____

== link:https://scattered-thoughts.net/writing/moving-faster/[Moving faster]

[quote]
____
I used to spend a lot of time thinking about how to split code up into files and directories based on what code 'belongs' together. But that's a completely vague criteria and also doesn't have any obvious connection to my actual goals. There are also usually multiple different axes along which things could be grouped eg a compiler could be split by pass, or by language features. So now I tend to put everything into one file until I start to notice difficulty navigating, and then I split out things that I've noticed I tend to read or edit at the same time. Unlike the previous criteria this is easy to evaluate by just remembering what I did and is easy to connect to my goals - it means less jumping around in future edits which will make coding and debugging slightly faster.
____
