= Links - Soon
Julien Kirch
v1.0, 2022-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://blog.lazerwalker.com/2020/10/22/virtual-events-and-game-design.html[Using game design to make virtual events more social]

[quote]
____
In games, we talk about the idea of the "`magic circle`", a boundary that
clearly delineates the space where a game or play takes place as
distinct from the normal world. Activities within the magic circle being
distinct from normal reality gives people freedom to express themselves
more freely and to, well, play (within reason and established safety
limits, of course).

A similar thing happens with in-person conferences. The event venue
(especially if in a destination location!) serves as a freeing liminal
space that helps attendees be present and engaged. Whether you're at a
conference to learn from the talks, to meet new people, or frankly to
just enjoy a free employer-paid vacation, the act of being in a
different physical place does a lot to get you in a mindset where you're
ready to embrace new experiences.

This is difficult for online events in the time of quarantine! If you're
like me, you're largely spending 40 hours a week sitting at home, using
Slack and Zoom or some other similar text and videoconferencing
software. Asking people to spend their weekends at their same computers
attending a Zoom conference with a Discord or Slack doesn't accomplish
that goal!

We realized that, even if our custom social space was otherwise a
complete and utter failure, the mere act of having it be a new and novel
space would still be valuable.
____

[quote]
____
Video chat is far more effective than audio chat at helping convey
emotional nuance, and audio chat is equally more effective than text
chat. This is important if our goal is to foster new friendships and
interesting connections!

But at this point in quarantine, we're all well aware of Zoom Fatigue.
It's clear that running an entire conference on video or audio chat is a
great way to burn everyone out.

As we spoke with potential attendees, we realized there are broadly two
types of online communicators: those who are happier communicating
online in text, and those who are happier using videochat to the extent
that they have the emotional energy. Finding a way to make both groups
of people feel comfortable and socially stimulated felt like a valuable
goal.

This led us to aim for an event where communication over text chat was
the default, but there were many opportunities for attendees to
consensually opt-in to escalate into audio or video chat. Being
primarily based in text chat lets attendees save up their emotional
energy for focused higher-quality moments of video conversation, and
grounding those moments in opt-in activities means that each individual
attendee can self-moderate how much video chat they can handle.

Our plan for video chat in the space was twofold: we planned to schedule
discrete blocks of time for video chat-based networking sessions, but
also offer lower-key videoconferencing in every room that people in that
room could join at any time.

For the former, we held unconferencing sessions where attendees could
propose and upvote discussion topics, which were then assigned to
specific rooms. We also intended to schedule breakout room-style
networking sessions (where you would be randomly moved into a videochat
with 3-5 random people for 10 minutes), but couldn't find room in our
final conference schedule. These are the two structures I've seen work
particularly well for structured video chat to avoid the anarchy and
fatigue of unstructured 30-person Zoom calls.
____

== link:https://blog.dbsmasher.com/2022/05/24/not-my-job.html[Not my job]

[quote]
____
I liken the work that goes under "`glue work`" to spackling paste that
ensures that all parts of the software delivery for the business is
happening smoothly.

However, that is not the same as saying "`as a senior leader, everything
is your job`". Gaps can happen in many shapes and sizes, and you need to
recognize when a gap needs more senior leadership attention instead of
trying to absorb them all. In those cases, you should be working on
properly communicating the gap and its risk to the business (and risk to
_which part_ of the business) and NOT attempting to solve everything.
Here are some examples of possible gaps that you should be _definitely_
saying "`this is not my job`" and instead communicating risk about:

* A team is severely understaffed, and their manager is not advocating
for them
* You are involved in planning with a part of the organization and can
see clear signs of a toxic work environment
* A critical part of the technical stack is a recurring source of
incidents and no one officially "`owns`" it in engineering.

You might exclaim, "`but I can't stay quiet!`", and I am not suggesting
you pretend you saw nothing. But be cognizant of what you can and cannot
control as someone who is in leadership without explicit authority over
teams. You owe it to the engineering managers of managers you work with
to communicate the gap, but you should not put it on yourself to try to
_resolve_ the problem without communication.
____
