= Links - Soon
Julien Kirch
v1.0, 2022-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://leaddev.com/career-paths-progression-promotion/secret-getting-staff-level-leverage[The secret to getting to the Staff+ level? Leverage.]

[quote]
____
Can you get big things done? Do people involve you in complex projects
because they trust you to make those projects successful?

The basic skill needed for execution leverage is project management.
Everyone needs to know how to do this at some level, and being extremely
good at it paired with strong technical skills can make you a powerhouse
individual contributor.

Beyond the nuts and bolts process stuff, the leverage you're developing
here is understanding how to organize the work to unearth risks early,
how to identify different possible approaches, and how to remain
flexible so that you can pull out a win from the project even if the
final outcome is quite different from the initial proposal. If you can
break a complex problem down into pieces that can be understood and
shared across people or teams, and turn an impossible project into a
concrete roadmap, you can show the kind of broad impact that drives
senior promotions.

Long-tenured engineers have some natural execution leverage because they
know where bodies are buried, but this is a slow path to career growth.
People discount the impact of long-tenured employees who can't explain
how their depth of understanding of the systems allows them to do things
that others can't, and are likely to think that the system needs to be
fixed instead of promoting the rare people who can work with it.
____
