= Links - Soon
Julien Kirch
v1.0, 2024-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://blog.jim-nielsen.com/2022/the-case-for-design-engineers/[The case for design engineers]

[quote]
____
The problem of innumerable artifacts helps show why design engineers are worth their weight in gold. They can bridge the chasm of design to browser engineering, skipping the need for 60+ artifacts. How? They have an understanding of the constraints of the medium, so from sketches to wireframe to high fidelity mocks, they only have to produce one or two artifacts while simultaneously keeping a picture in their head of how the elements of those designs flex and flow and change across different sizes. They can imagine how it works, so they don't have to articulate it for every iteration. There's no need to explicitly design and document all possible states for whoever is downstream of the designs because _they are the ones downstream of the designs_.
____

== link:https://blogs.oracle.com/linux/post/whats-inside-a-linux-kernel-core-dump[What's inside a Linux kernel core dump]

[quote]
____
But have you ever wondered what's really in a core dump? In this blog, we'll answer that question. We'll start by discussing the different software which can actually _produce_ a vmcore (there are more than you might think). Next, we'll discuss the contents of vmcores, including what important metadata needs to be present in order to make analysis possible. We'll then dive into the details of a few of the most prominent vmcore formats and variations on them, before finishing with a quick overview of some tools that can be used to analyze them.
____

== link:https://www.kmjn.org/notes/message_existence.html[This message does not exist]

[quote]
____
The act of discarding a message that does not exist must therefore do one of two things. It may cause the message contents to also cease to exist. Alternately, it might not affect the existence but only the accessibility of message contents. Perhaps they continue to exist, but discarding the message (which already did not exist) causes the _copy_ operation to cease being invokable on the message contents (even though they do continue to exist). The story of existence has many mysteries.
____

== link:https://bigmedium.com/ideas/a-global-design-system.html[A Global Design System]

[quote]
____
Right now, vast numbers of human beings are devoting their time and energy to designing, building, documenting, and maintaining the exact same set of common components. Accordions that open when a user clicks them. Accordions that -- you guessed it -- close when a user clicks them again. Datepickers that … pick dates. Tabs that switch panels when selected. link:https://bradfrost.com/blog/post/enforcing-accessibility-best-practices-with-automatically-generated-ids/[Form fields that associate labels with their respective inputs]. Alerts that communicate success, error, warning, and information status. Dialogs and tooltips and drawers oh my! By and large, _these components are unexceptional commodities that assume the same general shape and behavior_ regardless of whether the design system serves a non-profit, a federal agency, a bank, a publication, an e-commerce site, a Fortune 500 enterprise, a dog salon, a startup, SaaS company, you get the picture.

These basic UI components are tricky to get right. Looking across the World Wide Web, link:https://meiert.com/en/blog/html-conformance-2023/[zero of the top 100 websites use valid HTML], and our collective accessibility game is abysmal. The link:https://webaim.org/projects/million/[WebAIM Million project] crawls the top million websites and reliably delivers a depressing annual report about the state of website accessibility:
____

== link:https://qualitysafety.bmj.com/content/14/2/130["`Going solid`": a model of system dynamics and consequences for patient safety]

[quote]
____
In the past most healthcare delivery systems were loosely coupled—that is, activities and conditions in one part of the system had only limited effect on those elsewhere. Loose coupling allowed the system to buffer many conditions such as short term surges in demand. Modern management techniques and information systems have allowed facilities to reduce inefficiencies in operation. One side effect is the loss of buffers that previously accommodated demand surges. As a result, situations occur in which activities in one area of the hospital become critically dependent on seemingly insignificant events in seemingly distant areas. This tight coupling condition is called "`going solid`".
____

[quote]
____
Practitioners are familiar with "`bed crunch`" situations where a busy unit such as a surgical intensive care unit (ICU) becomes the operational bottleneck within a hospital. Other units in the hospital usually buffer the consequences of a localized bed crunch by absorbing workload, deferring transfers, etc. We have observed situations where an entire hospital is saturated with work, creating a system wide bed crunch. The result is a dramatic change in workplace operational characteristics that creates new demands for coordination of work across the facility and increases the stakes for practitioner decisions and actions.
____

[quote]
____
"`Going solid`" creates new work for practitioners and managers and new opportunities for failure. It increases the pressure to discharge patients, puts a premium on practitioner ability to identify candidates for discharge, and encourages them to speed the completion of care at each stage. The phenomenon involves the facility rather than a single unit. This leads managers to demand information about the conditions in each unit, further increasing the performance pressure. The situation encourages high management to try to control usually routine details of daily operations, bringing senior management into direct contact with practitioners. The clinical conditions of patients take on organizational and managerial significance and management/practitioner conflicts are common.
____

== link:https://command-not-found.com/[command-not-found.com]

[quote]
____
Install any command on any operating system and in Docker.
____

== link:https://lore.kernel.org/all/2024022103-municipal-filter-fb3f@gregkh/[Re: fs/bcachefs/]

[quote]
____
All of the current stable developers are busy handling other kernel developer issues or reviewing properly tagged kernel patches. Please wait for the next available developer, or press 0 to return to the main menu.

You are caller number SEVENTY FIVE in the queue with an expected wait time of ELEVEN HUNDRED AND TWENTY FIVE MINUTES.
____
