= Links - Soon
Julien Kirch
v1.0, 2022-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://www.baldurbjarnason.com/2022/first-principles/[Playacting genius: the performative logic of reasoning from first principles]

[quote]
____
The first confusion is that a lot of the time what they call "`reasoning
from first principles`" is more accurately "`being a fast learning
autodidact`". Going from zero to expertise in six months is not in any
real way discovering a field by reasoning from first principles. They've
just speedrun a field from a logical starting point. This is a major
accomplishment, one that is enormously useful in the right context, as
long as you are _aware_ that this is what you did.

Anybody can reason from first principles or _basic truths_ (if you are a
regressive Aristotelian intent on ignoring all progress in human thought
over the past two millennia). It's generally useless because for any
given field you just end up running into a series of ‘turkey' problems
on a compressed timeline without the benefit of history.
____

== link:https://twitter.com/etcandsoforth/status/1571164736422825984[Unsolicited advice]

[quote, attribution, cite title]
____
Was at a training once where the facilitator said "`Unsolicited advice is criticism. Always.`"

Half the room audibly gasped / objected.

The other half shouted a chorus of yes/thank you/ amen.

She offered no quarter to the "`just being helpful`" brigade. It was glorious.
____
