= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://medium.com/nice-work-from-active-voice/hey-designers-theyre-gaslighting-you-e02e5a4d9cff[Hey designers, they're gaslighting you.]

[quote]
____
Here are some statements I've heard one too many times in this cursed year:

* We need you to do more with less.
* Always be helpful. Never miss an opportunity to demonstrate value.
* You need to stretch across the full product surface area until we get more headcount.

This advice might sound reasonable on its face, but it doesn't work. Doing more with less doesn't give us power -- and it doesn't produce good design work, either. Instead, we get overloaded and overcommitted. We feel personally responsible for keeping all the plates in the air.

We also get shallow work -- because we're prioritizing juggling it all over doing anything really well. And you know what that does? It teaches our partners that that's our full value: quick fixes. Firefighting. Smoothing out the rough edges. It also makes it even easier for the organization to keep understaffing our teams. Why would we add headcount if everything's covered?
____

== link:https://lukeplant.me.uk/blog/posts/no-one-actually-wants-simplicity/[No one actually wants simplicity]

[quote]
____
A lot of developers want simplicity in the same way that a lot of clients claim they want a fast website. You respond "`OK, so we can remove some of these 17 Javascript trackers and other bloat that’s making your website horribly slow?`" -- no, apparently those are all critical business functionality.
____

== link:https://cohost.org/v21/post/3117267-a-few-things-on-this[A brief history of the corporate presentation]

[quote]
____
PowerPoint is a prime example of technology meaning that admin work is laid upon the knowledge worker directly, rather than handled by a web of others. And this is something I work towards, myself -- I am a strong believer in the power of making tools that mean that people can directly touch the thing they're shaping. But it also increases the workload on the knowledge worker -- the exec now has to think about colours, and formats, and templates & timing, not on the content of the presentation. And the people who previously were employed to think about colour and format and picking a nice stock photo are now… no longer employed? Or very rarely employed.
____

== link:https://www.robertgaskins.com/powerpoint-history/sweating-bullets/gaskins-sweating-bullets-webpdf-isbn-9780985142414.pdf[Notes about inventing PowerPoint]

[quote]
____
You would expect that it has always been obvious that PowerPoint was a good idea.
But Robert Gaskins, writing here from notes made at the time, describes how, for three years until the first product was completed, almost everyone (including potential investors) thought it was unpromising. Only relentless determination by the core group and a few visionary investors kept PowerPoint alive to succeed.
____

== link:https://cohost.org/xkeeper/post/3138786-maxims-to-live-by[maxims to live by]

[quote]
____
. The more confusing the error message, the better.
. If it doesn’t run under Windows, then it’s Windows’ fault.
. Detect Windows, and crash.
. Manuals are a waste of time.
. Words in boldface don’t count.
. Just because you’re a Windows application doesn’t mean that you have to be compatible with Windows.

…
____
