= Links - Soon
Julien Kirch
v1.0, 2024-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://gpanders.com/blog/state-of-the-terminal/[State of the Terminal]

[quote]
____
In this article, we'll discuss some of the problems that terminal based applications have historically had to deal with (and what the modern solutions are) as well as some features that modern terminal emulators support that you may not be aware of.
____

== link:https://bonesmoses.org/2024/pg-phriday-redefining-postgres-high-availability/[PG Phriday: redefining Postgres high availability]

[quote]
____
What is High Availability to Postgres? I've staked my career on the answer to that question since I first presented an HA stack to link:https://bonesmoses.org/presentations/ha_postgres.pdf[Postgres Open in 2012], and I _still_ don't feel like there's an acceptable answer. No matter how the HA techniques have advanced since then, there's always been a nagging suspicion in my mind that something is missing.

But I'm here to say that a bit of research has uncovered an approach that many different Postgres cloud vendors appear to be converging upon. Postgres is about to be transformed into something few of us could have possibly imagined, and I think I see the end goal.
____

== link:https://ludic.mataroa.blog/blog/the-violent-role-of-relentless-positivity-in-the-workplace/[The violence of relentless positivity in the workplace]

[quote]
____
The relentless demand for employees to express themselves in ways that are necessarily inadequate for affecting organizational change, implicating others in unacceptable behavior, and voicing authenticity is, to my eyes, nothing short of a form of violence. I'd certainly take it over having someone work my kneecaps over with a lead pipe, but I assure you that vulnerable people have absolutely been harmed by this over extended periods of time.
____

== link:https://johan.hal.se/wrote/2024/03/05/churn/[Churn]

[quote]
____
The main reason Web Components aren't going to save you from the JS treadmill, however, is that the JS treadmill is first and foremost a _cultural product_.
____

== link:https://buttondown.email/hillelwayne/archive/what-mob-programming-is-bad-at/[What Mob Programming is Bad At]

[quote]
____
Proponents of pairing/mobbing attribute all sorts of benefits to it: higher quality code, more shared ownership, no more need for code review, even (in the most extreme claims) eliminating bugs entirely. Naysayers claim it slows team velocity down, is emotionally exhausting, and only works with very particular personalities. To which the advocates respond that if mobbing doesn't work, it's a problem with _your company culture_.

And things kind of go in circles from there, because you can't _go anywhere_ from "`it's a problem with the culture`". I've made this same mistake in the past too! "`Company culture`" is the "`wizard did it`" of software techniques: you can explain the success or failure of _anything_ with "`culture`". If you think the only possible problem with your $THING is "bad culture", then you're saying $THING doesn't have any problems, which means it's snake oil.
____
