= Links - Soon
Julien Kirch
v1.0, 2022-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://lethain.com/reminiscing/[Reminiscing: the retreat to comforting work.]

[quote]
____
In _link:https://staffeng.com/guides/work-on-what-matters[Work on what
matters]_, I wrote about Hunter Walk's idea of snacking: doing work that
is easy to complete but low impact. The best story of my own snacking
behaviors comes from my time at Stripe. I was focused on revamping the
engineering organization's approach to operating reliable software, and
decided that it might also make sense to start an internal book club. It
was, dear reader, not the right time to start a book club. Once you
start looking for this behavior, it is everywhere, including on your
weekly calendar. Snacking isn't necessarily bad, a certain amount gives
you energy to redeploy against more impactful tasks, but you do have to
be careful to avoid overindulging.

Beyond snacking, which can be valuable when it helps you manage your
energy levels, there is a similar pattern that happens when a business
or individual goes through a difficult moment: under pressure, most
people retreat to their area of highest perceived historical impact,
even if it isn't very relevant to today's problems. Let's call this
_reminiscing_. When you see your very capable CEO start to micromanage
words in a launch email, or your talented CTO start to give style
feedback in code reviews, take it for what it's worth: they're
reminiscing. If you spend the time to dig deeper, they're almost
certainly panicking about something entirely unrelated.
____
