= Links - Soon
Julien Kirch
v1.0, 2024-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://cohost.org/bruno/post/5322687-the-more-proficient[Tool proficiency]

[quote]
____
A particular thing that these old customizable GUIs were good for -- still seen in a lot of professional software, eg Photoshop -- was just hiding irrelevant affordances. Not everything needs to be visible or accessible by default; some features have niche uses, users have different levels of engagement and proficiency. You could go into the menu and toggle aspects of the UI on or off depending on whether you used them.

Discord doesn't give itself the affordances to selectively veil parts of its UI, and as a result _every_ user sees _every_ change to _every_ feature. Often a change that is welcomed by the users who embrace a given feature appears as just a pointless alteration for the users who don't use the feature. This, again, contributes to the sense of instability.
____

== link:https://docseuss.medium.com/the-biggest-threat-facing-your-team-whether-youre-a-game-developer-or-a-tech-founder-or-a-ceo-is-8cd1ad359508[the biggest threat facing your team, whether you’re a game developer or a tech founder or a CEO, is not what you think]

[quote]
____

____
