= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://www.penguin.co.uk/books/461276/how-infrastructure-works-by-chachra-deb/9781911709541[How Infrastructure Works: Transforming our shared systems for a changing world]

[quote]
____
Climate instability means more uncertainty in the larger context of infrastructural systems. As the environment in which they're embedded becomes more variable, that means de-optimizing these systems. It means investing in making them reliable under a wider and less predictable range of conditions and putting in the safeguards necessary to prevent outlier events from becoming natural disasters, where the highest human costs are paid by the most vulnerable. If the twentieth century was about building infrastructural systems that could manage or even just displace risks, the twenty-first century is going to be about building out systems -- human as well as technological -- that are resilient enough to sustain our communities during conditions of ongoing uncertainty.
____

== link:https://cohost.org/mcc/post/3982704-i-simply-do-not-care[I simply do not care for it when people describe code as having a "`code smell`"]

[quote]
____
What else do you expect your code to smell like
____
