= Links - Soon
Julien Kirch
v1.0, 2023-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://naml.us/post/thank-you-for-holding-my-duck/[Thank you for holding my duck]

[quote]
____
There`'s a story I like to tell, which I vaguely remembered as originating at Bell Labs or Xerox PARC. A researcher had a rubber duck in his office. When he found himself stumped on a problem, he would pick up the duck, walk over to a colleague, and ask them to hold the duck. He would proceed to explain the problem, often realizing the solution himself in the middle of the explanation. Then he would say, "`Thank you for holding my duck`", and leave.

I love this story. Years ago, Tamar Shinar and I agreed that the "`Thank you for holding my duck`" expression is better if it is understood to not mean the colleague didn’t contribute, as then it can be used in boundary cases without slight. But finally, someone asked for the source, and I looked for one and failed.
____

== link:https://thebookofshaders.com[The book of shaders]

[quote]
____
This is a gentle step-by-step guide through the abstract and complex universe of Fragment Shaders.
____
