= Links - Soon
Julien Kirch
v1.0, 2025-01-01
:article_lang: en
:figure-caption!:
:article_description: 

== link:https://cutlefish.substack.com/p/tbm-370-dependencies-arent-your-problem[TBM 370: Dependencies Aren't Your Problem]

[quote]
____
Dependency problems are frequently boiled down to discussions about estimation and commitment, when the real conversation should be about priorities and actual outcomes. In the current economic climate, teams are too gun-shy to escalate issues, so you’ll hear a lot of talk about the evils of dependencies but very few concrete examples.
____

== link:https://www.seangoedecke.com/pure-and-impure-engineering/[Pure and impure software engineering]

[quote]
____
This pure/impure distinction has been obscured by the fact that _there used to be much more scope for pure engineering at large tech companies_*_. In the 2010s, link:https://www.seangoedecke.com/good-times-are-over[times were different]. Companies were driven almost entirely by hype, and they were hiring more engineers than they knew what to do with. Funding pure engineering projects solved both of those problems: it produced impressive open-source artifacts that made the company look good to prospective engineering hires, and it provided a bottomless pit of useful-looking work for those engineers to do.

Even impure engineering got colonized by pure engineering. Companies burned hundreds of thousands of engineer-hours migrating from monoliths to microservices, or from HTTP service calls to event-sourced architecture, or from event-sourced architecture to full CQRS, and so on. A lot of very skilled engineers found their niche in navigating these hard, technical projects.

But like I said, those times are gone. Tech companies now have to make money. Hiring has slowed down dramatically, and companies are tightening their belts. A lot of pure engineers have had a rough time navigating this transition. From their perspective, work has all of a sudden become much more political. But what's really happened is that their previous role -- which was effectively a covert developer marketing position -- isn't being funded in the current market.
____