= Live love lore: enjoying video games’ lore by reading their wiki instead of playing them
Julien Kirch
v0.1, 2023-06-03
:article_lang: en

There are many video games with great spiraling universes. Unfortunately for me, enjoying them often requires good motor skills (like souls-like) for or lots of time (like JRPGs), and I have neither.

[quote]
____
In the Age of Ancients the world was unformed, shrouded by fog: a land of gray crags, Archtrees and Everlasting Dragons.
____


A thing I’ve seen mentioned several times for people wanting to create is "`if you want to write lore instead of a video game trying doing a TTRPG`". And I read TTRPG books for their universes and lore while skimming the parts explaining mechanics. I don’t want to read another generic fantasy book with a white cishet male hero’s journey.

For video games a direct alternative is to use cheats but there’s lots of games where it’s not possible.

The fallback available for most titles is to read the games’ wikis. On these wikis all the lore found in a game is carefully organized and tagged. It means instead of (failing to) killing enemies and hunting items in the game, then putting all the scattered parts together to make sense of it, I can read things from the beginning to the end, with everything interlinked including references and easter eggs.

[quote]
____
The Nameless King was once a dragon-slaying god of war, before he sacrificed everything to ally himself with the ancient dragons.
____

In an ideal world, I could play more games that match my tastes, or at least I could pay the games' creators for the content instead of having to rely on volunteers' work that benefits the wiki's hosters that plaster adds everywhere.

But until it happens, wikia here I come.
