= Playing gacha games until burning out in 6 days
Julien Kirch
v0.1, 2023-07-11
:article_lang: en

I love the idea of playing video games on my phone, unfortunately there’s not a lot of "`real`" games I want to play but lots of cool-looking gacha grinding games.

Every few weeks, when I’m bored and tired on a Friday evening I can’t resist and install one.

The first few hours can be played in one evening: the gameplay is often a variation of known elements, and the level-up is fast enough to not trigger the energy-limiting mechanisms.

Each level-up often unlock a new mechanic with its accompanying tutorial. As each mechanic is displayed somewhere, seeing the screens becoming gradually cramped is visually fascinating: more numbers, icons, menus, submenus, tabs and subtabs.

Most of these mechanics have a per-day limit like 5 PvP or a character gacha roll.

So the daily game todos list keeps growing, often an explicit list managed by the game, providing its own rewards when completed.

After the first day, the game is included in my morning routine: doing some of the simpler tasks while taking my coffee, playing ads for gacha while brushing my teeth, and more complex things during my commute.

First there is the discovery of the new tasks, then the fun of finding them in the interface, then the fun of organizing them to maximize the result (first the tasks that level you up, then those whose output is increased by your level).

On day five I’m settled on my routine and everything feels smooth.

On day six I feel the dreaded futility of spending so much time and effort on a game, and I often feel bad enough to delete it at the end of the day.

Then on day seven I feel free, at least for a few weeks.
