= Externalités négatives et déni plausible
Julien Kirch
v0.1, 2020-05-08
:article_image: 
:article_description: Deux concepts pour comprendre les organisations
:article_lang: fr

Dans une organisation séparée en plusieurs équipes, il est courant de présenter ces équipes comme agissant grosso-modo comme des organisations clientes et/ou fournisseuses les unes des autres.

Que cela reste au niveau de la discussion pour mieux comprendre les logiques de fonctionnement interne, ou que cela soit matérialisé à l'aide de systèmes de facturation interne.

Or j'ai l'impression que deux concepts appliqués aux organisations ne sont pas souvent appliquées quand il s'agit de sous-équipes et qu'ils mériteraient de l'être.

== Les externalités négatives

Le premier est celui d'externalité négative.

En économie une externalité est le fait pour un agent d'avoir un effet sur un autre agent sans contrepartie.
Un externalité négative survient lorsqu'un agent a un effet négatif sur un autre agent.

Ainsi une entreprise dont l'activité créé de la pollution environnementale créé une externalité négative pour l'écosystème où elle est installée.

Si le système plus grand dans lequel l'agent s'insère, par exemple la société dans laquelle opère cette entreprise, juge que cette externalité négative est un problème, elle pourra tenter de la corriger.

Pour corriger une externalité, il faut faire en sorte que l'effet produit ait une contrepartie.

Dans le cas de la pollution, cela peut signifier par exemple la mise en place de normes à appliquer, et d'amendes en cas de non-application de ces normes.

Dans une organisation séparée en plusieurs équipes, il est normal que des externalité négatives existent par exemple quand deux équipes ont des intérêts différents.
Par exemple une équipe qui développe un logiciel et qui voudrait se concentrer sur le fait de créer de nouvelles fonctionnalités, et une autre utilise ce logiciel et préférerait que ce logiciel n'évolue pas car elle est satisfaite de la version qu'elle utilise.

Si la première équipe est libre de faire ses choix _sans avoir à prendre en compte les besoins de la deuxième équipe_, on a affaire à une externalité négative.

L'organisation doit donc faire la chasse à ces situations pour, comme les sociétés dans le cas de la pollution, mettre en place des rétroactions lorsqu'elles manquent.

Dans le cas des deux équipes, cela ne signifie pas forcément que la deuxième équipes doit décider, mais qu'idéalement son avis doit être pris en compte dans la mesure où il permet d'améliorer les choses pour l'organisation au niveau global.

== Le déni plausible

Le deuxième concept très utile est celui du déni plausible.

En droit américain, le déni plausible est la capacité pour des personnes de nier avoir connaissance d'actions commises par d'autres individus faisait partie de la même organisation tant que cette connaissance n'est pas prouvée.

[quote]
____
Si vous ou l'un de vos agents étiez capturés ou tués, le Département d'État nierait avoir eu connaissance de vos agissements. Bonne chance, Jim
____

Si on croise souvent l'idée dans des _thrillers_ où des hommes et femmes politiques échappent à des condamnations grâce à des artifices, ils est plus souvent utilisé par des dirigeant·e·s d'entreprise.