= Trusted peers network
Julien Kirch
v0.1, 2023-01-15
:article_lang: en
:tpn: trusted peers network

I'm thinking of link:https://cutlefish.substack.com/p/tbm-266-human-load-balancers-renegades[this article] by John Cutler, and especially this part:

[quote]
____
People who understand the architecture, who influence who, and who can barter favors with other groups can remain effective for much longer.
They also tend to have more influence in the organization overall, so their perspective of the situation often carries much weight. These are people who don't need to file a ticket ("`we didn't do that back in the day when people just got stuff done!`").
They're valuable due to their contextual understanding, so they build a fair amount of social capital (though sometimes they can dismiss newcomers).
They simply don't know or understand the experience of arriving as a fresh set of eyes and trying to make sense of the organization, its architecture, and how things get done.
____

The large organizations I worked at had at least one informal {tpn}: reliable people that knows each other, that often share the same kind of world view, and that can be called for help.

== Tapping a {tpn}

When working in a new organization reaching one of these networks is an important goal.
It's true as an employee who plan to spend some time working there, but even more as a temporary consultant who has a limited time to reach some goals: being able to tap in a existing network can makes a big difference when you try to gather information or to build some momentum.

I suspect knowing how to do it is a skill that can be honed up to a certain point: how to identify people who have high chance to be in this kind of group, and from there how to find a way into it.

Up to a certain point only unfortunately, because personal characteristics like your gender can make joining the network easier or harder depending on the organization.

== Being in the network vs. being glue

A few months ago there was a lot of talk about link:https://noidea.dog/glue[being glue].
Being a part of a {tpn} is very helpful, and probably a prerequisite to be an efficient glue, but it's useful even if you're not glue and don't intend to become one.

I'm mentioning it because I'm a bit afraid that the glue discourse could discourage people that want to avoid the glue track to join a {tpn} as a preventive measure.

== The temptation of going peers-only

Being in a {tpn} has a drawback:
when you have a set of unofficial shortcuts that enable you to make things done, it can be tempting to rely as much as you can and thus to only use the official processes when you can't escape it.

People have valid reasons to do it, but it can be bad for the system as a whole.

People in a {tpn} often have some political weight in the organization.
When processes are not working as intended, or when they are becoming worse, these people have two ways to deal with it:

. Use their {tpn} to avoid the processes
. Try to use their political weight to try to improve the processes

You don't have to pick one or the other: the right thing to do is even probably to find the right balance between the two.

But if you only use the first choice, it means that some of the people 

Push people to do the right thing so there is a feedback.