= Network oif trusted peers
Julien Kirch
v0.1, 2023-01-15
:article_lang: en

I'm thinking of link:https://cutlefish.substack.com/p/tbm-266-human-load-balancers-renegades[this article] by John Cutler, and especially this part:

[quote]
____
People who understand the architecture, who influence who, and who can barter favors with other groups can remain effective for much longer. They also tend to have more influence in the organization overall, so their perspective of the situation often carries much weight. These are people who don't need to file a ticket ("`we didn't do that back in the day when people just got stuff done!`"). They're valuable due to their contextual understanding, so they build a fair amount of social capital (though sometimes they can dismiss newcomers.) They simply don't know or understand the experience of arriving as a fresh set of eyes and trying to make sense of the organization, its architecture, and how things get done.
____

The large organisations I worked at had at least one informal network of trusted peers: reliable people that knows each other, that often share the same kind of world view, and that can be called for help.

== Tapping the peers network

When working in a new organisation reaching one of these networks can be an important goal.
It's true as an employee who plan to spend some time working there, but even more as a temporary consultant who has a limited time to reach some objectives: being able to tap in a existing network can makes a big difference with you try to gather information or to build some momentum.

I suspect knowing how to do it is a skill that can be honed up to a certain point: how to identify people who are in the group, and how to find a way into it, or even how to fast-track.
Up to a certain point only because to be able to join the group, personal characteristics like your gender can make things easier or harder depending on the organisation.
