= Insiders and vicious circle of worsening workflows
Julien Kirch
v0.1, 2023-01-15
:article_lang: en

I'm thinking of link:https://cutlefish.substack.com/p/tbm-266-human-load-balancers-renegades[this article] by John Cutler, and especially this part:

[quote]
____
People who understand the architecture, who influence who, and who can barter favors with other groups can remain effective for much longer. They also tend to have more influence in the organization overall, so their perspective of the situation often carries much weight. These are people who don't need to file a ticket ("`we didn't do that back in the day when people just got stuff done!`"). They're valuable due to their contextual understanding, so they build a fair amount of social capital (though sometimes they can dismiss newcomers.) They simply don't know or understand the experience of arriving as a fresh set of eyes and trying to make sense of the organization, its architecture, and how things get done.
____

All large enough orga