= Impressions of Detail
Julien Kirch
v0.1, 2023-01-01
:article_lang: en

[quote]
____
Every time you wake, the tattoo has changed. Today you find it on your forearm, high near the elbow, on the outside so you have to arrange yourself in front of a mirror to see.
____

When you manage to see it you're confused at first: it's like a star with sigils in it. Then you realize you can take a picture of it with your phone and even use one of the obscure buttons of the photo app to flatten the drawing.

It looks like one of those old-school comic action bubbles, complete with a large "`BAM!`" written in it.

You wonder what you're supposed to do with this: will you have to chase down the joker, maybe while wearing a fancy costume with a cape?

Today is errands' day, where you have to deal with all the tasks you procrastinated this last month: buying some food, dropping some old stuff at the recycling depot, and a last stop at the bookstore.

You're tense and look around you every few seconds: will you have to voluntarily elbow somebody, or will you do it accidentally and end up mortified by your action? You silently evaluate all people you see around to see in which category they could be.
When you’re back home in the afternoon you’re exhausted by the constant attention and frustrated because you still don’t know: will somebody attack you at your place? Time goes by slowly.

At 11pm you finally got your answer: the bathroom’s cupboard, the one with sharp corners. It hurts so badly.

[quote]
____
You studied the blade? Quaint. You cannot win this; the blade studied _me_.
____

The only thing they knew was murder, they were created for it.

They watched me as I stole them from their previous owner, and escaped the palace instead of seizing the throne.

They studied me as I stole other precious artifacts, as I sabotaged plans, as I mocked rulers.

They studied me and realized that, more than murder, the thing they craved for was pain.
And that frustrating powerful people is more painful for them than murdering them or making them bleed.

The blade changed, it is no more the blade the history books you read talk about.

They are useless for your grand plans of overthrowing rulers, and you can't beat me in a way that matters.

Now please leave.

[quote]
____
"`Mind...the _gap_,`" droned the recorded announcement. "`Mind...the _gap_. The signifier...is not..the signified.`"
____

Mind the gap in your knowledge before trying to step on the next concept, or you'll fall into the concept wilderness and risk becoming a feral thinker.

If you try to reach a curved signified from a straight signifier, please use a metaphor with the right curvature.

If you try to reach a low concept from a high one, you can use a _faux pas_ if you're comfortable with awkwardness. Spraining your metaphorical ankle can even increase your street cred.

If you try to reach a high concept from a low one, the _détournement_ can achieve the intended result, but it only works if you wear a Guy Debord t-shirt.

The uncomfortable hissing sounds coming from below should be ignored to the best of your abilities.

[quote]
____
Tussling over the bag, wind buffeting you back and forth, your hands brushing as you both frantically dig around inside it. Then the momentary, frozen standoff -- one of you clutching the priceless figurine, the other the wallet containing a single plane ticket, the unmarked bills, and the unread love letter.
____

Then you leave the pier to call a taxi.

Staring in VR custom movies pays well but is a mixed bag: not knowing the setup before the recording starts means some nasty surprises since some clients have very specific tastes.

You read the info on the plane ticket: from Chicago to Lima, on the 17th April 1943.
Lima explains the strange looking figurine and the tweed outfit: an Indiana Jones remake, gender-swapped.

You sight at the ideas of the fatal traps in the jungle temple, hoping there won't be any racist native.

You prefer rom-coms to adventure movies, but the date could mean punching some nazis, and it has been so long since you had this opportunity.

[quote]
____
"`The secret ingredient _is_ love.`" She puts her head on one side, eyes soft. "`Nobody ever asks _how I extract it_. Not until too late.`"
____

- The quantity of love is fixed, linked to the number of living people.
- So everybody has a fixed quantity of love?
- No it's a global pool, shared by everyone, but the size grows with how-.
- It doesn't make any sense!
- I know, but my scientists have an explanation, they made a 10 hour long webinar about it and they're very proud of it.
- And how do you?
- We must make some love available so we can reclaim it. We don't want things to get messy so we target old memories: deleting a few ones here and there, on enough people, and we get enough.
- How did you create such a precise system?
- I mean it's the general idea, some people are impacted more than others, it must suck to be them.

[quote]
____
Archaeologists unearth a prehistoric spacecraft; excited by its unusual iconography.
____

On each side a large symbol was visible: `=\^..^=` .

People acted like they didn't know the symbol. It could be something else after all.

Then near the bottom of the hull, they reached two large docking bays, one with a `UwU` symbol, the other with an `OwO` one.

Once one of the bays was opened, there was equipment everywhere.
Some of it was carefully hung but most was left loose on the floor.

Among them are some pressurized spacesuits, human-sized helmets with prominent cat ears.

[quote]
____
In the ruthlessly capitalist Land of the Dead, the lowest class of destitute ghosts are burned to their second and total deaths as industrial fuel.
____

But of course it doesn't end here: the reach of capitalism doesn't end at the first death, but neither at the second death.

After their second destruction, they respawn on the Land of the Dead^-1^, and their cursedness is compared to the requirement of the level.
Each Land of the Dead has a higher limit, so they go down until they reach the Land of the Dead^-n^ that match their cursedness level.

Then they can start working to decrease their cursedness.
The lower tasks are of course the most revulsive, like working for ad networks or lobbying for change in the cursedness management laws.

When their cursedness is low enough, they can do the highest status job of the level: the destruction of the ghosts that are destined to the lower level, each death removing some of the curse.

When a slot is available, they respawn on a higher Land of the Dead level.

There are rumors that the Land of the Dead numbering scheme is a scam, but there are also rumors that anybody caught mentioning it will suffer an even worse fate.

[quote]
____
"`Scalpel,`" the surgeon barks, holding his hand out for it to be slipped into his palm before he continues his work. "`Forceps. Cursed obsidian medallion—`"
____

- Some days I am nostalgic for when software development before agile and all those metaphors related to rituals.

You hear a wet muffled sound that makes you uncomfortable.

- Is the scrum master ready ? I'll need them soon.

You turn around and check the status on the dashboard.

- They're getting dressed, putting on the delivery uniform is always taking more time than estimated.

A distant sound, that you feel more than you hear, and the feeling is unpleasant.

- The build started, I hope the other teams are ready.

Everything turns black.

[quote]
____
"`I'm not sure we can fund a grant proposal which involves attacking and dethroning god as the stage of eight. I have concerns about your _project scope_.`"
____

Recruiting catboys has a high veto risk from the ethics committee: since the last incident it's been a really touchy topic because of the insurance premium.

Also anything with this level of impact needs validation from the university steering council, and they won't take any decision until a new chancellor is elected.

On the other hand your proposed modus operandi is really intriguing: maybe we could rescope your project in a way that keeps the interesting parts while escaping the red tape, and if it works you'll be on firmer ground to try your initial idea.

My personal suggestion would be to target a baron of hell.
First hell means the lab can take the single responsibility of the project if we can convince the department chair.

Second, if you target one of the hell barons who unofficially support the software engineering department and win, it could mean being able to claim some of their tenure budget.

[quote]
____
"`Get your coat,`" they snap. "`I'm taking you to the drive-thru exorcist—`"
____

How many times have I told you to never play a Bethesda game that just shipped?

I promise you that if I discover that your sibling is infected as well, you'll be on a strict ttrpg diet for at least 3 months.

[quote]
____
You never expected another one: the unmarked envelope slipped under your door. A single sheet of folded letter paper. A single word.
____

You hoped that you had fucked your last move enough that they would remove you from the game, but it seems the bar is even lower than you expected, or perhaps they are into this.

Anyway you're still registered, so you will play.

You read the word printed in Helvetica 16pt.

And again you don't know what it means. Why the hell are they swapping languages each time?
20 years ago it would have added some challenge, but with the internet they could stick to English, it just adds a level of annoyance.

You pick your phone and look for a translation.

The word means "`cantaloupe`" in one language and "`piston`" in another.

You slowly sit down on the floor, close your eyes and pinch the bridge of your nose.

[quote]
____
"`We're going to need an old priest, a young priest, and a network engineer.`"
____

Last time we tried to enable IPv6 on this appliance, the enterprise energy blast switched half the data center machines to NT 4.0.

The network cables have been coated with entropy-resistant material, and all the air in the server room has been swapped to an inert mixture.
People enjoy working in a pressurized suit when it's one day every month.

An intern is ready near the main power switch, just in case.

Everything is ready, starting deployment.

At least the postmortem will be funny, unless there are, you know, actual bodies to deal with.

[quote]
____
If anyone sees you -- here, now, like _this_ -- you'll have to answer so many questions.
____

You already have been told that only pilots and trainees can wear a mech suit, and specially that the simulator is out of limits for you.

I heard that spending the night connected to the simulator helps with your nightmares, but it leaves traces in the _gestalt_, and it affects the trainees: they have trouble concentrating, and it gives them _bad_ ideas that mess with the teaching.

If you want there's a research project for the new mech that involves an isolated _gestalt_, they have trouble finding volunteers for the tests because of the new wetware controls.

[quote]
____
A spear: its handle of ash wood, its grip wrapped in cord spun from the fibres of nameless plants, its blade a dark, honed flake retrieved from uneasy dreams.
____

It's the spear of the Death of the Author: the only weapons that can really kill an author.

Barthes mentioned it in the lost chapter of his book.

It will free all the author's concepts and characters from the author's nefarious influence.

All fanfic writers dream of holding it.

[quote]
____
It takes twenty to forty hunters to bring down the Humungous Land-Snail, and weeks to butcher it, before the shell can be passed on to the shipbuilders of the Space Navigation Clan.
____

Rituals are important among such a large civilisation. In theory they are here to remind them of their origin, but they also maintain a link among all the different cultures that tends to drift away if not enough efforts are invested to keep them together.

So old rituals are kept alive, and new ancestral traditions are invented when the need arises.

During history and sociology seminaries, scholars are encouraged to LARP about topics they know, and the results are sent to playwrights in charge of creating the rituals.

Even the discovery of "`lost rituals`" has been made an event, with its own tradition.

[quote]
____
It's not fungi pushing their way out of the damp wall at all; it's teeth.
____

Web development's tooling has always been a kind of its own.

When a new build chain called "`developper's dreams`" was announced, promising enhanced productivity, low maintenance, and a flat learning curve, many companies were eager to try it.

The license was kind of strange, but people who wrote about the oddities were called luddites and joy-killers and promptly ignored.

With the vibes on your side, tapping the collective unconscious to minimize JavaScript is something you can get away with.

Of course the sysadmins complained "`dealing with nightmares portals in their networks was never a part of our job description`".

Many quitted until Google published a whitepaper touting Nightmare Engineering as the next thing.

Plus ça change…

[quote]
____
The map is old, and marks the locations of three things with only the numbers 1–3. Someone has torn away the legend.
____

- Is this the system architecture diagram?
- You see, with all the "`stories`", "`epics`" and things like that, the founders that were D&D fans went all the way and made all the documentation and system around RPG design.
- So all the architecture diagrams look like dungeon maps?
- All the ones I saw at least.
- Customers are yelling at us because the system is wrong, and what we have to deal with the issue are maps of necromancers' lair?
- No, I mean they are maps of the system not…
- You understood what I meant! And those rooms on the map, fuck I mean these applications,  are there more info on them?
- Yes we have some documentation on the applications, let me show you.
- Wait, did they?
- Yes, they used character sheets.
- The billing system has 12AP, it's the worst day of my life!


[quote]
____
Eyes replaced with orbs of gold, he sees the world still; but now in only cold, valueless, price-tag worths.
____

Since the beginning of the great webmarketing war things are slowly worsening in the field: ads designed to create intrusive thoughts, state actors investing in content blocker in the name of national sovereignty, and the conversion rates going down, down, down.

The new eyes should help him spot undermonetized content where new ads could be sneakily pushed.

[quote]
____
The Librarian is a bronze-masked elephant, moderately sprightly but nonetheless ancient.
____

Since nearly all the web content has been replaced by generated gibberish, it's a golden age for boutique search engines specialized on a single topic.

It was not ideal because you first needed to find the right search engines, but it would be much more bearable if they didn't feel obliged to add obnoxious user interfaces to increase their brand recognition.

[quote]
____
A sky like the dust of ground seashells; underfoot, endless dunes the blue of a storybook sky.
____

Obtaining a grant for a PhD studying the storage bays of decommissioned virtual reality platforms has not be an easy task, but it was worth the effort.

Even when all the data was supposed to be scrapped, some of it remains.

They started to call it "`ghost data`".

During power fluctuations they could see mirages of buildings, it was disconcerting at first but not really interesting, because all remarkable ones have been screenshoted to death.

But their data detector could spot fragments of ghost thoughts, like searching for trinkets with a metal detector.

Nearly all were linked to strong emotions, but a few were more mundane: guilds meeting notes, changelogs for mods… They were a refreshment among all the horny roleplay content.

No pattern emerged yet that could explain what data survived the deletion: it could become a large liability for disk providers.

Meanwhile, the PhD candidate was dreaming of opening a new kind of urban exploration tour operator.

[quote]
____
A monster made of paint and ritual. A story told of victory and heroes, told often, told confidently, to be spoken into truth.
____

Every videogame post-mortem trigger a trauma response from those involved.

Investing so much effort and pain to turn an idea into something you could play always leave a mark.

People need a closure, so they can leave some of the bad things behind.