= Impressions of Detail
Julien Kirch
v0.1, 2023-01-01
:article_lang: en

[quote]
____
Every time you wake, the tattoo has changed. Today you find it on your forearm, high near the elbow, on the outside so you have to arrange yourself in front of a mirror to see.
____

When you manage to see it you're confused at first: it's like a star with sigils in it. Then you realize you can take a picture of it with your phone and even use of the obscure button of the photo app to flatten the drawing.

It looks like one of those old-school comic action bubbles, complete with a large "`BAM!`" written in it.

You wonder what you're supposed to do with this: will you have to chase down the joker, maybe while wearing a fancy costume with a cape?

Today is errands' day, where you have to deal with all the tasks you procrastinated this last month: buying some food, dropping some old stuff at the recycling depot, and a last stop at the bookstore.

You're tense and look around you every few seconds: will you have to voluntarily elbow somebody, or will you do it accidentally and end up mortified by your action? You silently evaluate all people you see around to see in which category they could be.
When you’re back home in the afternoon you’re exhausted by the constant attention and frustrated because you still don’t know: will somebody attack you at your place? Time goes by slowly.

At 11pm you finally got your answer: the bathroom’s cupboard, the one with sharp corners. It hurts so badly.

[quote]
____
You studied the blade? Quaint. You cannot win this; the blade studied _me_.
____

The only thing they knew was murder, they were created for it.

They watched me as stole them from their previous owner, and flew the palace instead of seizing the throne.

They studied me as I stole other precious artifacts, as I sabotaged plans, as I mocked rulers.

They studied me and realized that, more than murder, the thing they craved for was pain.
And that frustrating powerful people is more painful for them than murdering them or making them bleed.

The blade changed, it is no more the blade the history books you read talk about.

They are useless for your grand plans of overthrowing rulers, and you can't beat me in a way that matters.

Now please leave.

[quote]
____
"`Mind...the _gap_,`" droned the recorded announcement. "`Mind...the _gap_. The signifier...is not..the signified.`"
____

Mind the gap in your knowledge before trying to step on the next concept, or you'll fall into the concept wilderness and risk becoming a feral thinker.

If you try to reach a curved signified from a straight signifier, please use a metaphor with the right curvature.

If you try to reach a low concept from a high one, you can use a _faux pas_ if you're comfortable with awkwardness. Spraining your metaphorical ankle can even increase your street cred.

If you try to reach a high concept from a low one, the _détournement_ can achieve the intended result, but it only works if you wear a Guy Debord t-shirt.

The uncomfortable hissing sounds coming from below should be ignored to the best of your abilities.

[quote]
____
Tussling over the bag, wind buffeting you back and forth, your hands brushing as you both frantically dig around inside it. Then the momentary, frozen standoff -- one of you clutching the priceless figurine, the other the wallet containing a single plane ticket, the unmarked bills, and the unread love letter.
____

Then you leave the pier to call a taxi.

Staring in VR custom movies pays well but is a mixed bag: not knowing the setup before the recording starts means some nasty surprises since some clients have very specific tastes.

You read the info on the plane ticket: from Chicago to Lima, on the 17th April 1943.
Lima explains the strange looking figurine and the tweed outfit: an Indiana Jones remake, gender-swapped.

You sight at the ideas of the fatal traps in the jungle temple, hoping there won't be any racist native.

You prefer rom-coms to adventure movies, but the date could mean punching some nazis, and it has been so long since you had this opportunity.

[quote]
____
"`The secret ingredient _is_ love.`" She puts her head on one side, eyes soft. "`Nobody ever asks _how I extract it_. Not until too late.`"
____

- The quantity of love is fixed, linked to the number of living people.
- So everybody has a fixed quantity of love?
- No it's a global pool, shared by everyone, but the size grows with how-.
- It doesn't make any sense!
- I know, but my scientist have a explanation, they made a 10 hours long webinar about it and they're very proud of it.
- And how do you?
- We must make some love available so we can reclaim it. We don't want things to get messy so we target old memories: deleting a few ones here and there, on enough people, and we get enough.
- How did you created such a precise system?
- I mean it's the general idea, some people are impacted more than others, it must suck to be them.

[quote]
____
Archaeologists unearth a prehistoric spacecraft; excited by its unusual iconography.
____

On each side a large symbol was visible: `=\^..^=` .

People acted like they didn't knew the symbol. It could be something else after all.

Then near the bottom of the hull, they reached two large docking bays, one with a `UwU` symbol, the other with an `OwO` one.

Once one of the bay has been opened, there were equipments everywhere.
Some of it carefully hanged but most was left loose on the floor.

Among it some pressurized spacesuits, human-sized, helmets with prominent cat ears.

[quote]
____
In the ruthlessly capitalist Land of the Dead, the lowest class of destitute ghost are burned to their second and total deaths as industrial fuel.
____

But of course it doesn't end here: the reach of capitalism doesn't end at the first death, but neither at the second death.

After their second destruction, they respawn on the Land of the Dead^-1^, and their cursedness is compared to the requirement of the level.
Each Land of the Dead has a higher limit, so they go down until they reach the Land of the Dead^-n^ that match their cursedness level.

Then they can start working to decrease their cursedness.
The lower tasks are of course the most revulsive, like working for ad networks or lobbying for change in the cursedness management laws.

When their cursedness is low enough, they can do the highest status job of the level: the destruction of the ghosts that are destined to the lower level, each death removing some of the curse.

When a slot is available, they respawn on a higher Land of the Dead level.

There are rumors that the Land of the Dead numbering scheme is a scam, but there are also rumors that anybody caught mentioning it will suffer an even worse fate.

[quote]
____
"`Scalpel,`" the surgeon barks, holding his hand out for it to be slipped into his palm before he continues his work. "`Forceps. Cursed obsidian medallion—`"
____

- Some days I am nostalgic for when software development before agile and all those metaphors related to rituals.

You hear a wet muffled sound that makes you uncomfortable.

- Is the scrum master ready ? I'll need them soon.

You turn around and check the status on the dashboard.

- They're getting dressed, putting the delivery uniform is always taking more time than estimated.

A distant sound, that you feel more than you hear, and the feeling is unpleasant.

- The build started, I hope the other teams are ready.

Everything turns black.

[quote]
____
"`I'm not sure we can fund a grant proposal which involves attacking and dethroning god as the stage of eight. I have concerns about your _project scope_.`"
____

Recruiting catboys has a high veto risk from ethic committee: since the last incident it's a really touchy topic because of the insurance premium.

Also anything with this level of impact need a validation from the university steering council, and they won't take any decision until a new chancellor is elected.

On the other hand your proposed modus operandi is really intriguing: maybe we could rescope your project in a way that keeps the interesting parts while escaping the red tape, and if it works you'll be on firmer ground to try you initial idea.

My personal suggestion would be to target a baron of hell.
First hell means the lab can take the single responsibility of the project if we can convince the department chair.

Second, if you target one of the hell barons who unofficially support the software engineering department and win, it could mean being able to claim one of their tenure budget.

[quote]
____
"`Get your coat,`" they snap. "`I'm taking you to the drive-thru exorcist—`"
____
