= Impressions of Detail
Julien Kirch
v0.1, 2023-01-01
:article_lang: en

[quote]
____
But when you do that _one particular thing_, your reflection in the mirror breaks up into fuzz and jagged shapes, only swimming back to coherency when you stop.
____

– What is this? I though this bug was linked to the technology used in the previous pervious, it should not happen with the new serie. +
– You're right in theory, but some vocals users are really attached to the bug, so we had to painstakingly emulate it in the new version, it's enabled by default to please them but you can disable it from the advanced settings screen.

[quote]
____
The murder weapon was a coffee-table art book title _The End_, consisting of glossy photographs of staged bloodstains.
____

– Lemme look in the book, I'm sure we'll find this particular pattern somewhere! +
– … No, wait +
— It could even be on the last page, with only blank pages after it! +
— Stop right now with your Mulder bullshit and read the report! +
– I'm reading! +
– And you don't notice anything? +
– Ehmmm, the victim has been bashed to death with the book and died of internal trauma, no visible blood. +

[quote]
____
Welcome to our legal system! It is large and has many teeth.
____

– So now that we are finally here I want to know: why the teeth? +
– It's because of a ancient tradition related to… +
– I've read the changelog for the court application, the teeth are only here since the v3.0 released ten years ago, I didn't saw a single tooth in the V2 screenshots. +
– It's because of a clerical error, the company in charge of developing the v3.0 bought a very expensive teeth asset package, and making everything teeth-related was the best way we found to justify the spending to the the auditors.

[quote]
____
Twelve newly-unearthed megaliths of local stone, buried since antiquity, describing the perimeter of a perfect square.
____

At least most of the work were done by drones so it wasn't so unpleasant if you could handle the dust, but you still wonder who is paying to restore these ancients macro LCD screens: what kind of message would you want to show on a monitor with 100 meters wide pixels.

[quote]
____
The things that fire takes, and the things it capriciously leaves behind.
____

A way was needed to cleanse the tar pit of cursed things people continually see on the internet.

The repeated bad takes slowly decayed in the human psyche, poisoning the well that irrigates the next generation of ideas.

Scholars started to notice all the odd metaphors creeping in the discourses' water pipes.

Fire was the answer: its elemental nature was very potent against the brittle memes.
For months, the web smelt like cold smoke.

Then, new things started to grow from under the ashes, things that the fire forgot, or didn't dare to touch.
