= Impressions of Detail
Julien Kirch
v0.1, 2023-01-01
:article_lang: en

[quote]
____
Every time you wake, the tattoo has changed. Today you find it on your forearm, high near the elbow, on the outside so you have to arrange yourself in front of a mirror to see.
____

When you manage to see it you're confused at first: it's like a star with sigils in it. Then you realize you can take a picture of it with your phone and even use of the obscure button of the photo app to flatten the drawing.

It looks like one of those old-school comic action bubbles, complete with a large "`BAM!`" written in it.

You wonder what you're supposed to do with this: will you have to chase down the joker, maybe while wearing a fancy costume with a cape?

Today is errands' day, where you have to deal with all the tasks you procrastinated this last month: buying some food, dropping some old stuff at the recycling depot, and a last stop at the bookstore.

You're tense and look around you every few seconds: will you have to voluntarily elbow somebody, or will you do it accidentally and end up mortified by your action? You silently evaluate all people you see around to see in which category they could be.
When you’re back home in the afternoon you’re exhausted by the constant attention and frustrated because you still don’t know: will somebody attack you at your place? Time goes by slowly.

At 11pm you finally got your answer: the bathroom’s cupboard, the one with sharp corners. It hurts so badly.

[quote]
____
You studied the blade? Quaint. You cannot win this; the blade studied _me_.
____

The only thing they knew was murder, they were created for it.

They watched me as stole them from their previous owner, and flew the palace instead of seizing the throne.

They studied me as I stole other precious artifacts, as I sabbotaged plans, as I mocked rulers.

They studied me and realized that, more than murder, the thing they craved for was pain.
And that frustrating powerful people is more painful for them than murdering them or making them bleed.

The blade changed, it is no more the blade the history books you read talk about.

They are useless for your grand plans of overthrowing rulers, and you can't beat me in a way that matters.

Now please leave.

[quote]
____
"`Mind...the _gap_,`" droned the recorded announcement. "`Mind...the _gap_. The signifier...is not..the signified.`"
____

Mind the gap in your knowledge before trying to step on the next concept, or you'll fall into the concept wilderness and risk becoming a feral thinker.

If you try to reach a curved signified from a straight signifier, please use a metaphor with the right curvature.

If you try to reach a low concept from a high one, you can use a _faux pas_ if you're comfortable with awkwardness. Spraining your metaphorical ankle can even increase your street cred.

If you try to reach a high concept from a low one, the _détournement_ can achieve the intended result, but it only work if you wear a Guy Debord t-shirt.

The uncomfortable hissing sounds coming from bellow should be ignored to the best of your ability.