= Impressions of Detail
Julien Kirch
v0.1, 2023-01-01
:article_lang: en

[quote]
____
Every time you wake, the tattoo has changed. Today you find it on your forearm, high near the elbow, on the outside so you have to arrange yourself in front of a mirror to see.
____

When you manage to see it you're confused at first: it's like a star with sigils in it. Then you realize you can take a picture of it with your phone and even use of the obscure button of the photo app to flatten the drawing.

It looks like one of those old-school comic action bubbles, complete with a large "`BAM!`" written in it.

You wonder what you're supposed to do with this: will you have to chase down the joker, maybe while wearing a fancy costume with a cape?

Today is errands' day, where you have to deal with all the tasks you procrastinated this last month: buying some food, dropping some old stuff at the recycling depot, and a last stop at the bookstore.

You're tense and look around you every few seconds: will you have to voluntarily elbow somebody, or will you do it accidentally and end up mortified by your action? You silently evaluate all people you see around to see in which category they could be.
When you’re back home in the afternoon you’re exhausted by the constant attention and frustrated because you still don’t know: will somebody attack you at your place? Time goes by slowly.

At 11pm you finally got your answer: the bathroom’s cupboard, the one with sharp corners. It hurts so badly.