= Messages et services
Julien Kirch
v0.1, 2019-04-29
:article_lang: fr

Thèse : ce qu'on appelle "`services`" (SOAP, REST, CORBA, {nbsp}…) est un certain type de messages, et pas une catégorie à part.

Voila ce que j'entends parfois autour de moi

[cols="3", options="header", cols="h,1,1", stripes=none] 
|===
|
^.^|Synchrone
^.^|Asynchrone

>.^|1{nbsp}consommateur
^.^|Services
|

>.^|X{nbsp}consommateurs
|
^.^|Messages

|===

Voila la réalité

[cols="3", options="header", cols="h,1,1", stripes=none]
|===
|
^.<|Synchrone
^.<|Asynchrone

>.^|1{nbsp}consommateur
^.^|Services +
Messages
^.^|Messages

>.^|X{nbsp}consommateurs
|
^.^|Messages

|===

Exemples :

* Messages synchrones vers 1 consommateur : JMS, IBM MQ
* Messages synchrones vers X consommateurs : multicast la plupart des files de messages le supportent
* Messages synchrones vers 1 consommateur : la plupart des files de messages le supportent, s'agit d'un cas simplifié du cas précédent

D'ailleurs il est tout à fait possible d'utiliser une file de message pour faire de l'appel de service : IBM MQ peut exposer du SOAP et est utilisé de cette manière dans de nombreuses organisations, c'est d'ailleurs une des manières historiques d'exposer des services.

Mon hypothèse : les services viennent des web services, c'est à dire SOAP, qui était une manière d'exposer des appels synchrones entre un service exposant et un service consommateur. SOAP et les pratiques qui l'accompagnaient promettait de nombreux avantages et du coup le mot "`service`" s'est implanté comme dénomination comme s'il était différent du mode messages.

Un caractéristique des services qui ne sont pas partagées par tous les systèmes de messages est le fait que  l'intermédiaire entre l'exposant et le consommateur ne stocke pas de messages d'une manière structurée : certaines technologies de message peuvent faire de la persistance si le consommateur n'est pas disponible, mais pas toutes, par exemple link:http://zeromq.org[ZeroMQ].

Une autre différence est le mode de communication, soit en mode procédure "`fait moi ça`" soit en mode notification "`ceci est arrivé`", cela structure le format et le contenu qui est transmit, il y a des habitudes et certaines approches fonctionnent mieux avec un ou l'autre mode, mais il n'y a pas de séparation "`dure`".

Conclusion : le mot "`service`" a son utilité car il désigne un cas particulier (communication synchrone en point à point), mais atteintion à ne pas penser que les différences entres "`service`" et "`messages`" ne sont pas celles qu'on croit.