graph TD

Start
Ajouter1[Add initial states]
subgraph 
Récupérer[Fetch first state from the list]
Tester[Is it a winning state?]
Calculer[Compute possible children of the state and add them to the list]
end
Fail[No solution found]
Solution[\o/ Found a solution!]

Start --> Ajouter1
Ajouter1 --> Récupérer
Récupérer --> |Got one|Tester
Récupérer-->|List is empty|Fail
Tester -->|Yes| Solution
Tester -->|No|Calculer
Calculer -->Récupérer