= Writing a "`Baba Is You`" solver, part 1
Julien Kirch
v0.1, 2019-05-05
:article_lang: en
:ignore_files: graph.mmd

link:https://hempuli.com/baba/[Baba Is You] is a great puzzle game with a more-than-usual complex gameplay since manipulating the game rules is part of the game.

I think it's a good candidate to write a solver for, and to write some articles documenting how I'm doing it.

As I've explained link:../solveurs/[in a previous article] (in French), the main engine of a puzzle solver is a loop used to iterate until we find a solution.

image::graph.svg[width=731,height=513]

But, first we need to be able to feed the data to the loop, which means reading the levels from disk.

== Create the project

First thing is to bootstrap the project.

A solver has often complex data types so a language with static types is great, and a fast language is nice to have to make things faster, my tool of choici for this situation is Java.

[source,bash]
----
mvn archetype:generate -DarchetypeGroupId=org.apache.maven.archetypes -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4
----