== Villain who ran into a wall.

– Hello, Knife, why the long face and -- wait -- why the arm cast?

Knife took their time to sit down, they enjoyed the _gravitas_ the cast gave them.

– I tried to catch the Harlequin, just after his representation, lots of tourists in the attendance, and they are so eager to show they enjoy things by spending money. +
– The Harlequin? You should know better than attacking one of these funny people. Remember what happened when Stan tried to attack the mime? +
– Yes, I was at the bar when Jess found the body. Bless his soul, or what's left of it. +
– So the Harlequin? +
– I was following him along the old road, and he started to run, probably heard me, but we were alone, so I decided to chase him. +

Moss pointed to the cast.

– A bad fall? +
– No, worse, remember the part of their act when they paint a road on a wall, and it kinda looks like a real one even if we can notice it's not a real one? +
– Yes, but what's the link with… +
– When it's half dark and you're running, it really looks like a fucking road. +
