= Ces idées qui auraient du révolutionner l'informatique d'entreprises mais qui ont fait pschit
:idee: Idée :
:pourquoi: Pourquoi ça n'a pas fonctionné ?
:maintenant: Et maintenant ?

// Idées à prendre :
// - BPM
// - CORBA
// - Central architecture team
// - Cheap outsourcing
// - Design patterns
// - EAI
// - Enterprise wiki
// - LDAP
// - MDA
// - ODS
// - SOAP
// - UML
// - XML for everything
// - Métriques de code

= Introduction

L'informatique d'entreprise a vécue de nombreuses promesses de révolutions … qui ont presque toutes échouées.
Chacune portait une promesse merveilleuse, mais chacune avait aussi un défaut fatal, qui l'a empêché d'aboutir.

Toutes ces idées n'ont pas été des fiascos total — certaines des approches sont encore utilisées aujourd'hui — mais elles n'ont pas apportées les transformations promises, ou alors seulement à la marge.

Pour les plus jeunes qui ne les ont pas connues directement, rappeler pourquoi elles furent si attirantes permet de comprendre les problèmes qui se posent dans les projets, et les raisons de leurs échecs permet de voir les contraintes de la réalité qu'on a trop vite fait d'oublier.

Les paris sont ouverts sur les entrées à ajouter d'ici quelques années, même si on a déjà quelques solides candidats.

---

= Les outils de portail d'entreprise

*{idee}*
Les pages d'accueil des sites intranet des grandes entreprises sont composés de plusieurs éléments disparates : calendrier, fils de news, annuaire, liens vers application.
La théorie du portail est que ces éléments disparates seraient autant de composants appelés _portlets_ qui seraient conçues dans un même socle.
L'outil permettant ensuite de les rendre disponibles et de permettre aux utilisateurs des les réarranger et de les paramétrer.
On pourrait ainsi facilement multiplier les composants et avoir des portails intranet très riches.

*{pourquoi}*
Tout d'abord les outils de portails étaient catastrophiques: ils étaient bourrés de bugs, écrire des _portlets_ était une souffrance, et les fonctionnalités promises par l'outil se sont révélées assez faible.
Ensuite la vérité est que les gens "n'utilisent" pas les portails intranet :
ils y accèdent car c'est la page par défaut de leur navigateur, et s'en servent presque uniquement comme d'une liste de liens pour aller sur leurs applications métier.

*{maintenant}*
Les CMS remplissent généralement ce rôle : ils fournissent les quelques composants qui sont réellement nécessaires sur une page d'accueil, et permettant de publier le contenu qui constitue l'essentiel des pages.

---

= Titre

*{idee}*
Excepteur est voluptate qui ad esse eu est magna duis ea velit labore ipsum.

*{pourquoi}*
Amet Lorem ullamco consectetur cillum irure qui incididunt dolore eu voluptate voluptate sint.

*{maintenant}*
Esse nostrud elit sit qui esse sit laborum magna dolore aute exercitation.
