= Ces idées qui auraient du révolutionner l'informatique d'entreprises
:idee: Idée
:pourquoi: Pourquoi ça n'a pas fonctionné ?
:maintenant: Et maintenant ?

// Idées à prendre : BPM, CORBA, Central architecture team, Cheap outsourcing, Design patterns, EAI, Enterprise wiki, LDAP, MDA, ODS, Portals, SOAP, UML, XML for everything, Métriques de code

= Introduction

L'informatique d'entreprise a vécue de nombreuses promesses de révolutions … qui ont presques toutes échouées.
Chacune pourtait une promesse merveilleuse, mais chacune avait aussi un défaut fatal, qui l'a empeché d'aboutir.

Toutes ces idées n'ont pas été des fiascos total — certaines des approches sont encore utilisées aujourd'hui — mais elles n'ont pas apportées les transformations promises, ou alors seulement à la marge.

Pour les plus jeunes qui ne les ont pas connues directement, rappeller pourquoi elles furent si attirantes permet de comprendre les problèmes qui se posent dans les projets, et les raisons de leurs échecs permet de rappeller les contraintes de la réalité qu'on a trop vite fait d'oublier.

Les paris sont ouverts sur les entrées à ajouter d'ici quelques années, mais si on a déjà quelques solides candidats.

= Titre

*{idee}* Excepteur est voluptate qui ad esse eu est magna duis ea velit labore ipsum.

*{pourquoi}* Amet Lorem ullamco consectetur cillum irure qui incididunt dolore eu voluptate voluptate sint.

*{maintenant}* Esse nostrud elit sit qui esse sit laborum magna dolore aute exercitation.
