= Links - 17^rd^ November 2024
Julien Kirch
v1.0, 2024-11-17
:article_lang: en
:figure-caption!:
:article_description: List Syntax, tram map in T~E~X, complexity in organizations

== link:https://stopa.io/post/265[An intuition for Lisp Syntax]

[quote]
____
Every lisp hacker I ever met, myself included, thought that all those brackets in Lisp were off-putting and weird. At first, of course. Soon after we all came to the same epiphany: _lisp's power lies in those brackets_! In this essay, we'll go on a journey to that epiphany.
____

==  link:https://stuebinm.eu/posts/milano-tram-network.html[A line map for Milano's trams in T~E~X]

[quote]
____
So there I was, sitting in my hotel room, and wondering how to procrastinate on making the slides for my talk (thankfully scheduled for the last day of the conference, so I had some time). Why not try to make my own map?

By complete coincidence, the weekend before I'd been at link:https://baytex.in-ulm.de/2024/[BayT~E~X], where Aada had given link:https://baytex.in-ulm.de/2024/slides/liniennetzplaene.pdf[an amazing last-minute talk] about how to draw line network maps with T~E~X, so I had a rough idea of how to go about it.
____

== link:https://cutlefish.substack.com/p/tbm-321-reducing-complexity[TBM 321: "`Reducing Complexity`"]

[quote]
____
I've been reading a lot of articles recently about executives wanting to "`reduce complexity`". But if product work is inherently complex and groups of humans form complex adaptive systems, then reducing complexity in this case is impossible (and undesirable).

The key way the executive can "`simplify`" is to focus on reducing the drag and friction caused by too many priorities and other things that make it difficult for people to come together and do productive, complex knowledge work. From the outside, it looks simple -- even if all the complex goodness is happening on the inside.
____

[quote]
____
But you often see, as in our story, a sort of knee-jerk reaction to blame the people in the room for why things are the way they are. Because, as an outsider, things look like a mess, it is easy to make the mental leap from mess to "`these people are making this too complex`" to "`they are dropping the ball!`" This kind of thinking is counterproductive -- it puts undue pressure on the people already trying their best to navigate an overloaded system.
____
